### ISSUE TITLE
All .emu emulators - input lag occurs for several seconds if button mashing repeatedly.

### ISSUE THREAD

**Issue by gannon345** [Rakashazi/emu-ex-plus-alpha#100]
If multiple buttons are repeatedly, rapidly pressed, the input lags out and inputs become very delayed and continue occurring well after the buttons are no longer pressed. This can be replicated in any game, as far as I know for any of the .emu series emulators (I've personally tested on SNES9x, GBA.emu, and MD.emu). It seems most prominent on SNES9x.

**Comment by Rakashazi** [comment]
Please re-test on a current release.
