### ISSUE TITLE
[Question]: How to disable autosave in 1.5.66 

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1000]
### Describe your question

I want to disable autosave in 1.5.66, but no "off" option. 1.5.65 is O.K.

**Comment by Rakashazi** [comment]
To skip loading the autosave state set Options -> System -> Autosave Launch Mode -> Load (No State)

If you don't plan on using autosave states at all you can additionally disable the timer with Options -> System -> Autosave Timer -> Only On Exit

**Comment by leoxxx** [comment]
> To skip loading the autosave state set Options -> System -> Autosave Launch Mode -> Load (No State)
> 
> If you don't plan on using autosave states at all you can additionally disable the timer with Options -> System -> Autosave Timer -> Only On Exit
I select the two option as you said, but it still create .nca file.
I don't want to create .nca file, like1.5.66 no this file.

**Comment by Rakashazi** [comment]
Oh ok, if you don't want any save files created at all, no even as a backup, then use Options -> System -> Autosave Launch Mode -> Ask, then when opening a game select No Save.

**Comment by leoxxx** [comment]
> Oh ok, if you don't want any save files created at all, no even as a backup, then use Options -> System -> Autosave Launch Mode -> Ask, then when opening a game select No Save.

Then I will select it when open every time, is it?  
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1002
Can add a option like 1.5.65? No ask to disable.
