### ISSUE TITLE
[Feature request]: Please add a option to disable the autosave file

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1002]
### Describe the feature
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1000#issuecomment-1294329405
Like 1.5.65, select "off", it will not create a autosave file.

### Add screenshots

![2022-10-28_100206](https://user-images.githubusercontent.com/5364709/198457072-557794fc-ca0a-42c5-a541-19f685d77e2e.png)

**Comment by Rakashazi** [comment]
Ok, I've added a "No Save" option to Autosave Launch Mode. I'll be included in the upcoming version 1.5.68.

**Comment by leoxxx** [comment]
THX. I'll test it.
