### ISSUE TITLE
[Question]: Possible to update Snes9x with the next update?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1016]
### Describe your question

Hi @Rakashazi is it possible to update Snes9x with the next update?

They changed some things regarding MSU1:
https://github.com/snes9xgit/snes9x/commit/4b8d3c6c6b1403616b1501f3559fd96223f79728
https://github.com/snes9xgit/snes9x/commit/3c4982edddfdba482204ed48cf0b1d41ccae5493

Thanks in advance.

**Comment by bladeoner** [comment]
@Rakashazi these seem to be some small changes, is it possible to add it with the next commit?

Thanks in advance.

**Comment by Rakashazi** [comment]
Added in last commit
