### ISSUE TITLE
[Feature request]: [Swan.emu]Need remap some portrait keys

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1019]
### Describe the feature

In 1.5.65

> A↷X4
> B↷X1
> Y1↷B
> Y2↷A
> Y3↷X3
> Y4↷X2

After remapping.

> ~~A↷X3
> B↷X4
> Y1↷X2
> Y2↷X1
> Y3↷A
> Y4↷B~~

> A↷X3
> B↷X4
> Y1↷X2
> Y2↷A
> Y3↷B
> Y4↷X1

In portrait games, the key function X3=A; X4=B.
A↷X3
B↷X4

The 2 keys need remap, others are optional.

### Add screenshots

![1111](https://user-images.githubusercontent.com/5364709/201473110-3c68da7d-0700-47bb-8e34-e4b52abfcaa3.jpg)
![1111](https://user-images.githubusercontent.com/5364709/201473448-763ce683-9bad-454e-a04f-438badce7a7d.jpg)![123](https://user-images.githubusercontent.com/5364709/222622217-73e82d52-423c-4b3e-a870-7cd30ac115ea.jpg)
~~https://user-images.githubusercontent.com/5364709/201474252-2d3d819c-c9d7-4b77-b21a-4e0500b65626.jpg~~

**Comment by soundsnow** [comment]
> ### Describe the feature
> 
> In 1.5.65 A↷X4 B↷X1 Y1↷B Y2↷A Y3↷X3 Y4↷X2 After remapping. A↷X3 B↷X4 Y1↷X1 Y2↷X2 Y3↷A Y4↷B In portrait games, the key function X3=A; X4=B.
> ### Add screenshots
> 
> _No response_

![ws](https://user-images.githubusercontent.com/109885044/201472430-b614874f-570f-47a0-ade8-9cab90ebca7f.png)

**Comment by leoxxx** [comment]
> > ### Describe the feature
> > In 1.5.65 A↷X4 B↷X1 Y1↷B Y2↷A Y3↷X3 Y4↷X2 After remapping. A↷X3 B↷X4 Y1↷X1 Y2↷X2 Y3↷A Y4↷B In portrait games, the key function X3=A; X4=B.
> > ### Add screenshots
> > _No response_
> 
> ![ws](https://user-images.githubusercontent.com/109885044/201472430-b614874f-570f-47a0-ade8-9cab90ebca7f.png)

Your picture is too small.

**Comment by soundsnow** [comment]
![wsx](https://user-images.githubusercontent.com/109885044/201472623-9cc837f7-c06f-4217-995b-852da161a029.png)

**Comment by leoxxx** [comment]
> ![wsx](https://user-images.githubusercontent.com/109885044/201472623-9cc837f7-c06f-4217-995b-852da161a029.png)

I upload the picture.

**Comment by leoxxx** [comment]
Virtul key is right.
I said it is the physical device key mapping.

**Comment by leoxxx** [comment]
Changing remapping.
