### ISSUE TITLE
remove "system" usage iOS 11 /Xcode 9

### ISSUE THREAD

**Issue by thededman** [Rakashazi/emu-ex-plus-alpha#104]
"system" is removed in iOS 11  on the FileUtils.cc 

Call to unavailable function 'system': not available on iOS
https://stackoverflow.com/questions/45420717/call-to-unavailable-function-system-not-available-on-ios

Can't simple replace the SYSTEM with NFTW as there are parameters missing

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/ftw.h:56:5: note: candidate
      function not viable: requires 4 arguments, but 1 was provided
int     nftw(const char *, int (*)(const char *, const struct stat *, int,
        ^

I've tried to figure this out but brain hurts!

**from FileUtils.cc**
auto execPath = FS::makePathStringPrintf("%s/fixMobilePermission '%s'", Base::assetPath().data(), path);
	//logMsg("executing %s", execPath);
	int err = nftw(execPath.data());
	if(err)
	{
		logWarn("error from fixMobilePermission helper: %d", err);
	}
	#endif
}

**Comment by palla89** [comment]
@thededman solved in issue #103 look my latest comment!

Just need to let latest version run with rom loading!
