### ISSUE TITLE
[Question]: Is it possible to update Github Workflow?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1041]
### Describe your question

Hi @Rakashazi I've noticed the Nightly builds will expire at some point:

![image](https://user-images.githubusercontent.com/24655170/205307425-306e6c56-4614-4e88-8d2d-95f52d44d2d5.png)

To be able to download the latest Nightly build files I've added a Pre-release section under Releases. 
What it will do is everytime a CI/CD build is triggered it will replace the files in the Pre-release section, it will look like this:
![image](https://user-images.githubusercontent.com/24655170/205308289-7c7e4923-0ac5-4c18-930a-2b9431851b01.png)

![image](https://user-images.githubusercontent.com/24655170/205307720-9e5c3a7a-6d61-4c95-886e-88c2906d068b.png)

Can you add the following file?
[update_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/10361023/update_workflow.zip)

Thanks in advance!

**Comment by bladeoner** [comment]
@Rakashazi the best wishes for the new year, I've optimized the attached file today.

When you have some time can you take a look at it and see if it can be added?

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks @bladeoner and a happy new year to you as well. I should be able to fit this into the next commit.

**Comment by bladeoner** [comment]
Thank you

**Comment by Rakashazi** [comment]
Added in last commit
