### ISSUE TITLE
[Issue]: The app crashes package installer when uninstalling

### ISSUE THREAD

**Issue by ActionWavele** [Rakashazi/emu-ex-plus-alpha#1050]
### Describe the bug

The app (version 1.5.67) crashes package installer when uninstalling, leaving it stuck on the device

### Steps to reproduce

I installed the latest cersion, then tried to uninstall it

### Expected behavior

The app should ve able to br removed

**Comment by Rakashazi** [comment]
Hi, the APKs are all generated using standard tools so any kind crashing of the installer app would point to a bug with the firmware on your device. Unfortunately there's nothing I can do on my end to fix it.

**Comment by TheBoxGame1234** [comment]
Rakashazi add mapper 134 176 and 205 plis very very plis nes.emu

**Comment by TheBoxGame1234** [comment]
because games without these mappers don't work

**Comment by TheBoxGame1234** [comment]
![Screenshot_2023-01-17-16-10-55-029_com google android gm](https://user-images.githubusercontent.com/116956029/213696759-fc21a68a-c291-4b10-b472-54494105a330.jpg)
)

**Comment by TheBoxGame1234** [comment]
![Screenshot_2023-01-17-21-34-02-087_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696815-3dfd83bc-eaf3-4460-9374-afd79a296578.jpg)
![Screenshot_2023-01-17-21-34-28-530_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696826-b5bab535-5447-466d-a48c-006dc0565e52.jpg)
![Screenshot_2023-01-17-21-34-09-399_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696869-45c265ff-8cac-4383-893e-bd92e6d92a11.jpg)
![Screenshot_2023-01-17-21-40-30-902_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696872-f93a0f15-e6a1-465d-87b9-e41aa5bdbe3d.jpg)
![Screenshot_2023-01-17-21-34-50-078_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696874-140a8e10-b601-4e67-aefd-c321aa2a4195.jpg)
![Screenshot_2023-01-17-21-34-56-967_com explusalpha NesEmu](https://user-images.githubusercontent.com/116956029/213696878-9af52588-baa1-4460-9dcc-11c02308586d.jpg)

**Comment by TheBoxGame1234** [comment]
![208290997-99b91d36-5c9d-4918-8409-50b35eaf7d03](https://user-images.githubusercontent.com/116956029/213697221-5c29b042-2658-4327-a84c-fda457457934.jpg)
![208291546-d168725b-64e9-4916-a7a0-311bdd6781c4](https://user-images.githubusercontent.com/116956029/213697228-bab803f8-600e-4296-a9f1-2371466557d9.jpg)
![Screenshot_2023-01-13-13-12-41-486_com android chrome](https://user-images.githubusercontent.com/116956029/213697230-45c1b5ac-9c1a-474e-80b6-a30aec8e0926.jpg)
![208290996-f1c0693d-3e5b-42dc-a579-704cbce578aa](https://user-images.githubusercontent.com/116956029/213697232-af54414b-d9aa-4c22-95cd-bc2b79e95cc5.jpg)
