### ISSUE TITLE
[Feature request]: md MODE button position

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1057]
### Describe the feature

It looks as if Sega wants players to use right hand to press the MODE button and both hands to press the START button, MODE is actually a right shoulder button

START position same as 3 button gamepad

Individual button toggles
Mode On/Off
Start On/Off
![image43](https://user-images.githubusercontent.com/109885044/210193559-4d39e6f2-5a01-4279-8c2c-2373e3afd085.png)

**Comment by Rakashazi** [comment]
Mode is now movable as an independent button group
