### ISSUE TITLE
[Feature request]: VBA-M 2.1.5

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1059]
### Describe the feature

update GBA.emu
https://github.com/visualboyadvance-m/visualboyadvance-m/releases

**Comment by Rakashazi** [comment]
Most of the GIT updates between 2.1.4 and 2.1.5 were already rolled in but I'll add the rest for the next release.

**Comment by Rakashazi** [comment]
Updated past version 2.1.5 in last commit
