### ISSUE TITLE
Can't load roms on iOS 11 because of sandbox problem

### ISSUE THREAD

**Issue by palla89** [Rakashazi/emu-ex-plus-alpha#106]
Hi, I tried lot of things but I can't load roms in the emulators on iOS because of the sandbox problems. Can you help us?

**Comment by thededman** [comment]
In the debugger there is this on the launch- without opening roms. This maybe the clue.
**Application windows are expected to have root view controller at the end of application launch.**
![debug](https://user-images.githubusercontent.com/5215424/31239702-0ade4220-a9cc-11e7-935c-b6ec727ef638.jpg)

**Comment by palla89** [comment]
Unfortunately that's not related to the emulator or file system :(

I found that there is a file in emu-explus-alpha/imagine/src/base/iphone/iphone.mm that relates to directories, but I couldn't fix it :\

I thought it was something related to this:

`FS::PathString documentsPath()
{
	if(isRunningAsSystemApp)
		return {"/User/Library/Preferences"};
	else
	{
		NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
		NSString *documentsDirectory = [paths firstObject];
		if(documentsDirectory)
			FS::makePathString([documentsDirectory cStringUsingEncoding: NSASCIIStringEncoding]);
		return {};
	}
}`

**Comment by thededman** [comment]
So seems that this code was made to leave the sandbox when this was on Cydia with Jailbreak.
It should point here:  **/var/mobile/Containers/Data/Application/EXAMPLE-1F1468AA-A6D4-4379-84C7-ABC99BDC9302** Something in that code above may lead to a fix, or I'm totally of key.
This is why I don't understand when he updated the code after 1.5.29 this all broke? I had this issue since #73. 
@Rakashazi is a person of mystery and I'm sure he's busy working and has a family, so have to wait. *But fun to hunt this issues down and learn the code.

**Comment by palla89** [comment]
I solved it @thededman!!! I'm not at home right now, I'll try to write the steps but I have got the latest version working!! Tested with NEO.emu and MD.emu! I tried some roms and it's fully working at full speed! The only problem I had is that there is a bug when putting the phone in landscape! I'll try to make a fork and put there all the fixes to compile everything, with the help of the tutorial you wrote!

**Comment by palla89** [comment]
https://github.com/palla89/emu-ex-plus-alpha/tree/master I used also your tutorial to help people compiling and tried to add a readme, try with my version if it work!

**Comment by thededman** [comment]
Excellent work! The main emulators that I wanted to use are working great again. NES and SNES confirmed.



Sent from my iPhone

On Oct 7, 2017, at 1:41 PM, palla89 <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/palla89/emu-ex-plus-alpha/tree/master I used also your tutorial to help people compiling and tried to add a readme, try with my version if it work!
