### ISSUE TITLE
[Feature request]: update cmake 3.25 and exit code 100

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1066]
### Describe the feature

echo y | sdkmanager "cmake;3.18.1"

The job was canceled because "_2600_emu" failed.
Process completed with exit code 100.

**Comment by bladeoner** [comment]
Cmake will be updated to the latest stable after the following is added: #1041

The job failed but that was a local issue on the machine it was running on, I tested it myself and it finished succesfully.
