### ISSUE TITLE
[Issue]: Set screen's reported rate with 120Hz display

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#1067]
### Describe the bug

I'm testing on a Redmi Note 10 Pro phone with 120Hz display. When the phone is set to 120Hz mode, .emu emulators mostly work correctly: 60Hz when emulation is running and 120Hz whenever the menu is open. Display remains at 120Hz when Force Max Screen Refresh Rate is enabled.

The frame rate options also mostly work: "Detect screen's rate and set" works even with Force Max Screen Refresh Rate enabled. The display switches to 60Hz during the detection process.

The one thing which _doesn't_ quite work, is "Set screen's reported rate": that just shows an error "120.00Hz not in valid range". That happens whether or not Force Max Screen Refresh Rate is enabled.

### Steps to reproduce

Set phone display to 120Hz, launch emulator and tap Set screen's reported rate.

### Expected behavior

Emulator notices that display refresh rate is near-double the emulated frame rate and adjusts accordingly.

**Comment by Rakashazi** [comment]
Thanks for the report, looks like there was a bug processing the refresh rate value after checking the list of of supported rates. I've fixed it in the last commit so it will properly set the refresh rate if it divides into the the device's rate, or fall back to the emulated system's rate.

**Comment by M-a-r-k** [comment]
I checked the nightly builds of GBA.emu and GBC.emu.

The error message no longer appears but for sone reason the frame rate set after tapping Set screen's reported rate is 60.27Hz? It should be 60.00.

**Comment by Rakashazi** [comment]
Ok, the last commit should fix that and it'll now use the exact divided refresh rate.
