### ISSUE TITLE
[Question]: App not installed as package conflicts

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1073]
### Describe your question

Do you want to update this app?
Update
App not installed as package conflicts
 Commit 1e8c120

**Comment by TheBoxGame1234** [comment]
have you tried uninstalling the version you have installed and installing a newer one

**Comment by M-a-r-k** [comment]
I noticed that when installing the latest nightly build. Wouldn't update Snes9X Ex and wouldn't install as a separate app either.

**Comment by soundsnow** [comment]
> have you tried uninstalling the version you have installed and installing a newer one

that's not good
uninstall old
install new

**Comment by Rakashazi** [comment]
The signing certificate was updated from 1024-bit to 2048-bit automatically by the Android dev tools so it looks like you guys will have to remove the current apps and install the APK fresh to avoid security errors. In case there's still install issues after that let me know.

**Comment by TheBoxGame1234** [comment]
@Rakashazi these 2 roms are still missing Rakashazi add these 2 mappers I'll give you the page right now what I mean 

https://www.nesdev.org/wiki/INES_Mapper_134
https://www.nesdev.org/wiki/INES_Mapper_176

**Comment by TheBoxGame1234** [comment]
@Rakashazi I will give you the names of the roms I am asking for 7-in-1 (YH708) (Unl) [p1].nes and Super 188-in-1 (BS-6013) (Unl).nes

**Comment by TheBoxGame1234** [comment]
@Rakashazi thank you for adding Turbo A Turbo B buttons to the NES. Emu is worth waiting for updates though
