### ISSUE TITLE
[Question]: too low screen position

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1081]
### Describe your question

my Android device aspect ratio 20:9
That's not friendly for 20:9, 21:9 users

### Add screenshots

![image28](https://user-images.githubusercontent.com/109885044/213880654-8a9be326-449b-4123-ba55-ef18a1827549.png)

**Comment by Rakashazi** [comment]
I'm planning to make the screen position adjustable in 1.5.68 so you can move it to any height.

**Comment by Rakashazi** [comment]
Video position in now adjustable in the last commit
