### ISSUE TITLE
[Feature request]: change screen position for 18:9 users

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1082]
### Describe the feature

NGP:  20:19 = 1.05263157
GB: 10:9 = 1.11
4:3 = 1.33
GBA: 3:2 = 1.5
WS: 14:9 = 1.55

Android Phones

Not Recommended:
4:3 and 3:2 (GBA size)

Recommended:
8:5=1.6
5:3=1.66
16:9=1.77
18:9=2
18.5:9=2.055
19:9=2.11
19.5:9=2.166
20:9=2.22
21:9=2.33

Original Aspect Ratio
Android Phone

SNES
Default Full UI
Recommended: 18:9
Rotate 90°, 270° (Top to Fast-forward and menu button)
Recommended: More Than 21:9

GBA
Default Full UI
Recommended: 16:9
Rotate 90°, 270° (Top to Fast-forward and menu button)
Recommended: More Than 21:9

ColecoVision
Default Full UI
Recommended: 18:9
Rotate 90°, 270° (Top to Fast-forward and menu button)
Recommended: More Than 21:9

WS
Default Full UI
Y
X|B|A
Recommended: 18:9
Rotate 90°, 270° (Top to Fast-forward and menu button)
Recommended: More Than 21:9

new bug (I think), screen position too low
Default and Content Rotation 90°, 270°

**Comment by soundsnow** [comment]
These consoles and computers aren't touchscreen devices, make virtual buttons away from game screen
Thanks @rakashazi

**Comment by Rakashazi** [comment]
Video position in now adjustable in the last commit
