### ISSUE TITLE
[Issue]: No Saved Settings In Input Groups Button

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#1084]
### Describe the bug

@Rakashazi

Does not save the settings of the add/re-assigning buttons to NES.emu/Snes9x EX+/PCE.emu/2600.emu/MD.emu/GBC.emu/GBA.emu/MSX.emu/Swan.emu/C64.emu/NGP.emu/NEO.emu when you turn off the emulator and turn it back on, the settings are lost

### Steps to reproduce

Please fix this

### Expected behavior

.

**Comment by Rakashazi** [comment]
This will be fixed before 1.5.68. Currently I'm updating some of the on-screen input code so the code for saving/loading the input configuration is disabled until that's finished.
