### ISSUE TITLE
Error when compiling C64.emu on macOS High Sierra 13.13.3 and Xcode 9.2

### ISSUE THREAD

**Issue by ck16** [Rakashazi/emu-ex-plus-alpha#109]
I've managed to compile all the emulators except C64.emu.

After running the following command "make -f ios-release.mk V=1 -j4", I'm seeing the following linker errors:

Undefined symbols for architecture arm64:
  "Base::libPath(char const*)", referenced from:
      EmuSystem::onOptionsLoaded() in lto.o
      __ZZN12DelegateFuncIFbR12TextMenuItemR4ViewN5Input5EventEEEC1IZNS0_18wrapSelectDelegateIN18CustomMainMenuView6systemMUlS1_S3_S5_E_EEES7_T_EUlS1_S3_S5_E_EERKSC_ENUlRKNS7_7StorageES1_S3_S5_E_8__invokeESI_S1_S3_S5_ in lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [target/ios-release/bin/c64emu-arm64] Error 1
make: *** [ios-arm64] Error 2
make: *** Waiting for unfinished jobs....
Undefined symbols for architecture armv7:
  "Base::libPath(char const*)", referenced from:
      EmuSystem::onOptionsLoaded() in lto.o
      __ZZN12DelegateFuncIFbR12TextMenuItemR4ViewN5Input5EventEEEC1IZNS0_18wrapSelectDelegateIN18CustomMainMenuView6systemMUlS1_S3_S5_E_EEES7_T_EUlS1_S3_S5_E_EERKSC_ENUlRKNS7_7StorageES1_S3_S5_E_8__invokeESI_S1_S3_S5_ in lto.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [target/ios-release/bin/c64emu-armv7] Error 1
make: *** [ios-armv7] Error 2

**Comment by Rakashazi** [comment]
Thanks, will be fixed in next commit

Line 579 of imagine/src/base/iphone/iphone.mm should be:

FS::PathString libPath(const char *)
