### ISSUE TITLE
[Question]: Can you add this Snes9x commit?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1090]
### Describe your question

Hi @Rakashazi, when you will do the next update, is it possible to add the following commit?
https://github.com/snes9xgit/snes9x/commit/a06974940362923c224626c6ecbcf0d96308d75e

Thanks in advance.

**Comment by Rakashazi** [comment]
Sure, I can fit it into the next commit.

**Comment by bladeoner** [comment]
@Rakashazi could you also add the following in the next commit?
https://github.com/snes9xgit/snes9x/commit/a2e0580992873ec3913fd1ef09f22f368fe44b3b

**Comment by Rakashazi** [comment]
Added in last commit

**Comment by bladeoner** [comment]
Thanks!
