### ISSUE TITLE
Unable to build imagine for android-release, regparm (incorrectly) used in arm64 and armv7 compiles

### ISSUE THREAD

**Issue by rhester72** [Rakashazi/emu-ex-plus-alpha#110]
On latest tip revision, I get the following when trying to build the imagine library for android-release (after successful build of bundle/all):

    Compiling ./src/thread/PThread.cc
    In file included from ./src/thread/PThread.cc:17:
    In file included from ./include/imagine/thread/Thread.hh:23:
    In file included from ./include/imagine/thread/PThread.hh:20:
    /usr/include/pthread.h:682:6: error: 'regparm' is not valid on this platform
         __cleanup_fct_attribute;
         ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                        
    /usr/include/bits/pthreadtypes-arch.h:103:50: note: expanded from macro '__cleanup_fct_attribute'
    # define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
                                                     ^            ~
I have deliberately avoided specifying a target platform (e.g. arm64) so that release-15 builds include all of the appropriate targets - but can't explain why regparm is being used for arm64 and armv7.

**Comment by Rakashazi** [comment]
That error indicated the system headers are being pulled into the build and not the Android ones. Are you using the latest NDK r16 with the unified Android headers? Make sure the directory sysroot/usr/include exists in your NDK installation.

**Comment by rhester72** [comment]
I'm using NDK r16b.  From make dry-run:

/home/rhester/android/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -c -MMD -MP ./src/thread/PThread.cc -DNDEBUG
-DANDROID --sysroot=/home/rhester/android/android-ndk-r16b/sysroot -isystem /home/rhester/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -DANDROID_COMPAT_API -Ibuild/android-armv7-release/gen -I./include -I./include/imagine/override -I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/include -isystem /home/rhester/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem /home/rhester/android/android-ndk-r16b/sources/android/support/include -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics  -target armv7-none-linux-androideabi -gcc-toolchain /home/rhester/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -fpic -pipe -fvisibility=hidden -O2 -fomit-frame-pointer -fno-stack-protector  -flto -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/android-armv7-release/obj/thread/PThread.o

sysroot appears to be populated as expected:

$ ls /home/rhester/android/android-ndk-r16b/sysroot/usr/include
aarch64-linux-android  dlfcn.h     GLES2               locale.h                paths.h      spawn.h      time.h
aaudio                 drm         GLES3               malloc.h                poll.h       stdatomic.h  uchar.h
alloca.h               EGL         glob.h              math.h                  pthread.h    stdint.h     ucontext.h
android                elf.h       grp.h               media                   pty.h        stdio_ext.h  unistd.h
ar.h                   endian.h    i686-linux-android  memory.h                pwd.h        stdio.h      utime.h
arm-linux-androideabi  err.h       iconv.h             mips64el-linux-android  rdma         stdlib.h     utmp.h
arpa                   errno.h     ifaddrs.h           mipsel-linux-android    regex.h      string.h     video
asm-generic            error.h     inttypes.h          misc                    resolv.h     strings.h    vulkan
assert.h               fcntl.h     jni.h               mntent.h                sched.h      sys          wait.h
bits                   features.h  KHR                 mtd                     scsi         syscall.h    wchar.h
byteswap.h             fenv.h      langinfo.h          net                     search.h     sysexits.h   wctype.h
camera                 fnmatch.h   lastlog.h           netdb.h                 semaphore.h  syslog.h     x86_64-linux-android
complex.h              fts.h       libgen.h            netinet                 setjmp.h     tar.h        xen
cpio.h                 ftw.h       limits.h            netpacket               signal.h     termio.h     xlocale.h
ctype.h                getopt.h    link.h              nl_types.h              SLES         termios.h    zconf.h
dirent.h               GLES        linux               OMXAL                   sound        time64.h     zlib.h

**Comment by rhester72** [comment]
You do appear to be correct, though, that it's trying to draw pthread.h from /usr/include rather than sysroot:

make -f /home/rhester/android/emu-ex-plus-alpha/imagine/make/shortcut/common-builds/android-armv7-release.mk projectPath=. ; make -f /home/rhester/android/emu-ex-plus-alpha/imagine/make/shortcut/common-builds/android-arm64-release.mk projectPath=. ; make -f /home/rhester/android/emu-ex-plus-alpha/imagine/make/shortcut/common-builds/android-x86-release.mk projectPath=. ;
make[1]: Entering directory '/home/rhester/android/emu-ex-plus-alpha/imagine'
Android NDK path: /home/rhester/android/android-ndk-r16b
NDK GCC path: /home/rhester/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin
NDK Clang path: /home/rhester/android/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin
Compiling ./src/thread/PThread.cc
/home/rhester/android/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -c -MMD -MP ./src/thread/PThread.cc -DNDEBUG -DANDROID --sysroot=/home/rhester/android/android-ndk-r16b/sysroot -isystem /home/rhester/android/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -DANDROID_COMPAT_API -Ibuild/android-armv7-release/gen -I./include -I./include/imagine/override -I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/include -isystem /home/rhester/android/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem /home/rhester/android/android-ndk-r16b/sources/android/support/include -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics  -target armv7-none-linux-androideabi -gcc-toolchain /home/rhester/android/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -fpic -pipe -fvisibility=hidden -O2 -fomit-frame-pointer -fno-stack-protector  -flto -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/android-armv7-release/obj/thread/PThread.o
In file included from ./src/thread/PThread.cc:17:
In file included from ./include/imagine/thread/Thread.hh:23:
In file included from ./include/imagine/thread/PThread.hh:20:
/usr/include/pthread.h:682:6: error: 'regparm' is not valid on this platform
     __cleanup_fct_attribute;
     ^~~~~~~~~~~~~~~~~~~~~~~

yet it exists in sysroot:

$ ls -l /home/rhester/android/android-ndk-r16b/sysroot/usr/include/pthread.h
-rw-r--r-- 1 rhester rhester 12156 Dec  1 10:55 /home/rhester/android/android-ndk-r16b/sysroot/usr/include/pthread.h

I don't understand how that's possible.

**Comment by rhester72** [comment]
It's worth noting that I am manually setting ANDROID_NDK_PATH since I don't have Android Studio 3.0.

**Comment by Rakashazi** [comment]
I see there's -I/usr/include right after the pkgconfig include path, so it could be an issue with the files generated after you ran imagine/bundle/all/makeAll-android.sh. Check the prefix and includedir variables in all the the .pc files under imagine-sdk/[name of arch]/lib/pkgconfig. Make sure the prefix variable is a relative path like ${pcfiledir}/../.., and includedir is based on that.

**Comment by rhester72** [comment]
Nothing stands out, unless I'm missing the obvious:

[rhester@igor imagine-sdk]$ find . -name "*.pc" -exec egrep -H "^prefix=|^includedir=" {} \;
./android-armv7/lib/pkgconfig/ogg.pc:prefix=${pcfiledir}/../..
./android-armv7/lib/pkgconfig/ogg.pc:includedir=${prefix}/include
./android-armv7/lib/pkgconfig/vorbisidec.pc:prefix=${pcfiledir}/../..
./android-armv7/lib/pkgconfig/vorbisidec.pc:includedir=${prefix}/include
./android-armv7/lib/pkgconfig/sndfile.pc:prefix=${pcfiledir}/../..
./android-armv7/lib/pkgconfig/sndfile.pc:includedir=${prefix}/include
./android-armv7/lib/pkgconfig/liblzma.pc:prefix=${pcfiledir}/../..
./android-armv7/lib/pkgconfig/liblzma.pc:includedir=${pcfiledir}/../../include
./android-arm64/lib/pkgconfig/ogg.pc:prefix=${pcfiledir}/../..
./android-arm64/lib/pkgconfig/ogg.pc:includedir=${prefix}/include
./android-arm64/lib/pkgconfig/vorbis.pc:prefix=${pcfiledir}/../..
./android-arm64/lib/pkgconfig/vorbis.pc:includedir=${prefix}/include
./android-arm64/lib/pkgconfig/vorbisfile.pc:prefix=${pcfiledir}/../..
./android-arm64/lib/pkgconfig/vorbisfile.pc:includedir=${prefix}/include
./android-arm64/lib/pkgconfig/sndfile.pc:prefix=${pcfiledir}/../..
./android-arm64/lib/pkgconfig/sndfile.pc:includedir=${prefix}/include
./android-arm64/lib/pkgconfig/liblzma.pc:prefix=${pcfiledir}/../..
./android-arm64/lib/pkgconfig/liblzma.pc:includedir=${pcfiledir}/../../include
./android-x86/lib/pkgconfig/ogg.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/ogg.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/vorbis.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/vorbis.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/vorbisfile.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/vorbisfile.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/sndfile.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/sndfile.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/liblzma.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/liblzma.pc:includedir=${pcfiledir}/../../include
./android-x86/lib/pkgconfig/libarchive.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/libarchive.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/imagine.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/imagine.pc:includedir=${prefix}/include
./android-x86/lib/pkgconfig/emuframework.pc:prefix=${pcfiledir}/../..
./android-x86/lib/pkgconfig/emuframework.pc:includedir=${prefix}/include

**Comment by Rakashazi** [comment]
Let's verify the incorrect path is actually coming from pkg-config, add the following 2 lines to imagine/make/evalPkgConfigCFlags.mk, below "CPPFLAGS += $(pkgConfigCFlagsOutput)" and above "endif"

```
 $(info pkgconfig cflags command: PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) PKG_CONFIG_SYSTEM_INCLUDE_PATH=$(PKG_CONFIG_SYSTEM_INCLUDE_PATH) pkg-config $(pkgConfigDeps) $(pkgConfigStaticDeps) --cflags $(pkgConfigOpts))
 $(info pkgconfig cflags output: $(pkgConfigCFlagsOutput))
```
Then try compiling again and check the output of those 2 info statements.

**Comment by rhester72** [comment]
pkgconfig cflags command: PKG_CONFIG_PATH=/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig: PKG_CONFIG_SYSTEM_INCLUDE_PATH= pkg-config  libarchive liblzma --cflags
pkgconfig cflags output: -I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/include

**Comment by Rakashazi** [comment]
Take the command printed from the first line and run from a shell but also pass in --debug at the end, what is the output?

**Comment by rhester72** [comment]
I'm very sorry...which command?  pkgconfig doesn't seem to take --debug as an arg, I may be misunderstanding what you're asking for.

**Comment by rhester72** [comment]
I may have a clue on this.

archive.h has always been created via libarchive for all platforms, but with the latest git, it is only created for x86.

Since archive.h also exists in /usr/include (but not sysroot include), it seems possible that since libarchive isn't generating archive.h for the ARM platforms, the compiler is instead seeking it out wherever it can find it.

Question is...why isn't archive.h being generated for ARM?

**Comment by rhester72** [comment]
OK - it's not just ARM.

I get this for libarchive for all three variants:

make[2]: Entering directory '/tmp/imagine-bundle/libarchive/build/android-arm64'
  CC       libarchive/archive_acl.lo
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.40-6ca5-dirty.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-1
libtool: and run autoconf again.

I checked the tarball for libarchive, and the Debian version string is indeed hardcoded in lt-main.sh - but is only appropriate for that specific environment.

Suggestions?

**Comment by BlueMax** [comment]
I had the same problem and it vanished as i set **export android_arch="armv7"**.
Possible that i previously limited some dependencies to armv7 as well.

**Comment by Rakashazi** [comment]
Let's work on the pkg-config issue first. What's the output of "pkg-config --version" ? I'm using currently using 0.29.2 which does support the --debug parameter.

**Comment by rhester72** [comment]
I'm runing 0.29.2 as well - I don't think I quite understood what you were asking for earlier.

Running pkg-config as requested from CLI (so thus not as part of the build process, so this is using on-system packages):

    Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Valu
e of --silence-errors: 0
    Error printing enabled
    Adding virtual 'pkg-config' package to list of known packages
    Looking for package 'libarchive'
    Looking for package 'libarchive-uninstalled'
    Reading 'libarchive' from file '/usr/lib/pkgconfig/libarchive.pc'
    Parsing package file '/usr/lib/pkgconfig/libarchive.pc'
      line>prefix=/usr
     Variable declaration, 'prefix' has value '/usr'
      line>exec_prefix=${prefix}
     Variable declaration, 'exec_prefix' has value '/usr'
      line>libdir=${exec_prefix}/lib
     Variable declaration, 'libdir' has value '/usr/lib'
      line>includedir=${prefix}/include
     Variable declaration, 'includedir' has value '/usr/include'
      line>
      line>Name: libarchive
      line>Description: library that can create and read several streaming archive formats
      line>Version: 3.3.2
      line>Cflags: -I${includedir}
      line>Libs: -L${libdir} -larchive
      line>Libs.private: -lcrypto -lacl -lexpat -llzma -llz4 -lbz2 -lz
    Unknown keyword 'Libs.private' in '/usr/lib/pkgconfig/libarchive.pc'
    Path position of 'libarchive' is 1
    Adding 'libarchive' to list of known packages
    Package libarchive has -I/usr/include in Cflags
    Removing -I/usr/include from cflags for libarchive
    Package libarchive has -L /usr/lib in Libs
    Removing -L /usr/lib from libs for libarchive
    Looking for package 'liblzma'
    Looking for package 'liblzma-uninstalled'
    Reading 'liblzma' from file '/usr/lib/pkgconfig/liblzma.pc'
    Parsing package file '/usr/lib/pkgconfig/liblzma.pc'
      line>
      line>
      line>
      line>
      line>
      line>
      line>
      line>prefix=/usr
     Variable declaration, 'prefix' has value '/usr'
      line>exec_prefix=/usr
     Variable declaration, 'exec_prefix' has value '/usr'
      line>libdir=/usr/lib
     Variable declaration, 'libdir' has value '/usr/lib'
      line>includedir=/usr/include
     Variable declaration, 'includedir' has value '/usr/include'
      line>
      line>Name: liblzma
      line>Description: General purpose data compression library
      line>URL: http://tukaani.org/xz/
      line>Version: 5.2.3
      line>Cflags: -I${includedir}
      line>Libs: -L${libdir} -llzma
      line>Libs.private: -pthread
    Unknown keyword 'Libs.private' in '/usr/lib/pkgconfig/liblzma.pc'
    Path position of 'liblzma' is 1
    Adding 'liblzma' to list of known packages
    Package liblzma has -I/usr/include in Cflags
    Removing -I/usr/include from cflags for liblzma
    Package liblzma has -L /usr/lib in Libs
    Removing -L /usr/lib from libs for liblzma
     post-recurse: libarchive liblzma
    adding CFLAGS_OTHER string ""
     post-recurse: libarchive liblzma
     original: libarchive liblzma
       sorted: libarchive liblzma
    adding CFLAGS_I string ""
    returning flags string ""

**Comment by Rakashazi** [comment]
That's the debug output from the system pkg-config paths. I'm looking for the output with build system paths listed above, so the full command is:

`PKG_CONFIG_PATH=/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig: PKG_CONFIG_SYSTEM_INCLUDE_PATH= pkg-config libarchive liblzma --cflags --debug`

**Comment by rhester72** [comment]
Well, the inclusion of /usr/include is definitely coming from my system libarchive, which brings me back to my suspicion that it's the issue with libtool with the arm builds of libarchive:

    make[1]: Entering directory '/tmp/imagine-bundle/libarchive/build/android-armv7'
    make  all-am
    make[2]: Entering directory '/tmp/imagine-bundle/libarchive/build/android-armv7'
      CC       libarchive/archive_acl.lo
    libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-1, but the
    libtool: definition of this LT_INIT comes from libtool 2.4.6.40-6ca5-dirty.
    libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-1
    libtool: and run autoconf again.
    make[2]: *** [Makefile:5680: libarchive/archive_acl.lo] Error 63
    make[2]: Leaving directory '/tmp/imagine-bundle/libarchive/build/android-armv7'

because clearly libarchive.pc isn't present for armv7:

    Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
    Error printing enabled
    Adding virtual 'pkg-config' package to list of known packages                                                                       
    Looking for package 'libarchive'
    Looking for package 'libarchive-uninstalled'
    Reading 'libarchive' from file '/usr/lib/pkgconfig/libarchive.pc'
    Parsing package file '/usr/lib/pkgconfig/libarchive.pc'
      line>prefix=/usr
     Variable declaration, 'prefix' has value '/usr'
      line>exec_prefix=${prefix}
     Variable declaration, 'exec_prefix' has value '/usr'
      line>libdir=${exec_prefix}/lib
     Variable declaration, 'libdir' has value '/usr/lib'
      line>includedir=${prefix}/include
     Variable declaration, 'includedir' has value '/usr/include'
      line>
      line>Name: libarchive
      line>Description: library that can create and read several streaming archive formats
      line>Version: 3.3.2
      line>Cflags: -I${includedir}
      line>Libs: -L${libdir} -larchive
      line>Libs.private: -lcrypto -lacl -lexpat -llzma -llz4 -lbz2 -lz                                                                  Unknown keyword 'Libs.private' in '/usr/lib/pkgconfig/libarchive.pc'
    Path position of 'libarchive' is 3                                                                                                  Adding 'libarchive' to list of known packages
    Package libarchive has -L /usr/lib in Libs
    Removing -L /usr/lib from libs for libarchive
    Looking for package 'liblzma'
    Looking for package 'liblzma-uninstalled'
    Reading 'liblzma' from file '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/liblzma.pc'
    Parsing package file '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/liblzma.pc'
      line>
      line>
      line>
      line>
      line>
      line>
      line>
      line>prefix=${pcfiledir}/../..
     Variable declaration, 'prefix' has value '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../..
'
      line>exec_prefix=${pcfiledir}/../..
     Variable declaration, 'exec_prefix' has value '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/
../..'
      line>libdir=${pcfiledir}/../../lib
     Variable declaration, 'libdir' has value '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../..
/lib'
      line>includedir=${pcfiledir}/../../include
     Variable declaration, 'includedir' has value '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/.
./../include'
      line>
      line>Name: liblzma
      line>Description: General purpose data compression library
      line>URL: http://tukaani.org/xz/
      line>Version: 5.2.3
      line>Cflags: -I${includedir}
      line>Libs: -L${libdir} -llzma
      line>Libs.private:
    Unknown keyword 'Libs.private' in '/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/liblzma.pc'
    Path position of 'liblzma' is 1
    Adding 'liblzma' to list of known packages
     post-recurse: libarchive liblzma
    adding CFLAGS_OTHER string ""
     post-recurse: libarchive liblzma
     original: libarchive liblzma
       sorted: liblzma libarchive
     removing duplicate "-I/usr/include"
    adding CFLAGS_I string "-I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/i
nclude "
    returning flags string "-I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/i
nclude"
    -I/home/rhester/android/emu-ex-plus-alpha/imagine-sdk/android-armv7/lib/pkgconfig/../../include -I/usr/include

**Comment by Rakashazi** [comment]
Looks like liblzma is ok but libarchive didn't build for some reason. Try going into /tmp/imagine-bundle/libarchive/libarchive-3.3.2 and run:
`autoreconf --force --install`
Then delete the build directory /tmp/imagine-bundle/libarchive/build
After that, try running makeAll-android.sh and check if you still get the libtool error.

**Comment by rhester72** [comment]
Works!

Now what does that mean?  :)  Is there something misconfigured with my build environment?

**Comment by Rakashazi** [comment]
Thanks for confirming, after some more research it looks like there was an issue with version string in the libtool 2.4.6-1 Debian package that's probably causing the error. The version 2.4.6-2 package should fix it according to the changelog below:

https://launchpad.net/ubuntu/+source/libtool/2.4.6-2
