### ISSUE TITLE
[Issue]: MD.emu/Snes9x EX+: hq2x color bug on GPU Mali-450 (Open GL ES2.0)

### ISSUE THREAD

**Issue by Dim7x0** [Rakashazi/emu-ex-plus-alpha#1102]
### Describe the bug

Color inversion

### Steps to reproduce

in Video option turn on  - hq2x 

### Expected behavior

choose the hq2x shader, the picture is distorted, the colors of the picture in the emulator change, become darker. It seems that the firmware does not have something for this hq2x shader to work, or the emulator is crooked / does not fully support

### Add screenshots

befor ![22828283](https://user-images.githubusercontent.com/124557589/217717825-becb384c-a8ac-4ea9-a8e9-f8579cc0a718.png)

after
![22828282](https://user-images.githubusercontent.com/124557589/217717878-176e525b-b801-472d-a446-301fa4c01890.png)

**Comment by Rakashazi** [comment]
Thanks for the report, can you tell me the exact device and Android version it's running?

**Comment by Dim7x0** [comment]
Brand: Minix 
Model: NEO U1 
System: Android 5.1.1 
GPU: Mali-450 
CPU: Amlogic S905

**Comment by Dim7x0** [comment]
TV BOX: H96MAX 
Android 11
GPU: Mali-450

**Comment by Rakashazi** [comment]
I was able to test on this GPU and should have a fix in the next update.

**Comment by Dim7x0** [comment]
You are very responsible thank you for improving this product

**Comment by Rakashazi** [comment]
No problem and thanks for the feedback, the nighty builds should have the fix now.
