### ISSUE TITLE
[Issue]: c64.emu keyboard lacks cursor movement option (up, down, left, right) that have worked before.

### ISSUE THREAD

**Issue by tokariu** [Rakashazi/emu-ex-plus-alpha#1104]
### Describe the bug

somehow the new keyboard in c64.emu has changed how cursor arrows work. 

before you could go DOWN and RIGHT with the cursor and while switching the keyboard back to hit SHIFT and then go back to press down and right you could go UP and LEFT.

however, in the latest version this doesnt work anymore. hitting the keys in the c64 console don't even show the appropriate arrows being entered but some other chars.

also the design of the keyboard has changed, it doesn't even show UP/DOWN and LEFT/RIGHT. it shows only LEFT and UP

![c64-emu](https://user-images.githubusercontent.com/7195846/217963935-192f37f0-8139-4ea2-8f9f-47e984c35af0.png)
(left: the older version, right: the latest preview)

### Steps to reproduce

compare latest preview with older versions.

### Expected behavior

Cursor movement like in older versions.

**Comment by Rakashazi** [comment]
Hi, in the current C64.emu version the cursor keys are accessed via the d-pad by setting Joystick Mode -> Keyboard Cursor. In a future update you'll be able to customize the keyboard and add them there as well but the current method should easier to use than having to use shift + the keyboard key in the older versions.

**Comment by tokariu** [comment]
Yes I noticed the D-Pad method. However, it turned out to be cumbersome. Imagine having to toggle values in a list line by line with the arrow keys and "ENTER". in that case you'll always have to switch between D-Pad and keyboard for each line... with the old keyboard I could just hit shift one time, and then use UP and enter in the same place.

looking forward for the customizable keyboard then!
