### ISSUE TITLE
[Regression][1.5.37]Reset not working

### ISSUE THREAD

**Issue by BlueMax** [Rakashazi/emu-ex-plus-alpha#113]
The 'Reset' functions (soft/hard) are not working anymore in 1.5.37. Previous version 1.5.34 is ok.

It's kinda useful and important as it's (to my knowledge) the only way to start other programs on a disk beside '*’ (load disk, reset, dir, load, run). Custom roms like Speeddos are useful here (F7, F5, F3 = dir, load, run) even though moving the cursor with current osd keyboard is somewhat frustrating.

**Comment by Rakashazi** [comment]
Thanks, reset function wasn't exported properly after updating to VICE 3.1, fixed in upcoming 1.5.38 release.

**Comment by BlueMax** [comment]
Not sure if the fix is complete yet but the commit 372023d99fdcaef9fd4b8e447ad29eaac5e18a50 (C64.emu: Fix missing VICE_API on machine_trigger_reset()) doesn't fix it. I've compiled master and it still doesn't work.
