### ISSUE TITLE
[Issue]: GBC.emu / Snes9x Ex+  on-screen d-pad/button position adjustments are not saved and reset each start.

### ISSUE THREAD

**Issue by tokariu** [Rakashazi/emu-ex-plus-alpha#1132]
### Describe the bug

adjusting the on-screen keyboard is not saved with GBC.emu. (Edit: also happens with Snex9x Ex+) 
i can rearrange buttons and spacing, but after a restart, everything is back to default. 
also: the controls are hidden on each start, it shows just black space until I tap one time with the finger on the black space, then the on-screen buttons show up.

I also notice the app doesn't ask for any permissions like access to storage. it only asks for folder access when trying to open a rom. 

either it does not try to save the button layouts or it doesn't ask for write permissions and then fails.

### Steps to reproduce

1. open GBC.emu
2. adjust on-screen buttons, position, spacing.
3. restart the app

-> reset back to default.

### Expected behavior

settings should be saved.

**Comment by TortugaV6SC** [comment]
Happens with the NGPEMU also.

**Comment by Rakashazi** [comment]
Fixed in last commit
