### ISSUE TITLE
[Android][NGP.EMU]Two roms freeze

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#114]
SNK Gals Fighters
Freeze in fighting soon. Maybe press key too fast.It's fine in NeoPop.
King of Fighters, The - Battle De Paradise
After about turn 10 or more,appear some mosaics,then freeze.The same in NeoPop.
These roms' bgm are fine when they freeze.

**Comment by leoxxx** [comment]
I try 1.5.37. It's more terrible. Freeze sooner than before and crash.

**Comment by leoxxx** [comment]
https://github.com/libretro/beetle-ngp-libretro/issues/43#issuecomment-478035190
SNK Gals Fighters can be fixed.

**Comment by Rakashazi** [comment]
Closing out some old issues, all freezing issues should be fixed.
