### ISSUE TITLE
[Question]: Saturn.emu

### ISSUE THREAD

**Issue by maiodin** [Rakashazi/emu-ex-plus-alpha#1152]
### Describe your question

I see saturn.emu in "the code" but dont see it in release as an apk.

Would apreciate it if it was downloadabke and usable 

Thabk you

**Comment by soundsnow** [comment]
2016-May-01
[Yabause Latest Android](https://download.tuxfamily.org/yabause/releases/travis-ci/yabause-latest-android.apk)
armeabi-v7a 32bit only
no arm64-v8a 64bit

**Comment by Rakashazi** [comment]
As of version 1.5.77, Saturn.emu is now based on Mednafen and is fully supported along with the other .emu apps here and on Google Play.
