### ISSUE TITLE
[Android] [snes9x ex+] (Input Lag)

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#116]
snes9x ex+ has input lag when using a bluetooth controller (about a second after input is pressed input is recognized, it gets worse the more you press) (using - 8bitdo sn30 bluetooth controller)

**Comment by Rakashazi** [comment]
Closing out some old issues, input handling code is now fully optimized so any additional latency will be from the OS/hardware layer.
