### ISSUE TITLE
[Issue]: Custom Button Positions Cannot Be Saved

### ISSUE THREAD

**Issue by XiaErrr** [Rakashazi/emu-ex-plus-alpha#1166]
### Describe the bug

I'm not absolutely sure if this is a bug or an intended feature but since this didn't happen to me on a previous version of the emulator I'm going to tentatively mark it as a "bug"

I recently installed the latest ( i think ) version of the Snes9x EX+ emulator ( 1.5.67 ) for Android which i got from this github that came with the EX emulators bundle ( around 75MB ) 

The first thing i did was to re-arrange the on-screen gamepad buttons to a position which made it more comfortable for me to play with.. But after closing and opening the app again the buttons returned to their defaults position ( which made me feel awful since i spent a considerable amount of time to get the buttons to the exact position i liked ) 

I tried a couple of times after that but every time the system returned the buttons to the default position after i closed the app.

I had a previous version of the Snes9x EX+ emulator which was capable of remembering the custom position of the buttons and i find it weird that the latest version of the emulator that i installed is unable to do the same ( so the idea that this could be a "bug" )

If the feature to automatically reset the button positions cannot be removed ( bringing back the old method ) i wish there was at least an option to save a particular button configuration in a separate file so it can be loaded for future playing sessions thus counteracting the roll back that the system does ( on purpose? )

I'm running android 5.1 on my ZTE ZMAX 2 (Z955A)

### Steps to reproduce

as mentioned above.

### Expected behavior

as mentioned above.

**Comment by Rakashazi** [comment]
The nightly builds here have in-development code which may be incomplete, as was the case with the new virtual controls which are currently being worked on. I added support for saving the controller state in the last commit so if you do run into issues with something not saving properly feel free to post an issue about that.
