### ISSUE TITLE
[Android] [bundle] Problem linking liblzma on "first build"

### ISSUE THREAD

**Issue by kevbo-oh** [Rakashazi/emu-ex-plus-alpha#119]
emu-ex-plus-alpha/imagine/bundle/all/makeAll-android.sh is failing when building libarchive for armv7:

common.mk:47: recipe for target '/tmp/imagine-bundle/libarchive/build/android-armv7/Makefile' failed
make: *** [/tmp/imagine-bundle/libarchive/build/android-armv7/Makefile] Error 77

From the config.log:

configure:4002: checking whether the C compiler works
configure:4024: /home/kwhite/android/android-ndk-r17-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -DNDEBUG -DANDROID --sysroot=/home/kwhite/android/android-ndk-r17-beta2/sysroot -isystem /home/kwhite/android/android-ndk-r17-beta2/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -DANDROID_COMPAT_API -std=gnu99 -fno-common -target armv7-none-linux-androideabi -gcc-toolchain /home/kwhite/android/android-ndk-r17-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -I/home/kwhite/imagine-sdk/android-armv7/lib/pkgconfig/../../include  -target armv7-none-linux-androideabi -gcc-toolchain /home/kwhite/android/android-ndk-r17-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -Wl,--fix-cortex-a8 -flto -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -fno-integrated-as -ffunction-sections -fdata-sections --sysroot=/home/kwhite/git/emu-ex-plus-alpha/imagine/bundle/android-9/arch-arm -no-canonical-prefixes -Wl,--no-undefined,-z,noexecstack,-z,relro,-z,now -s -Wl,-O3,--gc-sections,--compress-debug-sections=zlib,--icf=all,--as-needed  -lm -L/home/kwhite/imagine-sdk/android-armv7/lib/pkgconfig/../../lib -llzma conftest.c  >&5
/home/kwhite/android/android-ndk-r17-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: lzma: no archive symbol table (run ranlib)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So, that's an error with the liblzma made just prior.  Comparing the build log between armv7 (which fails) and arm64 (which passes), I notice a difference:

armv7:

libtool: link: ranlib .libs/liblzma.a
libtool: link: ( cd ".libs" && rm -f "liblzma.la" && ln -s "../liblzma.la" "liblzma.la" )
rm -f liblzma.pc
sed \
        -e 's,@prefix[@],${pcfiledir}/../..,g' \
        -e 's,@exec_prefix[@],${pcfiledir}/../..,g' \
        -e 's,@libdir[@],${pcfiledir}/../../lib,g' \
        -e 's,@includedir[@],${pcfiledir}/../../include,g' \
        -e 's,@PACKAGE_URL[@],http://tukaani.org/xz/,g' \
        -e 's,@PACKAGE_VERSION[@],5.2.3,g' \
        -e 's,@PTHREAD_CFLAGS[@],,g' \
        -e 's,@LIBS[@],,g' \
        < /tmp/imagine-bundle/xz/xz-5.2.3/src/liblzma/liblzma.pc.in > liblzma.pc || { rm -f liblzma.pc; exit 1; }

arm64:
libtool: link: /home/kwhite/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar s .libs/liblzma.a
libtool: link: ( cd ".libs" && rm -f "liblzma.la" && ln -s "../liblzma.la" "liblzma.la" )
rm -f liblzma.pc
sed \
        -e 's,@prefix[@],${pcfiledir}/../..,g' \
        -e 's,@exec_prefix[@],${pcfiledir}/../..,g' \
        -e 's,@libdir[@],${pcfiledir}/../../lib,g' \
        -e 's,@includedir[@],${pcfiledir}/../../include,g' \
        -e 's,@PACKAGE_URL[@],http://tukaani.org/xz/,g' \
        -e 's,@PACKAGE_VERSION[@],5.2.3,g' \
        -e 's,@PTHREAD_CFLAGS[@],,g' \
        -e 's,@LIBS[@],,g' \
        < /tmp/imagine-bundle/xz/xz-5.2.3/src/liblzma/liblzma.pc.in > liblzma.pc || { rm -f liblzma.pc; exit 1; }

Note that armv7 uses (what I presume is) the box's 'ranlib', while arm64 uses ar from the NDK's toolchain.

Other 'libtool: link' lines in the armv7 build process use the NDK's ar, so I think that's the problem.

I tried this with both the most recent NDK that Studio will download (16), and the most recent 17 beta (which imagine/doc/INSTALL-Android says should be used).  Both acted the same.

I'm attempting the build on a Ubuntu 17-10 Server box.  It is a vanilla install, only adding this:

sudo apt-get install openjdk-8-jre-headless unzip make pkg-config automake libtool-bin

which were all needed to get the build to work.

In gathering data to make this report, I discovered that the problem may not be in armv7, but instead, may be in the "first" architecture that is built.  makeAll-android.sh builds armv7 first, them arm64.  If I do a "reset":

rm -rf /tmp/imagine-bundle
rm -rf ~/imagine-sdk

and then manually call makeAll-android-arm64.sh and makeAll-android-armv7.sh (without "resetting" in between), whichever one is called first fails, and second, works.

Here is the link line from building armv7 when run _after_ a failed arm64 build:
libtool: link: /home/kwhite/android/android-ndk-r17-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar s .libs/liblzma.a

Finally, I made the system ranlib disappear (renamed it), cleared everything out again, and ran the armv7 build.  It failed, differently:

libtool: link: : .libs/liblzma.a

In this same situation, if the arm64 build is run first, it fails, and a subsequent armv7 build succeeds.  In other words, the first build after a cleaning fails, the second succeeds.

So, it appears, on ubuntu 17.10, the _first_ liblzma build will mistakenly not use the NDK's ar to do a link.  Subsequent builds seem to do the correct thing.

**Comment by kevbo-oh** [comment]
I've done some more testing.  I tried NDK 17 Beta 1 (since Beta 2 probably didn't exist when the last checkin to this repo happened).  It didn't change anything.

I've created a process to try to get around this.  I run the normal "makeAll-android.sh" script, which will result in an imagine-sdk bundle that has a completely-compiled "android-arm64" and "android-x86".  Then, I rename the imagine-sdk folder and remove /tmp/imagine-bundle, and create a "makeAll-android.sh" script that builds arm64 first, followed by armv7.  This will result in an incomplete arm64, but a complete armv7.  I then combine the complete versions of all 3 into imagine-sdk, and continue on with the build.

While this lets me continue on with the build, I can't actually successfully build any of the android-15 emulators.  The resulting arm64 libraries have another problem, and I haven't been able to figure it out.  The android-9 builds create .apk files (that don't work on my nVidia Shield nor my Essential Phone, but I think that's because they're both 64-bit devices.)  The android-9 apk file does work in an emulator from Android Studio.

The android-15 builds die like this (for Snes9x):
Linking target/android-15/src/main/jniLibs/arm64-v8a/libmain.so
/home/kwhite/android/android-ndk-r17-beta1/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: error: archive: no archive symbol table (run ranlib)
./src/io/ArchiveIO.cc:43: error: undefined reference to 'archive_entry_pathname'
./src/io/ArchiveIO.cc:50: error: undefined reference to 'archive_entry_filetype'
./src/io/ArchiveIO.cc:56: error: undefined reference to 'archive_entry_size'
./src/io/ArchiveIO.cc:133: error: undefined reference to 'archive_read_data'
./src/io/ArchiveIO.cc:165: error: undefined reference to 'archive_seek_data'
./src/io/ArchiveIO.cc:56: error: undefined reference to 'archive_entry_size'
./src/fs/ArchiveFS.cc:65: error: undefined reference to 'archive_read_new'
./src/fs/ArchiveFS.cc:46: error: undefined reference to 'archive_read_support_format_7zip'
./src/fs/ArchiveFS.cc:47: error: undefined reference to 'archive_read_support_format_rar'
./src/fs/ArchiveFS.cc:48: error: undefined reference to 'archive_read_support_format_zip'
./src/fs/ArchiveFS.cc:113: error: undefined reference to 'archive_read_set_seek_callback'
./src/fs/ArchiveFS.cc:150: error: undefined reference to 'archive_read_open2'
./src/fs/ArchiveFS.cc:157: error: undefined reference to 'archive_error_string'
./src/fs/ArchiveFS.cc:204: error: undefined reference to 'archive_read_next_header'
./src/fs/ArchiveFS.cc:213: error: undefined reference to 'archive_error_string'
./src/fs/ArchiveFS.cc:219: error: undefined reference to 'archive_error_string'
./src/fs/ArchiveFS.cc:69: error: undefined reference to 'archive_read_free'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
/home/kwhite/git/emu-ex-plus-alpha/imagine/make/imagineAppTarget.mk:30: recipe for target 'target/android-15/src/main/jniLibs/arm64-v8a/libmain.so' failed

I'm wondering if there's something "off" about this Ubuntu environment.  I've tried builds on Fedora 27 and also had problems.

What environment do you use to make the official releases?  I'm certainly willing to try other environments if that might help.  Ubuntu-16.4?

I have kept copious notes on the commands/steps I've run, and I can generate full log files of builds.  I've done these builds many many times and consistently get the same results.

**Comment by AveyondFly** [comment]
Yes, met the similar issue and cost the whole good weekend.……
ubunt 18.04
ndk 17
need aarch arm64
Seems clang generated the llvm binary but not arm64 in bundle.

**Comment by bladeoner** [comment]
@kevbo-oh @AveyondFly did you guys managed to get further compiling?

With NDK 17 and 18 I see the same issues on Ubuntu.

**Comment by Rakashazi** [comment]
This issue should be fixed when using the most up to date Android NDK.
