### ISSUE TITLE
GPU copy mode auto setting not optimal on MT6737 device

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#123]
I tested Snes9x and NES.emu with a Bush Spira D5 phone (a rebranded Archos Sense 50DC). Mediatek MT6737, Mali-T720 GPU, Android 7.0. Display refresh rate reported as 64.4Hz(!).

For this device, the emulators use a sub-optimal GPU copy mode for "Auto": surface texture. With that, I hear sound glitches and frames are duplicated (with skip late frames off). When copy mode is set to standard it's much better. [The emulator says graphic buffer isn't supported by the GPU.]

**Comment by Rakashazi** [comment]
Closing out some old issues, GPU copy modes have been optimized.
