### ISSUE TITLE
[Issue]: Libpng error when compiling

### ISSUE THREAD

**Issue by hilltop804** [Rakashazi/emu-ex-plus-alpha#1231]
### Describe the bug

When compiling, there is a redefinition error related to png_err

![image](https://user-images.githubusercontent.com/41207087/223011012-1c0dffb8-d678-4731-b635-9eb661eb2a13.png)

### Steps to reproduce

Run imagine/linux-x86_64-release.mk on Ubuntu 22.10 x64

### Expected behavior

Compile completes without error

### Add screenshots

I think it's related to this code in imagine-sdk/linux-x86_64/include/libpng16/png.h

![image](https://user-images.githubusercontent.com/41207087/223011100-61074f54-6d34-4efc-855f-a884c300b0c8.png)

**Comment by Rakashazi** [comment]
Thanks for the report, I hadn't updated the bundle libpng files in a while but it should be fixed now if you rebuild and install it. Alternatively, if your Linux install already has libpng 1.6 installed, delete the libpng.pc and libpng16 header files in imagine-sdk to link with the system libpng instead.

**Comment by TheBoxGamePL** [comment]
@Rakashazi why are you ignoring me add these 2 mappers 134.cpp and 176.cpp to src/fceu/boards specially I will give you 2 pages with c++ codes for those mappers you need
