### ISSUE TITLE
[iOS] Screen rotation issues

### ISSUE THREAD

**Issue by yoshisuga** [Rakashazi/emu-ex-plus-alpha#124]
On the iPhone XS Max, the screen size doesn't appear to be correct on startup and rotation results in some further mis-sizing and rotating.

I found build instructions to build for iOS in another issue and was super helpful:
https://github.com/thededman/emu-ex-plus-alpha/wiki/emu-ex-plus-alpha-How-to-build-(MacOSX--XCode-Only)

I went down the rabbit hole to see how this worked, and ended up at the cross-platform imagine framework. It looks like it's like SDL in that it implements the cocoa touch api's at the platform level.

I'm guessing the `IOSWindow::updateContentRect` method in `imagine/src/base/iphone/IOSWindow.mm` might be the cause. I'd like to fix it but is there a way to attach a debugger to this? It'd be nice to be able to step through without having to wait and rebuild the base stack every time.

**Comment by Rakashazi** [comment]
I haven't yet tested on the iPhone XS Max, but the recent commit has new framebuffer handling code for iOS that may or may not help the issue. Let me know if there's any change with it.

**Comment by ck16** [comment]
I can confirm the screen rotation issues still exist on an iPhone XS Max (iOS 12 and 12.0.1) with all emulators (except C64.emu which I'm not able to run).

**Comment by yoshisuga** [comment]
I got around the screen rotation issues by selecting landscape orientations only in the "Deployment Info" section when configuring the target in xcode. This makes it work only in landscape mode, but it at least is more usable.

I can't get C64.emu to run either - crashes on startup too.

**Comment by ck16** [comment]
Hi @yoshisuga,

Are you able to provide updated Xcode project for the emulators?  I've been using the shell projects from thededman's project for many years, but they don't seem to work any more for me in the latest version of Xcode/macOS Big Sur.

Adding them to the main project would be helpful to many people trying to compile these emulators.

Thanks in advance!


Regards,
ck16
