### ISSUE TITLE
[Feature request]: hide instead of color change

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1242]
### Describe the feature

Some features may not be used for a long time, but the emulator keeps showing them
Showing FDS Control is a waste of pixels when you don't have FDS BIOS, or when you only play NES games.  Another example, for people who don't like manually Load State, shows that it is a complete waste, because no States are saved manually. Do all SNES games support SuperFX?  Because I can find it after opening every game. I am using MVS BIOS, but the emulator still displays the Unibios Option on the screen. That's not all, there are many more that I haven't listed. There's a lot more than that, when you're doing one thing, you can't do another, or have to finish something else before you can do that.  One exception is State Slots, since each of them can be saved. When you select a saved slot, Load State will appear, otherwise it will disappear.

**Comment by Rakashazi** [comment]
FDS control is now hidden when disk system isn't in use
