### ISSUE TITLE
[Feature request]: All emulators built-in full featured virtual keyboard big update

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1244]
### Describe the feature

The best way to solve input devices, add a virtual modern PC keyboard

All I can say is that reinventing the wheel is such a pain.  Since these emulators were originally developed for PC, why not include a fully customizable keyboard?  Similar to the PC version, all presets can be implemented, including keyboard shortcuts, and you can add a keyboard shortcut manager.  Another example is MSX and C64, which have their own keyboards, so the keys of the emulator should be bound to the keyboard.  If I want to use buttons other than the Gamepad, I can just select Port and bind each button.  As long as the keyboard has enough keys, I can bind all the keys of all Ports.  The following Virtual Keyboard is from Magic DosBox, which provides a complete solution for mouse and keyboard

For example this is Snes9x's default keyboard Gamepad Port 1 preset
up:up, down:down, left:left, right:right, enter:start, rshift:select, z:b, x:a, a:y, s:x, q:l, w:r
I can use the virtual keyboard to achieve the same operation as the PC version

Most of the controllers in the PC version of the emulator are bound, and there is no need to add virtual buttons for each button of each control, because it is too tiring

For example, the shortcut key for Save State: Slot 0 is Ctrl+F1, and the shortcut key for Load State: Slot 1 is F1. I can use the virtual keyboard to achieve it

Only allow us to add the virtual buttons you created, which is equivalent to limiting our thinking
Adding a full virtual keyboard to each emulator allows most PC emulators to operate

I know @Rakashazi  can't create PNGs for all input devices, so adding a virtual keyboard solves this perfectly

I can add the keys I want to use to the screen, and I can change the size and position of each key.  Hide or show certain keys when I don't want to use them

### Add screenshots

![image135](https://user-images.githubusercontent.com/109885044/224236796-424d7787-8d67-4ade-a2ae-e4e61c098c3e.png)
![image136](https://user-images.githubusercontent.com/109885044/224236830-4c1af9b3-3fe4-40b5-a9e1-f551c5005c79.png)
![image137](https://user-images.githubusercontent.com/109885044/224236863-67a1db3a-048e-4618-84da-88d6e354e047.png)
![image138](https://user-images.githubusercontent.com/109885044/224237105-2929665c-c35c-4d70-86b6-dd044caee0e6.png)
![image139](https://user-images.githubusercontent.com/109885044/224237112-4cd1fb65-d95b-4eb3-98c2-486c4e2c6000.png)
![image140](https://user-images.githubusercontent.com/109885044/224237115-eb37caf7-6211-40ce-bb8b-808a9bfeb84a.png)

**Comment by soundsnow** [comment]
![image141](https://user-images.githubusercontent.com/109885044/224243644-82aeed3d-0b44-4850-8fc3-c3c6d29c8e23.png)

**Comment by soundsnow** [comment]
ctrl+alt+l
ctrl+c
ctrl+v

**Comment by soundsnow** [comment]
Please don't show them as MSX keyboards, show them as modern keyboard keys for commonality of all emulator virtual keyboards.  You can see their real key names in the port key binding interface

#### Keyboard

| Modern Keyboard         | MSX Keyboard         |
|------------------------------|-----------------------|
| Keyboard Backspace           | BACKSPACE             |
| Keyboard Tab                 | TAB                   |
| Keyboard Return              | RETURN                |
| Keyboard Pause               | PAUSE                 |
| Keyboard Escape              | ESCAPE                |
| Keyboard Space               | SPACE                 |
| Keyboard Quote '             | COLON                 |
| Keyboard Comma ,             | COMMA                 |
| Keyboard Minus -             | NEGATIVE              |
| Keyboard Period .            | PERIOD                |
| Keyboard Slash /             | DIVIDE                |
| Keyboard 0                   | 0                     |
| Keyboard 1                   | 1                     |
| Keyboard 2                   | 2                     |
| Keyboard 3                   | 3                     |
| Keyboard 4                   | 4                     |
| Keyboard 5                   | 5                     |
| Keyboard 6                   | 6                     |
| Keyboard 7                   | 7                     |
| Keyboard 8                   | 8                     |
| Keyboard 9                   | 9                     |
| Keyboard Semicolon ;         | SEMICOLON             |
| Keyboard Equals =            | CIRCUMFLEX            |
| Keyboard Left Bracket [      | LEFT BRACKET          |
| Keyboard Backslash \         | BACKSLASH (YEN)       |
| Keyboard Right Bracket ]     | RIGHT BRACKET         |
| Keyboard Backquote `         | AT                    |
| Keyboard a                   | A                     |
| Keyboard b                   | B                     |
| Keyboard c                   | C                     |
| Keyboard d                   | D                     |
| Keyboard e                   | E                     |
| Keyboard f                   | F                     |
| Keyboard g                   | G                     |
| Keyboard h                   | H                     |
| Keyboard i                   | I                     |
| Keyboard j                   | J                     |
| Keyboard k                   | K                     |
| Keyboard l                   | L                     |
| Keyboard m                   | M                     |
| Keyboard n                   | N                     |
| Keyboard o                   | O                     |
| Keyboard p                   | P                     |
| Keyboard q                   | Q                     |
| Keyboard r                   | R                     |
| Keyboard s                   | S                     |
| Keyboard t                   | T                     |
| Keyboard u                   | U                     |
| Keyboard v                   | V                     |
| Keyboard w                   | W                     |
| Keyboard x                   | X                     |
| Keyboard y                   | Y                     |
| Keyboard z                   | Z                     |
| Keyboard Delete              | DELETE                |
| Keyboard Keypad 0            | NUMPAD 0              |
| Keyboard Keypad 1            | NUMPAD 1              |
| Keyboard Keypad 2            | NUMPAD 2              |
| Keyboard Keypad 3            | NUMPAD 3              |
| Keyboard Keypad 4            | NUMPAD 4              |
| Keyboard Keypad 5            | NUMPAD 5              |
| Keyboard Keypad 6            | NUMPAD 6              |
| Keyboard Keypad 7            | NUMPAD 7              |
| Keyboard Keypad 8            | NUMPAD 8              |
| Keyboard Keypad 9            | NUMPAD 9              |
| Keyboard Keypad Period .     | NUMPAD COMMA          |
| Keyboard Keypad Divide /     | NUMPAD DIVIDE         |
| Keyboard Keypad Multiply *   | NUMPAD MULTIPLY       |
| Keyboard Keypad Minus -      | NUMPAD SUBTRACTION    |
| Keyboard Keypad Plus +       | NUMPAD ADD            |
| Keyboard Keypad Enter        | NUMPAD PERIOD         |
| Keyboard Up                  | UP                    |
| Keyboard Down                | DOWN                  |
| Keyboard Right               | RIGHT                 |
| Keyboard Left                | LEFT                  |
| Keyboard Insert              | INSERT                |
| Keyboard Home                | CLS                   |
| Keyboard End                 | STOP                  |
| Keyboard Page Up             | SELECT                |
| Keyboard F1                  | F1                    |
| Keyboard F2                  | F2                    |
| Keyboard F3                  | F3                    |
| Keyboard F4                  | F4                    |
| Keyboard F5                  | F5                    |
| Keyboard Caps Lock           | CAPS                  |
| Keyboard Right Shift         | RIGHT SHIFT           |
| Keyboard Left Shift          | LEFT SHIFT            |
| Keyboard Left Control        | CONTROL               |
| Keyboard Left Alt            | GRAPH                 |
| Keyboard Print               | PRINT                 |

**Comment by soundsnow** [comment]
Some of these keys have three states
1. Stateless
2. Press lAlt, Caps Lock, lCtrl, lShift, rAlt, rCtrl, rShift, they will turn gray, release these keys, and the letters, numbers, and symbols will change at this time, you can input without pressing the previous key  changed text
Caps Lock and Shift in the screenshot are a key, so numbers, symbols, and letters change at the same time
3. Press the previously mentioned keys twice, and all text entered after that will be changed.  Undoing this just needs to be pressed again, and they will change from gray to purple to the original color
![Screenshot_20230310-172700_Trebuchet](https://user-images.githubusercontent.com/109885044/224282890-7b033685-f6f1-4152-8796-114db5249a2b.png)
![Screenshot_20230310-172802_Trebuchet](https://user-images.githubusercontent.com/109885044/224282900-e38b2e17-b6a9-470a-9643-e7f0a9f20ae1.png)

**Comment by soundsnow** [comment]
Several other keys will also be affected by this, num lock will make 7, 8, 9, 4, 6, 1, 2, 3,. become Home, Left, Right, Up, Down, End, Page Up, Page  Down, Delete
Since num lock is not held down, its color will not change
![image143](https://user-images.githubusercontent.com/109885044/224287274-818c10f7-b637-45ec-9ba9-6cc3bc19a967.png)

**Comment by TheBoxGamePL** [comment]
why rakshazi don't want to add nsf player and mappers 134 176 205 342

**Comment by TheBoxGamePL** [comment]
these mappers 134 176 205 and 342 mapper coolgirl is but there is no mapper 342 there is no and they should be in fceux

**Comment by SuperWillow** [comment]
> ![image141](https://user-images.githubusercontent.com/109885044/224243644-82aeed3d-0b44-4850-8fc3-c3c6d29c8e23.png)

Лол. Кривой фотошоп слева:)

**Comment by SuperWillow** [comment]
> ![image141](https://user-images.githubusercontent.com/109885044/224243644-82aeed3d-0b44-4850-8fc3-c3c6d29c8e23.png)

А как же чайник с функцией Жопа
