### ISSUE TITLE
Swan.emu seems couldn't write SRAM data correctly when save second time.

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1250]
I play Final Fantasy game, save first time then reload ROM, it's normal, the emulator and game loaded my save. But when I try save second time, then reload ROM, my progress won't be saved and it shows my previous save (first time saving)...

**Comment by Rakashazi** [comment]
I just tested out the original Final Fantasy and it saved correctly after multiple ROM loads. Were you using any save states or just the game's backup RAM?

**Comment by Yave-Yu** [comment]
> I just tested out the original Final Fantasy and it saved correctly after multiple ROM loads. Were you using any save states or just the game's backup RAM?

I won't use savestate, just backup RAM.
My system settings: Main Slot (No State), Off, Only Backup RAM.
In other emu it works normally, only Swan.emu I met this issue. Everytime I play FF2 raised character much stronger, then save... but next time load, it backed to previous save that has weaker state.
Also I wonder, why SRAM file has long key (MD5?) value on filename?

**Comment by Rakashazi** [comment]
Thanks for the info. Swan.emu didn't trigger Backup RAM writes in-game so it's possible the app didn't shutdown fully and the save file wasn't updated. I just updated it to save backup RAM as it's written to in-game so please test this new version and check if you still get any data loss.

About the MD5 text, it's to match the save files with Mednafen in case you want to share save games with it on a PC, but I'll add an option in the future to use simple filenames.
