### ISSUE TITLE
[Question]:New Mappers and nsf nes.emu 1.5.69

### ISSUE THREAD

**Issue by TheBoxGamePL** [Rakashazi/emu-ex-plus-alpha#1251]
### Describe your question

Hi @Rakashazi  will you add nsf player and mappers 176 342 134 205

**Comment by Rakashazi** [comment]
I'm currently working on other features and don't have time to work on nsf support and mappers, but they may be added in a future update. Do not spam any more issues for these or you will be banned.

**Comment by TheBoxGamePL** [comment]
Ok thanks

sob., 11 mar 2023, 09:31 użytkownik Rakashazi ***@***.***>
napisał:

**Comment by TheBoxGamePL** [comment]
thank you very much for the other mappers because now I can play nes games
on android :

sob., 11 mar 2023, 13:22 użytkownik TheBoxGamePL ***@***.***>
napisał:

**Comment by TheBoxGamePL** [comment]
you update to nes.emu
you know what just add mappers and nsf you will add another time for the
nsf function se I'll wait
in the next update i will give you rom names i need just don't ban me please

niedz., 12 mar 2023, 09:35 użytkownik TheBoxGamePL ***@***.***>
napisał:

**Comment by TheBoxGamePL** [comment]
Please
7-in-1 (YH708) mapper 134
Super 188-in-1 (BS-6013) (Unl) mapper 176
15-in-1 [p1] mapper 205
7-IN-1(MMK-02E-00) mapper 342

niedz., 12 mar 2023, 09:37 użytkownik TheBoxGamePL ***@***.***>
napisał:

**Comment by TheBoxGamePL** [comment]
hello rakshazi will you update mappers for NES.Emu to add mapper 134 176
342 256 please don't ban me, i was just asking

**Comment by TheBoxGamePL** [comment]
rakashazi, will you add them in the next update so I can run this normally
without glitches
7-in-1 (YH708) Mapper 134
Super 188-in-1 (BS-6013) (Unl) Mapper 176
NEW 7-IN-1(MMK-024-01) coolgirl Mapper 342
dreamGEAR Plug 'N' Play 50 Classic & Racing Games (DGUN-853) Mapper 256

**Comment by TheBoxGamePL** [comment]
hello, I have a question, will you update these mappers that I mentioned
many times, please don't ban me

**Comment by TheBoxGamePL** [comment]
Please add this mapper

**Comment by TheBoxGamePL** [comment]
hello I have a question if you could add this one mapper 134 for now

iNES Mapper 134 denotes an MMC3 <https://www.nesdev.org/wiki/MMC3>-clone-based
multicart PCB referred to alternatively as T4A54A, WX-KB4K, or BS-5652.

2-in-1 Family Kid & Aladdin 4
Super Cool Boy 4-in-1 (CB-4034) (commonly-available ROM file has been
hacked to run as INES Mapper 044
<https://www.nesdev.org/wiki/INES_Mapper_044>)
Super Cool Boy 4-in-1 (CB-4035)
Super 4-in-1 1998 (JH-274)
1998 HIGH 4-in-1 (YH-463)

Contents
1 Mode Register ($6000, write)
2 Outer Bank Register ($6001, write)
3 CNROM register ($6002, write)
4 Unknown Register ($6003, write)
5 MMC3-compatible registers ($8000-$FFFF)
Mode Register ($6000, write)
Mask: $E003
D~7654 3210

LDcp C...
|||| +---- CHR-ROM banking mode
|||| 0: MMC3 (inner banks from $8000.0-$8000.5)
|||| 1: CNROM (8 KiB inner bank from $6002)
|||+------ PRG A19
||+------- CHR A19
|+-------- CPU $8000-$FFFF mode
| 0: PRG-ROM
| 1: Read solder pad setting
+--------- $6xxx Register Lock (except $6002.0-1)
0: unlocked
1: locked, further writes ignored until reset
Outer Bank Register ($6001, write)
Mask: $E003
D~7654 3210

NcCC npPP
|||| ||++- PRG A18..17
|||| |+--- Outer PRG Bank Size
|||| | 0: 256 KiB, PRG A17 from MMC3
|||| | 1: 128 KiB, PRG A17 from $6001 bit 0
|||| +---- PRG A14 mode in NROM mode ($6001 bit 7=1)
|||| 0: PRG A14=CPU A14 (NROM-256)
|||| 1: PRG A14=MMC3 PRG A14 (NROM-128)
||++------ CHR A18..17
|+-------- Outer CHR Bank Size
| 0: 256 KiB, CHR A17 from MMC3
| 1: 128 KiB, CHR A17 from $6001 bit 4
+--------- PRG-ROM banking mode
0: MMC3
1: NROM
In NROM mode, the MMC3 clone's CPU A13 and A14 inputs are held low, so that
MMC3 register 6 applies to the entire CPU $8000-$FFFF range, with PRG A13
substituted by CPU A13 and PRG A14 subject to $6001.3.

CNROM register ($6002, write)
Mask: $E003
Contains the 8 KiB CHR-ROM bank if $6000.3=1, masked to 128 or 256 KiB
according to $6000.6. Bits 0-1 respond even if the "Lock" bit is set, while
changes to bits 2-7 will be ignored if the "Lock" bit has been set.

Unknown Register ($6003, write)
Mask: $E003
MMC3-compatible registers ($8000-$FFFF)
Mask: $E001

See [MMC3]
