### ISSUE TITLE
[Question]: Can you update the Github workflow?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1263]
### Describe your question

Hi @Rakashazi is it possible to add the following changes with the next commit?
[update_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/10955088/update_workflow.zip)

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks, I added it just now. Looks like Snes9x had a lot of updates so I'll try and fit those in for the next commit.

**Comment by bladeoner** [comment]
Thank you!
