### ISSUE TITLE
[Question]: Is it possible to update Snes9x?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1264]
### Describe your question

Hi @Rakashazi when you have time is it possible to update Snes9x to the latest commit?

A lot of changes have been done.

Thanks in advance.

**Comment by Rakashazi** [comment]
Updated in the last commit

**Comment by bladeoner** [comment]
Thanks @Rakashazi enjoy your weekend!
