### ISSUE TITLE
[Issue]: GBA Boktai, oh dear! rakashazi lied to us

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1275]
### Describe the bug

Please fix Boktai series gba games
Why do @Rakashazi  want to lie to us, the solar sensor is just a front-end text, it has no effect on the actual game

### Steps to reproduce

I ever wondered if it was something I did wrong?  My Windows PC has been doused with dirty water by idlers.  Today I tried Boktai 3 (English Translated Hack) with SkyEmu.  Now I can safely say that the value entered is useless at all
Even if I use the virtual keys (Luma+ and Luma-), they do change, but quickly become 0
The other options (darkness, indoor light, overcast day, custom value) also seem to have some bugs.  you better test it again
I tried 0, 10000, 50000 + virtual buttons
Another point is very unreasonable. I use a virtual button. After the value changes, it should become a custom value, showing the increased or decreased value.

Another thing I noticed is that if the value is set to 0, it will be displayed as full sun in the game, and you cannot shoot. After waiting for a while, it will become 0 sun in the game

### Expected behavior

![image207](https://user-images.githubusercontent.com/109885044/226818350-7879128e-0133-4af2-8192-06d16cdf3bac.png)

**Comment by soundsnow** [comment]
sorry, my english is poor, you'd better take all possible situations into account

**Comment by Rakashazi** [comment]
I'm confused as to what your setup is. The light sensor scale refers to the physical sensor on your device. The light sensor virtual controls are for devices without a sensor, so if you're trying to use both at once the inputs will overwrite each other. If you want to use the virtual controls even when your device has a sensor, use Console Options -> Hardware Sensor -> None to disable it.

**Comment by soundsnow** [comment]
> I'm confused as to what your setup is. The light sensor scale refers to the physical sensor on your device. The light sensor virtual controls are for devices without a sensor, so if you're trying to use both at once the inputs will overwrite each other. If you want to use the virtual controls even when your device has a sensor, use Console Options -> Hardware Sensor -> None to disable it.

Thanks for the help
I usually don't read replies to my comments, this time is an exception because it's Boktai
