### ISSUE TITLE
I need help, I can't compile successfully on Linux system.

### ISSUE THREAD

**Issue by li599020295** [Rakashazi/emu-ex-plus-alpha#129]
I encountered some errors when I executed sh makeAll-android.sh.
hj@ubuntu:~/Desktop/emu-ex-plus-alpha-master/imagine/bundle/all$ sh makeAll-android.sh 
running make on src/libogg/android-armv7.mk
Configuring libogg...
dir=`pwd` && cd /tmp/imagine-bundle/libogg/build/android-armv7 && CC="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CXX="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" LD="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" AR="/home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar" RANLIB="/home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar s" STRIP="/home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip" OBJDUMP="/home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump" CFLAGS="-DNDEBUG -DANDROID --sysroot=/home/hj/Desktop/android-ndk-r17/sysroot -isystem /home/hj/Desktop/android-ndk-r17/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -DANDROID_COMPAT_API -std=gnu99 -fno-common -target armv7-none-linux-androideabi -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces" LDFLAGS="-target armv7-none-linux-androideabi -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mtune=generic -mthumb -no-canonical-prefixes -Wl,--fix-cortex-a8 -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections --sysroot=/home/hj/Desktop/emu-ex-plus-alpha-master/imagine/bundle/android-9/arch-arm -no-canonical-prefixes -Wl,--no-undefined,-z,noexecstack,-z,relro,-z,now -s -Wl,-O3,--gc-sections,--compress-debug-sections=zlib,--icf=all,--as-needed  -lm" \
/tmp/imagine-bundle/libogg/libogg-1.3.3/configure --prefix='${pcfiledir}/../..' --disable-shared --host=arm-linux-androideabi 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... /home/hj/Desktop/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for arm-linux-androideabi-gcc... /home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in `/tmp/imagine-bundle/libogg/build/android-armv7':
configure: error: C compiler cannot create executables
See `config.log' for more details
common.mk:36: recipe for target '/tmp/imagine-bundle/libogg/build/android-armv7/Makefile' failed
make: *** [/tmp/imagine-bundle/libogg/build/android-armv7/Makefile] Error 77
running make on src/libogg/android-arm64.mk
Configuring libogg...
dir=`pwd` && cd /tmp/imagine-bundle/libogg/build/android-arm64 && CC="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CXX="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" LD="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" AR="/home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar" RANLIB="/home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar s" STRIP="/home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip" OBJDUMP="/home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-objdump" CFLAGS="-DNDEBUG -DANDROID --sysroot=/home/hj/Desktop/android-ndk-r17/sysroot -isystem /home/hj/Desktop/android-ndk-r17/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -std=gnu99 -fno-common -target aarch64-none-linux-android -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64  -no-canonical-prefixes -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces" LDFLAGS="-target aarch64-none-linux-android -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64  -no-canonical-prefixes -fuse-ld=gold -fpic -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections --sysroot=/home/hj/Desktop/android-ndk-r17/platforms/android-21/arch-arm64 -no-canonical-prefixes -Wl,--no-undefined,-z,noexecstack,-z,relro,-z,now -s -Wl,-O3,--gc-sections,--compress-debug-sections=zlib,--icf=all,--as-needed  -lm" \
/tmp/imagine-bundle/libogg/libogg-1.3.3/configure --prefix='${pcfiledir}/../..' --disable-shared --host=aarch64-linux-android 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... /home/hj/Desktop/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for aarch64-linux-android-gcc... /home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in `/tmp/imagine-bundle/libogg/build/android-arm64':
configure: error: C compiler cannot create executables
See `config.log' for more details
common.mk:36: recipe for target '/tmp/imagine-bundle/libogg/build/android-arm64/Makefile' failed
make: *** [/tmp/imagine-bundle/libogg/build/android-arm64/Makefile] Error 77
running make on src/libogg/android-x86.mk
Configuring libogg...
dir=`pwd` && cd /tmp/imagine-bundle/libogg/build/android-x86 && CC="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CXX="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" LD="/home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" AR="/home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-ar" RANLIB="/home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-ar s" STRIP="/home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-strip" OBJDUMP="/home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-objdump" CFLAGS="-DNDEBUG -DANDROID --sysroot=/home/hj/Desktop/android-ndk-r17/sysroot -isystem /home/hj/Desktop/android-ndk-r17/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=16 -std=gnu99 -fno-common -target i686-none-linux-android -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64  -no-canonical-prefixes -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces" LDFLAGS="-target i686-none-linux-android -gcc-toolchain /home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64  -no-canonical-prefixes -pipe -fvisibility=hidden -Ofast -fomit-frame-pointer -fno-stack-protector -fno-asynchronous-unwind-tables  -flto -fno-integrated-as -ffunction-sections -fdata-sections --sysroot=/home/hj/Desktop/android-ndk-r17/platforms/android-16/arch-x86 -no-canonical-prefixes -Wl,--no-undefined,-z,noexecstack,-z,relro,-z,now -s -Wl,-O3,--gc-sections,--compress-debug-sections=zlib,--icf=all,--as-needed  -lm" \
/tmp/imagine-bundle/libogg/libogg-1.3.3/configure --prefix='${pcfiledir}/../..' --disable-shared --host=i686-linux-android 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-linux-android-strip... /home/hj/Desktop/android-ndk-r17/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for i686-linux-android-gcc... /home/hj/Desktop/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in `/tmp/imagine-bundle/libogg/build/android-x86':
configure: error: C compiler cannot create executables
See `config.log' for more details
common.mk:36: recipe for target '/tmp/imagine-bundle/libogg/build/android-x86/Makefile' failed
make: *** [/tmp/imagine-bundle/libogg/build/android-x86/Makefile] Error 77

**Comment by bladeoner** [comment]
Hi there,

@li599020295

Make sure you use Android studio 3.2.1:
https://dl.google.com/dl/android/studio/ide-zips/3.2.1.0/android-studio-ide-181.5056338-windows.zip

Download and install NDK 18 (what I do is install NDK 19 from Android Studio and then replace the content in the created sub folder):
https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip

Use this modified source:
https://github.com/AveyondFly/emu-ex-plus-alpha?files=1

Run this command first:
sudo apt-get install openjdk-8-jre-headless unzip make pkg-config libtool-bin

Download and install automake version 1.15: https://debian.pkgs.org/10/debian-main-amd64/automake-1.15_1.15.1-5_all.deb.html

Follow the complete instructions for setting up Imagine and Emuframework depending on if you try to build for Android or IOS choose the correct doc:
https://github.com/Rakashazi/emu-ex-plus-alpha/tree/master/imagine/doc
https://github.com/Rakashazi/emu-ex-plus-alpha/tree/master/EmuFramework/doc

Make sure you SET and EXPORT to the locations like the Android Studio installation directory and the imagine-sdk, imagine amd EmuFramework folders otherwise the build will fail. 

Try to build.

**Comment by thebunnyrules** [comment]
Thanks so much !!

**Comment by momashi** [comment]
Something weird is happening with the headers. Some of the include lines don't actually point to right place. They point to: 

#include <imagine/...
#include <emuframework/...

as if imagine and emuframework were subfolders rather than folders in a completely different branch of the hierarchy. Did I miss some something?

**Comment by thebunnyrules** [comment]
Having the same issue...

**Comment by bladeoner** [comment]
Here is an additional 'quick guide' I made:

Source:
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/imagine/doc/INSTALL
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/imagine/doc/INSTALL-Android
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/EmuFramework/doc/INSTALL

Prerequisites:
automake: 1.15 (use DEB file)
sudo apt-get install openjdk-8-jdk unzip make pkg-config libtool-bin libtool clang llvm

Android Studio:
Install Android Studio 3.2 with the latest NDK, with Android 8 (API 26) support.
Go to $HOME/Android/Sdk/ndk-bundle and remove all files and replace them from the "android-ndk-r18b.zip" file

Ubuntu example: sudo gedit ~/.bashrc
Linux Mint example: sudo xed ~/.bashrc

Add the following to the "bashrc" file and click save:
export IMAGINE_PATH=$HOME/projects/imagine
export IMAGINE_SDK_PATH=$HOME/imagine-sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_NDK_PATH=$HOME/Android/Sdk/ndk-bundle
set ANDROID_SDK_ROOT=$HOME\Android\Sdk\
set ANDROID_HOME=$HOME\Android\Sdk\
set ANDROID_NDK_PATH=$HOME\Android\Sdk\ndk-bundle\

Run from the "imagine", "bundle", "all" directory:
cd projects/imagine/bundle/all
bash makeAll-android.sh TAR=gnutar

Note: building will go wrong with the first one, so perform the following steps after the build above:
- Make a Copy of the $HOME/imagine-sdk directory
- Remove the $HOME/imagine-sdk directory
- Remove the /tmp/imagine-sdk directory
- Run the following again, but this time arm64 first:
bash makeAll-android-arm64.sh TAR=gnutar
bash makeAll-android-armv7.sh TAR=gnutar
- Remove android-arm64 directory from the $HOME/imagine-sdk directory
- Copy the android-arm64 and android-x86 to the $HOME/imagine-sdk directory from the copy made earlier
- Remove the /tmp/imagine-sdk directory

Run from the $HOME/projects/imagine directory:
cd projects/imagine
make -f android-release.mk config -j4
make -f android-release.mk install V=1 -j4
make -f android-java.mk install V=1 -j4

Run from the $HOME/projects/EmuFramework directory:
cd projects/EmuFramework
make -f android-release.mk config -j4
make -f android-release.mk install V=1 -j4

Run from the "Snes9x" directory:
cd projects/Snes9x/
make -f android-release-15.mk V=1 -j4

*NOTE: The build will FAIL, copy and replace "build.gradle" in $HOME/projects/Snes9x/target/android-release-15

**Comment by bladeoner** [comment]
I adjusted the guide to the latest source with Android Studio 3.5, tested on Linux Mint:

Source:
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/imagine/doc/INSTALL
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/imagine/doc/INSTALL-Android
https://raw.githubusercontent.com/Rakashazi/emu-ex-plus-alpha/master/EmuFramework/doc/INSTALL

Prerequisites:
automake: 1.15 (use DEB file)
sudo apt-get install openjdk-8-jdk unzip make pkg-config libtool-bin libtool clang llvm

Create the following directories in HOME:
projects
imagine-sdk

Copy the files from emu-ex-plus-alpha-core1.60.zip into the "projects" folder earlier created.

Android Studio installation steps:
- Download Android Studio 3.5.1: https://developer.android.com/studio#downloads
- Extract android-studio-ide-191.5900203-linux.tar.gz
- Open a terminal and type: cd Downloads/android-studio/bin
- Then type: ./studio.sh
- Click Next
- Click Next
- Click Finish to start the installation
- Click on Finish
- When it shows Android Studio click on Configure followed by "SDK Manager"
- Select "Android 8.0 (Oreo) / API 26" on the "SDK Platforms" tab
- Go to the "SDK Tools" tab and select "NDK (Side by side)"
- Then click on "Ok" followed by another "Ok" to start the installation
- Choose "Accept" in the license agreement screen and click "Next", the download/installation will start
- Click on Finish to Finish the installation
- Close Android Studio

Ubuntu example: sudo gedit ~/.bashrc
Linux Mint example: sudo xed ~/.bashrc

Add the following to the "bashrc" file and click save:
export IMAGINE_PATH=$HOME/projects/imagine
export IMAGINE_SDK_PATH=$HOME/imagine-sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_NDK_PATH=$HOME/Android/Sdk/ndk/20.0.5594570
set ANDROID_SDK_ROOT=$HOME\Android\Sdk\
set ANDROID_HOME=$HOME\Android\Sdk\
set ANDROID_NDK_PATH=$HOME\Android\Sdk\ndk\20.0.5594570\

Run from the "imagine", "bundle", "all" directory:
cd projects/imagine/bundle/all
bash makeAll-android.sh TAR=gnutar

Run from the $HOME/projects/imagine directory:
cd projects/imagine
make -f android-release.mk config -j4
make -f android-release.mk install V=1 -j4
make -f android-java.mk install V=1 -j4
*NOTE* if the Gradle install fails go to the following file and modify it:
File: $HOME/projects/imagine/android-java.mk
Current value line 6: imagineV9BuildJarPath := $(imagineV9SrcPath)/build/outputs/aar/imagine-v9-release.aar
Edit to value on line 6: imagineV9BuildJarPath := $(imagineV9SrcPath)/build/outputs/aar/imagine-v9.aar

Run from the $HOME/projects/EmuFramework directory:
cd projects/EmuFramework
make -f android-release.mk config -j4
make -f android-release.mk install V=1 -j4

Run from the "Snes9x" directory:
cd projects/Snes9x/
make -f android-release-15.mk V=1 -j4

*NOTE: The build will FAIL, copy and replace "build.gradle" with the attached file in $HOME/projects/Snes9x/target/android-release-15

[build.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/3720701/build.zip)
