### ISSUE TITLE
[Question]: Is it possible to update Snes9x to the latest commit?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1292]
### Describe your question

Hi @Rakashazi in the latest Snes9x commit they fixed a snapshot issue. Is it possible to update Snes9x to the latest commit the next commit you will do?

Thanks in advance.

**Comment by Rakashazi** [comment]
Sure, I'll add it in the next commit. There's actually still a bug with the snapshot code when loading files made with the previous version so I'll apply a fix for that too. I've already reported and provided the fix here: https://github.com/snes9xgit/snes9x/issues/838

**Comment by bladeoner** [comment]
Thanks a lot!
