### ISSUE TITLE
[Question]: How to "accept" selected path on Linux

### ISSUE THREAD

**Issue by hilltop804** [Rakashazi/emu-ex-plus-alpha#1297]
### Describe your question

When selecting a path for saves, screenshots, etc, what input is needed to "accept" the selected path in Linux? I can only seem to reset the browser or escape out.

This is on the linux build running on Steam Deck.

### Add screenshots

![20230401_085542](https://user-images.githubusercontent.com/41207087/229291235-f3668701-b698-45e4-b081-ca6a978f73f7.jpg)

**Comment by Rakashazi** [comment]
Currently the Linux build is packaged manually so you'll have to copy or link in the ui.png file from EmuFramework/res/ui into the path of the executable so the checkbox appears in the top right of the file picker to confirm path selection. For full functionality do the same with gpOverlay.png and the shaders directory. Here's how the file layout should look.

![GBC emu linux dir](https://user-images.githubusercontent.com/6722875/229308229-90b2a526-5e8f-4628-a4e0-1291b6758551.png)

**Comment by hilltop804** [comment]
Great, thanks for your help!

**Comment by Rakashazi** [comment]
Thanks for testing it out on the Steam Deck, I'm hoping to get one myself in the future but if you run into any other issues let me know.

**Comment by hilltop804** [comment]
Thanks for the response! The steam deck is really a great device for emulation. I've loved mine so far and would definitely recommend it.

I haven't tested all the emulators, but so far everything has run natively except for MD (due to libflac8 vs libflac12). I got around that by building it in a flatpak with dependencies bundled. I do have one issue with a line through the middle of the screen when fullscreen, but I'm still messing around with it.

**Comment by Rakashazi** [comment]
I added in a Linux x86_64 makefile for building the bundled libflac in a recent commit in case you'd like to test it out.

**Comment by hilltop804** [comment]
@Rakashazi Thanks for the heads-up! I tested with the bundled libflac, but it generates the same errors I was getting before when I was trying to manually build a newer libflac myself (see issue #1291). As far as I'm able to tell, this may be from a mismatch between the libflac and libogg versions. I tried building a newer version of libogg as well but I think that also needed a newer libvorbis, and I ultimately wasn't able to get everything to build properly.

I also think you could get around this on a newer Ubuntu, but GitHub runners are still on 22.04

![image](https://user-images.githubusercontent.com/41207087/230993760-365cd17e-7b5c-49be-aafb-e463f50a4e38.png)
