### ISSUE TITLE
[Issue]: 2600 c64 button name from stella/vice source code

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1299]
### Describe the bug

The button names are Button 1, Button 2, Button 3, but what do they mean?  i don't understand
Why don't you name the buttons after Stella's source code?

### Steps to reproduce

According to my observation on the actual controller, the buttons from top to bottom are Booster, Trigger, Fire
![image221](https://user-images.githubusercontent.com/109885044/229680236-b9b791ec-735c-4580-bf11-a34a83a220f0.png)

### Expected behavior

stella
Genesis.cxx
myButtonCEvent

Booster.cxx
myBoosterEvent
myTriggerEvent

Joystick.cxx
myUpEvent
myDownEvent
myLeftEvent
myRightEvent
myFireEvent

**Comment by soundsnow** [comment]
I don't know what the Genesis' other button is called in Stella's code.

Virtual Button Position
Booster should be placed above Trigger, Fire should be below Trigger, and Trigger in the middle

Genesis Gamepad should be its button name, and it should be arranged in the order of ABC from left to right

**Comment by soundsnow** [comment]
vice
joystick.c
Joystick (joystick_mapping)
Up
Down
Left
Right
Fire1
Fire2
Fire3

Joystick (joystick_no_pot_mapping)
Up
Down
Left
Right
Fire

SNES Pad (snes_mapping)
D-Pad Up
D-Pad Down
D-Pad Left
D-Pad Right
A Button
B Button
X Button
Y Button
Left Bumber
Right Bumper
Select
Start

**Comment by soundsnow** [comment]
C64GS Cheetah Anhilitor Joystick is similar to Atari 2600 Joystick+Booster Grip, but it's one port only
@Rakashazi  didn't add this joystick and snes pad for c64.emu
![51567c4c0d556f2e11e081cd6d41ccb7--cheetahs](https://user-images.githubusercontent.com/109885044/229691562-066c24bd-1098-4c27-8775-ce127668aaee.jpg)

**Comment by Rakashazi** [comment]
I'm keeping the generic button names for now since the mappings are used for multiple controllers (joystick, genesis, booster, paddle) but will look into making the button names context sensitive in a future update of the input code.
