### ISSUE TITLE
linker unrecognized option '--compress-debug-sections=zlib'

### ISSUE THREAD

**Issue by CptMonkeyFist** [Rakashazi/emu-ex-plus-alpha#13]
I am trying to compile on archlinux using the linux-x86_64-release.mk makefiles. I am using gcc 4.9.2 and ld 2.24. The imagine and EmuFramework libraries both built successfully, but I can't get Snes9x or GBA.emu to build. When I try I eventually get this error, "/usr/bin/ld: unrecognized option '--compress-debug-sections=zlib'. I'll try compiling on an ubuntu machine as others seem to have better results with that flavor, but any help with this would be appreciated.

Edit 1: I just tried again with Ubuntu 14.10 using gcc 4.9.1 and ld 2.24 and got the same result. Here is detailed output of the failure:

make -f linux-x86_64-release.mk V=1 t=2
Linking target/linux/s9xp
g++ -o target/linux/s9xp build/linux-x86_64-release/obj/main/Main.o build/linux-x86_64-release/obj/main/S9XApi.o build/linux-x86_64-release/obj/main/EmuControls.o build/linux-x86_64-release/obj/main/Cheats.o build/linux-x86_64-release/obj/snes9x/bsx.o build/linux-x86_64-release/obj/snes9x/c4.o build/linux-x86_64-release/obj/snes9x/c4emu.o build/linux-x86_64-release/obj/snes9x/cheats.o build/linux-x86_64-release/obj/snes9x/cheats2.o build/linux-x86_64-release/obj/snes9x/clip.o build/linux-x86_64-release/obj/snes9x/controls.o build/linux-x86_64-release/obj/snes9x/cpu.o build/linux-x86_64-release/obj/snes9x/cpuexec.o build/linux-x86_64-release/obj/snes9x/cpuops.o build/linux-x86_64-release/obj/snes9x/dma.o build/linux-x86_64-release/obj/snes9x/dsp.o build/linux-x86_64-release/obj/snes9x/dsp1.o build/linux-x86_64-release/obj/snes9x/dsp2.o build/linux-x86_64-release/obj/snes9x/dsp3.o build/linux-x86_64-release/obj/snes9x/dsp4.o build/linux-x86_64-release/obj/snes9x/fxemu.o build/linux-x86_64-release/obj/snes9x/fxinst.o build/linux-x86_64-release/obj/snes9x/gfx.o build/linux-x86_64-release/obj/snes9x/globals.o build/linux-x86_64-release/obj/snes9x/loadzip.o build/linux-x86_64-release/obj/snes9x/memmap.o build/linux-x86_64-release/obj/snes9x/movie.o build/linux-x86_64-release/obj/snes9x/obc1.o build/linux-x86_64-release/obj/snes9x/ppu.o build/linux-x86_64-release/obj/snes9x/stream.o build/linux-x86_64-release/obj/snes9x/sa1.o build/linux-x86_64-release/obj/snes9x/sa1cpu.o build/linux-x86_64-release/obj/snes9x/sdd1.o build/linux-x86_64-release/obj/snes9x/sdd1emu.o build/linux-x86_64-release/obj/snes9x/seta.o build/linux-x86_64-release/obj/snes9x/seta010.o build/linux-x86_64-release/obj/snes9x/seta011.o build/linux-x86_64-release/obj/snes9x/seta018.o build/linux-x86_64-release/obj/snes9x/snapshot.o build/linux-x86_64-release/obj/snes9x/spc7110.o build/linux-x86_64-release/obj/snes9x/srtc.o build/linux-x86_64-release/obj/snes9x/tile.o build/linux-x86_64-release/obj/snes9x/apu/apu.o build/linux-x86_64-release/obj/snes9x/apu/bapu/dsp/sdsp.o build/linux-x86_64-release/obj/snes9x/apu/bapu/dsp/SPC_DSP.o build/linux-x86_64-release/obj/snes9x/apu/bapu/smp/smp.o build/linux-x86_64-release/obj/snes9x/apu/bapu/smp/smp_state.o     -s  -Wl,-O1,--gc-sections,--as-needed,--compress-debug-sections=zlib,--icf=all -m64 -lm -L/home/balornt/imagine-sdk/linux-x86_64/lib/pkgconfig/../../lib -L/usr/lib/x86_64-linux-gnu -lemuframework -lm -limagine -lm -lpthread -lpulse -lX11 -lXi -lXfixes -lXrandr -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0 -lGL -lbluetooth -lfontconfig -lfreetype -lpng12 -lminizip -lz  -pipe -fvisibility=hidden -O2 -fomit-frame-pointer -funsafe-loop-optimizations -fno-stack-protector  -flto -fno-fat-lto-objects -fno-ident -ffunction-sections -fdata-sections -m64 -mtune=generic 
/usr/bin/ld: unrecognized option '--compress-debug-sections=zlib'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
/home/balornt/emu-ex-plus-alpha/imagine//make/imagineAppTarget.mk:26: recipe for target 'target/linux/s9xp' failed
make: *** [target/linux/s9xp] Error 1

**Comment by CptMonkeyFist** [comment]
:(

**Comment by Rakashazi** [comment]
A happy new year to you :)

This error is due to using BFD instead of GOLD as your linker. Unfortunately there is no distro-agnostic way to change the linker so I can only explain how to do it for Gentoo which I'm currently using. Both linkers are shipped as part of the binutils package but are separate executables, one of them being default. To change to GOLD you'll run binutils-config as follows:

binutils-config --linker ld.gold x86_64-pc-linux-gnu

Try looking up information on setting GOLD as your linker on your distro's wiki or message board for further help.
