### ISSUE TITLE
[Feature request]: Lynx Add support for headerless (NO-INTRO) romsets.

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1304]
### Describe the feature

I can't find any Headered ROMs from No-Intro .dat file
they're Headerless/Unheadered
Lynx.emu's user are Android most
I didn't use Handy, but if it's possible run them
why not add support for them? @rakashazi

I found this from Handy's code
https://github.com/libretro/libretro-handy/blob/master/lynx/cart.cpp
lynx/cart.cpp
Check if this is a headerless cart, either 410 (EPYX_HEADER_NEW) or 512 (EPYX_HEADER_OLD) zeros

Mednafen Lynx? No! I don't know where's it!

A GitHub user request for Headerless ROMs support
https://github.com/libretro/beetle-lynx-libretro/issues/16
A PR about Mednafen Lynx Headerless ROMs
https://github.com/libretro/beetle-lynx-libretro/pull/20/files

**Comment by soundsnow** [comment]
Yes! I used buggy old aLynx emulator
Android 2.3
Handy can open Unheadered/Headless ROMs without any problem
@Rakashazi 'd better fix this
I'm certain of it

**Comment by Rakashazi** [comment]
Thanks for the report. I didn't have any headerless ROMs to test at the time of release but will look into this for the next update.

**Comment by soundsnow** [comment]
> Thanks for the report. I didn't have any headerless ROMs to test at the time of release but will look into this for the next update.

I tested them
they're unheadered/headerless
You can download them from Myrient
myrient. .erista. .me files No-Intro Atari%20-%20Lynx
Atari isn't out of business yet, so I can't post the link directly

Not working, extensions and I don't know how to fix
https://myrient.erista.me/files/No-Intro/Commodore%20-%20VIC-20/

Not working, extensions and [nibtools](https://c64preservation.com/files/nibtools) Dependency from Commodore 64 Preservation Project
Nibtools [example and readme](https://github.com/libretro/vice-libretro/tree/master/deps/nibtools)
https://myrient.erista.me/files/No-Intro/Commodore%20-%20Commodore%2064%20(PP)/

pc2 extension and virtual button position
myrient. .erista. .me files No-Intro Benesse%20-%20Pocket%20Challenge%20V2

**Comment by soundsnow** [comment]
VIC-20
Make sure vice appends appropriate -cart for VIC-20 raw cartridge dumps (.20, .40, .60, .A0, .B0), as they are not auto-detected.
https://github.com/libretro/vice-libretro/commit/fd0179e06ec5ad5a407ddcf99befb5f808a1877c

**Comment by Rakashazi** [comment]
I was able to test some headerless .lnx files and added support for them in the last commit
