### ISSUE TITLE
[Question]: Is false positive by Google?

### ISSUE THREAD

**Issue by skelletR** [Rakashazi/emu-ex-plus-alpha#1305]
### Describe your question

I have Xiaomi Poco X3 NFC android 10. I try to install the version 1.5.69 but it show me notification from Google play protect the unsafe application was blocked, the programmer of this app is not recognised, first time it show me this, with all previous versions not. Is false positive by Google?

### Add screenshots

![IMG_20230405_134939](https://user-images.githubusercontent.com/25982450/230059468-e0443e49-8882-441d-8e90-74725000d4d0.jpg)

**Comment by Tsudayfrt** [comment]
Yes, github is safe so don't worry

**Comment by Tsudayfrt** [comment]
I have poco x3 pro btw

**Comment by Rakashazi** [comment]
Thanks for the report, I think this is due to different signing certificates used on the Github build and not any security issues with the app itself so you can safely disregard the message.
