### ISSUE TITLE
[Feature request]: lynx HLE BIOS

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1315]
### Describe the feature

handy High Level Emulation BIOS
If you don't have a BIOS file, use this as a substitute.
Or @Rakashazi  got a fake lynxboot.img file

master branch

 HLE BIOS, activated in case of an invalid BIOS rom file.
To be tested on commercial games, and implemented on homebrews.
https://github.com/libretro/libretro-handy/commit/952603f2ec719e43b237191a51bb5f8840fddf8b

HLE BIOS for CC65 homebrews
https://github.com/libretro/libretro-handy/commit/77a1a923d5d71bdbfae0684adc2e50dae481d249

HLE Bios fake doesnt wokr (crashes) with BLL Type Roms
https://github.com/libretro/libretro-handy/issues/13
 Boot Loader replacement fixes

  Fixed the HLE Boot Loader replacement by replacing the whole thing by something which is working.

Instead of ignoring/skipping the header , the new loader intercepts calls to the boot ROM and
"emulates" the functions normally sone by the bootrom.
Tested with *all* kind of loaders. Including strange homebrew things.
https://github.com/libretro/libretro-handy/commit/05d341292a680adec1765ff03461ce801c99d085

**Comment by soundsnow** [comment]
You added C-BIOS for MSX.emu, I think Lynx.emu require an extra BIOS too

**Comment by soundsnow** [comment]
add this
Options - System - BIOS
BIOS: Auto, HLE, Lynx

Auto: When the BIOS file is not selected or the loading fails, it will be replaced by HLE BIOS

**Comment by soundsnow** [comment]
The emulators with built-in BIOS that I know: Redream, PokeMini, Drastic, SameBoy(with its boot Logo)

Some are source code, some are binaries (can be used by that system emulators)

**Comment by Rakashazi** [comment]
The HLE BIOS was added in the last commit, a BIOS ROM is now optional.
