### ISSUE TITLE
[Feature request]: sega/atari 8-bit early joystick handness

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1317]
### Describe the feature

This picture shows the evolution of Atari 7800 and SG-1000 from Joystick to Joypad. The biggest advantage of Joystick is the handness
Left hand: D-Pad, Right hand: 1 and 2
Left hand: 1 and 2, Right hand: D-Pad

### Add screenshots

Atari 7800 (North America) Joystick to Atari 7800 (Europea) Joypad
SG-1000 Joystick to SG-1000 II Joypad
![image226](https://user-images.githubusercontent.com/109885044/230279558-4f77ff33-ed5f-4c25-97dc-4962e92c877c.png)

**Comment by Rakashazi** [comment]
You can already move virtual controls around as you like. Do not post issues about subjective aspects of the UI/controls or they may be deleted.

**Comment by soundsnow** [comment]
> You can already move virtual controls around as you like. Do not post issues about subjective aspects of the UI/controls or they may be deleted.

If I don't reply to you, it means I didn't see it, because I always turn off notifications.  My English is not good, so sometimes I post it even if you don't want to see it.  I know that many of my ideas seem stupid, and some of my creative ideas I can't explain.  Of course, if you don't like it, you can ignore it, after all, I am neither a player nor a developer.  Please do not reply to this comment, because I turned off the notification, so I will not reply.
I rarely read other people's replies to me
