### ISSUE TITLE
[Question]:  what's the difference between  square pixels and original?

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1318]
### Describe your question

I see no difference.

**Comment by Rakashazi** [comment]
On LCD handhelds like GBA, WonderSwan, etc. there is no difference. On consoles that connect to TVs they will use rectangular pixels depending on the resolution so you'll see a difference especially when using 256 wide pixel modes. I'll hide the square pixels options for LCD systems in a future update to avoid confusion.

**Comment by Rakashazi** [comment]
Square Pixel mode is now hidden on systems where it is identical to Original.

**Comment by leoxxx** [comment]
I see.
