### ISSUE TITLE
[Feature request]: Denote Y/X1+Y/X2+Y/X3+Y4/X as Y/X

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1320]
### Describe the feature

~~Y1-Y4~~ to Y
~~Y1-4~~ to Y
~~X1-X4~~ to X
~~X1-4~~ to X
One uppercase letter can represent four buttons, which reduces app size

and Video - Content Rotation
0, CW 90°, 180°, CCW 90°
Less app size

**Comment by Rakashazi** [comment]
Do not post issues related to subjective menu naming, they will be deleted and you may be temporarily banned.
