### ISSUE TITLE
[Issue]: lynx Zaku blackscreen

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1321]
### Describe the bug

Zaku, Homebrew not working on emulator
https://github.com/libretro/libretro-handy/issues/36

### Steps to reproduce

Don't tell software this is emulation
https://github.com/libretro/beetle-lynx-libretro/pull/55

### Expected behavior

Zaku's developer is PenguiNet
PenguiNet made good games for Atari consoles
[Zaku](http://www.penguinet.net/Games/Zaku/index.php) is made for Atari Lynx
[Rikki & Vikki](http://www.penguinet.net/Games/Rikki_Vikki/index.php) is made for Atari 7800

**Comment by soundsnow** [comment]
I don't have a HEALTHY windows pc
mame supports it? I don't know

**Comment by soundsnow** [comment]
lynx/mikie.cpp

         break;
         //return 0x42;

or

			// return 0x42;
			break;

**Comment by Rakashazi** [comment]
Fixed in last commit
