### ISSUE TITLE
Paths in includes is all wrong. Am I missing a step?

### ISSUE THREAD

**Issue by momashi** [Rakashazi/emu-ex-plus-alpha#133]
I've getting errors because the includes, example:

#include <imagine/...
#include <emuframework/...

are relative, yet need to point to towards $IMAGINE_PATH/include/imagine and $SRC/EmuFramework/include/emuframework instead. They're treating includes as if they're subdirectories rather than parent directories...

This is resulting in the compiler not finding most of the includes and exiting with errors. 

Since I've not seen a single person complain about this, am I missing a step that fixes this? 

I've had to resort to bruteforce approach by using find+sed to recursively replace all includes with absolute paths but I *imagine* (pun intended) there is an easier way than this??

**Comment by Rakashazi** [comment]
It sounds like you didn't install imagine and emuframework headers into your imagine-sdk directory, please check imagine/doc for more info.
