### ISSUE TITLE
[Feature request]: Old and New Famicom Virtual Button Position

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1337]
### Describe the feature

This will fix Robot Gyro (same game Gyromite in USA) for Japanese Old Famicom console

The old P2 Gamepad has a Microphone and is not removable, the new Gamepads can be replaced at will

Including P2(Old/New)+P1, P1+P2(Old/New), P2(Old/New) only, P1 only
![image234](https://user-images.githubusercontent.com/109885044/230547983-aaf5c8af-c395-4af3-b3f2-5dd125a9a89f.png)

**Comment by soundsnow** [comment]
It is an obvious fact that Famicom has more input devices and ports than NES in theory. Most NES input devices are Gamepads with changed shells, while Famicom's input devices are all dedicated to corresponding games.

**Comment by Rakashazi** [comment]
Once again, do not post subjective issues related to the UI. This is your final warning before you are banned.
