### ISSUE TITLE
[Feature request]: Clean Code: Reduce app size

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1339]
### Describe the feature

Fix Mednafen official website redirect
mednafen.sourceforge.net
to
mednafen.github.io
And I can't get latest Mednafe source on SourceForge

Fix GnGeo Google Code website redirect
I typed
code.google.com/p/gngeo
it leads me to
code.google.com/archive/p/gngeo
In addition, the latest official code of GnGeo is not in Google Code, please make the following changes

NEO.emu
Replace "code.google.com/p/gngeo" with "https://github.com/pepone42/gngeo"
It's GnGeo's main developer's Github Repository, 4 or 5 commits ahead Google Code page

Mednafen based emulators
Replace "mednafen.sourceforge.net" with "mednafen.github.io"

All emulators
Remove www.
Remove "Portions (c) the"
Remove "Team"
Remove "Built :"
Replace "-2023" with "-'Built Date''"
Remove "(c)"
Move "1.5.69" to About page

NGP.emu
Replace www.nih.at with mednafen.github.io
Replace NeoPop Team with Mednafen

Why? Check Lynx.emu and Swan.emu
They're not Mednafen Original Emulators
So you need to change NGP.emu's About page

Duplicate text takes up more storage space
Modern web browsers can access many websites without typing "www."
If you want to add "www.", do you also need to add "http://"?

Don't say the same thing twice, you have already added the official website on the About page, why add another one to the Options page?

Options page
Remove "Online Documentation" and link

Options - Video - Content Rotation
Replace them with 0, CW 90°, 180°, CCW 90°
You'd better test them yourself, because I don't know if your so-called Left and Right are clockwise or counterclockwise

### Add screenshots

Snes9x EX+
Here is an example
![image235](https://user-images.githubusercontent.com/109885044/230596554-36373c7c-5514-41e6-80f2-df79585e3930.png)
![image236](https://user-images.githubusercontent.com/109885044/230596566-e7e6a21e-2da5-44b8-a8ca-ab76fada6350.png)
![image237](https://user-images.githubusercontent.com/109885044/230597222-dd67ad9b-eb9c-46b6-a28e-a65a4ac07f02.png)

**Comment by Rakashazi** [comment]
Mednafen URLs are fixed, for Genesis Plus since I couldn't find the exact site I added the Sega Retro page which also has archived links to the original site.
