### ISSUE TITLE
[Question]:I'm sorry

### ISSUE THREAD

**Issue by TheBoxGame12345** [Rakashazi/emu-ex-plus-alpha#1341]
### Describe your question

@Rakashazi I'm sorry for spamming you with requests for mappers, you'll unban me, I won't spam anymore :(

**Comment by Rakashazi** [comment]
Ok, I've unblocked your accounts but if you post any more duplicate issue they will be blocked again.

**Comment by TheBoxGame** [comment]
@Rakashazi by the way you will add the black bars feature to md.emu What I mean
![220162562-a5ad182b-10d4-4d87-93f1-db93a171f34e](https://user-images.githubusercontent.com/109180532/230716915-326bc1ca-1af2-4e24-b0ce-83d78b1bd208.png)

**Comment by Rakashazi** [comment]
This is a low-priority feature so probably not for a while.

**Comment by TheBoxGame** [comment]
@Rakashazi ok and will you add at least half of the mappers to nes. There are some of them, add half with nick and the rest some other time.
