### ISSUE TITLE
[Feature request]: 3 speed mode

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1344]
### Describe the feature

Slow: 0.01 - 0.99 and Custom
Normal: 1
Fast: 1.01 - Custom

Show 8.0 or 8.00 as 8
Show 6.70 as 6.7
Show 0.50 as 0.5
Reduce app size without showing extra 0's

Only 2 Buttons: Fast and Slow
Normal is default status

Normal+Fast=Fast
Slow+Fast=Fast
Normal+Slow=Slow
Fast+Slow=Slow
Slow+Slow=Normal
Fast+Fast=Normal

and I have to tell you a bug
System Options
Fast-forward speed: Custom Value
Slow-motion speed: Custom Value
Input 0.05 up to 1.0
Input above 1.0 to 20.0

I inputted 1 or 1.0
Value not in range,are you kidding me?
You should change them like this
Input 0.01 to 0.99
Input 1.01 to 20
8.00x->8x
0.50x->0.5x

**Comment by Rakashazi** [comment]
The decimal formatting now hides zeroes. For Slow motion speed it says "up to 1.0" so 1 is not included in the valid range.
