### ISSUE TITLE
[Feature request]: lynx.emu vertical game bug: Handheld Rotation Auto isn't working

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1346]
### Describe the feature

Open a game - Console Options - Handheld Rotation: Auto
And @ didn't add another horizontal rotation

This is the database I used to test the games
[Atari - Lynx (DB Export) (20230322-221226).zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/11182820/Atari.-.Lynx.DB.Export.20230322-221226.zip)

Default horizontal
D-Pad - Screen - Bs,As

Vertical Up to Down
As,Bs - Screen - D-Pad

Title|Lynx.emu|Original
:---:|:---:|:---:
Centipede (USA) (Proto)|![4-8-23 16 04 49](https://user-images.githubusercontent.com/109885044/230711455-318274be-d560-4f5e-aa14-65768d04b39d.png)|![Centipede (USA) (Proto)](https://user-images.githubusercontent.com/109885044/230711494-bab6c5d3-5992-4ab2-931b-75150d5648b7.png)
Lexis (USA)|![4-8-23 16 05 37](https://user-images.githubusercontent.com/109885044/230711523-96efef77-190d-4d4d-babe-7cd234032144.png)|![Lexis (USA)](https://user-images.githubusercontent.com/109885044/230711671-a4e378ea-98b8-47fb-992f-2617c4d99f2d.png)
NFL Football (USA, Europe)|![4-8-23 16 05 51](https://user-images.githubusercontent.com/109885044/230711690-a9a7aa42-8a66-4010-a75b-5e20fd4e960f.png)|![NFL Football (USA, Europe)](https://user-images.githubusercontent.com/109885044/230711701-2083d1cd-5ec0-4c4a-8669-39b4fd088778.png)
Raiden (USA)|![4-8-23 16 06 17](https://user-images.githubusercontent.com/109885044/230711714-e26d5599-42bc-4bed-ae9a-fdbca80187fd.png)|![Raiden (USA)](https://user-images.githubusercontent.com/109885044/230711725-449ae886-153b-417e-844a-bbec9ac70bd7.png)
Raiden (USA) (Proto)|![4-8-23 16 06 17](https://user-images.githubusercontent.com/109885044/230711714-e26d5599-42bc-4bed-ae9a-fdbca80187fd.png)|![Raiden (USA)](https://user-images.githubusercontent.com/109885044/230711725-449ae886-153b-417e-844a-bbec9ac70bd7.png)

Vertical Up to Down
As,Bs - Screen - D-Pad

Title|Lynx.emu|Original
:---:|:---:|:---:
Gauntlet - The Third Encounter (USA, Europe)|![4-8-23 16 05 10](https://user-images.githubusercontent.com/109885044/230711789-d44e8c83-77b3-42c9-8490-7f9e4e8c04c8.png)|![Gauntlet - The Third Encounter (USA, Europe)](https://user-images.githubusercontent.com/109885044/230711813-62e9cc5a-a9ae-4c4e-9229-ec42cc2476c4.png)
Gauntlet - The Third Encounter (USA, Europe) (Beta) (1990-06-04)|![4-8-23 16 05 10](https://user-images.githubusercontent.com/109885044/230711789-d44e8c83-77b3-42c9-8490-7f9e4e8c04c8.png)|![Gauntlet - The Third Encounter (USA, Europe)](https://user-images.githubusercontent.com/109885044/230711813-62e9cc5a-a9ae-4c4e-9229-ec42cc2476c4.png)
Klax (USA, Europe)|![4-8-23 16 05 21](https://user-images.githubusercontent.com/109885044/230711846-e52e7c9c-5d62-42a0-87d3-2a34c917fd32.png)|![Klax (USA, Europe)](https://user-images.githubusercontent.com/109885044/230711859-044495e9-6e90-4e79-8831-6806f3f202ba.png)
Klax (USA, Europe) (Beta)|![4-8-23 16 05 21](https://user-images.githubusercontent.com/109885044/230711846-e52e7c9c-5d62-42a0-87d3-2a34c917fd32.png)|![Klax (USA, Europe)](https://user-images.githubusercontent.com/109885044/230711859-044495e9-6e90-4e79-8831-6806f3f202ba.png)

**Comment by Rakashazi** [comment]
This is expected if the games you're using don't have ROM headers since there's nothing in the ROM itself to indicate the correct screen rotation.
