### ISSUE TITLE
How to build Android ?

### ISSUE THREAD

**Issue by mobydick2611** [Rakashazi/emu-ex-plus-alpha#135]
I trying build for android. But i don't know how to setup enviroment.
Please help me to build android. 

Many thanks,

**Comment by Rakashazi** [comment]
Check the text files under imagine/doc for details about building the apps. There's been some small changes to the process recently such as not needing to build android-java.mk manually but the general process for building the Android ports under Linux is:

1. Make a copy of the entire repository and set IMAGINE_PATH env variable to the path of the imagine directory on your filesystem, for example: /home/user1/emu-ex-plus-alpha/imagine/
2. Install Android Studio and set the ANDROID_SDK_ROOT env variable to the path it's installed in
3. Install everything listed under "2. Dependencies" in imagine/doc/INSTALL-Android
4. Build all the bundled libraries by running "bash makeAll-android.sh install" in imagine/bundle/all/
5. Build Imagine with "make -f android-release.mk install" in imagine/
6. Build EmuFramework with "make -f android-release.mk install" in EmuFramework/
7. Build & install the app you want with "make -f android-release.mk android-install"
