### ISSUE TITLE
[Question]:question about adding mappers in updates

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1354]
### Describe your question

@Rakashazi I have a request if you could add a couple of mappers that I wrote in the request, of course, for now, add half of it and the rest later, would you be able to handle them

**Comment by Rakashazi** [comment]
More mappers will be added over time as the FCEUX code is updated but there's no specific time frame.

**Comment by TheBoxGame** [comment]
> Więcej maperów zostanie dodanych z czasem, gdy kod FCEUX zostanie zaktualizowany, ale nie ma określonych ram czasowych.

@Rakashazi mapper 342 jest w fceux 2.6.5 tylko niema go dodanego do folderu boards czy mógłbyś go dodać i mapper 175 bo mapper 342 jest powiązany z mapperem coolgirl a coolgirl mapper 342 czy dodasz go do następnej aktualizacji

**Comment by TheBoxGame** [comment]
coolgirl it's practically related to mapper 342 that's why half of the games don't work and how are some builds 2 or 1 of the builds the game starts with graphical errors could you add the missing mapper 342?

**Comment by TheBoxGame** [comment]
I give a screeenshot what is wrong if there is no 342 mapper it pisses me off a bit because I want to play it and here is a glitch in the FCEUX 2.6.5 version there is a 342 mapper and there is no problem with starting the game, for example Crisis Force

**Comment by TheBoxGame** [comment]
![Screenshot_2023-04-09-12-31-21-949_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/230767803-c0d52fb9-0d84-4510-85a4-33b8df4f1968.jpg)
![Screenshot_2023-04-09-12-30-26-192_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/230767805-74ae07cc-6191-4b04-b9c6-f76c05aa09cd.jpg)

**Comment by TheBoxGame** [comment]
@Rakashazi and could you add them as a side note please
