### ISSUE TITLE
[Issue]: md.emu Android TV - 6 Buttons emulation cannot be permanently set

### ISSUE THREAD

**Issue by Albert-1970** [Rakashazi/emu-ex-plus-alpha#1359]
### Describe the bug

When running md.emu in Android TV i can map all gamepad keys ( 8 buttons and the DPAD ) however when playing 3 of buttons do not work, for example in street fighter  II i can move the fighter arms but not the legs, to temporarily fix the issue i go to "System Actions" ->  "Console Options" -> "6-button Gamepad" to enable it ( i set it to "On"), after that all buttons work, i can move arms and legs, however if i close the game the game and open it again or any other game the "6-button Gamepad" is automatically set back to "Off", so far i haven't found a way to keep it On permanently

### Steps to reproduce

Street Fighter II' - Special Champion Edition (USA).md

1- Connect a Bluetooth GamePad to an android TV 10 ( see mine's picture attached )
2- Map your buttons as shown in the attached pictures
3- Start the attached game with md.emu ( Street Fighter II' - Special Champion Edition (USA).md )
4- try to use all mapped buttons ( some of them will not work )

btw, i have also purchased 2600.emu, neo.emu, nes.emu and Snex9X Ex+ in which this issue does not happen
i am experiencing a similar issue with pce.emu, i will open another issue report for it.

If you need anything else do not hesitate to contact me

Thank you

Luis Espinoza
lespinozav@hotmail.com

![My Gamepad](https://user-images.githubusercontent.com/130262285/230750802-19959578-65d7-4ae9-bd14-0ee9794a73e3.jpg)

### Expected behavior

All mapped buttons must work, if not it will not be possible to play games

### Add screenshots

![1- GamePad Detected](https://user-images.githubusercontent.com/130262285/230750973-6ccdb53a-b390-4c77-a326-d00a22d3b817.jpg)
![2- GamePad Configuration](https://user-images.githubusercontent.com/130262285/230750976-63651ddb-aa1a-4287-827b-27039e147571.jpg)
![3- Mapped Buttons](https://user-images.githubusercontent.com/130262285/230750979-b99443f4-982d-47f3-a733-5c5d3e6e3581.jpg)
![4- Android TV info_1](https://user-images.githubusercontent.com/130262285/230751105-3134fca0-0948-415e-a90d-a8d032df5751.jpg)
![5- Android TV info_2](https://user-images.githubusercontent.com/130262285/230751108-0a8381bf-1c60-4f12-9fb6-fa4642fc86ce.jpg)

**Comment by Rakashazi** [comment]
The 6-button support for those systems is enabled for each game individually since games that were not programmed with 6-button controllers in mind may have compatibility issues. However, the option should be saved so you don't need to enable it every time you launch the game. To save the per-game configuration make sure Options -> File Paths -> Saves is valid. As a test try these steps

* Open Street Fighter in MD.emu
* Turn on Console Options -> 6-button Gamepad, and verify you can use the extra buttons in-game
* Select Close Content
* Open Street Fighter in MD.emu again
* Check that Console Options -> 6-button Gamepad is still on

**Comment by Albert-1970** [comment]
Hello

After setting a valid File Path for "Saves" the 6-button option remained "On" even after closing md.emu, now since i am kind of new user of this mega drive emulator there is something i would like to ask you 

As you know there are several games that require 6 buttons like street fighter, fatal fury ( takara) ...  etc . according to your explanation i must enable the 6 button options game by game because they are not all compatible with that setting, is that correct ?

Thank you

**Comment by Rakashazi** [comment]
Yes, you should only enable the 6 button mode on games that need that option, this is especially true on PCE since unsupported games will have input issues.
