### ISSUE TITLE
Add ability to set 5x integer (vertical) scaling for 1080-line screens

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#136]
This is a feature request.

Many games were designed such that no critical information is in the top and bottom few scanlines, since not all CRT TVs showed those back in the day.

Nowadays it's common to use a display with 1080 lines vertically. Exact 5x vertical scaling would mean that 216 lines of the console image fit. For many games the top and bottom 4 scanlines (assuming 224 full image) being off-screen is no big deal, and a larger image would be welcome on small phone screens.

Ideally have some way to control which scanlines get clipped, e.g. perhaps certain titles would be better having the bottom 8 lines clipped instead of  4+4.

**Comment by Rakashazi** [comment]
Thanks for the request, this should be possible to implement fairly soon once I iron out a couple of bugs from the last release. Having a common default setting and being able to override it per-game seems like the best way to go.

**Comment by M-a-r-k** [comment]
A couple of thoughts on how the UI could work for that...

Pinch-to-zoom in/out similar to how the Android YouTube app works on phones with e.g. 18:9 screen. Starting from 100% (occupying full screen height, 4.5x scaling), pinch-zoom in to show 216 lines of emulated image (5x scaling). Pinch-zoom out back to 4.5x, out again to 4x, out again to 3x.

Or perhaps, long-press middle of screen, four buttons appear: zoom in and out and up and down arrows. The arrows would move the emulated image up or down one line.

**Comment by M-a-r-k** [comment]
If anyone wants to achieve 5× scaling with real hardware, the RetroTink 5X supports it, complete with vertical position adjustment. :)

https://www.retrotink.com/product-page/5x-pro
