### ISSUE TITLE
[Question]: missing features of bluemsx and typo

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#1362]
### Describe your question

MSX.emu
About: BlueMSX is incorrect
It's blueMSX
another typo GBA.emu: VBA-m

Its features are classified in detail on the official website, but MSX.emu does not support most of them.
https://www.msxblue.com/manual/

**Comment by Rakashazi** [comment]
You have been blocked after multiple warnings to not spam issues like this.
