### ISSUE TITLE
[Question]:FCEUX 2.6.5 Mapper 342

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1365]
### Describe your question

@Rakashazi could you add mapper 342 from fceux 2.6.5 which i mentioned many times ?

### Add screenshots

![Screenshot_2023-04-12-11-42-40-732_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/231420089-a58c87d8-085d-44b6-821f-61cab9cb288b.jpg)
![Screenshot_2023-04-12-11-42-30-171_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/231420100-06c07e9b-5016-4dce-8a41-1c60b1320c5f.jpg)
![Screenshot_2023-04-12-11-42-25-680_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/231420106-2dccc92b-cde2-4cd3-8d06-c6729e2a9225.jpg)

**Comment by TheBoxGame** [comment]
![Uploading Screenshot_2023-04-12-11-45-27-253_com.android.chrome.jpg…]()

**Comment by TheBoxGame** [comment]
![Screenshot_2023-04-12-11-45-27-253_com android chrome](https://user-images.githubusercontent.com/109180532/231420804-1be140b7-e6d5-45fb-937f-ac47e4326f91.jpg)

**Comment by Rakashazi** [comment]
Mapper 342 support is already present and matches FCEUX 2.6.5, but the ROM you're using doesn't work properly even with FCEUX on PC. If you're sure it's a proper dump then please report this to the FCEUX github page instead.
