### ISSUE TITLE
[Issue]: App conflict after uninstalling old version

### ISSUE THREAD

**Issue by beefmechado** [Rakashazi/emu-ex-plus-alpha#1369]
### Describe the bug

I downloaded the newest nightly for GBC and attempted an install, but couldn't until I uninstalled the previous version, which I did.

I think the thing I did wrong was I didn't clear out the previous version's data because I wanted to retain my settings.

Now, when I try to install the app, it asks if I want to update the app (even though I uninstalled it) and then it says "App not installed as package conflicts with an existing package."

### Steps to reproduce

Uninstal *.emu app, select "keep data", then try to install newer version of app.

### Expected behavior

Will not be able to install and be locked out, unless one has the previous version APK.

**Comment by Rakashazi** [comment]
To fix this, go into your Android Settings app -> Apps -> All Apps -> tap search button and type in gbc. It should show the leftover data as "com.explusalpha.GbcEmu" and let you uninstall it there.

**Comment by beefmechado** [comment]
> To fix this, go into your Android Settings app -> Apps -> All Apps -> tap search button and type in gbc. It should show the leftover data as "com.explusalpha.GbcEmu" and let you uninstall it there.

Thanks for the response. Unfortunately, I'm not seeing it when I search. It seems the problem is linked to the app signatures being different in the older and newer releases, as described in [this comment](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1129#issuecomment-1510684922).

**Comment by Rakashazi** [comment]
Right, you can't install a version of the app with a different signature because the app is still "installed" due to the leftover data. If it's not showing up in the settings it may be be a bug in the version of Android you're using, so in this case I recommend enabling developer settings and using ADB to uninstall the app. The command is:

`adb uninstall com.explusalpha.GbcEmu`

**Comment by beefmechado** [comment]
Success! That was exactly what I needed to do. Thanks so much.

In case you're wondering, I am on 13, so it could very well be a bug.
