### ISSUE TITLE
Gba.emu the noise is heard very low 

### ISSUE THREAD

**Issue by Guillermo4060** [Rakashazi/emu-ex-plus-alpha#1374]
### Describe the bug

First of all, I'm sorry if I'm not very good at explaining it to you, but I'll do my best, what happens is that in the emulator I feel that the noise is very low and that affects the sound of the games. I was seeing what the noise is and I don't know if it can be increased more from the code or those things like your emulator no longer has lag that's very good but the sound is already basic and I would like if you could solve the problem thank you very much

### Steps to reproduce

Play sonic advance 2 

### Expected behavior

The noise is very low

### Relevant log output

```shell
Noise
```

**Comment by Guillermo4060** [comment]
@Rakashazi It won't let me upload the video to show you the details :(

**Comment by Yave-Yu** [comment]
#432 I've already posted this thing.

**Comment by Rakashazi** [comment]
Can you post just the audio clips of what it sounds like currently and what it should sound like?

**Comment by Guillermo4060** [comment]
@Rakashazi Of course look now if I let myself, well as I was saying this is the difference between the retroarch emulator if you realize how you can hear it is as if channel 4 or the noise is heard very low and the truth is that it does affect the games see below the video from another emulator so it should sound in the gba.emu 

https://user-images.githubusercontent.com/100426962/233909427-63f9cd45-6918-4589-807a-247eb7c3faf3.mp4


Now this video from your emulator is only a part but from here you can see the difference between the sound and well I would like if you could solve it or turn up the volume since it does affect the sound of the games



https://user-images.githubusercontent.com/100426962/233909706-00ba9a4a-b9e7-49e9-a547-605dd0e5be90.mp4


As you can hear the volume of the noise it is heard very low and that in the emulator settings I have everything at 100 but even so it is heard very low, I wait for a solution or an answer

**Comment by Rakashazi** [comment]
You guys are right, the noise channel there does sound unusually low. For now I'll double the volume until I can do more research on it.

**Comment by Yave-Yu** [comment]
Holy sh*t! Now I can hear noise drum clearly! Great job, and finally... I waited this!

**Comment by Yave-Yu** [comment]
Still I wanna post that foobar2000 GSF plugin here, it uses VBA-M as sound and contains source code.
https://foobar2000.xrea.jp/up/files/up1469.7z
This plugin changes noise implemention so high value could keep VBA-M's original but low value could louder than VBA-M.
