### ISSUE TITLE
[Issue]: Game saving not working in Advance Wars / GBA.emu

### ISSUE THREAD

**Issue by Code-Otto** [Rakashazi/emu-ex-plus-alpha#1375]
### Describe the bug

Hello again! After the CPU usage issue was solved, I set myself in a journey to never look back at 1.5.27-beta1 ever again... Started a game of Advance Wars and had some fun through the 'Field Training' tutorials. After a play session of satisfactory frame rate smoothness, the usual gamer moment came:
![save](https://user-images.githubusercontent.com/129909770/233845908-ef372f44-d6b7-42a4-91d7-2e47943229c2.png)
I didn't know what was I about to find out... Here I am, back at installing 1.5.27-beta1 one more time :laughing:

When saving, the game stays indefinitely at this state:
![aw](https://user-images.githubusercontent.com/129909770/233847230-8b7dec5f-ba1b-48b6-aac7-ce122a3e9a95.png)
It's not a total game hang since animations and music keep playing in the background, however this process never makes it to completion

Out of the versions I have an APK for, managed to pinpoint down this issue to have been introduced somewhere between v1.5.54 (where saving works) and v1.5.65 (where it no longer does)
Commit 6275e5f93182e08c623ae2b7aca01e408566dfda which sits in between said versions sounds quite blamable, however I can't pinpoint further to prove whether that's really the case

Have as well tested changing the save data folder at system options to the app folder, without any luck

Tested Advance Wars 2 as well, where saving faces no issues. This looks like a VBA-M issue, however wanted you to check this out first and confirm whether that's the case

### Steps to reproduce

Fire up Advance Wars (I'm using the version with a CRC32 of 66fb29e9) and while ingame, attempt to save
Here's a save state to get you directly to a save prompt: [savestate.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/11304068/savestate.zip)

### Expected behavior

https://user-images.githubusercontent.com/129909770/233848112-3dae51c4-675d-4821-ab29-55e83372383b.mp4

### Relevant log output

```shell
No relevant output spotted at logcat
```

**Comment by Rakashazi** [comment]
Thanks for the report. So you were using a state created from an older GBA.emu version? It looks like the save method was incorrectly detected as SRAM whereas it's correctly detected as flash memory in the current version, but VBA-M's state loader overwrites the save type setting and the game bugs out when it tries to access the flash memory.

I updated it so the save type isn't modified and it should correctly be set to flash memory when you reload the state. Give the newest commit a try once it's done building and let me know if it's fixed.

**Comment by Code-Otto** [comment]
Now that you say, that was the case indeed. I had once launched the game with 1.5.27-beta1 which left an automatic savestate and a savegame around, and these were later loaded when I got back to playing in the latest version

The latest fix makes saving functional again even with savestates from said ancient version. Thank you! :heart:
