### ISSUE TITLE
[Issue]: When multiple gamepads are connected, they all control player 1.

### ISSUE THREAD

**Issue by moh3nnn** [Rakashazi/emu-ex-plus-alpha#1377]
### Describe the bug

When multiple gamepads are connected, they all control player 1, making it impossible for 2 players to play simultaneously.

### Steps to reproduce

.

### Expected behavior

.

**Comment by Rakashazi** [comment]
If they are different gamepad types and default to player 1, set the desired player with Key/Gamepad Input Setup -> Auto-detect Device To Setup -> Player.
