### ISSUE TITLE
[Issue]: Workflow failed

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#1379]
### Describe the bug

Hi @Rakashazi,

How are you doing?

I saw that the last workflow build failed, I don't know exactly why but if you will re-run it, it should finish fine.

### Steps to reproduce

n/a

### Expected behavior

That the build is successful.

**Comment by bladeoner** [comment]
I am fine thank you, when I find some time I will look into it also and let you know if I find a way.

What I noticed with the latest release is that my Android device UI is hanging when starting the GBA emu, it is also not usable. This started after commit https://github.com/Rakashazi/emu-ex-plus-alpha/commit/b6675dea969d92f3059a9aaf327e038bd199b289

**Comment by Rakashazi** [comment]
What is your device and OS version? Are you able to capture a video of it? I just checked the nightly and didn't find any issues so far.

**Comment by bladeoner** [comment]
I am using a Samsung Galaxy S22 with Android 13, I am not able to capture a video of it.

**Comment by Rakashazi** [comment]
Is it just GBA.emu or does it happen with the others too? Does it show the app's menu or does it hang on the launch icon? Do you get the "app not responding" message from the OS?

**Comment by bladeoner** [comment]
I have only seen it with GBA, GBC and Snes9x are working without a problem. It hangs on the launch icon and it doesn't show the menu. The OS doesn't say "app not responding" after some time is crashes and then the OS says system UI not responding "wait" "close app" and the only option that I have is to reboot the device to get the UI responding normal again.

**Comment by Rakashazi** [comment]
That sounds very strange since the app shouldn't be able to make the system UI crash. Did you have any OS or system app updates recently? The only things that were changed in that commit were some icons and the intent filters for file extensions, neither of which should cause an issue like that.

**Comment by bladeoner** [comment]
The device didn't have any recent updates, last one was from the beginning of April. When I have time I wanted to test two things:
- The older clang build in that commit
- And as a separate test revert: GBA.emu: Don't modify save type when loading a state, fixes issue with older states forcing an incorrectly detected backup memory type

**Comment by bladeoner** [comment]
@Rakashazi with the latest build the issue is resolved I will close the issue, thanks.

**Comment by Rakashazi** [comment]
Thanks for letting me know. In the future if you get a system UI crash also check the device's logcat since it will print out any Java exceptions that could help find the cause.
