### ISSUE TITLE
[Issue]: Sound never plays back again when configured to deactivate during fast forward

### ISSUE THREAD

**Issue by Code-Otto** [Rakashazi/emu-ex-plus-alpha#1380]
### Describe the bug

Since issue #1375 nuked my Advance Wars progress, I found myself fast forwarding through the tutorials to get progress back at where I reached back then. To gain some more fast forwarding speed in my not too powerful device I thought setting 'Options > Audio > Sound During Fast/Slow Mode' to Off could be of some little help by skipping audio emulation during fast forward (Does it actually do such a thing or just mutes the audio?)

The option takes effect, however when fast forward is stopped sound never comes back again (tried changing several options with no luck) until the game is restarted

### Steps to reproduce

Disable 'Options > Audio > Sound During Fast/Slow Mode'
Fast forward in any game then stop

### Expected behavior

Sound is re-enabled when fast forward stopped

**Comment by emyaqin** [comment]
I got the same issue with the 1.5.71

**Comment by Rakashazi** [comment]
Thanks for the report, I borked something while refactoring the sound option code but should have a fix soon. In the meantime, to get audio back if this happens without restarting the game, set the "Volume" option to any value and back to 100%.

**Comment by TheBoxGame** [comment]
nes.emu is the same
