### ISSUE TITLE
[GBA.emu] Could it stretch color value from 248 to 255?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1383]
VBA-M uses VBA's color implemention: take single 15-bit R/G/B color value multiply by 8, results 248, a little darker than modern screen. So could it stretch color value to 255 to match modern screen's brightness? ~~singlecolor + (singlecolor >> 5)~~

**Comment by Rakashazi** [comment]
Sure, looks like VBA chops off the extra bits so I'll replace the function with one that normalizes and scales the colors into the full RGB range in the next update.

**Comment by Rakashazi** [comment]
Added in 1.5.72 release

**Comment by Yave-Yu** [comment]
I think it could use a faster calculation, like somehow “(singlecolor << 3) + (singlecolor >> 2)”, or if the _singlecolor_ is already multiplied by 8, then “singlecolor + (singlecolor >> 5)”, so it could generate slightly smoother color 231 239 247 255 rather than 230 238 246 255 and of course, << or >> calculation is way faster than * or /
