### ISSUE TITLE
[Question]:NSF Format 

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1384]
### Describe your question

@rhello sir would you add the nsf to nes.emu how would it be possible in the next update to be able to play music from the nsf format if so what would you like to wait for you to add it because I would love to see something like this

**Comment by Rakashazi** [comment]
I added basic NSF support in the last commit, currently there's no visual display but that will be added in a future update.

**Comment by TheBoxGame** [comment]
> Dodałem podstawową obsługę NSF w ostatnim zatwierdzeniu, obecnie nie ma wizualnego wyświetlania, ale zostanie to dodane w przyszłej aktualizacji.
@Rakashazi could you fix the bug that when i switch to another song once it presses twice
