### ISSUE TITLE
NES.emu - Some plataform games showing a line that doesn't exist

### ISSUE THREAD

**Issue by GabrielP27i** [Rakashazi/emu-ex-plus-alpha#1391]
### Describe the bug

When i'm playing Super Mario Bros. 3, Kirby's Adventure and Tiny Toons Adventures 1, a line on the left of my screen appears.

Recently, i got the NES emu on my Play Store account, and i'm so happy to support this project! 

### Steps to reproduce

I just select this games to play and, when the game starts, the line appears.

### Expected behavior

That this line on the screen doesn't appears.

### Add screenshots

Kirby's Adventure:
![Screenshot_20230508-004750](https://user-images.githubusercontent.com/128992225/236730854-12346212-583d-4837-99e8-536cdd06adaf.png)

Super Mario Bros. 3:
![Screenshot_20230508-004820](https://user-images.githubusercontent.com/128992225/236730857-d35de1ec-df28-462e-a119-f4f40c2b06b2.png)

Tiny Toons Adventures 1:
![Screenshot_20230508-010421](https://user-images.githubusercontent.com/128992225/236731366-83bf1adb-84f9-423b-b9e1-ad55d4e0df52.png)

**Comment by TheBoxGame** [comment]
there were always these lines on pegasus

**Comment by TheBoxGame** [comment]
Use 8 Pixels on Sides

**Comment by Yave-Yu** [comment]
This is PPU mask, NES's feature, by setting $2001... so this is not emulator issue.

**Comment by GabrielP27i** [comment]
> Use 8 Pixels on Sides

Thanks, i didn't know much about nes emulation 😅
