### ISSUE TITLE
[Issue]: Virtual gamepad not shown on Set Button Positions screen

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#1392]
### Describe the bug

When you tap Set Button Positions, it seems the buttons are only shown if "Use Virtual Gamepad" is set to On. If it's set to Auto or Off, no buttons are visible.

### Steps to reproduce

Launch e.g. NES.emu. Before loading a game, tap On-screen Input Setup, then (with Use Virtual Gamepad _not_ set to On) tap Set Button Positions.

### Expected behavior

Buttons should always be shown when the user wants to change their positions.

**Comment by Rakashazi** [comment]
Thanks for the report, I'll have a fix for this in the next commit.

**Comment by Rakashazi** [comment]
Fixed in last commit.
