### ISSUE TITLE
[Issue]: [Swan.emu]Save file no md5 can't be loaded

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1395]
### Describe the bug

I copy my game save file from PC to my other device which installed Swan.emu. I found the save file can't be loaded. 
It's not necessary in mednafen, even if on the option for md5 save file name(default), you delete the md5 characters, it still can be loaded.

### Steps to reproduce

Save file no md5 can't be loaded.

### Expected behavior

The same as mednafen.

**Comment by leoxxx** [comment]
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1220
I think add a opttion to off md5 in save file name.

**Comment by Yave-Yu** [comment]
I hope Swan.emu could add an option that choose whether MD5 or not on save filename.

**Comment by Rakashazi** [comment]
I added a system option to not use MD5 in filenames. Try it out and let me know if the file loads properly.

**Comment by leoxxx** [comment]
@Rakashazi 
https://github.com/Rakashazi/emu-ex-plus-alpha/actions/runs/5031077462
It' O.K. THX.

BTW.
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1224
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1019
What do you think about this?

**Comment by Rakashazi** [comment]
@leoxxx I'm working on a way to have custom input mappings that should address those issues in the future.
