### ISSUE TITLE
[Feature request]: Turbo switch and push button switch.

### ISSUE THREAD

**Issue by Drak-eternal** [Rakashazi/emu-ex-plus-alpha#1397]
### Describe the feature

The app is missing two features:
1. A turbo button, in the form of a switch (pressed / not pressed), but so that it applies only to buttons with letters, and not to other keys. It is not convenient to take out all 6 buttons separately in the turbo version or keep the turbo button pressed manually. for example, the MK series and other fighting games.

2. turbo-type buttons, only in the form of switches (pressed / not pressed). This is necessary for those games where you often need to be able to keep one or another button pressed almost constantly. A vivid example of the game is Tom and Jerry - there, for example, the main attack of enemies is a run-away attack. Unfortunately, jumping or using projectiles in this way is not convenient.

**Comment by Rakashazi** [comment]
Thanks for the requests. I'm planing to update the input code to allow for any key to be turbo or switched in a future update.

**Comment by Rakashazi** [comment]
This is now implemented for virtual controls in the last commit and will be in version 1.5.74.
