### ISSUE TITLE
[Issue]: Cobra Triangle graphic bug on NES.emu

### ISSUE THREAD

**Issue by mosestyle** [Rakashazi/emu-ex-plus-alpha#1406]
### Describe the bug

Hello, whenever I try to play Cobra Triangle using NES.emu I always get a weird graphical issue that makes it unplayable. Do you know why or how we can fix it?

### Steps to reproduce

Just launch the game and you will get the graphical issue 

### Expected behavior

Graphical glitches

**Comment by TheBoxGame** [comment]
![Screenshot_2023-05-23-09-47-22-782_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/1456971c-607d-4c32-90a3-5f4a644d9536)

**Comment by TheBoxGame** [comment]
give a screenshot of what is it will help

**Comment by mosestyle** [comment]
> and you have codes enabled, see if you have launched the American version because the European version with NTSC mode is biting @TheBoxGame 

Thank you!! The American version worked great!!

**Comment by TheBoxGame** [comment]
> > a masz włączone kody zobacz czy uruchomiłeś wersję amerykańską bo wersja europejska z trybem NTSC gryzie@TheBoxGame
> 
> Dziękuję!! Amerykańska wersja działała świetnie!

no problem :)

**Comment by TheBoxGame** [comment]
no problem
