### ISSUE TITLE
[Issue]: UI buttons don't turn off

### ISSUE THREAD

**Issue by Fireadolfo** [Rakashazi/emu-ex-plus-alpha#1411]
### Describe the bug

When turn off UI buttons, this buttons are hide and not off

### Steps to reproduce

turn off any UI Button

https://github.com/Rakashazi/emu-ex-plus-alpha/assets/101057683/70396bd8-4913-4420-9cdb-cfc12cd573ff

### Expected behavior

buttons off

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in last commit
