### ISSUE TITLE
[Issue]: Force close when close content in Android 4.4.4

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1414]
### Describe the bug

Force close when close content in Android 4.4.4

### Steps to reproduce

Playing game, then open the menu and select the "close content", it force close.

### Expected behavior

Close the game.

**Comment by Rakashazi** [comment]
Thanks for the report, this should be fixed in the last commit so please test it out and let me know.

**Comment by leoxxx** [comment]
Great!
