### ISSUE TITLE
[Question]: How do I install this?

### ISSUE THREAD

**Issue by mschfqirl** [Rakashazi/emu-ex-plus-alpha#1415]
### Describe your question

I'm new too coding and i'm not sure how to install it

**Comment by TheBoxGamePL** [comment]
and you can replace robert broglia in updating emulators @mschfqirl

**Comment by Rakashazi** [comment]
I recommend looking at the github workflow to see the most up to date build steps:

https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/.github/workflows/build.yml
