### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#142]
Hi @Rakashazi after commit https://github.com/Rakashazi/emu-ex-plus-alpha/commit/4b5b8db I'm getting these compile errors. Do you have any idea where to look or what I can do to solve it?

Thanks in advance.

./src/io/ArchiveIO.cc:21:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.
/home/usr/projects/imagine/make/common.mk:29: recipe for target 'build/android-arm64-release/obj/io/ArchiveIO.o' failed
make[1]: *** [build/android-arm64-release/obj/io/ArchiveIO.o] Error 1
make[1]: *** Waiting for unfinished jobs....
./src/fs/ArchiveFS.cc:23:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.
/home/usr/projects/imagine/make/common.mk:29: recipe for target 'build/android-arm64-release/obj/fs/ArchiveFS.o' failed
make[1]: *** [build/android-arm64-release/obj/fs/ArchiveFS.o] Error 1

./src/io/ArchiveIO.cc:21:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.
/home/usr/projects/imagine/make/common.mk:29: recipe for target 'build/android-arm64-release/obj/io/ArchiveIO.o' failed
make[1]: *** [build/android-arm64-release/obj/io/ArchiveIO.o] Error 1
make[1]: *** Waiting for unfinished jobs....
./src/fs/ArchiveFS.cc:23:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.

./src/io/ArchiveIO.cc:21:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.
/home/usr/projects/imagine/make/common.mk:29: recipe for target 'build/android-arm64-release/obj/io/ArchiveIO.o' failed
make[1]: *** [build/android-arm64-release/obj/io/ArchiveIO.o] Error 1
make[1]: *** Waiting for unfinished jobs....
./src/fs/ArchiveFS.cc:23:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^~~~~~~~~~~
1 error generated.

**Comment by Rakashazi** [comment]
Check if the file ~/imagine-sdk/android-arm64/include/archive.h exists. If not then run:

```
cd $IMAGINE_PATH/bundle/all/src/libarchive
make -f android-arm64.mk install
```

**Comment by bladeoner** [comment]
@Rakashazi archive.h didn't exist in the location, the command you provided fixed the issue, thanks!

**Comment by bladeoner** [comment]
@Rakashazi after commit https://github.com/Rakashazi/emu-ex-plus-alpha/commit/9fea3dfd7346c2d32b147124e03dd42d0cb152ce I'm getting the same error messages, but this time I created libarchive upfront so the file does exist, any idea?

./src/io/ArchiveIO.cc:21:10: fatal error: 'archive.h' file not found
#include "archive.h"
         ^~~~~~~~~~~
1 error generated.
/home/usr/projects/imagine/make/common.mk:29: recipe for target 'build/android-x86_64-release/obj/io/ArchiveIO.o' failed
make[1]: *** [build/android-x86_64-release/obj/io/ArchiveIO.o] Error 1
make[1]: *** Waiting for unfinished jobs....
./src/fs/ArchiveFS.cc:23:10: fatal error: 'archive.h' file not found
#include "archive.h"
         ^~~~~~~~~~~
1 error generated.

**Comment by Rakashazi** [comment]
You're now building for the x86_64 architecture so you must build & install libarchive with the previous command but use the android-x86_64.mk makefile instead. To do this for all the bundled libraries used on Android and all architectures in one-shot, run these commands:
`cd $IMAGINE_PATH/bundle/all`
`bash makeAll-android.sh install`

If instead you only want to use a specific architecture instead of compiling for all 4, set the android_arch make variable when building Imagine, EmuFramework, & emulator cores. For example, to only build for the 64-bit ARM architecture:
`make -j4 -f android-release.mk android_arch=arm64`

**Comment by bladeoner** [comment]
@Rakashazi I had libarchive compiled for all 4 of them. Archive.h did exist when I was compiling, looking a little bit further into the issue I saw that Liblzma was showing in error that 'Autopoint' was not installed I installed that. And libogg also showed an error I had automake 1.15 installed and needed to updats to automake version 1.16 to be able to compile libogg. I need to perform some more testing.

I wanted to ask are there some guidelines which libs and tools are necessary to be installed to be able to compile and/or for example which Linux distribution can best be used. Which Linux distribution do you use to compile? I use a Linux Mint environment.

Thanks in advance.

**Comment by Rakashazi** [comment]
No problem, I'm using Gentoo Linux so many of the dev packages are already installed by default. Looks like autopoint is part of the gettext package, and you're correct that libogg requires automake 1.16. Here's the versions of the tools currently installed on my system for reference:

autoconf 2.69
automake 1.16.1
gettext 0.20.1
pkgconfig 0.29.2

**Comment by bladeoner** [comment]
Thank you for your feedback, installing gettext and automake 1.16.1 fixed the problem it is compiling now.
