### ISSUE TITLE
[Issue]: [Swan.emu]Only Y4 key?

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1424]
### Describe the bug

![12313](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/5364709/c304f8a9-3d7b-4b83-99ad-afb74d552281)
As shown in the picture, only  Y4 key. 

### Steps to reproduce

Goto "Gamepad"

### Expected behavior

Y1 Y2 Y3 Y4

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in last commit
