### ISSUE TITLE
[Issue]: L & R button got switched up

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#1425]
### Describe the bug

The bug occur with the latest pre-release of GBA.emu when I press the R button, it actually L button and so does the L button actually R button. Virtual or gamepad, the bug is there

### Steps to reproduce

Just play anything with GBA.emu

### Expected behavior

L = L
R = R

**Comment by Rakashazi** [comment]
Thanks, it's fixed in the last commit.
