### ISSUE TITLE
[Issue]:nes.emu fast forward speed error

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1428]
### Describe the bug

hello, I have a problem if it could be fixed,

### Steps to reproduce

when I press the fast reward speed button it is gray instead of red and after the reset it is only red

### Expected behavior

when you press the rewind button it should be red and it is gray when you press it and after game reset whether hard or soft reset it is only red

**Comment by TheBoxGame** [comment]
![Screenshot_2023-08-09-14-38-47-562_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/1155b73e-0a87-4108-b1e0-829efc93e5f1)
![Screenshot_2023-08-09-14-36-34-270_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/99780f04-ad7c-45de-907d-ba17c7d17153)

**Comment by Rakashazi** [comment]
Thanks, fixed in last commit
