### ISSUE TITLE
Add global custom palette setting (NES.emu)

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#143]
Add global custom palette setting, please, like set Disksys.rom

**Comment by Rakashazi** [comment]
I added default video mode and palette options in the last commit, coming in 1.5.43 release.

**Comment by Yave-Yu** [comment]
Same thing on GBC.emu, **Use Built-in GB Palettes** and **Report Hardware as GBA** are better make them as global setting than local.
