### ISSUE TITLE
[Issue]: Fast forward virtual button's highlight bugs

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#1431]
### Describe the bug

Basically when you press the fast forward button in every emu, it works but it doesn't highlighted, but when we go to the menu and back to the emu, the speed back to normal but the button stuck at highlighted

### Steps to reproduce

Open any emu and press the virtual fast forward button

### Expected behavior

Highlighted as the other buttons

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in last commit
