### ISSUE TITLE
[NES.emu] Update core to FCEUX 2.6.6

### ISSUE THREAD

**Issue by MinecraftMario27** [Rakashazi/emu-ex-plus-alpha#1434]
### Describe the feature

@Rakashazi FCEUX 2.6.6 is released
https://github.com/TASEmulators/fceux/commit/35218bd3135397afb647e6d117f325f1f42fcd46

**Comment by TheBoxGame** [comment]
@MinecraftMario27 and there are some new changes and new mappers added

**Comment by Rakashazi** [comment]
Updated to 2.6.6 in last commit
