### ISSUE TITLE
[Issue]:NES.Emu PPU Error

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1438]
### Describe the bug

@rakshazi could you check what happened that because not once there is something weird that glitches

### Steps to reproduce

if you run the game for a few minutes, it's ok, but then when you start another one, the screen glitches, for example in batman, i.e. the screen is once normal once glitched and so on alternately every second

### Expected behavior

after starting either a compilation or another game and launching another game should not glitch even though another game was just launched

**Comment by rakshazi** [comment]
No, I can't.
Typo in the username 😉

**Comment by TheBoxGame** [comment]
@rakshazi what a typo in the username

**Comment by TheBoxGame** [comment]
@Rakashazi ok can you add nsf UI and new mappers in next update i will gladly wait
256 356 315 313 ​​502 295 please add them
in version 1.5.74
