### ISSUE TITLE
Music breaks

### ISSUE THREAD

**Issue by RenanSD007** [Rakashazi/emu-ex-plus-alpha#144]
In Snes9x EX+ the music of these games below are having problems, are two SMW hacks and both run on Snes9x EX without problems.

●Mario's Mission [SMW Central]: Music breaks in the game.

●Super "Mario" World "2" [SMW Central]: Mute/Break sound in game title and the game does not start.

Maybe it can be a problem in games since music breaks on accurate emulators

I tried on other versions of Snes9x EX+, I saw both doesn't work on any, only on Snes9x EX.

I haven't seen this problem in other games since I only have SMW hacks downloaded at the moment, if I find any problems I will let you know, sorry for the inconvenience.

**Comment by Yave-Yu** [comment]
Try to turn off Block Invalid VRAM Access in Console Options?

**Comment by RenanSD007** [comment]
@Yave-Yu Turned off but nothing changed (Snes9x EX+ v1.5.41)

**Comment by RenanSD007** [comment]
I saw that it only works with a option "Echo Buffer Hack" that doesn't have in the mobile version, it would be nice if you added this option

**Comment by RenanSD007** [comment]
The problem is that it only worked on "SMW2", and it didn't work on "Mario's Mission" (I'm using RetroArch, then I'll see if Snes9x v1.60 Windowns works both)

**Comment by RenanSD007** [comment]
Oh shit, the music only works from Overworld, if you reset the Snes9x core (with Echo Buffer enabled) in this part the music works fine ​​but it only works by doing this every time you enter the game which is really annoying, again sorry for the inconvenience.

**Comment by RenanSD007** [comment]
In Snes9x Windows it was the same thing as the other two (Snes9x EX+ & Snes9x Core), only the Snes9x EX that really works, what a waste of time haha, I will use the EX only for SMW hacks and the EX + for any other game, it is the best to do

**Comment by Rakashazi** [comment]
Ok, thanks for the report. I'm adding the separate echo buffer option in the next update to match PC Snes9x.

**Comment by RenanSD007** [comment]
Thanks for the great work @Rakashazi, I downloaded the new version, now Super Mario World 2 works perfectly, then I will test other hacks that have this same sound problems.

**Comment by RenanSD007** [comment]
"Separate Echo Buffer" only works the first time you enter the game (after turning on and resetting the game), the next time it only works if you delete the game's configuration file or "turn off" and "turn on" Echo Buffer again  and reset the game, is there any way to make it work whenever you enter the game without having to delete / change the settings?

 I have a suggestion, these games only give error because of a bug in the Addmusic program that had in the older versions (It made the Echo much higher than the Original Hardware), so you would have to take part of the source code where it is stored the Echo (if this code exists) or take the entire APU/SPC code from the Snes9x EX and put it in a separate code on the Snes9x EX+ to make it work well in this new option?  I tested other SMW hacks with this problem and they all worked very well on the EX, it would also be good to work on the EX+ as it is a accurate emulator in the emulation of SA-1 and other chips (required for some hacks).

**Comment by Rakashazi** [comment]
I didn't spot the config error until after the last release but it's fixed now and the echo buffer setting will save properly in the upcoming 1.5.43 version.

The echo is handled by the SPC's DSP and implemented under Snes9x/src/snes9x/apu/bapu/dsp if you want to have a look. As for converting the 1.43 APU code, there were various API changes that would make it quite time consuming so it's beyond the scope of my port.

**Comment by RenanSD007** [comment]
I see, thanks for answering and fix the config error.

I did a translation in Brazilian Portuguese with the texts I saw in the App except with the "Error messages", if you want I will send you if it is not a problem.

It is in this format, example:

#MENU_STRINGS (Strings for Menu Items)

[load_game] (Original String)
Carregar Jogo (Translation String)

[recent_games]
Jogos Recentes

[cheats]
(when there is no translation)

I saw that the texts are inside the source code which is much more difficult to do a translation
