### ISSUE TITLE
[Issue]: Gamepad Profile Keeps Resetting

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#1448]
### Describe the bug

Whenever I disconnect and reconnecting my gamepad, the emulator keeps resetting the input profile to the PC keyboard. It occurs in GBA.emu

### Steps to reproduce

Create a new input profile, then disconnect and reconnecting the gamepad

### Expected behavior

Keep the input setting into our own custom profile

**Comment by Rakashazi** [comment]
Thanks for the report, is this still happening on the latest build? If so, can you attach a screen recording showing the sequence of action from launching the app that causes the input profile to reset?

**Comment by emyaqin** [comment]
Its fixed, thank you! I'll close it now
