### ISSUE TITLE
[NES.emu] Global setting for NES timing (NTSC/PAL/Dendy)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#145]
**1.5.37**
_options -> video -> video system = [Auto / NTSC / PAL / Dendy]_
NES timing was global for all ROMs

**1.5.40**
_system actions -> console options - > video system = [Auto / NTSC / PAL / Dendy]_
NES timing is custom for every ROM now, it reading from "_romname_.config" in your ROM folder.

Can you make option to set global timing for all ROMs, like it was in 1.5.37 and earlier please?
Most of _desktop NES emulators_ have similar behaviour (timing = global option)

Same thing about palette: https://github.com/Rakashazi/emu-ex-plus-alpha/issues/143

**Comment by Rakashazi** [comment]
I added default video mode and palette options in the last commit, coming in 1.5.43 release.
