### ISSUE TITLE
[GBA.emu] Update core to latest?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1455]
### Describe the feature

Currently I’ve seen VBA-M 2.1.7, it’s core got some update. First I feel it no longer much laggy like 2.1.4 (still laggy than mGBA), and I feel it’s emulation accuracy more close to mGBA, such as same error happens on some Pokemon hack. Second a fan Chinese translation of Rockman EXE 2/Mega Man Battle Network 2 **could** run normally, not cause softlock when hit start key to open menu. So it’s worth to update core.

### Add screenshots

This is VBA-M 2.1.7, now it could run MMBN2 fan Chinese translation normally, opened menu.
<img width="721" alt="{7D377D85-604F-426c-AF3A-AE8486B057D6}" src="https://github.com/Rakashazi/emu-ex-plus-alpha/assets/54294476/e8065f7e-d00c-41f1-8734-406d6f415ff1">

**Comment by Rakashazi** [comment]
I ported over the changes from the current VBA-M GIT version that includes 2.1.7. Let me know if you run into any differences in the emulation between VBA-M and GBA.emu.

**Comment by ErickN13** [comment]
Wait, is the 1.5.77 launching tomorrow?
