### ISSUE TITLE
MSX.emu compile error

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#146]
After commit https://github.com/Rakashazi/emu-ex-plus-alpha/commit/47914dc9272b97dc6da34fdcbc12c1a9ba4af90e I'm getting the following compile error:

/src/main/BlueMSXApi.cc:76:19: error: no member named 'now' in 'std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1, 1000000000> >'
        return IG::Time::now().mSecs();
               ~~~~~~~~~~^
1 error generated.

**Comment by bladeoner** [comment]
I used the attached file to fix the compilation issue.
@Rakashazi could you review it and merge if the change is valid?

Thanks in advance.
[MSX.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4269558/MSX.zip)

**Comment by Rakashazi** [comment]
Thanks, I forgot to update that function. It's now fixed in the latest commit.
