### ISSUE TITLE
[Feature request]:add option reset game in emulators

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1462]
### Describe the feature

I mean adding this option in Key/Gamepad input setup and action settings and emulations actions

### Add screenshots

![Screenshot_2023-10-18-08-32-38-552_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/a8927cfd-25ef-4744-a0c3-94b0f215309d)
![Screenshot_2023-10-18-08-32-11-748_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/9254adb0-a41e-4773-9179-7efcb7d2a4f2)
![Screenshot_2023-10-18-08-32-35-810_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/1923841f-ed5c-43ee-b0d0-ff78cbfd2f07)

**Comment by Rakashazi** [comment]
Added in last commit
