### ISSUE TITLE
[Issue]: Clear list - Recent content 

### ISSUE THREAD

**Issue by master1274** [Rakashazi/emu-ex-plus-alpha#1463]
### Describe the bug

Shield Tablet 32GB/LTE, Tegra K-1, Android 7.0, ARMv7, 320 dpi(1920х1200), OpenGL ES 3.2, Vulkan 1.0, Core 4x ARM Cortex-A15 - 2218 MHz.
In the latest build of emulators https://github.com/Rakashazi/emu-ex-plus-alpha/commit/5e093a8e5f0bb16424a27e79be681937d8459295 does not work clear list In chapter recent content

### Steps to reproduce

*

### Expected behavior

*

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in last commit
