### ISSUE TITLE
Why is Saturn.emu not in Version Release?

### ISSUE THREAD

**Issue by ErickN13** [Rakashazi/emu-ex-plus-alpha#1468]
### Describe your question

Why saturn.emu is not in Version Release?

**Comment by Rakashazi** [comment]
Saturn.emu was based on an old version of Yabause and had various issues so it's not currently supported. I plan to fully re-do the app in the future and start releasing builds of it.

**Comment by ErickN13** [comment]
> Saturn.emu was based on an old version of Yabause and had various issues so it's not currently supported. I plan to fully re-do the app in the future and start releasing builds of it.

Alright, I'll wait if you ever start Remaking Saturn.emu
