### ISSUE TITLE
GBA.emu update core?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#147]
Update VBA-M core to latest?

**Comment by Rakashazi** [comment]
It looks like most of the recent changes were port-specific code that doesn't apply to GBA.emu but if you have a specific game fix you'd like to see pulled in let me know.

**Comment by Yave-Yu** [comment]
Pokemon Emerald Chinese Translation.
It stucks in Pokedex details on GBA.emu, but won't stuck on newer VBA-M.

**Comment by Rakashazi** [comment]
The GBA.emu core was updated to VBA-M 2.1.4 in the last commit.
