### ISSUE TITLE
[Issue]: Cheat Codes Are not saving when i update the app

### ISSUE THREAD

**Issue by ZeDaGOIABA7-BR** [Rakashazi/emu-ex-plus-alpha#1470]
### Describe the bug

everytime that i update this app, my cheat codes dissapear..
Please fix that

### Steps to reproduce

Uodate the app..

### Expected behavior

Save my cheat codes when i update

**Comment by ErickN13** [comment]
Não Cara,Nas Configurações do File Path Nas Configurações do Emulator, você deve colocar o Path do Cheats na Pasta onde Está os Arquivos .cht

**Comment by ZeDaGOIABA7-BR** [comment]
A, obrigado Mano

**Comment by ErickN13** [comment]
Conseguiu resolver?
