### ISSUE TITLE
[Feature Request] Enhance Screen Positioning and Zoom

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Rakashazi/emu-ex-plus-alpha#1472]
I've been using your app and I have a few suggestions that could make it even better.

1. **Add Vertical Screen Positioning:** Right now, the app only lets you move left and right. How about adding the ability to move up and down as well? This would make the positioning of the app on the screen more flexible.

2. **Separate Screen Positioning Option For App Screen:** I was thinking it might be cool to have a separate option for moving the App screen. This way, we can customize the  App Screen Positioning  independently from the Content Screen.

3. **Increase Content Zoom Limit:** The current zoom limit for the Content Screen is between 10-100. I'm thinking it'd be nice to bump that up to 1-500.

4. **Increase App Zoom Limit:** Similar to the content zoom limit, I think it'd be great to increase the App zoom limit from 50-100 to 1-500.

**Comment by TheBoxGame** [comment]
and this function

**Comment by Rakashazi** [comment]
@OilSubjectLoss7 Thanks, I'll add these to the list of requested features. In the last commit I also added the ability to increase content zoom up to 200%.
