### ISSUE TITLE
Mirroring with TV

### ISSUE THREAD

**Issue by ErickN13** [Rakashazi/emu-ex-plus-alpha#1479]
### Describe the feature

One thing that many people want is the Mirroring of the Emulator with the TV, so that everything that appears on the Emulator Screen also appears on the TV

**Comment by Rakashazi** [comment]
This is already supported if your device supports wired or wireless video output. Use the "External Screen" video option to control what's displayed.

**Comment by ErickN13** [comment]
But how can I mirror the screen in the Emulator Settings?
