### ISSUE TITLE
NES not working

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#148]
@Rakashazi after commit https://github.com/Rakashazi/emu-ex-plus-alpha/commit/fdaf327d185b9a489d739b76abe18f3698318277 I'm getting a black screen when trying to load a game NES.emu. The emulator starts but when you load a game it won't continue, I tried multiple games. Do you also experience this?

**Comment by Rakashazi** [comment]
Thanks, I missed this by accident since I was testing with auto-save states on. The PPU is off the first few frames after power-on and FCEUPPU_Loop() wasn't calling into EmuVideo as is required by the updated timing code. It's now fixed in the last commit.
