### ISSUE TITLE
[Issue]:fix custom settings controller 

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1483]
### Describe the bug

Can you fix the problem with saving the profile of a controller without a wired one? I have set the buttons for my controller, but when I restart it, it switches to the standard profile and not to the one created by the user. Oh, and one more thing, can you fix the problem with the controller settings? If I want to configure my controller, it doesn't work. I can because I'm about to switch to custom 1

### Steps to reproduce

Well, when I want to set my gamepad to a normal generic gamepad, I can't because it jumps to ccustom 1 and, secondly, it loses the settings of the saved profile of the gamepad from custom 1 to generic gamepad.

### Expected behavior

so if I set the controller arbitrarily, after reconnecting the controller to Bluetooth and running the emulator, the settings should be kept the same as they were after configuration, even after creating a custom one.

### Add screenshots

![Screenshot_2023-11-17-16-45-35-491_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/a4eb421a-f22b-43d0-ba54-76900c049c99)
![Screenshot_2023-11-17-16-45-26-715_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/4e2f99bf-5cbb-493d-92f5-96a77bd089d3)
![Screenshot_2023-11-17-16-45-24-390_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/8613559d-36ce-48d0-a7da-48c22c76c256)
![Screenshot_2023-11-17-16-45-16-904_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/2adc16ce-e42d-4cb1-aca3-7a3b75698fbe)

**Comment by Rakashazi** [comment]
Does it still do that with the latest build? If so, can you attach a step-by-step screen recording from launching the app until the issue occurs?

**Comment by Rakashazi** [comment]
Some additional fixes to input device configurations were applied in 1.5.76 so I believe this is resolved.
