### ISSUE TITLE
[Feature request]:FDS Control Disk Settings

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1485]
### Describe the feature

@can you add this option to the pad, for example, if someone had a controller, they could use the controller to change the page of the disk without entering the menu

### Add screenshots

![Screenshot_2023-11-20-12-44-29-369_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/cc17cc17-b7ac-4949-9678-c362b449cc5d)
![Screenshot_2023-11-20-12-44-09-916_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/4c4aa3fd-6ac3-46ec-9f75-3876c6bed8dc)
![Screenshot_2023-11-20-12-44-02-725_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/63535327-d984-446b-9538-9824c143f1e2)

**Comment by Rakashazi** [comment]
Sure, I added this in the last commit, under the "Extra Functions" category

**Comment by TheBoxGame** [comment]
@rakashazi the app crashes, something is broken
