### ISSUE TITLE
Forecast of when 1.5.75 will be released

### ISSUE THREAD

**Issue by ErickN13** [Rakashazi/emu-ex-plus-alpha#1486]
### Describe your question

@Rakashazi Do you already have an estimate of when 1.5.75 will be released for Android?

**Comment by ErickN13** [comment]
@Rakashazi a Versão 1.5.73 foi lançado logo 3 meses Antes da Versão 1.5.74, e a Versão 1.5.74 foi lançada a 3 meses atrás ,então,  já é tempo para lançar a versão 1.5.75,ou então falta bem poucos dias para lançarem

**Comment by Rakashazi** [comment]
There's no fixed schedule but I'm almost done testing the newly implemented features so the next update should be released on the Play Store soon.
