### ISSUE TITLE
[Issue]:Crash Aplication NES.Emu

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1487]
### Describe the bug

after starting the application, it crashes to the main screen

### Steps to reproduce

after starting the application, it crashes to the main screen

### Expected behavior

the application should run but it crashes
​

### Add screenshots

the application should run but it crashes
​

**Comment by Rakashazi** [comment]
What version of Android are you using? Did it start happening in the last commit?

**Comment by TheBoxGame** [comment]
yes android 14

**Comment by TheBoxGame** [comment]
@Rakashazi please fix https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1484

and add new mappers 419 295 502 256

**Comment by Rakashazi** [comment]
Thanks for the info, please check if the last commit still has the crashing issue.

**Comment by TheBoxGame** [comment]
now no thanks
