### ISSUE TITLE
GBA.emu keep crashing

### ISSUE THREAD

**Issue by Tsudayfrt** [Rakashazi/emu-ex-plus-alpha#1488]
### Describe the bug

https://github.com/Rakashazi/emu-ex-plus-alpha/assets/116885476/2fb98755-aedc-4503-82c2-a6e9e7de333b

### Steps to reproduce

GBA.emu keep crashing

### Expected behavior

GBA.emu keep crashing

**Comment by Rakashazi** [comment]
Is this the Play Store build or the nightly build?

**Comment by Tsudayfrt** [comment]
> Is this the Play Store build or the nightly build?

Nightly build

**Comment by Rakashazi** [comment]
What Android version and device are you using?

**Comment by Tsudayfrt** [comment]
> What Android version and device are you using?

Android 13 • Poco X3 Pro

**Comment by ErickN13** [comment]
My GBA.emu doesn't have this bug.

be yourself
https://github.com/Rakashazi/emu-ex-plus-alpha/assets/144749573/290c4661-a9b6-4be6-9aab-b639da451778


And here is some information about my cell phone.


![Screenshot_20231126-171513.jpg](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/144749573/69295056-3fa4-415f-9d0e-eb1a74f55bdb)

![Screenshot_20231126-171508.jpg](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/144749573/e432fa97-d88f-4223-8a88-5143af46b231)

That's it

**Comment by Tsudayfrt** [comment]
> My GBA.emu doesn't have this bug.
> 
> be yourself https://github.com/Rakashazi/emu-ex-plus-alpha/assets/144749573/290c4661-a9b6-4be6-9aab-b639da451778
> 
> And here is some information about my cell phone.
> 
> ![Screenshot_20231126-171513.jpg](https://private-user-images.githubusercontent.com/144749573/285679341-69295056-3fa4-415f-9d0e-eb1a74f55bdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzM3MjgsIm5iZiI6MTcwMTAzMzQyOCwicGF0aCI6Ii8xNDQ3NDk1NzMvMjg1Njc5MzQxLTY5Mjk1MDU2LTNmYTQtNDE1Zi05ZDBlLWViMWE3NGY1NWJkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQyMTE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzQ0NmJlYmYzYmFhZmY1NGUyYzllZmU4OWJiMjNiYWE1ZTlkMDJlMzY3MjYwNDFmYTMzNmYyNGYxMzcyZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wC-5CwprraPB6gdpnvdYiKqAOB7CyXq8iTuTS4kDhTs)
> 
> ![Screenshot_20231126-171508.jpg](https://private-user-images.githubusercontent.com/144749573/285679342-e432fa97-d88f-4223-8a88-5143af46b231.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzM3MjgsIm5iZiI6MTcwMTAzMzQyOCwicGF0aCI6Ii8xNDQ3NDk1NzMvMjg1Njc5MzQyLWU0MzJmYTk3LWQ4OGYtNDIyMy04YTg4LTUxNDNhZjQ2YjIzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQyMTE3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzllMDFmNDUxMjQwZTBkYzFlZDk5NGRjMWQwZWY4MDFjMDBjNjE3MGJjMWQwNDFmOWNkNTFmNDNhNWI5N2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ox_I3r6AFksYnKdsRPffN74jnqUuYCdbQSjAubgHHns)
> 
> That's it

You're on Android 10, Mine is Android 13

**Comment by Tsudayfrt** [comment]
> Thanks for the info, please check if the last commit still has the crashing issue.

It's working 😃. Thanks for the update
