### ISSUE TITLE
Gba.emu crashes 

### ISSUE THREAD

**Issue by Guillermo4060** [Rakashazi/emu-ex-plus-alpha#1489]
### Describe the bug

When you enter the emulator, it exits and makes it unplayable. I would also like to take this opportunity to tell you if there is already a solution for the noise issue since very little is heard, those would be the only problems that I would like to report.

### Steps to reproduce

Open

### Expected behavior

No

### Relevant log output

```shell
No
```

**Comment by TheBoxGame** [comment]
yes of course

**Comment by ErickN13** [comment]
@Rakashazi come read this

**Comment by Rakashazi** [comment]
Please check if the last commit still has the crashing issue.

**Comment by ErickN13** [comment]
Eu acho que a versão 1.5.75 vai ser uma das melhores Atualizações de Todas.
