### ISSUE TITLE
Snes9x - SuperFXClockMultiplier

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#149]
Hi @Rakashazi thank you for solving the issues I send in.

I wanted to ask if it is possible to add the SuperFXClockMultiplier to the options menu of Snes9x.

If so, the default is 100 and the range should be until 200 with increments of 1 or 5, as you prefer.

Thanks in advance.

**Comment by Rakashazi** [comment]
Sure, should be able to fit this in sometime this month.

**Comment by Rakashazi** [comment]
I added this in the last commit, will be in 1.5.43 release.
