### ISSUE TITLE
[Issue]: Will not be able to install any version MD.Emu (signatures conflict after uninstalling previous version apk)

### ISSUE THREAD

**Issue by makpmp** [Rakashazi/emu-ex-plus-alpha#1496]
### Describe the bug

After deleting the previous version (Md.Emu 1.5.74) with the "keep data" option, the new version (Md.Emu 1.5.75) is not installed. Signatures do not match previously installed version.

After trying to install via adb
 `adb install MdEmu-release.apk`

got an error: _Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.explusalpha.MdEmu signatures do not match previously installed version; ignoring!]_

Adb command 
`adb shell pm uninstall com.explusalpha.MdEmu` or `adb uninstall com.explusalpha.MdEmu`

don't work, error: _Failure [DELETE_FAILED_INTERNAL_ERROR]_

And I can't find "com.explusalpha.MdEmu" in the list using 
`adb shell cmd package list packages -f`

Tried several apk from internet (v1.5.71 - v1.5.75) but got same error _Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.explusalpha.MdEmu signatures do not match previously installed version; ignoring!]_. Find same apk imposible.
Rebooting, wipe cache, cleaning with standard smartphone tools did not help

Same problem:
[issues 1369](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1369)
[issues 1129](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1129)
[issues 1180](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1180)

### Steps to reproduce

1. Install old version apk (Md.Emu v1.5.74 or earlier)
2. Uninstal with "keep data" option
3. Install actual version (Md.Emu v1.5.75)

### Expected behavior

- Need a tool to delete "keep data" from smartphone or solving problem
- Need "how to" information about solving this problem
- Need archive program with different signatures
- Need additional information when uninstalling emu

**Comment by Rakashazi** [comment]
If you select keep data, the app should still be listed in your Android Settings app and can be fully uninstalled there. Currently the nightly builds are signed with a debug key but I'll look into signing them with my production key in the future.
