### ISSUE TITLE
[Issue]: Flickering Issues in GBA.emu

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#1497]
### Describe the bug

The game's flickering and sometimes glitching whenever it shows an upper text box like in Final Fantasy DoS and Advance Wars 2. I can confirm this is a bug cause I didn't have the issue with another emulator

### Steps to reproduce

Keep playing the game, you won't miss it

### Expected behavior

Smooth as silk, crisp as... crisp

### Add screenshots

You can see the line glitch on the left
![Screenshot_20231211-133900_GBAemu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/74818814/828b9a33-622c-4a33-ae20-116f4b28d29f)

And the glitch after flickering
![Screenshot_20231211-134022_GBAemu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/74818814/409dc02b-5aa5-45fe-a341-29ce5139afa4)

**Comment by Rakashazi** [comment]
This is probably related to timing differences when using a real vs simulated BIOS. I'll add real BIOS support in a future update so we can test again when that's implemented.

**Comment by emyaqin** [comment]
Aw yeah, thanks. Keep up the good work, can't wait to see it got implemented

**Comment by emyaqin** [comment]
I'm gladly report that the issue is fixed with the implementation of the BIOS

**Comment by Rakashazi** [comment]
Ok, can you check in Key/Gamepad Input Setup -> Individual Device Settings, and see if any of the devices are defaulting to the "Generic Gamepad" profile? That indicates the app is detecting a gamepad and isn't showing the virtual controls by default.

**Comment by emyaqin** [comment]
Apparently, there is. I just switched to a new device, which is Xiaomi with MIUI and there's one individual settings that defaulted to generic gamepad. Can it be fixed or something?

![Screenshot_2024-04-04-00-00-26-921_com explusalpha Snes9xPlus](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/74818814/b4ae9e42-c7cf-42e8-8895-e4decd544ca7)

![Screenshot_2024-04-04-00-00-17-865_com explusalpha Snes9xPlus](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/74818814/34ad1ec0-1052-4963-845c-0b56e83d4df0)

**Comment by Rakashazi** [comment]
Thanks, it looks like uinput-fpc is the fingerprint sensor and is using the uinput driver which reports itself as other device types including a joystick/gamepad. I'm going to add a special rule to ignore this in the next commit which should fix the issue.
