### ISSUE TITLE
[Question]:Fix Mapper MMC3 MMC5

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1499]
### Describe your question

@Rakashazi Can you fix these two mappers in the next commit because something is broken in them and the games from the mmc3 mmc5 mapper do not run as they should?

### Add screenshots

![Screenshot_2023-12-14-15-07-02-875_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/bb063b3e-daa0-4d9a-9b03-d7d35aa8940a)

**Comment by Rakashazi** [comment]
What's a specific MMC3 or MMC5 game that's having this issue?

**Comment by TheBoxGame** [comment]
@Rakashazi 6-in-1 (MMK-012-04)
4-in-1 (K-4049)
with these and other games that have this mmc5 and mmc3 mapper

**Comment by TheBoxGame** [comment]
@Rakashazi this mappers mmc3
iNES mappers 4,12,44,45,47,49,52,74,114,115,116,118,
 119,165,205,245,249,250,254

**Comment by TheBoxGame** [comment]
@Rakashazi fix this mapper plis
