### ISSUE TITLE
Add option to not clip display for NES

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#15]
This is a small feature request.

Both PAL and NTSC NES consoles output 240 active picture lines, but NES.emu clips the top and bottom 8, showing only 224. While some NTSC TVs might have the top and bottom few lines not visible, they are output by the console. And all 240 lines are always visible on PAL consoles.

An option to show the full 240 lines would be good for a several reasons:
- Some games put important information in the currently-blanked lines, e.g. Parodius PAL, Elite PAL.
- The user may prefer to see more of the playfield. If using integer vertical scaling, the display may be no smaller than when only showing 224 lines, just without black bands at the top and bottom (e.g. for 480 or 720 pixel screen height).
- Scaling a 240-line image to e.g. 1080 pixels is 4.5x scaling, a nice round ratio which should look better than scaling 224->1080 (a 135/28 ratio). Similarly, scaling a 240-line image to 600 pixels is 3.5x scaling, vs 75/28 for 224->600.

**Comment by Rakashazi** [comment]
I've been meaning to add more control over the visible lines/overscan, will keep this open until I start working on it.

**Comment by Rakashazi** [comment]
An option for showing the overscan lines was added in the last commit.
