### ISSUE TITLE
[Issue]: In-game saves are gone when I restart the application.

### ISSUE THREAD

**Issue by HelpMeGetANamePlease** [Rakashazi/emu-ex-plus-alpha#1502]
### Describe the bug

Whenever I save the game in-game, and then close the application. The save game is nor there when I open the app and the game again. I've tried this on Chrono Trigger, Super Mario All-Stars, Earthbound and Legend of Zelda: A Link to the past.

Savestates work as intended. Only the in-game saves don't work. Also if I use the "Close content" option and start the game again the save game is there. I've tried change the file path to a folder in internal memory but that does nothing differently.

### Steps to reproduce

Use the save feature in any game. Close the app. Open the app, select the game. I don't see my save file.

### Expected behavior

I expect the in-game save to be there after I restart the application.

**Comment by emyaqin** [comment]
Weird, but I've never had this issue ever. You sure don't mess or change the autosave launch mode, etc?

**Comment by HelpMeGetANamePlease** [comment]
I've set autosave launch mode to (No save slot).

**Comment by Rakashazi** [comment]
I wasn't able to reproduce the in-game save issue here. Are you quitting by swiping the app away or using the Exit command in the main menu? Also, in your Android Settings app do you have Developer Options enabled and if so, what is "Background process limit" set to?

**Comment by HelpMeGetANamePlease** [comment]
I've tried exiting the app by both of the methods that you described. The background process limit' is set to 'standard limit'.

**Comment by Rakashazi** [comment]
If you already have an existing save file does it get deleted or does it stay in the previous state from when you initially loaded the game? If possible, please attach a short screen recording showing the exact sequence of actions you're doing and also the contents of Options -> System.

**Comment by HelpMeGetANamePlease** [comment]
Uploading Screenrecorder-2023-12-15-20-39-44-116.mp4…
I've done as you asked.

**Comment by HelpMeGetANamePlease** [comment]
https://github.com/Rakashazi/emu-ex-plus-alpha/assets/96776376/d85685c1-77b9-45bb-8c76-ba5b5a166f26
I've done as you asked.

**Comment by Rakashazi** [comment]
Thanks for the video, you have Autosave Launch Mode set to No Save Slot so that won't load anything including in-game saves. Change it to Main Slot (No State). That will load just the in-game save which is the probably the behavior you're looking for.

**Comment by HelpMeGetANamePlease** [comment]
Thank you very much. It's working as expected now.
