### ISSUE TITLE
[Issue]: Every emu crash

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#1505]
### Describe the bug

The app will crash when I choose yes from anything in the console options that prompted to restart

### Steps to reproduce

Play any game with any emu, go to console options in system actions, toggle anything that will prompt to restart (like video system, etc) choose yes, poof, crash

### Expected behavior

Reset the system or game (?)

**Comment by Rakashazi** [comment]
Thanks for the report, this should be fixed in the last commit.
