### ISSUE TITLE
[Question]:Overclocking NES.Emu 

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1507]
### Describe your question

can you tell me what the hell this overclocking is for as nes shouldn't support it
In the case of Laser Invasion, there is something that when I have the touchscreen on, the game runs fast and when I have a pad connected, the game slows down, which shouldn't even happen.

### Add screenshots

![Screenshot_2023-12-20-16-14-51-264_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/840a1e4b-617c-4a75-8fb0-57f571a4aac9)

**Comment by kausikkumaar** [comment]
@TheBoxGame dude it is already there. Look my screenshot, when game running for to menu Console Options 
![IMG_20231224_162028](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/154484701/ad2ac5c2-fb6b-49c8-9b46-5c1f92fe3e9d)

**Comment by TheBoxGame** [comment]
@kausikkumaar what I mean is that when I have it on bluetooth connected to the phone and when I run the Laser Invasion game, the game slows down, and when I disconnect it from bluetooth and return to the touch screen, it works normally without any slowdowns.
