### ISSUE TITLE
Snes9X EX: Add 224 lines lock

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#151]
New version of Snes9X EX(or Snes9X EX+) can change 224/240 lines automaticly, but every pixel will change to dwarf when in 240 lines, so can you add a global option to lock in 224 lines? Thanks!
![Screenshot_2020-03-28-16-04-01-027_com explusalpha Snes9xPlus](https://user-images.githubusercontent.com/54294476/77818552-4e93a080-710e-11ea-955b-7addf0392f47.png)

**Comment by Rakashazi** [comment]
Thanks for the report, I'll look into this for a future update.

**Comment by bladeoner** [comment]
@Rakashazi is this added with the following commit?
https://github.com/Rakashazi/emu-ex-plus-alpha/commit/5fc4109b5407f59207cc1e33d94477f76a4bd239

**Comment by Rakashazi** [comment]
Added and will be included in the 1.5.59 release.
