### ISSUE TITLE
[Question]: snes9x ex+

### ISSUE THREAD

**Issue by monarck1** [Rakashazi/emu-ex-plus-alpha#1513]
### Describe your question

hi, what does "benchmark content" mean?

**Comment by emyaqin** [comment]
It's for testing the performance of your phone to emulate the said system, most modern phone is capable to run most of emulator in this repo, so yeah, just a basic feature

**Comment by monarck1** [comment]
I understand, it shows the fps that the smartphone gets in the game

**Comment by emyaqin** [comment]
Yep, some kind like that

**Comment by Rakashazi** [comment]
Yes, this is a CPU throughput benchmark done by emulating a series of frames without outputting any audio/video.
