### ISSUE TITLE
[Question]:NES.Emu Mapper 45 Fix

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1514]
### Describe your question

@Rakashazi please fix this mapper 45 in the next commit because I can't run any rom with this mapper 45

**Comment by TheBoxGame** [comment]
![284249199-2faf3f8b-9c40-4736-a3af-a62b64cc928b](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/2a8f78b8-75a3-4e94-8396-99d81107b50f)

**Comment by TheBoxGame** [comment]
@Rakashazi please fix this mapper

**Comment by Rakashazi** [comment]
I fixed the mapper 45 issues. Don't spam issues you've already posted before, If you open another duplicate issue your account will be banned.
