### ISSUE TITLE
[Question]:NES.Emu Fix This Mapper Please

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1519]
### Describe your question

I mean this rom, there is a problem with mapper 45 57 52 , could you fix it in the next commit, I asked for it many times, I give the rom

### Add screenshots

![Screenshot_2024-01-03-13-32-15-108_com eltechs ed](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/20d48207-e360-407c-86d9-32009494ca34)
![Screenshot_2024-01-03-13-33-21-702_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/0ef975f7-e2d3-41ed-a49e-99d02aa44d9e)
[4-in-1 (YG-4002).zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/13818966/4-in-1.YG-4002.zip)

**Comment by ErickN13** [comment]
O que são mappers?

**Comment by TheBoxGame** [comment]
nes suporta algo como mapeadores e eles respondem ao lançamento de um determinado tom ou disquete, então se não houver mapeador 45, um determinado título com este mapeador não será executado mesmo após um reset, neste caso estou fornecendo uma captura de tela
![Screenshot_2024-01-01-16-20-34-111_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/a9ea3309-44e1-4979-953f-bbafe4561377)
![Screenshot_2024-01-01-16-20-49-503_com explusalpha NesEmu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/a3e9371b-3fe5-4bc5-9ad1-fad2bc6b6608)

**Comment by ErickN13** [comment]
E esses mapeadores são ROMs Originais?

**Comment by TheBoxGame** [comment]
@ErickN13 Eu não entendo

**Comment by TheBoxGame** [comment]
@Rakashazi please fix this 3 mappers 52 57 45
