### ISSUE TITLE
Is it couldn't keep screen on now?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#152]
In 1.5.42, when running any .emu, screen can not be keeped on, but in old version like 1.5.37. it can keep screen on.
Is it a bug, or on purpose?

**Comment by Rakashazi** [comment]
This is controlled by Options -> GUI -> Dim Screen If Idle. The handling of this option was changed during an update and it should default to off while in-game so I'll fix it in the next update.

**Comment by Rakashazi** [comment]
I fixed the default behavior in the last commit and renamed the option to "Allow Screen Timeout In Emulation" for clarity.
