### ISSUE TITLE
[Feature request]: PCE.emu (CD games only) - Open CHD/CUE files via frontend/file search

### ISSUE THREAD

**Issue by SiobobKipper** [Rakashazi/emu-ex-plus-alpha#1520]
### Describe the feature

Currently, when trying to open .chd or .cue files using "Browse for File" or via frontend (I use Pegasus), the app shows an error that "the content must be opened with a folder" instead.

This is not an issue if the content is in bin/cue format and in a .zip archive. A zipped CHD still doesn't work but instead the error message states "Failed to load CHD image."

The zipped bin/cue workaround is fine, but is it possible to implement the direct loading of CHD files, zipped or not?

**Comment by Rakashazi** [comment]
Thanks for the report. Both issues should be fixed in the last commit. The folder error was only meant for multi-file cases like .cue files and was incorrectly applied to CHD files. I also updated the CHD code to handle loading inside archives.
