### ISSUE TITLE
[C64.emu] The emulator defaults to inaccurate drive emulation settings and there's no way to change the default

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [Rakashazi/emu-ex-plus-alpha#1521]
### Describe the bug

When a new disk image is launched, the "True Drive Emulation (TDE)" setting in Machine Options always defaults to false. There seems to be no global setting for this, which forces users to set it manually for each and every new disk image they use. The True Drive Emulation is required for a lot of games/demos to work properly and VICE defaults to having it enabled.

### Steps to reproduce

1. Select "Start System With Blank Disk"
2. Input a completely new name, such as new00001
3. Go to machine options -- True Drive Emulation is set to Off.
4. Change it to "On"
5. Select "Start System With Blank Disk" again
6. Input a completely new name, such as new00002
7. Go to machine options -- True Drive Emulation is set to Off again.

The steps described above work for any new image you try to use with the emulator, including anything downloaded from the web.

### Expected behavior

One should be able to change the True Drive Emulation setting to default to true for all disk images.

**Comment by Rakashazi** [comment]
Thanks for the report. I'm going to add a setting to set the default mode under Options -> System in the next update.
