### ISSUE TITLE
Duplicate option 1 in Linx.emu

### ISSUE THREAD

**Issue by Fireadolfo** [Rakashazi/emu-ex-plus-alpha#1529]
### Describe the bug

There are two options 1 when there should be an option 2

### Steps to reproduce

add a option 2 button

### Expected behavior

option 1 and option 2 text

### Add screenshots

![Screenshot_20240113-215739_Lynxemu](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/101057683/6b719888-26c5-468c-9392-3816d428a5cf)

**Comment by Rakashazi** [comment]
Thanks for reporting, fixed in last commit
