### ISSUE TITLE
[Issue]: App close when setup controller

### ISSUE THREAD

**Issue by leoxxx** [Rakashazi/emu-ex-plus-alpha#1533]
### Describe the bug

As shown in the picture.
Build 2024.1.14 is error. Build 2023.12.8 is O.K.

### Steps to reproduce

Key/Gamepad Input Setup > Individual Device Settings, select any option below "Individual Device Settings"

### Expected behavior

Like build 2023.12.8.

### Add screenshots

https://github-production-user-asset-6210df.s3.amazonaws.com/5364709/296649093-602b0e48-2393-4ec2-abab-bd34dcc37724.gif

**Comment by Rakashazi** [comment]
Thanks for the report. Can you re-check on the current commit once the nightly build is ready?

**Comment by leoxxx** [comment]
Fixed.
