### ISSUE TITLE
[Issue]:  backbone android controller attempting to map crashes emulator.

### ISSUE THREAD

**Issue by AlexS2412** [Rakashazi/emu-ex-plus-alpha#1538]
### Describe the bug

in the intial 15.7.6 release in workflows this does not happen. in all releases after it does.

### Steps to reproduce

simoly try to map external gamepad in all releases past 15.7.6

### Expected behavior

the menu to open and not to crash the emulator.

**Comment by Rakashazi** [comment]
Thanks for the report. Can you re-check on the current commit once the nightly build is ready?
