### ISSUE TITLE
Undefined symbols for architecture arm64 and armv7 when compiling emulators on macOS 10.15.4 / Xcode 11.4 (11E146)

### ISSUE THREAD

**Issue by ck16** [Rakashazi/emu-ex-plus-alpha#154]
I'm trying to compile the emulators using macOS 10.15.4 and Xcode 11.4 (11E146) and receive the following errors when trying to compile any of the emulators:

Undefined symbols for architecture arm64:
  "EmuTiming::advanceFramesWithTime(std::__1::chrono::duration<double, std::__1::ratio<1l, 1l> >)", referenced from:
      DelegateFunc2<16ul, bool (Base::Screen::FrameParams)>::DelegateFunc2<EmuViewController::initViews(ViewAttachParams)::$_2>(EmuViewController::initViews(ViewAttachParams)::$_2 const&)::'lambda'(DelegateFunc2<16ul, bool (Base::Screen::FrameParams)>::Storage const&, Base::Screen::FrameParams)::__invoke(DelegateFunc2<16ul, bool (Base::Screen::FrameParams)>::Storage const&, Base::Screen::FrameParams) in lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [target/ios-release/bin/2600emu-arm64] Error 1
make: *** [ios-arm64] Error 2
make: *** Waiting for unfinished jobs....
Undefined symbols for architecture armv7:
  "EmuTiming::advanceFramesWithTime(std::__1::chrono::duration<double, std::__1::ratio<1ll, 1ll> >)", referenced from:
      DelegateFunc2<8ul, bool (Base::Screen::FrameParams)>::DelegateFunc2<EmuViewController::initViews(ViewAttachParams)::$_2>(EmuViewController::initViews(ViewAttachParams)::$_2 const&)::'lambda'(DelegateFunc2<8ul, bool (Base::Screen::FrameParams)>::Storage const&, Base::Screen::FrameParams)::__invoke(DelegateFunc2<8ul, bool (Base::Screen::FrameParams)>::Storage const&, Base::Screen::FrameParams) in lto.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [target/ios-release/bin/2600emu-armv7] Error 1
make: *** [ios-armv7] Error 2

The Imagine SDK and EmuFramework appears to compile successfully.

Any help would be appreciated!

Cheers,
ck16

**Comment by Rakashazi** [comment]
There was a missing TargetConditionals.h in the previous commit that caused symbol errors. Please re-test with the latest commit that also includes a few other iOS fixes.
