### ISSUE TITLE
[Issue]: Frame timing logic update 

### ISSUE THREAD

**Issue by master1274** [Rakashazi/emu-ex-plus-alpha#1543]
### Describe the bug

GBA.emu. I can't get a stable framerate in the game Tekken Advance. With any settings I see frame skipping. And the stuttering sound returned again. Until the last update everything was fine. Device Shield Tablet, Android 7.0, armeabi-v7a 

### Steps to reproduce

Starting the game

### Expected behavior

I'm waiting for the previous implementation. No dropped frames or audio stuttering.

**Comment by Rakashazi** [comment]
Is there any change with the new "Frame timing logic update part 2..." commit?

**Comment by master1274** [comment]
In the update  "Frame timing logic update part 2..." the problem is no longer observed. Thank you. Good luck in further development
