### ISSUE TITLE
crach on  Android 10 when Click the exit button

### ISSUE THREAD

**Issue by kenkieo** [Rakashazi/emu-ex-plus-alpha#155]
04-02 17:47:40.327 32766-32766/? A/DEBUG: Build fingerprint: 'HUAWEI/TAS-AN00/HWTAS:10/HUAWEITAS-AN00/10.0.0.205C00:user/release-keys'
04-02 17:47:40.327 32766-32766/? A/DEBUG: Revision: '0'
04-02 17:47:40.327 32766-32766/? A/DEBUG: ABI: 'arm'
04-02 17:47:40.328 32766-32766/? A/DEBUG: SYSVMTYPE: Maple
                                          APPVMTYPE: Art
04-02 17:47:40.329 32766-32766/? A/DEBUG: Timestamp: 2020-04-02 17:47:40+0800
04-02 17:47:40.329 32766-32766/? A/DEBUG: pid: 32704, tid: 32704, name: lusalpha.NesEmu  >>> com.explusalpha.NesEmu <<<
04-02 17:47:40.329 32766-32766/? A/DEBUG: uid: 10451
04-02 17:47:40.329 32766-32766/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
04-02 17:47:40.329 32766-32766/? A/DEBUG: Abort message: 'terminating'
04-02 17:47:40.329 32766-32766/? A/DEBUG:     r0  00000000  r1  00007fc0  r2  00000006  r3  ffead0d8
04-02 17:47:40.329 32766-32766/? A/DEBUG:     r4  ffead0ec  r5  ffead0d0  r6  00007fc0  r7  0000016b
04-02 17:47:40.329 32766-32766/? A/DEBUG:     r8  ffead0e8  r9  ffead0d8  r10 ffead108  r11 ffead0f8
04-02 17:47:40.329 32766-32766/? A/DEBUG:     ip  00007fc0  sp  ffead0a8  lr  f3698143  pc  f3698156
04-02 17:47:40.630 1437-2896/system_process E/WificondControl: Noise: 0, Snr: -80, Chload: 127
04-02 17:47:40.769 54-54/? W/migration/7: type=1400 audit(0.0:5969860): avc: granted { setsched } for pid=54 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=process
04-02 17:47:40.790 32766-32766/? A/DEBUG: backtrace:
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #00 pc 00054156  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: a4512dbc201a034f375ebdf7a21495c8)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #01 pc 0003606d  /system/lib/libc++.so (abort_message+88) (BuildId: fa0397c630f1e14558b6409ed72175a4)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #02 pc 0003615d  /system/lib/libc++.so (demangling_terminate_handler()+20) (BuildId: fa0397c630f1e14558b6409ed72175a4)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #03 pc 00044eef  /system/lib/libc++.so (std::__terminate(void (*)())+2) (BuildId: fa0397c630f1e14558b6409ed72175a4)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #04 pc 00044ea1  /system/lib/libc++.so (std::terminate()+40) (BuildId: fa0397c630f1e14558b6409ed72175a4)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #05 pc 00080527  /system/lib/libc++.so (std::__1::thread::~thread()+10) (BuildId: fa0397c630f1e14558b6409ed72175a4)
04-02 17:47:40.790 32766-32766/? A/DEBUG:       #06 pc 0009e4ff  /apex/com.android.runtime/lib/bionic/libc.so (__cxa_finalize+142) (BuildId: a4512dbc201a034f375ebdf7a21495c8)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #07 pc 000997d3  /apex/com.android.runtime/lib/bionic/libc.so (exit+10) (BuildId: a4512dbc201a034f375ebdf7a21495c8)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #08 pc 00138159  /data/app/com.explusalpha.NesEmu-EihxbJAdHN2N9pQkCu2muQ==/lib/arm/libmain.so
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #09 pc 00138139  /data/app/com.explusalpha.NesEmu-EihxbJAdHN2N9pQkCu2muQ==/lib/arm/libmain.so
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #10 pc 000a6287  /system/lib/libandroid_runtime.so (android::NativeCode::~NativeCode()+22) (BuildId: e4a71b99adebbcbf28a5fb48d916cafb)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #11 pc 000a5d27  /system/lib/libandroid_runtime.so (android::unloadNativeCode_native(_JNIEnv*, _jobject*, long long)+14) (BuildId: e4a71b99adebbcbf28a5fb48d916cafb)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #12 pc 002d4e73  /system/framework/arm/boot-framework.oat (art_jni_trampoline+82) (BuildId: 41c70514db8fb0cae092ad93dfa42e04d07b591d)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #13 pc 000e1bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #14 pc 0044cd4b  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+250) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #15 pc 000e9ff5  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #16 pc 0021b15f  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+274) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #17 pc 002172c7  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+802) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #18 pc 00443dff  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+358) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #19 pc 000dc914  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #20 pc 0021a04c  /system/framework/framework.jar (android.app.NativeActivity.onDestroy+64)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #21 pc 00442c35  /apex/com.android.runtime/lib/libart.so (MterpInvokeSuper+1888) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #22 pc 000dc894  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_super+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #23 pc 000ce71a  [anon:dalvik-classes.dex extracted in memory from /data/app/com.explusalpha.NesEmu-EihxbJAdHN2N9pQkCu2muQ==/base.apk] (com.imagine.BaseActivity.onDestroy+6)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #24 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #25 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.791 32766-32766/? A/DEBUG:       #26 pc 001b03f4  /system/framework/framework.jar (android.app.Activity.performDestroy+56)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #27 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #28 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #29 pc 00210d60  /system/framework/framework.jar (android.app.Instrumentation.callActivityOnDestroy)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #30 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #31 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #32 pc 0019d2b8  /system/framework/framework.jar (android.app.ActivityThread.performDestroyActivity+312)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #33 pc 00444f1d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtualRange+972) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #34 pc 000dcb14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual_range+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #35 pc 001a42e0  /system/framework/framework.jar (android.app.ActivityThread.handleDestroyActivity)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #36 pc 00444f1d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtualRange+972) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #37 pc 000dcb14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual_range+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #38 pc 002823f0  /system/framework/framework.jar (android.app.servertransaction.DestroyActivityItem.execute+32)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #39 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #40 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #41 pc 0028526c  /system/framework/framework.jar (android.app.servertransaction.TransactionExecutor.executeLifecycleState+64)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #42 pc 0044407b  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+994) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #43 pc 000dc914  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #44 pc 0028510a  /system/framework/framework.jar (android.app.servertransaction.TransactionExecutor.execute+170)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #45 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #46 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #47 pc 0019b580  /system/framework/framework.jar (android.app.ActivityThread$H.handleMessage+176)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #48 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #49 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #50 pc 0032043e  /system/framework/framework.jar (android.os.Handler.dispatchMessage+38)
04-02 17:47:40.792 32766-32766/? A/DEBUG:       #51 pc 00442159  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1184) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #52 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #53 pc 0034b60a  /system/framework/framework.jar (android.os.Looper.loop+466)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #54 pc 00444781  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+932) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #55 pc 000dc994  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #56 pc 001a776e  /system/framework/framework.jar (android.app.ActivityThread.main+410)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #57 pc 001f75b3  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6866433496563190725+194) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #58 pc 001fbc25  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+120) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #59 pc 00431c2d  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+832) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #60 pc 000e65a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #61 pc 000e1bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #62 pc 0044ce5f  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+246) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #63 pc 000ea009  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+180) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #64 pc 00388fc3  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #65 pc 0038a2a7  /apex/com.android.runtime/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+798) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #66 pc 0033465f  /apex/com.android.runtime/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #67 pc 000f07ef  /system/framework/arm/boot.oat (art_jni_trampoline+110) (BuildId: 463000c84938e64a55b8bc71e90fc83520ed41bb)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #68 pc 000e1bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #69 pc 0044cd4b  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+250) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #70 pc 000e9ff5  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+160) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.793 32766-32766/? A/DEBUG:       #71 pc 0021b15f  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+274) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #72 pc 002172c7  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+802) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #73 pc 00441f01  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+584) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #74 pc 000dc814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #75 pc 003a2246  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #76 pc 001f75b3  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6866433496563190725+194) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #77 pc 001fbc25  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+120) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #78 pc 00431c2d  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+832) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #79 pc 000e65a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #80 pc 0094f8eb  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2122) (BuildId: 41c70514db8fb0cae092ad93dfa42e04d07b591d)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #81 pc 000e1bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #82 pc 0044ce5f  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+246) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #83 pc 000ea009  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+180) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #84 pc 00388fc3  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.794 32766-32766/? A/DEBUG:       #85 pc 00388df5  /apex/com.android.runtime/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+288) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #86 pc 002c7a0f  /apex/com.android.runtime/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+458) (BuildId: 2f1da2282ed9ab3ce5c8d66b2440693c)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #87 pc 00098391  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: e4a71b99adebbcbf28a5fb48d916cafb)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #88 pc 0009af91  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+504) (BuildId: e4a71b99adebbcbf28a5fb48d916cafb)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #89 pc 000022f5  /system/bin/app_process32 (main+688) (BuildId: 9979c215af59ed821fac6ea4f956225d)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #90 pc 0004dffb  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: a4512dbc201a034f375ebdf7a21495c8)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #91 pc 0000202f  /system/bin/app_process32 (_start_main+38) (BuildId: 9979c215af59ed821fac6ea4f956225d)
04-02 17:47:40.795 32766-32766/? A/DEBUG:       #92 pc 00004456  <anonymous:f5211000>

**Comment by Rakashazi** [comment]
Hi, is this still an issue on the latest version?
