### ISSUE TITLE
[C64.emu] Autostart fails to work if used immediately after launching the emulator

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [Rakashazi/emu-ex-plus-alpha#1559]
### Describe the bug

"Open Content" does not autostart the selected .d64 image immediately after opening the emulator. It'll attach the image, reset the emulated computer, but it will fail to autoload "*", just a ready prompt with a blinking cursor will be displayed. Subsequent attempts will usually work.

### Steps to reproduce

1. Ensure that C64.emu (1.5.77) is closed by selecting Exit or removing it from background apps.
2. Open C64.emu
3. Select "Open Content".
4. Select a .d64 image to autostart. This .d64 must not be associated with an automatically loaded autosave slot, or Options -> System -> Autosave Launch Mode should be set to whatever doesn't automatically bypass the autoload ("No Save Slot" / "Select Slot").
5. Ready prompt will be displayed, no file "*" will be loaded.
6. Press three dots to exit to menu, go back to the main menu.
7. Repeat steps 3 and 4.
8. The first file will be loaded as expected.

### Expected behavior

Autostart should work reliably.

**Comment by Rakashazi** [comment]
Thanks for the report. I'm planning to port over VICE 3.8 soon and will work on a fix for this too.

**Comment by automatedbugreportingfacility** [comment]
Thanks!

Since you mentioned a planned upgrade to 3.8, one word of warning to prevent a potential regression. In the newest version, the authors made a (questionable) decision to boost the default values of contrast and saturation to an arbitrary value of 125%. Also, as of v3.8, even though those settings are grouped under Display->CRT settings, they take effect even if the CRT emulation render filter is disabled. As a result of this change, all external palettes look differently by default in v3.8.

In order to allow people to restore the neutral color settings and avoid being limited to contrast/saturation artificially boosted by an arbitrary margin, a global setting for contrast and saturation would be needed alongside the already existing global color palette setting.

Please see the following links for more info:
https://sourceforge.net/p/vice-emu/bugs/1970/
https://www.lemon64.com/forum/viewtopic.php?t=83728

**Comment by Rakashazi** [comment]
Awesome, thanks for letting me know about the color issue. I've added all the relevant settings in Options -> Video so you can tune them back to 100% and they're saved per core.

Let me know if you can reproduce the autostart issue on the new nightly when it's built. Thanks.

**Comment by automatedbugreportingfacility** [comment]
Thanks for all the improvements, I can't reproduce the autostart problem in 01c2056.

There's a regression with color settings, though -- if I change the values of saturation and contrast to 100%, then the default values of brightness, gamma, and tint are not preserved correctly after exiting the emulator and launching it again, they drop to 0% resulting in broken colors.

I'm going to close this ticket as the original issue is now fixed.

**Comment by Rakashazi** [comment]
Thanks, I just fixed the color settings issue and it'll be included in the next commit.
