### ISSUE TITLE
About new version's Fast Forward

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#156]
Current just my think.
1.5.43 changed fast forward working, but I feel it worse than older version.
1. It's not smooth now.
2. It seems a little slower than older version even I use same speed like 4x.
3. When speed up, high-pitch sound makes my ear painful.

So... if anyone hates it like me, could you make Fast Forward back to older version like?

**Comment by Rakashazi** [comment]
1.5.45 releasing soon will have an option to mute the audio during fast-forward. Future updates will being additional tweaks to performance but the new fast forward implementation is needed to properly take advantage of high refresh rate displays on recent devices.
