### ISSUE TITLE
[Feature request]: shortcut to close content

### ISSUE THREAD

**Issue by ciaskohansen** [Rakashazi/emu-ex-plus-alpha#1563]
### Describe the feature

Saturn.emu.

Right now there is an option to map a button to exit the emulator, would it be possible to add another button to close content without going through the menu? 
thanks

**Comment by Rakashazi** [comment]
Sure, I've added it in the newest commit

**Comment by TheBoxGame** [comment]
@Rakashazi add this fuction to md.emu plis 
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1562

**Comment by TheBoxGame** [comment]
@Rakashazi I miss this function in Sega Mega Drive
