### ISSUE TITLE
[Feature request]:GBA.Emu Bios

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1566]
### Describe the feature

@Rakashazi add support for loading bios into the emulator so that games run with bios
​

### Add screenshots

![hqdefault](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/109180532/089890e8-d13b-4941-8536-2a637867470a)
[gba_bios.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/14319015/gba_bios.zip)

**Comment by Rakashazi** [comment]
Added in last commit
