### ISSUE TITLE
[Issue]: Linux build fails config.cc:417:9: error: ‘else’ without a previous ‘if’

### ISSUE THREAD

**Issue by noabody** [Rakashazi/emu-ex-plus-alpha#1569]
### Describe the bug

I think the `#endif` at line 403 terminates `#ifdef CONFIG_GFX_OPENGL_ES`, at 325, prematurely (and its associated `if(extStr == "GL_OES_texture_npot")` at 326).  Line 404 `#ifndef CONFIG_GFX_OPENGL_ES` triggers in Linux because it isn't defined (but will not trigger on Android, so the problem never manifests).  It should be moved to line 428.

```diff
diff --git a/imagine/src/gfx/opengl/config.cc b/imagine/src/gfx/opengl/config.cc
index 82dbfb25e..8abb6ff54 100755
--- a/imagine/src/gfx/opengl/config.cc
+++ b/imagine/src/gfx/opengl/config.cc
@@ -400,7 +400,6 @@ void GLRenderer::checkExtensionString(std::string_view extStr)
        {
                setupVAOFuncs(true);
        }
-       #endif
        #ifndef CONFIG_GFX_OPENGL_ES
        /*else if(string_equal(extStr, "GL_EXT_texture_filter_anisotropic"))
        {
@@ -427,6 +426,7 @@ void GLRenderer::checkExtensionString(std::string_view extStr)
                setupMemoryBarrier();
        }
        #endif
+       #endif
 }
``` 

### Steps to reproduce

Every time I build.

### Expected behavior

It has the missing `if` statement

### Relevant log output

```shell
Compiling ./src/gfx/opengl/GLStateCache.cc
./src/gfx/opengl/config.cc: In member function ‘void IG::Gfx::GLRenderer::checkExtensionString(std::string_view)’:
./src/gfx/opengl/config.cc:417:9: error: ‘else’ without a previous ‘if’
  417 |         else if(extStr == "GL_ARB_texture_storage")
      |         ^~~~
```
```


### Add screenshots

_No response_

**Comment by noabody** [comment]
I think the `#endif` at line 403 terminates `#ifdef CONFIG_GFX_OPENGL_ES`, at 325, prematurely?  It should be moved to line 430?

**Comment by Rakashazi** [comment]
Thanks for the report. The issue is the initial `if` statement guarded by the CONFIG_GFX_OPENGL_DEBUG_CONTEXT macro. If this isn't defined then the next statements error out so I switched to testing a constexpr variable instead which has the same effect but now all the `else if` statements are always be valid.
