### ISSUE TITLE
[nes.emu] FCEUX PPU fixes

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#157]
nes.emu FCEUX GIT commit e48b2089182d4a2ac41a2a1d10e90b74089d9636 from 2020.01.30
have bug in PPU code that was fixed right now:
https://github.com/TASVideos/fceux/commit/fadb2008569f33ff6fe37e99706e9fb359388ac8
https://github.com/TASVideos/fceux/commit/16a965d15c45a938557700e0b763fef33a5f84d7

When sprite appears at first 8 left pixels, it must be hidden, but this doesn't happen.
"Prince of Persia" game highly affected by this bug.
You can just apply these commits to fix it.

![pop](https://user-images.githubusercontent.com/13199529/79696924-44d20880-8288-11ea-8d8d-0d0b27043db9.png)

**Comment by Rakashazi** [comment]
I updated to the latest FCEUX GIT in the last commit and this fix will be included in 1.5.44 coming sometime this month.
