### ISSUE TITLE
How Do I Contact You About Collaboration[Question]: 

### ISSUE THREAD

**Issue by DroidlyMobile** [Rakashazi/emu-ex-plus-alpha#1573]
### Describe your question

I am reaching out because I have paid for mostly every emulator you have developed on Google Play and recently found this repo for them and when I just installed the Saturn one you have really impressed me!  I am releasing a full Android Emulation Setup guide on my channel tomorrow DNA Mobile Gaming is my channel btw, and I'm going to direct everyone to most of your applications on Google Play for the systems like NES/SNES/GB/GBA/Saturn/MegaDrive/Genesis/Atari2600 one last emulator we need is GameGear perhaps mind you I know GameGear isn't huge for everyone!  Keep up the good work you've earned my support especially after seeing how well Sega Saturn runs, I really despise Retroarch UI and love my standalone apps!!!

BaByee!

**Comment by Rakashazi** [comment]
Hi and thanks for all the support. If you have any quests feel free to email me at info@explusalpha.com
