### ISSUE TITLE
[Snes9x Ex+] Starfox SuperFX Frame Rate Corruption

### ISSUE THREAD

**Issue by mrroniellelubay336** [Rakashazi/emu-ex-plus-alpha#158]
@Rakashazi When i played Starfox on Snes9x Ex+ 1.5.43 but the only problem issue the Frame Rate and SuperFX corrupted or glitched itself when i set SuperFX Clock Multiplier to 100 or lower. The 3d sprites is terrible and glitching. SuperFX needs to be improvement for the next update. 
My Device: Samsung J2 Prime (Arm7)

Gameplay
![Screenshot_20200419-182053](https://user-images.githubusercontent.com/63198056/79685588-70df9080-826c-11ea-9d62-a84df05bc141.png)

![Screenshot_20200419-130738](https://user-images.githubusercontent.com/63198056/79935420-7cf36a00-8487-11ea-8640-85a0ad12334d.png)

Title Screen
![Screenshot_20200419-125712](https://user-images.githubusercontent.com/63198056/79688132-ba38db80-827e-11ea-82a7-d6ebbffc4ba3.png)

**Comment by Rakashazi** [comment]
I fixed this in the last commit and it'll be included in the upcoming 1.5.44 release. The zbuffers weren't cleared on skipped frames leading to visual artifacts.

**Comment by mrroniellelubay336** [comment]
@Rakashazi  
1.5.44 Update Released?
