### ISSUE TITLE
[Issue]: Problem with Hide Status Bar option

### ISSUE THREAD

**Issue by MinecraftMario27** [Rakashazi/emu-ex-plus-alpha#1583]
### Describe the bug

@Rakashazi In Emu Apps (NES, Snes9x, ect.), when I set Hide Status Bar option to off and I exit the app, when I open again, it backs as default
**Watch this!**

https://github.com/Rakashazi/emu-ex-plus-alpha/assets/137607853/476eb064-30a1-4b5c-94a8-7ee90803fb11

### Steps to reproduce

.

### Expected behavior

.

### Add screenshots

.

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in the last commit
