### ISSUE TITLE
[C64.emu] Pausing emulation resets the autosave timer

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [Rakashazi/emu-ex-plus-alpha#1588]
### Describe the bug

This behavior may cause autosaving to be performed less frequently than expected. For example, if the timer is set to 10 minutes, and the game is interrupted by a phone call after 9 minutes, it'll take 19 minutes of emulation to autosave (assuming no need for another pause, for example to swap the disk image in the emulated drive).

### Steps to reproduce

1) Set Options -> System -> Autosave Timer to 10 minutes.
2) Open some content, wait a while.
3) Open System Actions and check the current state of the timer next to "Save Autosave State".
4) Return to content and immediately open System Actions again.
5) Check the current state of the timer next to "Save Autosave State".

### Expected behavior

The timer would reset only if it goes off or "Save Autosave State" is selected.

**Comment by Rakashazi** [comment]
Thanks for the report, there was an issue with the timer not accumulating elapsed time after pausing but I fixed it in the last commit.
