### ISSUE TITLE
Scanlines not appearing

### ISSUE THREAD

**Issue by Gillman69** [Rakashazi/emu-ex-plus-alpha#159]
On the new .emu versions (I use them all), scanlines and probably other effects do not appear when I load a game.  I have discovered that if I open options, then return to the game, the scanlines will be there.  This is happening on my nvidia Shield tablet.  I also get an occasional crash upon exiting the emus and a running game will not keep the screen on anymore (with no gamepad input).

**Comment by juamnitruh** [comment]
change the gpu copy mode to graphics buffer or standard

**Comment by Gillman69** [comment]
I tried this and it did not make a difference.  I set it to standard, the
other option is not supported on the Shield.

Corey Gilley

**Comment by Rakashazi** [comment]
Thanks for the report, looks like there was an issue with the overlay effect line count value set before the system's display mode was known. It's now fixed and will be included in the upcoming 1.5.44 update.
