### ISSUE TITLE
[MD.emu] Request: Add SG-1000, 32X and CD 32X Support

### ISSUE THREAD

**Issue by aleshiaclinton46** [Rakashazi/emu-ex-plus-alpha#160]
@Rakashazi Can someone please add for SG-1000, 32x and CD 32X Support for playing games for the Next Update?
Because i want to play Knuckles Chaotix for 32x, Congo Bongo for SG-1000 and NightTrap for CD 32x in MD.emu.

Keep it Up for Best Emulators! :)

**Comment by IdiotBlueMage** [comment]
I would normally say that MD.Emu should just be Genesis Plus GX straight instead.  That would presumably make things easy to update, and it would also carry with it Game Gear and better sound options, but the only thing on the list that it doesn't have is 32x compatibility.

32x is no small potatoes.  Picodrive's 32x ability also has some holes in it unfortunately.

**Comment by RonJay55** [comment]
> I would normally suggest that MD.Emu should just use Genesis Plus GX straight as the core instead. That would presumably make things easier to update and it would also carry with it Game Gear and better sound options, but the only thing on the list that it doesn't have is 32X compatibility.
> 
> 32X seems to be no small potatoes. Picodrive's 32X ability is unfortunately not perfect, and AFAIK only Kega Fusion is better (and it's closed source).

i rather to say Game Gear Support feature for the next update. ._.

**Comment by DVDVIDE** [comment]
Is There A KEGA Fusion On Android?

**Comment by DVDVIDE** [comment]
Is There A KEGA Fusion Emulator For Android / Chrome OS?

**Comment by IdiotBlueMage** [comment]
> Is There A KEGA Fusion Emulator For Android / Chrome OS?

Absolutely impossible.  There is no source code whatsoever.

**Comment by DVDVIDE** [comment]
It Will Be Updated To Genesis Plus GX On MD.emu To Add Support For SG-1000, Game Gear.

**Comment by SopTheSop27** [comment]
It's Supposed With Gearsystem 3.4.2 Core For Game Gear & SG-1000 Support On MD.emu. Update.

**Comment by SopTheSop27** [comment]
I Found MD/CD/MS/GG/SG-1000 Emulator Alternative Of KEGA Fusion Called Genesis Plus GX (1.7.4) And Gearsystem (3.4.2). It Works On Android.

**Comment by SteveCraft27** [comment]
On **MSX.emu** In Description Said **In Future Updated Will Be Added Support For SG-1000.** But SG-1000 Is Arealdy Added On blueMSX. But It's Cancelled On 1.5.56.

**Comment by Squidward22** [comment]
#416

**Comment by Squidward22** [comment]
Kega Fusion is closed source. Kega Fusion, MEKA, Gearsystem always uses SG-1000 TMS9918 VDP on SMS, GG, MD emulation.

**Comment by Squidward22** [comment]
#464
