### ISSUE TITLE
[Question]: SuperGrafx support only limited to commercial games?

### ISSUE THREAD

**Issue by Ryusennin** [Rakashazi/emu-ex-plus-alpha#1609]
### Describe your question

It doesn't seem possible to force pce.emu to run SGX homebrew productions.

For example, my own little tech demo of Strider doesn't work:
https://drive.google.com/file/d/1NEc9xio_6sbD2HqkLCI19GQmMVmZtQ9Z/view?usp=sharing

No problem on the real hardware, and with Mesen and Ootake in SGX mode.

**Comment by Rakashazi** [comment]
Thanks for the report. Looks there was a bug checking the file extension and the loader code was always falling back to the internal SGX mode database. I'll fix it in the next update so it activates SGX mode for anything ending in .sgx case-insensitive and in archives as well.

**Comment by Rakashazi** [comment]
Please test again on the newest nightly and let me know if it's loading into SGX mode properly.

**Comment by Ryusennin** [comment]
With the latest build, SGX mode is correctly forced for all ROMs with an .sgx extension.

Thank you for the fix!
