### ISSUE TITLE
[C64.emu] Opening the keyboard confuses the fast-forward indicator

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [Rakashazi/emu-ex-plus-alpha#1612]
### Describe the bug

If the keyboard is opened while the fast-forward mode is enabled, the state will be indicated incorrectly until the mode is disabled.

### Steps to reproduce

1) Press the fast-forward icon to enable the warp mode, the icon turns red.
2) Press the KB icon, the fast-forward icon turns gray.

### Expected behavior

The indicator should retain the state.

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in the last commit
