### ISSUE TITLE
[NES.emu] Built-in palette suggestion

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1615]
The second option **FirebrandX**, according to his [palette website](http://www.firebrandx.com/nespalettes.html), he ditched his many old palettes, so it’s better use **Digital Prime** instead of old **FirebrandX**.

**Comment by Yave-Yu** [comment]
Also could you add one more built-in palette option? Add this **Lightful** palette, it’s another NTSC NES palette but lightful than others, 
[Lightful.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/14900780/Lightful.zip)
nice to have it :p

**Comment by Rakashazi** [comment]
Thanks, I updated all the FBX palettes and added your lightful palette in the last commit.
