### ISSUE TITLE
[Issue]:Crash Aplication to Minimalize 

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1618]
### Describe the bug

crashing the application when starting it and after returning to it

### Steps to reproduce

when I minimize apps in split screen and then go back to it, it crashes

### Expected behavior

the application should not hang after opening it even though it has been minimized

**Comment by TheBoxGame** [comment]
Uploading Screenrecorder-2024-04-11-08-41-03-589.mp4…

**Comment by Rakashazi** [comment]
Thanks for the report. I should have a fix soon.
