### ISSUE TITLE
[Snes9x Ex +]Super Mario RPG lag

### ISSUE THREAD

**Issue by juamnitruh** [Rakashazi/emu-ex-plus-alpha#162]
Mario rpg lags too much. It's amost unplayable! and when i use the other version (based on snes9x 1.45) the sound effects are f*cked up.

**Comment by bladeoner** [comment]
@juamnitruh could you try my debug build (see attachment)
[Snes9xEXPlus-debug.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4667384/Snes9xEXPlus-debug.zip)
, I backported more changes from Snes9x.

If it works I can share my changes with @Rakashazi so it can be merged in the source.

Please let me know how it works for you.

Thanks in advance.
