### ISSUE TITLE
[NES.emu] Two options are wrongly mapped to FCEUX palette

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1622]
### Describe the bug

In 1.5.81, Smooth V2 and Magnum are not mapped to correct palette, but mapped to default FCEUX palette instead.

### Steps to reproduce

Options -> video -> default palette, choose Smooth V2 or Magnum.

### Expected behavior

Show Smooth V2 and Magnum as it should.

**Comment by Rakashazi** [comment]
Thanks for the report. There was a typo in the internal path names for those two palettes but I'll have a fix in the next commit.
