### ISSUE TITLE
[NES.emu] Another built-in palette suggestion

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#1629]
**Lightful.pal** updated, please update it into NES.emu, thanks.
Also introduces **Palightful.pal**, same saturated palette but prefer PAL NES, may be some PAL gamer love it?
[Lightfuls.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/15048315/Lightfuls.zip)

**Comment by Rakashazi** [comment]
Thanks for the update, where is the source for these palettes?

**Comment by Yave-Yu** [comment]
> where is the source for these palettes?

[Here](https://forums.nesdev.org/viewtopic.php?t=25127#top), see bottom post.
