### ISSUE TITLE
macos android compile error

### ISSUE THREAD

**Issue by kakimsun** [Rakashazi/emu-ex-plus-alpha#163]
I'm getting these compile errors:

JanedeiMac:imagine jane$ make -f android.mk
Compiling ./src/io/ArchiveIO.cc
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier 'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-armv7/obj/io/ArchiveIO.o] Error 1
Compiling ./src/io/ArchiveIO.cc
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier 'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-arm64/obj/io/ArchiveIO.o] Error 1
Compiling ./src/io/ArchiveIO.cc
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier 'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-x86/obj/io/ArchiveIO.o] Error 1
Compiling ./src/io/ArchiveIO.cc
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier 'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-x86_64/obj/io/ArchiveIO.o] Error 1
make: *** [all] Error 2

**Comment by Rakashazi** [comment]
Sounds like you didn't build & install libarchive and it's using the system one without my extra crc32 functions. To install the correct one go to the imagine/bundle/all directory and run:
`bash makeAll-android.sh install`

**Comment by kakimsun** [comment]
go to the imagine/bundle/all directory and run:
bash makeAll-android.sh install
but it's has error:


	/tmp/imagine-bundle/libogg/libogg-1.3.4/configure --prefix='${pcfiledir}/../..' --disable-shared --host=aarch64-linux-android
checking build system type... x86_64-apple-darwin19.4.0
checking host system type... aarch64-unknown-linux-android
checking how to print strings... printf
checking for aarch64-linux-android-gcc... /Users/kakimsun/Library/Android/sdk/ndk/16.1.4479499/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in `/tmp/imagine-bundle/libogg/build/android-arm64':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [/tmp/imagine-bundle/libogg/build/android-arm64/Makefile] Error 77
