### ISSUE TITLE
[Issue]: Trying to run content at 40fps (80, 1/2)

### ISSUE THREAD

**Issue by 382kB** [Rakashazi/emu-ex-plus-alpha#1639]
### Describe the bug

I'm trying to set frame rate to 40fps for performance reasons (and because I prefer it that way). 

I set the Custom Rate to 80fps and set the Target Frame Rate to 1/2 with the intention of reaching 40fps but strangely my game runs at 80fps (as if it were a fast-forward, internally)

The device I tested on is the Xiaomi Redmi 9 (refresh rate is 60Hz, ~59Hz)

### Steps to reproduce

1. set the frame rate target to `1/2`
2. set the frame rate to `80`
3. start the game

### Expected behavior

What was expected is that the content would be at 40fps and not at 80fps

### Add screenshots

![Screenshot_2024-05-01-16-21-59-129_com explusalpha Snes9xPlus](https://github.com/Rakashazi/emu-ex-plus-alpha/assets/168353325/c8c3c2df-a362-4d68-ba54-ebab25ea3467)

**Comment by 382kB** [comment]
https://github.com/Rakashazi/emu-ex-plus-alpha/assets/168353325/4a9d479d-35a4-42da-bce8-a66f29fc977c

**Comment by Rakashazi** [comment]
Hi, this is the expected behavior. Running at 80Hz will inherently speed up the emulation and setting the frame rate target to half will drop every other frame without affecting the speed.
