### ISSUE TITLE
bash makeAll-android.sh install ERROR

### ISSUE THREAD

**Issue by kakimsun** [Rakashazi/emu-ex-plus-alpha#164]
i am go to the imagine/bundle/all directory and run:
bash makeAll-android.sh install
but it's has error:

/tmp/imagine-bundle/libogg/libogg-1.3.4/configure --prefix='${pcfiledir}/../..' --disable-shared --host=aarch64-linux-android
checking build system type... x86_64-apple-darwin19.4.0
checking host system type... aarch64-unknown-linux-android
checking how to print strings... printf
checking for aarch64-linux-android-gcc... /Users/kakimsun/Library/Android/sdk/ndk/16.1.4479499/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in /tmp/imagine-bundle/libogg/build/android-arm64': configure: error: C compiler cannot create executables See config.log' for more details
make: *** [/tmp/imagine-bundle/libogg/build/android-arm64/Makefile] Error 77

**Comment by Rakashazi** [comment]
Your NDK version 16 looks too old so update it to 21 and try building again.

**Comment by kakimsun** [comment]
> Your NDK version 16 looks too old so update it to 21 and try building again.

i am update ndk to 21.1.6352462，android go to the imagine/bundle/all directory and run:
bash makeAll-android.sh install  finished：

1、
make: Nothing to be done for `install'.
running make on src/boost/android-arm64.mk
Installing boost to: /Users/kakimsun/imagine-sdk/android-arm64
cp -r /tmp/imagine-bundle/boost/boost/* /Users/kakimsun/imagine-sdk/android-arm64/include/boost/
make: Nothing to be done for `install'.

2、
i am go to imagine directory and run:
make -f android.mk

it's has error :
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier
      'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-armv7/obj/io/ArchiveIO.o] Error 1
make: *** [all] Error 2

**Comment by Rakashazi** [comment]
Use this command to enable verbose output when building and post the whole compile command:
`make -f android.mk V=1`

**Comment by kakimsun** [comment]
> Use this command to enable verbose output when building and post the whole compile command:
> `make -f android.mk V=1`

it's the same error :

/obj/io/ArchiveIO.o
./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier
      'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-armv7/obj/io/ArchiveIO.o] Error 1

**Comment by bladeoner** [comment]
@kakimsun please try the following:
- Remove Android Studio completely
- Be sure to install the following on your Linux distribution (I recommend Ubuntu or Linux Mint for easy use):
autoconf 2.69
automake 1.16.1
gettext 0.20.1
pkgconfig 0.29.2
- Install Android Studio 3.6.3, select NDK21 during installation (from the SDK Manager)
- Run the commands to build the environment
- Run the commands to compile

**Comment by kakimsun** [comment]
i am verry sorry,it's still has error:

./src/io/ArchiveIO.cc:61:9: error: use of undeclared identifier
      'archive_entry_crc32'
        return archive_entry_crc32(ptr);
               ^
1 error generated.
make[1]: *** [build/android-armv7/obj/io/ArchiveIO.o] Error 1
make: *** [all] Error 2

**Comment by bladeoner** [comment]
@kakimsun if you are following along, please install a clean Linux Mint machine on a physical machine or in a virtual machine (don't use the WSL builds of Linux in the Microsoft Store).

Follow the steps in attached files: 
[Files.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4739901/Files.zip)

**Comment by kakimsun** [comment]
> @kakimsun if you are following along, please install a clean Linux Mint machine on a physical machine or in a virtual machine (don't use the WSL builds of Linux in the Microsoft Store).
> 
> Follow the steps in attached files:
> [Files.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4739901/Files.zip)

Thanks !
 it's work in Linux Mint，but cant's in  mac os !
