### ISSUE TITLE
[Issue]: does someone have a copy of nes.emu 1.5.76?

### ISSUE THREAD

**Issue by SkeppyTheOne** [Rakashazi/emu-ex-plus-alpha#1664]
### Describe the bug

I Can't Install A New Version Bc Of A Bug, To Fix That I Need An APK Of 1.5.76, Pls

### Steps to reproduce

Install An Older Version, Uninstall It But Click 'Keep The Data'
Try To Install A Newer Version

### Expected behavior

The APK Installing Normaly

**Comment by master1274** [comment]
https://drive.google.com/file/d/1GuOoWSMYQ4YdutpQxsmwO4NUgLGaiMBp/view?usp=drivesdk

**Comment by SkeppyTheOne** [comment]
> https://drive.google.com/file/d/1GuOoWSMYQ4YdutpQxsmwO4NUgLGaiMBp/view?usp=drivesdk

Sorry But It Didn't Work :< Do You Happen To Have A 1.5.77 Copy? Pls?

**Comment by master1274** [comment]
https://drive.google.com/file/d/1H-VSIkaTcMzzbyN_lSa8WuuBEnZrtsMa/view?usp=drivesdk

**Comment by SkeppyTheOne** [comment]
> https://drive.google.com/file/d/1H-VSIkaTcMzzbyN_lSa8WuuBEnZrtsMa/view?usp=drivesdk

Sorry, It Didn't Work Out ಥ⁠_⁠ಥ I'll Try Using ADB To Fix My Problem, Thank You For Trying To Help Anyway ;)

**Comment by master1274** [comment]
Close it then. This has nothing to do with development.

**Comment by SkeppyTheOne** [comment]
> Close it then. This has nothing to do with development.

Okie
