### ISSUE TITLE
[Question]:nes.emu new mappers to run games

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#1668]
### Describe your question

Hello, will new mappers be added to nes.emu, at least these 5 mappers 313 295 374 281 353
to run super mario family mapper 313
J.Y Company 1996 Soccer 7-in-1 (JY-014B mapper 295
1995 Super HiK 4-in-1 (JY-022) mapper 374
J.Y Company 1996 Super HiK 4-in-1 (JY-052) mapper 281 
Mario Series 4-in-1 (JY-013) Mapper 313

**Comment by ErickN13** [comment]
Isso já está planejado!!!!

**Comment by TheBoxGame** [comment]
@ErickN13 e quando será adicionado

**Comment by ErickN13** [comment]
Não há uma estimativa de quando isso vai ser adicionado, mas, deve ser que daqui pra o Lançamento final isso já esteja sido adicionado, veja mais em #330

**Comment by TheBoxGame** [comment]
@ErickN13 why rakashazi not adding mappers 353 374 295 313 281
