### ISSUE TITLE
Snes9x changes

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#167]
Hi @Rakashazi I'm hoping you're doing fine in these strange times.

I backported all changes from the Snes9x source and added a speedhack for SMW 2 which has the perfect timing for the game.

See [Attachment](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4739873/Snes9x_Changes.zip)

**Comment by Rakashazi** [comment]
Doing fine, thanks for asking, hope everything's going ok for you as well. I added in the changes from Snes9x GIT as of 2020.06.07 in today's commit. Is there any reference that 8/3 is the correct SuperFX speed multiplier in SMW 2 vs 5/2?

**Comment by bladeoner** [comment]
Hi @Rakashazi I'm doing fine, thank you.

About Yoshi's Island timing settings I remember backporting some changes from Snes9x to Snes9x GX for the Wii last year. And Bearoso of the Snes9x team updated the SuperFX settings for this specific game:

Source: https://github.com/snes9xgit/snes9x/issues/522

The changes where made for Yoshi's Island which worked perfectly: https://github.com/snes9xgit/snes9x/commit/8eca5590e146bc74b096e23e79f58fc76f645d92#diff-b9cc597a581160e9781ec5d2c5b98aa4

But it broke other SuperFX games so Bearoso reverted the change:
https://github.com/snes9xgit/snes9x/commit/ffe72224bd4cc0daa3d8e0cbe661539ef765b013#diff-b9cc597a581160e9781ec5d2c5b98aa4

I remember that I asked if a hack could be implemented for Yoshi's Island but Bearoso said no: https://github.com/snes9xgit/snes9x/pull/543

**Comment by Rakashazi** [comment]
Ok, sounds reasonable to have a different base speed for Yoshi's Island. I've added it in the last commit.
