### ISSUE TITLE
Build environment files

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#168]
Hi @Rakashazi I'm using some files for: 
[Files.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4739909/Files.zip)

- Building the environment
- Compiling the emulators
- Made my simplified version of the documentation.

Could you look into the following files to see if they are any use of you or to make them public in Github? Thanks in advance.

You can close this afterwards.

**Comment by Rakashazi** [comment]
Thanks, I'll look through them when I get a chance and add/update the build docs.

**Comment by bladeoner** [comment]
@Rakashazi I will close this, this is not relevant anymore.
