### ISSUE TITLE
Added 8BitDo Controller Profiles

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#169]
Hi @Rakashazi I added three 8BitDo Controller Profiles, could you look into it when you have some time and see if it can be added to the master? Thanks!
- 8Bitdo SF30 Pro
- 8BitDo SN30 Pro+
- 8BitDo M30 gamepad (this one is only added to MD.emu)

[8bitdo_controller_profiles](https://github.com/Rakashazi/emu-ex-plus-alpha/files/4753972/8bitdo_controller_profiles.zip)

**Comment by Rakashazi** [comment]
Thanks, will include them in an update this month.

**Comment by Rakashazi** [comment]
Thanks again, I just added the patch in the last commit. The device name checks were using sub-string (strstr) tests so I changed them to test string equality instead since strstr("8Bitdo SF30 Pro") will match both "8Bitdo SF30 Pro" and "8BitDo SN30 Pro+", so that didn't seem right.
