### ISSUE TITLE
Make menu section headers bold/distinctive

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#17]
A small suggestion for the Android emulator GUI. Make section names in menus bold or otherwise distinctive (in addition to the grey underline), to distinguish them more from touchable setting items.

Also, when the title bar is not shown, you could have the first item in each menu being the text which would have been in the title bar.

**Comment by thededman** [comment]
Any chance there is a method at add BOLD to the menu items like @M-a-r-k is referring too.
I have tried but break the build out. :-(

**Comment by Rakashazi** [comment]
Initial bold text support now added
