### ISSUE TITLE
translation patches leading to black screen

### ISSUE THREAD

**Issue by thurmanator** [Rakashazi/emu-ex-plus-alpha#171]
when attempting to run fire emblem 4 with the most recent translation patch the emulator states "error loading game" at the bottom of the screen this is for snes9x ex+

**Comment by bladeoner** [comment]
@thurmanator could you test my debug build and see if that makes a difference?

https://github.com/Rakashazi/emu-ex-plus-alpha/issues/162

Direct download link: https://github.com/Rakashazi/emu-ex-plus-alpha/files/4667384/Snes9xEXPlus-debug.zip

Thanks in advance.
