### ISSUE TITLE
Custom button needed for c64  ( slap flight)

### ISSUE THREAD

**Issue by 3dcncuk** [Rakashazi/emu-ex-plus-alpha#1716]
### Describe the feature

I am using Odin 2 android . Playing the c64 version of slap flight.  You collect stars for powerups. To activate power ups you need to push spacebar. There seems to be  no way to add a custom key to a controller button.

**Comment by ErickN13** [comment]
But this is already possible.

**Comment by ErickN13** [comment]
Enviando c64.mp4 …

**Comment by 3dcncuk** [comment]
I cannot find a way to do it. I tried to use automatic device setup. All I want to do is allocate space to a Odin device button. Cntl to another button would be handy. Not sure what is enviando c64? It's not available on my device as a profile option

**Comment by ErickN13** [comment]
Watch the video

**Comment by 3dcncuk** [comment]
Thanks so much. Got it sorted
