### ISSUE TITLE
Add Snes9x code cleanup

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#176]
@Rakashazi I've backported some changes from Snes9x in regards of code cleanup:
https://github.com/snes9xgit/snes9x/commit/e322bbf109d4112d77f15f494deb85d6e7d64c02
https://github.com/snes9xgit/snes9x/commit/f04f1bbe4492eb95c9caa6e4a203b152922d812f
https://github.com/snes9xgit/snes9x/commit/e705e71a97ce2955ef126b5aeea5ac6172959658

Can you add it to the source please?

[snes9x-code_cleanup](https://github.com/Rakashazi/emu-ex-plus-alpha/files/5045252/snes9x-code_cleanup.zip)

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks, all the relevant code cleanup up to the Sept 23rd commit is now included.
