### ISSUE TITLE
[Snes9x Ex+] Super Mario World sound issue.

### ISSUE THREAD

**Issue by IdiotBlueMage** [Rakashazi/emu-ex-plus-alpha#177]
Either a sound channel or certain instruments always drop out in SMW's music.  This is easy to hear right at the start of th game, the outdoor world map's music has a noticable short point of silence.

This happens with both SMW and the version found with All-Stars.  I'm using a Galaxy Tab S6 here.

**Comment by Rakashazi** [comment]
I've made a recording (link below) of the start of the world map theme but am not noticing any dropped instruments. Can you share a recording from your Galaxy Tab to compare?

https://drive.google.com/file/d/1v-d_xlrqA08iHCQj6yaS6l3AX4MHXLhk/view

**Comment by IdiotBlueMage** [comment]
Unfortunately I've been trying, but it doesn't seem that the recording app wants to capture audio of EX+ after setting it to record media sound.

**Comment by bladeoner** [comment]
@IdiotBlueMage could you try my debug build and see if that makes a difference?

[Snes9xEXPlus-debug.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/5231808/Snes9xEXPlus-debug.zip)

**Comment by IdiotBlueMage** [comment]
I tried the debug version, and still no change.

**Comment by bladeoner** [comment]
Strange I'm using that build on an Android TV device and play SMW to test new builds, I don't have the sound issue.

Do you use the original Android OS on the tab S6?

**Comment by IdiotBlueMage** [comment]
Yep, normal latest android update for it.

Only thing I can say that's audio related in that regard is that Dolby Atmos is on. Also EX+ has 0 frame buffer, automatically changing buffer is off, and highest quality sound is on.

**Comment by IdiotBlueMage** [comment]
I just checked back, and a recent update fixed this.  Must've been related to AAudio.  In any rate, it's time to close this one.
