### ISSUE TITLE
[Snes9x EX+] fast forward toggle

### ISSUE THREAD

**Issue by zeraxx1** [Rakashazi/emu-ex-plus-alpha#179]
I'm playing with bluetooth controller, and the fast forward binded to my button only works on hold, there is no option to make it into toggle.

Somehow the fast forward on the screen is a toggle, so please add option to make binded key fast forward toggle.

**Comment by Rakashazi** [comment]
I've just added a key binding for this and it'll be included in the upcoming 1.5.47 release.
