### ISSUE TITLE
GBC.emu license compliance

### ISSUE THREAD

**Issue by bentley** [Rakashazi/emu-ex-plus-alpha#18]
Gambatte is released under the GPLv2 only:

    /***************************************************************************
     *   Copyright (C) 2008 by Sindre Aamås                                    *
     *   sinamas@users.sourceforge.net                                         *
     *                                                                         *
     *   This program is free software; you can redistribute it and/or modify  *
     *   it under the terms of the GNU General Public License version 2 as     *
     *   published by the Free Software Foundation.                            *
     *                                                                         *
     *   This program is distributed in the hope that it will be useful,       *
     *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
     *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
     *   GNU General Public License version 2 for more details.                *
     *                                                                         *
     *   You should have received a copy of the GNU General Public License     *
     *   version 2 along with this program; if not, write to the               *
     *   Free Software Foundation, Inc.,                                       *
     *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
     ***************************************************************************/

This license is not compatible with the GPLv3+ that Imagine is licensed under.

The simplest option would be to change the license of Imagine to GPLv2+ or a more permissive license (ISC, MIT…). There may be other options too.

**Comment by Rakashazi** [comment]
Thanks for your concern. I've spoken with the author of this code and received written permission to use it with a GPLv3 license.
