### ISSUE TITLE
Feature request: Option to deactivate the 3-dot-menu and FFWD icon on Android TV

### ISSUE THREAD

**Issue by rostbacke** [Rakashazi/emu-ex-plus-alpha#183]
The 3-dot-menu-icon in the upper right hand corner (while emulation runs) and the fast forward icon in the upper left hand corner are useful on smartphones. But I'd like to deactivate them on Android TV, since they distract from the immersion.

**Comment by Rakashazi** [comment]
The option to hide those icons is located under On-screen Input Setup -> Individual Button Toggles.
