### ISSUE TITLE
Super Metroid Speed Booster bug?

### ISSUE THREAD

**Issue by Shyri** [Rakashazi/emu-ex-plus-alpha#184]
Hi, I don't know if this is the right place to report this bug if it isn't please tell me where I can report it.

I've been playing Super Metroid on this emulator for a while. I've noticed that sometimes when using speed booster with a jump, like when you try fly from one side to other, it hits invisible walls... as if collision detection during that state was not working well. It was not a big deal but now it is blocking me from getting an important object in the game 

See this video to know what I'm talking about
https://youtu.be/-TzR8cXeQ6c?t=551

At the end of the run when he holds the speed booster and flies all the way up. In my case it doesn't... it immediately hits an invisible ceiling that prevents from getting up there. I've tried to stop at every position possible, it always hits the invisible ceiling so I can't go up.

I'm using Android TV, snes9x build from Jun 30 2020

**Comment by bladeoner** [comment]
@Shyri could you try my debug build see if it makes a difference?

I backported more code from Snes9x:
https://github.com/Rakashazi/emu-ex-plus-alpha/files/5231808/Snes9xEXPlus-debug.zip

**Comment by Rakashazi** [comment]
I gave it a try and the speed booster works fine for me. Can you show a screen recording of what happens on your copy? Here it is running on the current Snes9x EX+

https://drive.google.com/file/d/1q8VrSugdOZE0ZQmGTkVCnXchPG6ecbFT/view

**Comment by Shyri** [comment]
@Rakashazi Thanks for looking into it.

Please see this video:
https://drive.google.com/file/d/1lCVt1n_832n078a5PjMOdtJeLbXNJggz/view

Notice at the end of the video something even stranger happens. Not only Samus hit an invisible ceiling but... I don't know if those explosion sprites should appear

I'm using Snes9x EX+ 1.5.46 build from Jun 30 2020 on NVIDIA Shield TV

**Comment by odditude42** [comment]
apologies for the necrobump, but in case this comes in handy for other bug reports - this is intended game behavior, not an emulation bug.

Shinesparking drains energy and will force-abort if your energy is critical. the energy drain is visible in the example video you posted.

**Comment by Rakashazi** [comment]
@odditude42 Thanks for confirming, will close.
