### ISSUE TITLE
Your app for fdroid

### ISSUE THREAD

**Issue by theScrabi** [Rakashazi/emu-ex-plus-alpha#185]
Have you thought of releasing your app on fdroid.org? It's a repository of FLOSS applications for android, supported by the FSFE. It might give your app a little push.

**Comment by theScrabi** [comment]
Ah uff. Lots of binary blobs:
https://github.com/Rakashazi/emu-ex-plus-alpha

This will make it hard. Fdroid is a repository system like the one of debian. Meaning you push source code against a buildserver and compiled apps are distributed via mirrors. However fdroid is picki about .so .o or .jar as only source code is allowed. Pushing binarirs against it will result in a fail.

**Comment by alexanderadam** [comment]
Duplicate of #134
