### ISSUE TITLE
Prescale 2x issues

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#19]
The new Prescale 2x image effect fixes the main gripe I had with graphical output, that with linear filtering the display was too blurry. It can now look nice and sharp.

Unfortunately though, I encountered some issues testing on two Android devices. With a Huawei Y300 phone (Android 4.1.1, dual-core Cortex-A5 1GHz CPU, Adreno 203 GPU) Prescale 2x seriously reduces performance. With no image effect Snes9x-EX (not +) plays smoothly with frame skip 0. With Prescale 2x performance is much worse, I'd estimate 15-20fps.

With an Archos GamePad (Android 4.1.1, RK3066 dual-core Cortex-A9 1.6GHz CPU, Mali-400 MP GPU), Prescale 2x does not work; there's a message "GPU rejected shader (fragment compile error)" on startup. Maybe a GPU driver bug, since I hear both Qualcomm and Mali drivers suck?

Is there any possibility to optimise/adjust the shader code used for Prescale 2x? Or perhaps offer an alternative method using the CPU (NEON instructions on ARM)? I don't know anything about OpenGL, but would have thought prescaling would be simple to implement since it's just scaling a texture 2x with point filtering. I guess not, otherwise you'd have done it that way in the first place. :)

Also, would it be a good idea to automatically disable Prescale 2x when it has no benefit?
- When linear filtering is disabled
- When the image resolution is high enough relative to the device output. For example RPM Racing on Super NES uses 512x448 image. When outputting to an 800x480 screen (with 1x vertical scaling), pre-scaling probably has little or no benefit.

**Comment by Rakashazi** [comment]
I'm looking into the Mali issue but it may be a driver bug. Any change for either device if you turn off Fast CPU->GPU Copy?

**Comment by M-a-r-k** [comment]
With the GamePad, Prescale 2x does work if I disable Fast CPU->GPU copy.

With the Y300 phone I didn't notice any difference with Fast CPU->GPU Copy disabled. However I *did* notice a very significant difference with Use Highest Color Mode disabled. With Use Highest Color Mode disabled Snes9x-EX+ (note the +!) plays smoothly at frame skip 0 with linear filtering and no image effect. And Snes9x-EX plays smoothly at frame skip 0 with linear filtering and Prescale 2x.

To help users configure the settings, an option to show an FPS counter would be good; that way they should easily be able to see how much of a difference there is. Even if their device is fast enough to play smoothly, optimal settings should reduce CPU usage.

**Comment by Rakashazi** [comment]
For the Mali-400 MP, I tested it on a Galaxy S2 with the exact same GPU and it seems to be a bug in the shader compiler when using samplerExternalOES in a #define macro. I re-worked the shader code so the sampler type is explicitly prepended at runtime and all the shaders now work with Fast CPU->GPU Copy. This fix will be rolled into 1.5.27 when it's released.

As for the Huawei device, I tested Prescale 2x on an Xperia Play with Adreno 205 (the 203 is a supposedly faster version of it) and I didn't notice any performance drop when combining Prescale 2x with Highest Color Mode, but this is under Android 2.3. The Adreno 205 has really poor Android 4.0 drivers and I recall GPU performance taking a hit back when I was running it so your best bet is to avoid Highest Color Mode. Another possibility is it doesn't like the color conversion when rendering the Prescale 2x render target (16-bit color) to the frame buffer (24/32-bit when in Highest Color Mode). I'll add an option to set the color depth of render targets for video effects in the next update so give it a try then and check if it's better or worse.

**Comment by thededman** [comment]
the latest build of beta 1.5.27beta1 throw a gpu compiler error. Is this because this beta was for android only? if not this is effecting the iOS builds as well.
![image](https://cloud.githubusercontent.com/assets/5215424/7579138/0185f540-f82d-11e4-95d2-bb7356b783db.jpg)

**Comment by Rakashazi** [comment]
Closing out some old issues, this should be addressed from additional optimizations implemented since the last post.
