### ISSUE TITLE
Input setting don't get saved on Retroid Picjet 2 for neo.emu, md.emu, gba.emu, gbc.emu

### ISSUE THREAD

**Issue by rostbacke** [Rakashazi/emu-ex-plus-alpha#192]
Steps to reproduce:
Start emulator > key gamepad input setup > autodetect device > (selects generic gamepad) > set gamepad keys > (configure per preference) > back > back > exit > restart app and check gamepad settings

Result: settings haven't been saved, have to be reconfigured every time the app is started
Expected result: settings for generic gamepad are saved for this profile

Environment: Retroid Pocket 2, Android 6.0

**Comment by Rakashazi** [comment]
Is this specifically key configurations or is it any option (video, audio, etc.) that doesn't get saved?

**Comment by rostbacke** [comment]
Just looked it up. Any option. It also doesn't save the last rom directory. Snes9x ex works somehow...

**Comment by Rakashazi** [comment]
In your Android settings app do you have System -> Developer options -> Background process limit set to no background processes? If so, please test again with it set to 1 process or standard limit.

**Comment by rostbacke** [comment]
Thank you! This solved the problem. It saved the settings with standard limit and kept them after disabling background processes again. Do the emulators need those background processes anywhere else, so I should keep them enabled?

**Comment by Rakashazi** [comment]
No problem, the app's shutdown routine writes the config and any save data but should work with no background processes enabled. It looks like a bug in the Retroid's OS kills the app too early when it enters the paused/stopped state, preventing it from writing the files. To be safe I'd set it to at least 1 background process to make sure the app shuts down cleanly.
