### ISSUE TITLE
Added CI/CD Github Workflow

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#194]
@Rakashazi as mentioned before I'm busy building the CI/CD build which spins up a machine compiles the code and then removes the machine with a Github Workflow.

I made some progress but I was running in an error, it seems that there was something wrong with the IMAGINE_PATH env, I think I fixed it by adding this to the script:
echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV

I will keep you posted.

**Comment by bladeoner** [comment]
@Rakashazi I want to let you know that the CI/CD build in the Github Workflow has been finished and working.
Attached is the diff file: 
[Add_Github_Workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/5753866/Add_Github_Workflow.zip)

The diff contains:
- A Github Workflow file (continuous-integration-workflow.yml) which builds the environment and performs all steps. When you add the diff a build will automatically start under Actions on your Github page:
https://github.com/Rakashazi/emu-ex-plus-alpha/actions
- A README.md file which can be used to show the build status on your main page, this will be available after the first build. You can also add or change information as desired. You can see an example README.md under my 'workflow' branch it is visible under the code. 
https://github.com/bladeoner/emu-ex-plus-alpha/tree/workflow
- A build.gradle file which copies over the existing one to change the build from a Release to a Debug build. I don't sign the builds on my environment and didn't know how to perform a Debug build.

On the following page you can see a succesful build, where you can click on it and see all the steps and how long it takes per step:
https://github.com/bladeoner/emu-ex-plus-alpha/actions

It is also possible to upload the emulator artifacts, I didn't add that to this Github Workflow.

**Comment by bladeoner** [comment]
@Rakashazi thank you for your hard work on this project and enjoy New Year's Eve!

**Comment by Rakashazi** [comment]
@bladeoner Thanks for your work as well with getting the CI/CD pipeline running. I'll add it to the repo soon and hope you have a Happy New Year!

**Comment by bladeoner** [comment]
Thank you!
