### ISSUE TITLE
Added adjusted CI/CD Github Workflow file

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#198]
@Rakashazi I saw you added the CI/CD Github Workflow files, thanks.

I attached a diff where creating the EX-Emulators folder is removed, it is not used in your source but I use it for my own environment: 
[cleanup_github_workflow_file.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/5765684/cleanup_github_workflow_file.zip)

**Comment by Rakashazi** [comment]
thanks, added
