### ISSUE TITLE
Add Simultaneos D-pad and Analog Move

### ISSUE THREAD

**Issue by Valkyrie442** [Rakashazi/emu-ex-plus-alpha#200]
Hi there.
I have two products of your own...the Snes Emulator (Snes9x Exj and and Md. Emu)

In the Md. Emu I can move and select things with the d-pad and analog stick...but in the Snes emu I only can choose one or another, could you add the 2 options to move in the game simultaneously like as on the Genesis emu?
Obs. I use a Ípega Pg9099 gamepad and I play on a Xiaomi Redmi Note 8.

**Comment by Rakashazi** [comment]
Hi, do you mean the options to use the joystick axes as a d-pad? Can you show me some screenshots of the device settings menu to see how it's being detected differently in both apps?
