### ISSUE TITLE
Added Snes9x changes

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#202]
@Rakashazi could you please add the following backported changes from Snes9x, it will save me a lot of time not to have to add it everytime.
[snes9x_changes.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6008358/snes9x_changes.zip)

I backported all changes until the following commit, alligned them with the emulator and I'm using this for quite some time now:
https://github.com/snes9xgit/snes9x/commit/8a5d29c4a9dea22d036f63450cdfa8442fc8fce4

The changes are mostly refactor changes and code cleanup, it also fixes issues for some games and add compatibility to some game hacks.
I'm backporting changes from Snes9x to more ports.

Regarding the changes in fxemu, I've tested it thoroughly it doesn't make a difference, the Snes9x team just refactored it and they did some code cleanup, I only had to allign it with the emulator.

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks, I added the relevant changes but a large amount of items in the diff were modifications I made myself including:

* Reducing global variable access in certain code hot-spots
* Pre-calculating the FX1/FX2 speeds to skip the multiplication in every call of S9xSuperFXExec()
* Adding Settings.IdentifyAsPAL to run PAL games at NTSC speed but reporting the console as PAL to skip region checks

So those parts will stay as-is and you shouldn't submit any diffs against the those files unless something changes with them in the main Snes9x repo in a newer commit.

**Comment by bladeoner** [comment]
@Rakashazi thank you for your explanation and adding the code.
