### ISSUE TITLE
Added additional Artifact to Github Workflow with all emulators

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#203]
@Rakashazi I made an additional change to add all the emulators in one file called 'EX-Emulators'. This gives the option to download the emulators separate or in one bundle: 
[update_github_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6016816/update_github_workflow.zip)

**Comment by bladeoner** [comment]
The build completed successfully.

**Comment by Rakashazi** [comment]
Thanks for the update, now added
