### ISSUE TITLE
Nightly builds doesn't save settings

### ISSUE THREAD

**Issue by ZacharyFoxx** [Rakashazi/emu-ex-plus-alpha#206]
Hi,

First, thanks for the emulators.

OUYA, the ugly little cube, is still alive and maintained by a small community, but his versions of ex-emulators are old. The Nightly builds here are still compatible with OUYA and I tried them, version 1.5.51, and they work perfectly, but with only two bad behaviors: the options don't save and the emulators don't keep the list of recent games.

Well, I would like to know if there are any limitations with the Nightly builds.

**Comment by Rakashazi** [comment]
There's no limitation on the nightly builds, but I've gotten reports that on some devices setting the Background Process Limit setting under Developer Options to zero will prevent the app from shutting down properly and options won't be saved. Please confirm that isn't set on your OUYA.
