### ISSUE TITLE
Reduce input lag in Snes9x EX by porting patch from libretro

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#207]
The "snes9x2010" libretro core has a patch applied which reduces input lag by one frame, see https://github.com/libretro/snes9x2010/issues/74

Could that be ported to Snes9x EX?

**Comment by Rakashazi** [comment]
Thanks, this patch seems to be for an old version of Snes9x. In the main loop for current version I'm using (1.60) I can confirm it breaks out of execution as soon as the frame is ready so any input read after that point is applied to the next frame.
