### ISSUE TITLE
Windowed mode and fullscreen on samsung dex issues

### ISSUE THREAD

**Issue by arukamak** [Rakashazi/emu-ex-plus-alpha#209]
I'm using the app on my Note 10+ using a Dex Pad which opens the samsung dex system. When opening the app it doesnt have a border or the typical "minimize", "maximize" and "Close" buttons on the top right corner, but those functions still work in the same position as if they were there. thats a problem because if I click on the joystick button to return to the game, it closes the app.

Once again, this happen only using the app on Dex, which is a desktop like system, so it looks and fucntion similar to a windows system, but its still android. I'm attaching some images of the app to illustrate.

I understand this is not a >>bug<< per se, but I have no idea if there is a way to change this setting.

![Screenshot_20210424-203443_Snes9x EX+](https://user-images.githubusercontent.com/83144646/115975613-90269300-a53c-11eb-959b-98dea481fbf1.png)
![Screenshot_20210424-203409_Snes9x EX+](https://user-images.githubusercontent.com/83144646/115975618-9ae12800-a53c-11eb-91aa-cfd70ca0934a.png)

**Comment by Rakashazi** [comment]
Thanks for the report. It looks like the app is clearing the full contents of the window including the border drawn by the system when it updates the screen. I need to do some more research into freeform window mode and see if there's a way to prevent this from happening.

**Comment by arukamak** [comment]
![Screenshot_20210502-153917_Chrome](https://user-images.githubusercontent.com/83144646/116823756-acd65280-ab5c-11eb-9ef9-148bdf7212e5.png)
To add more details to this issue, its not limited to the phone model I'm using, as this happened back when I had a Galaxy S9 too. 

And the attached image shows how the normal window border is on samsung dex. in the top left corner there is a "back" button that if you click it will function as the back button on the bottom of the phone. if you are in the index or main page of an app and click on that arrow it will close the app, as it has nowhere else to return to. So the issue here with is that since the borders are not being shown, if I click in the region of that return arrow it will close the app as well.
