### ISSUE TITLE
More prescale modes (x3, x4, x5)

### ISSUE THREAD

**Issue by BlueMax** [Rakashazi/emu-ex-plus-alpha#21]
Ideal prescale resolution should be as close as possible to output resolution. For eg. typical SNES resolution (256x239 PAL) on FHD (1920x1080) already needs a 4x prescale (239*4=956) to get optimal Pixel weighting. There are already emulators that demonstrate and prove that (eg. some MAME derivates).
Thus, it would be great if you could add some more prescaler modes (3x, 4x, 5x).

**Comment by Rakashazi** [comment]
Rather than adding more fixed prescale modes, I can look into adding an "auto" prescale that will determine the best value based on the game & device resolution.

**Comment by BlueMax** [comment]
More options are never wrong but the manual modes shouldn't be removed as the optimal value is highly subjective (speed/quality tradeoff). It has a huge performance impact depending on the hardware and should remain under control for best results imho.
