### ISSUE TITLE
4 players on SNEX9x EX+ not working

### ISSUE THREAD

**Issue by mdiabolo** [Rakashazi/emu-ex-plus-alpha#210]
Hi,

Thank you for the app. I used to play on Recalbox 4 player at the same time at Super Bomberman. Unfortunately, with the same ROM and the same 4 USB gamepads (that are detected and configured in the app) I only have 2 players available. Am I missing an option somewhere or is it not supported ? 

Best regards,

**Comment by Rakashazi** [comment]
To enable the additional controllers, set System Actions -> Console Options -> 5-Player Adapter while the game is running. Does that solve the issue?

**Comment by mdiabolo** [comment]
Yes that solves it. Thanks a lot !

**Comment by Rakashazi** [comment]
Great, thanks for letting me know :)
