### ISSUE TITLE
NEO.emu Questions/Issues

### ISSUE THREAD

**Issue by pirsir76** [Rakashazi/emu-ex-plus-alpha#212]
I have 3 questions/issues and I made some suggestions below. Please read carefully as I have spent a lot of time and effort compiling this information.

1. When will all the games for the NEOGEO become playable/available? e.g. King of Fighters 2000-2003
There are games on the official compatibility list which are unplayable/buggy I've found:
Bang Bead: severe missing graphics; display bars missing at top of screen.
Ganryu: severe missing graphics; health bars in-game missing. (Bang Bead and Ganryu are made by the save developer; Visco, which might indicate the problem.)
Art of Fighting 2: (I have yet to 100% confirm this one.) When playing against John Crawley and he does his Mega Smasher it freezes the game. (Does seem only the computer controlled player can do this as I've tested in 2 player mode and it's doing the move without freezing the game. 

2. I am using a fightstick plugged into my NVIDIA Shield Pro (2019 model) I've noticed that I need to select my input device (in this case my fightstick) every time I start up NEO.emu. Is there a way NEO.emu can automatically load my preferred input device when I open NEO.emu?
It is detecting the device but not the button config.
For further information my controller is: Victrix Pro FS

3. I have noticed when using UniBios 4.0 when games are (fast) loading with .gno cache files, the load screen for UniBios becomes blurred on some of the larger ROMs such as Garou: Mark of the Wolves. Also, at the start of games there's a brief stutter when using cache.
I tried downgrading to UniBios 2.3 and the problem persists.

Help would be very appreciated as I really like the NEO.emu program.

SUGGESTIONS:
- NEOGEO CD support
- Ability to rename and reorganize games on the list
- Ability to enable/disable NEOGEO memory card in options (and still keep the unibios settings.)
- Option to switch off unibios and NEOGEO splash screens at start up.
- Ability to add game cover artwork. (I haven't had much luck in any of the front-ends working, yet.)
- I have noticed some the advice given here is inaccurate: http://www.explusalpha.com/home/neo-emu
"Make/Use Cache Files: Create and use .gno cache files" I have found a better way;
Do make a cache file (.gno) but after you have done that for all games go to: Options/System/Turn off "Make/Use Cache Files".
Doing that will make most games load pretty fast, but not as fast as turning on "Make/Use Cache Files."
Now, you get to avoid the corrupt graphics unibios load screen and also the intermittent freezing/stuttering at the start of games when they cache load.
- Rename bbbusters.zip to b2b.zip as bbbusters.zip is unrecognisable to most/all frontends as it it not the official/well known name of the zip file. You cannot even download bbbusters.zip as there is no such name, at least not what I've found.

RANDOM NOTE(S):
- I got a game to work that was not on the games list found here: http://www.explusalpha.com/home/neo-emu
It was: ZinTrick - zintrckb.zip (It's a hack of a NEOGEO CD game.)
- Samurai Showdown 5 & Samurai Showdown 5 Special are not "lockup" as the list says but have sound issues.
- I had to change the name of the ROM "Bang Bang Busters" from b2b.zip to bbbuster.zip to get it working in NEO.emu and I'm pretty sure the official name of the zipped ROM is b2b.zip.
- The ROM "Puzzle De Pon! R!" was hard to get working because someone had included BIOS files in the .zip file. I had to unzip it and remove the files to get it to work. Keep all the files starting with 202, delete the other files and re-compress the file.
- On the official games list found here: http://www.explusalpha.com/home/neo-emu It's missing Sengoku (sengoku.zip)

**Comment by IdiotBlueMage** [comment]
I think the answer to #1 is in GnGeo's repro not being updated since 2015.  These days most turn to arcade emulators to run NeoGeo properly and without problems, which left single NeoGeo emus in the lurch.  That's one reason why the required romsets are so old.

A switch in core to Final Burn Neo's NeoGeo and NeoCD drivers would fix almost every single problem here, but you can't charge for it like Snes9x.

**Comment by pirsir76** [comment]
> These days most turn to arcade emulators to run NeoGeo properly and without problems

NEO.emu has higher resolution than those other emulators.
