### ISSUE TITLE
any chance for paddle controllers for atari2600?

### ISSUE THREAD

**Issue by jinchoung** [Rakashazi/emu-ex-plus-alpha#213]
not really an "issue" but this seems to be the only place to add a feature request.

the dpad is ok with paddle games but just a horizontal slider at the bottom that just stops at the left and right would really make a big difference in enjoying games like kaboom or warlords. and stella itself has the ability to detect analog/paddle controls so it would be nice if your app switched to those controls automatically (though i suppose some would like the option to override).

thanks! otherwise, i'm really enjoying playing the 2600 library on an android.

p.s. any chance of getting theming for the controllers... i actually don't care that much about the aesthetics but right now, the dpad and buttons are just too DARK for me and it gets lost when i play.

**Comment by Rakashazi** [comment]
Thanks for the request, paddle controls are in the works and I'm planning to update various bits of the on-screen control code soon. There's no theming just yet but I'll look into adding options for different blending modes to make the controls appear brighter.

**Comment by Rakashazi** [comment]
An update, I added analog paddle support in a recent commit and it will be included in the upcoming 1.5.55 release.

**Comment by jinchoung** [comment]
woo hoo! thanks much!

jin
