### ISSUE TITLE
[Feature Request] Quick Save and Quick Load

### ISSUE THREAD

**Issue by Electrizzity** [Rakashazi/emu-ex-plus-alpha#217]
Hi Rakaahazi, your emulators are great!
Though we would like to request have a quick save and quick load to all emulators. 
Thanks in advance!

**Comment by Rakashazi** [comment]
Hi and thanks the for the request. Do you mean a quick save/load button for use with the on-screen controls?

**Comment by Electrizzity** [comment]
Hi Rakashazi, thanks for looking and checking on my request. Yes, a quick save/load button with the on-screen controls
