### ISSUE TITLE
Interlaced switching issue on Snes9x-EX 1.5.52 Android

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#219]
It looks like something broke relating to interlaced/non-interlaced switching with Snes9x-EX+ 1.5.52 on Android. No issue with 1.5.51.

Run 240p Test Suite and select "Alternate 240p/480i". With previous versions you can tap A repeatedly and see timestamps on each mode switch.

With 1.5.52 the emulated program seems to hang the first time you press A. You can open the emulator GUI and reset the console once that happens.

**Comment by M-a-r-k** [comment]
The problem happens with Snes9x-EX+ 1.5.52 but not with Snes9x-EX 1.5.52.

**Comment by Rakashazi** [comment]
Thanks, Snes9x calls a different update function for interlaced frames and that was confusing the framework after some recent changes. It's fixed in the last commit.
