### ISSUE TITLE
imagine engine debug

### ISSUE THREAD

**Issue by thededman** [Rakashazi/emu-ex-plus-alpha#22]
The last release with iOS seems to be hitting breakpoints in the execution:  
I have cleaned out imagine-sdk and recompiled with same issues. This may be nothing, but I figure I'd share. I have reverted back to https://github.com/Rakashazi/emu-ex-plus-alpha/commit/8f75d911e7a7b56ed749a9998d8faabe626dfd0f?diff=unified and all works fine.
![debug-issues](https://cloud.githubusercontent.com/assets/5215424/6312094/3b0c134c-b93c-11e4-9a72-d6113fe5ec4d.jpg)

-----------------
0x1002d5044:  b      0x1002d4f14               ; ___lldb_unnamed_function3155$$s9xp + 488
0x1002d5048:  add    x8, x26, #4
0x1002d504c:  movz   w24, #6407
0x1002d5050:  b      0x1002d4f14               ; ___lldb_unnamed_function3155$$s9xp + 488
0x1002d5054:  movz   w10, #32992
0x1002d5058:  cmp    w9, w10
0x1002d505c:  b.eq   0x1002d4f10               ; ___lldb_unnamed_function3155$$s9xp + 484
0x1002d5060:  movz   w10, #32993
0x1002d5064:  cmp    w9, w10
0x1002d5068:  mov    x24, x9
0x1002d506c:  b      0x1002d4f14               ; ___lldb_unnamed_function3155$$s9xp + 488
0x1002d5070:  adr    x8, #159548
0x1002d5074:  nop    
0x1002d5078:  b      0x1002d4e80               ; ___lldb_unnamed_function3155$$s9xp + 340
0x1002d507c:  adr    x8, #159532
0x1002d5080:  nop    
0x1002d5084:  b      0x1002d4e80               ; ___lldb_unnamed_function3155$$s9xp + 340
0x1002d5088:  movz   w10, #32836
0x1002d508c:  cmp    w9, w10
0x1002d5090:  b.gt   0x1002d50a4               ; ___lldb_unnamed_function3155$$s9xp + 888
0x1002d5094:  movz   w10, #32832
0x1002d5098:  cmp    w9, w10
0x1002d509c:  mov    x24, x9
0x1002d50a0:  b      0x1002d4f14               ; ___lldb_unnamed_function3155$$s9xp + 488
0x1002d50a4:  movz   w10, #32848
0x1002d50a8:  cmp    w9, w10
0x1002d50ac:  b.gt   0x1002d50c0               ; ___lldb_unnamed_function3155$$s9xp + 916
0x1002d50b0:  movz   w10, #32837
0x1002d50b4:  cmp    w9, w10
0x1002d50b8:  mov    x24, x9
0x1002d50bc:  b      0x1002d4f14               ; ___lldb_unnamed_function3155$$s9xp + 488
0x1002d50c0:  movn   w10, #32848
0x1002d50c4:  add    w10, w9, w10
0x1002d50c8:  cmp    w10, #7
0x1002d50cc:  b.hi   0x1002d4f10               ; ___lldb_unnamed_function3155$$s9xp + 484
0x1002d50d0:  movz   w24, #32856
0x1002d50d4:  adr    x11, #256                 ; ___lldb_unnamed_function3155$$s9xp + 1192
0x1002d50d8:  nop    
0x1002d50dc:  ldrsw  x10, [x11, x10, lsl #2]
0x1002d50e0:  add    x10, x10, x11
0x1002d50e4:  br     x10
0x1002d50e8:  mov    x21, x20
0x1002d50ec:  stur   w22, [fp, #-84]
0x1002d50f0:  adrp   x19, 573
0x1002d50f4:  ldr    w8, [x19, #3192]
0x1002d50f8:  cmp    w22, w8
0x1002d50fc:  b.ne   0x1002d5104               ; ___lldb_unnamed_function3155$$s9xp + 984
0x1002d5100:  str    wzr, [x19, #3192]
0x1002d5104:  sub    x8, fp, #84
0x1002d5108:  orr    w0, wzr, #0x1
0x1002d510c:  mov    x1, x8
0x1002d5110:  bl     0x1002f55ac               ; symbol stub for: glDeleteTextures
0x1002d5114:  sub    x8, fp, #84
0x1002d5118:  orr    w0, wzr, #0x1
0x1002d511c:  mov    x1, x8
0x1002d5120:  bl     0x1002f563c               ; symbol stub for: glGenTextures
0x1002d5124:  ldur   w20, [fp, #-84]
0x1002d5128:  str    w20, [x21, #12]
0x1002d512c:  ldr    w8, [x19, #3192]
0x1002d5130:  cmp    w8, w20
0x1002d5134:  b.eq   0x1002d5148               ; ___lldb_unnamed_function3155$$s9xp + 1052
0x1002d5138:  movz   w0, #3553
0x1002d513c:  mov    x1, x20
0x1002d5140:  bl     0x1002f551c               ; symbol stub for: glBindTexture
0x1002d5144:  str    w20, [x19, #3192]
0x1002d5148:  brk    #1
0x1002d514c:  .long  0xfffffce0                ; unknown opcode
0x1002d5150:  .long  0xfffffcd4                ; unknown opcode
0x1002d5154:  .long  0xfffffcdc                ; unknown opcode
0x1002d5158:  .long  0xfffffcdc                ; unknown opcode
0x1002d515c:  .long  0xfffffce0                ; unknown opcode
0x1002d5160:  .long  0xfffffcd4                ; unknown opcode
0x1002d5164:  .long  0xfffffcdc                ; unknown opcode
0x1002d5168:  .long  0xfffffcdc                ; unknown opcode
0x1002d516c:  .long  0xfffffd10                ; unknown opcode
0x1002d5170:  .long  0xfffffcfc                ; unknown opcode
0x1002d5174:  .long  0xfffffcd4                ; unknown opcode
0x1002d5178:  .long  0xfffffcdc                ; unknown opcode
0x1002d517c:  .long  0xfffffcdc                ; unknown opcode
0x1002d5180:  .long  0xfffffcdc                ; unknown opcode
0x1002d5184:  .long  0xfffffd08                ; unknown opcode

**Comment by Rakashazi** [comment]
The function pointer for glTexStorage2D wasn't being set in the iOS version, fix included in latest commit.
