### ISSUE TITLE
PKG_PROG_PKG_CONFIG: command not found

### ISSUE THREAD

**Issue by kenkieo** [Rakashazi/emu-ex-plus-alpha#221]
i build imagine by command :

export HOME=/home/work/emu-ex-plus-alpha
export IMAGINE_PATH=$HOME/imagine
export IMAGINE_SDK_PATH=$HOME/imagine-sdk
export EMU_FRAMEWORK=$HOME/EmuFramework
export EMU_2600=$HOME/2600.emu
cd $IMAGINE_PATH
make -f $IMAGINE_PATH/android-java.mk install

cd $IMAGINE_PATH/bundle/all
bash makeAll-android.sh

then failed show message(ubuntu-20.04)：

/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/configure: line 14769: PKG_PROG_PKG_CONFIG: command not found
/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/configure: line 14784: syntax error near unexpected token `FLAC_CFLAGS,'
/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/configure: line 14784: `_PKG_CONFIG(FLAC_CFLAGS, cflags, flac >= 1.3.1)'

has pkg-config and version is 1.6.3:

root@LAPTOP-QFDJDCS4:~/imagine/bundle/all# pkg-config --version
1.6.3

and how can fix it

**Comment by bladeoner** [comment]
Hi, I would recommend to compare the Github CI/CD Workflow file with your environment, it also uses Ubuntu 20.04 so it should work:

https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/.github/workflows/continuous-integration-workflow.yml

One side note: the first step is downloading a container with Android Studio, Android Studio should be installed manually in your environment.

**Comment by kenkieo** [comment]
It has been solved, because of environmental problems
