### ISSUE TITLE
Add updated build tools

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#222]
Hi @Rakashazi,

I hope you are doing fine, I wanted to share a change by updating Cmake and the Android software:
[update_build_tools.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/6783861/update_build_tools.zip)

**Comment by Rakashazi** [comment]
Thanks for the update, just added it. Btw, I'm planning to drop support for NDK r22 soon since r23 is now in release candidate so we'll update the build files again when that happens.
