### ISSUE TITLE
NES format support?

### ISSUE THREAD

**Issue by LaughingCheeze** [Rakashazi/emu-ex-plus-alpha#223]
Wondering why Snes9x Ex doesn't support the NES format, which seems to be the most common format? Instead it only supports .smc, .sfc, .fig, and .1 formats. 

Also, is this the official github repository of the project? I noticed the website didn't link to sources, which seems odd, since its based on two open source projects. 

Thanks

LC

**Comment by AlkaliManOG** [comment]
that's because nes is a whole different thing from SNES and the SNES isn't backwards compatible.

**Comment by LaughingCheeze** [comment]
> 
> 
> that's because nes is a whole different thing from SNES and the SNES isn't backwards compatible.

Derp, of course! I was getting confused with paperboy and paperboy 2 yesterday, thanks!
