### ISSUE TITLE
Github workflow issue

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#227]
Hi @Rakashazi it seems the following commit broke the Github Workflow:
[Input device handling updates and misc cleanup](https://github.com/Rakashazi/emu-ex-plus-alpha/commit/d4a9ca4007338f142fc354cd312ac0fa8261174c)

I was looking what could have caused it but it didn't see why it failed.

**Comment by Rakashazi** [comment]
Looks like I missed a few enum changes in MD.emu's EmuControls.cc, should be fixed now.
