### ISSUE TITLE
Please please please update GBA.emu core

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#228]
Play _Pokemon Emerald_ Chinese translation, then view Pokedex which you caught.
In VBA-M 2.1.1 and onwards it won't freeze anymore.
![Normal](https://user-images.githubusercontent.com/54294476/132988160-556f3040-58e3-4852-a688-f6429966cc08.png)

But GBA.emu still uses very old VBA-M core so it will freeze like this:
![Abnormal](https://user-images.githubusercontent.com/54294476/132988163-fdacc672-2aea-4a08-a752-96a7339f198c.png)

So please update VBA-M core, thanks!

**Comment by bladeoner** [comment]
@Yave-Yu can you try the attached build, I made some changes to the Pokemon games in the emulator to see if that makes a difference?

[GBAemu.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7269370/GBAemu.zip)

Thanks in advance.

**Comment by bladeoner** [comment]
If it doesn't make a difference can you see test following file?

[GBAemu_test2.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7269853/GBAemu_test2.zip)

**Comment by Yave-Yu** [comment]
I ran test2, still...
![Screenshot_2021-10-02-15-09-42-040_com explusalpha GbaEmu](https://user-images.githubusercontent.com/54294476/135707336-4a29b03d-7665-4397-8d0b-e3d1e3c417c3.jpg)
Update core might be a best solution.

**Comment by bladeoner** [comment]
Thanks for testing.

**Comment by Rakashazi** [comment]
I'll look into updating the GBA core in the near future. It currently has some performance optimizations I added for older devices that were based off an older VBA-M version and those need to be updated for the current version before the whole core can be updated.

**Comment by Yave-Yu** [comment]
Looking forward new VBA-M core in GBA.emu :p
One more situation: In Pokemon Unbound 2.0.2, if you use Fly to another place, it will freeze, only music keeps playing.

**Comment by Rakashazi** [comment]
The GBA.emu core was updated to VBA-M 2.1.4 in the last commit. Please test on the nightly and let me know if the issue is fixed. I'll include the updated core the GBA.emu 1.5.58 release.

**Comment by Yave-Yu** [comment]
Alright, all issue gone.
