### ISSUE TITLE
minor UI glitch in emulators

### ISSUE THREAD

**Issue by thededman** [Rakashazi/emu-ex-plus-alpha#23]
Newest  commitment has a minor glitch but emulators working.  May be nothing but want to make you aware. In the menu and fast forward items.

![img_0017](https://cloud.githubusercontent.com/assets/5215424/6314310/072f5806-b9a8-11e4-9d0c-bd430d4bd38b.png)
![img_0018](https://cloud.githubusercontent.com/assets/5215424/6314311/072ffaea-b9a8-11e4-9c07-ca8d5ae57e10.png)

**Comment by Rakashazi** [comment]
The new texture code isn't explicitly initializing the memory for the UI elements when they get loaded and CoreGraphics isn't writing the transparent pixels so you may get random junk left over. I'm now using kCGBlendModeCopy in the latest commit so all the pixels should be written correctly.
