### ISSUE TITLE
Github workflow build error

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#231]
@Rakashazi it seems the automatic build gives an error building the C64 and NEO emulators.

**Comment by bladeoner** [comment]
@Rakashazi, attached are the adjustments to fix the build errors:
[build_fix.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7162702/build_fix.zip)

**Comment by Rakashazi** [comment]
Thanks, those should be fixed in the last commit.
