### ISSUE TITLE
Added parallel builds to the Github Workflow

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#233]
@Rakashazi I've added parallel builds to the Github Workflow, this reduces the build time by half it takes around 30 minutes after adding this change:
[add_workflow_parallel_builds.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7268751/add_workflow_parallel_builds.zip)

I also corrected something in the following line, behind NeoEmu-release I accidentally added a minus:
cp NEO.emu/target/android-release/build/outputs/apk/release/NeoEmu-release.apk EX-Emulators/NeoEmu-release-.apk

**Comment by bladeoner** [comment]
You can add this change to the master, I got a succesful build, here you can see how it will look:
https://github.com/bladeoner/emu-ex-plus-alpha/actions/runs/1295750384

**Comment by Rakashazi** [comment]
Thanks, I went ahead and added it.

**Comment by bladeoner** [comment]
@Rakashazi I'm not sure why but NEO.emu failed maybe you should re-run the build when the rest finish.

You can do that from the Actions pane.
