### ISSUE TITLE
Parallel build failed

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#235]
@Rakashazi I'm not sure why but NEO.emu failed maybe you should re-run the build when the rest finish.

You can do that from the Actions pane, selecting the job and then Re-run jobs on the right side.

**Comment by Rakashazi** [comment]
Looks like one of the imagine builds started compiling before the imagine-config.h was generated. I'm going to double check and clean up the dependency code in the makefiles in case there's a small chance this can happen at random.
