### ISSUE TITLE
[Snes9x EX+] Several problems with some games

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#236]
The latest version of Snes9x EX+ has problems with some games: 

*Shin Megami Tensei if... - does not start after the Atlus logo
*Dream Maze: The Kigurumi Adventure (Kigurumi Daibouken) - crashes after selecting load in the main menu 
*Traverse: Starlight and Prairie - Crashes after entering name

**Comment by IdiotBlueMage** [comment]
I can't confirm the other two at all.  Are you using the patch on If... or Dream Maze?  Make sure you either patched it right (make sure headers are correct for example) or you're using the latest version.

**Comment by AbandonedWitchStarlight** [comment]
I did patch the game right and also tried the unpatched ones, but still not work.
