### ISSUE TITLE
Is all free? 

### ISSUE THREAD

**Issue by skelletR** [Rakashazi/emu-ex-plus-alpha#238]
Before some minutes go to buy GBA.emu from Google play and i read the description and i see a link and brought me here, and i see writes ex emulators and below see all emulators in a zip file, and all in one EX-Emulators.zip, all this is the same apps like Google play? And now is free from here? And is stable right? Not beta? I don't want damage my phone is new yet

**Comment by Rakashazi** [comment]
Hi, the versions here are builds of the latest code and haven't been extensively tested. There's no way they can damage your phone but I can't give any guarantee they'll work properly.

**Comment by skelletR** [comment]
> Hi, the versions here are builds of the latest code and haven't been extensively tested. There's no way they can damage your phone but I can't give any guarantee they'll work properly.

Thanks for answer. Oh, understand, it's ok, if not damage my phone, not have problems to test it
