### ISSUE TITLE
Sd card save?

### ISSUE THREAD

**Issue by skelletR** [Rakashazi/emu-ex-plus-alpha#239]
Hi i have Xiaomi Poco X3 NFC android 10, until now can't write save with emulators on sd card, i know Google close in the new android version the sd card write access, but maybe with some feature inside the emulators apps can access again

**Comment by Rakashazi** [comment]
Hi, please upgrade to 1.5.55+ and set the save path by tapping the middle of the grey top in the file browser, then select "Browse For Folder" which sets a path using the native Android folder picker. This should work with any external storage device regardless of OS differences between devices.

**Comment by skelletR** [comment]
Yeah, it's working, i download the version 1.5.55 from here, if i buy it from Google play have the same features right?

**Comment by Rakashazi** [comment]
Thanks for letting me know. Yes, the Google Play version has all the same features.

**Comment by skelletR** [comment]
That's is good, now keep this version download from here or buy Google play version? I think buy it if have a little discount for Christmas
