### ISSUE TITLE
[GBA.emu] Savegames does not load

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#241]
GBA.emu has problems with loading save games made from other emus.
Apperntly GBA.emu has a problem with loading SAV files for some games since the emu thinks they are corrupt and resets the game from the beginning, using saves made from other GBA emus (tried with Blender Bros, and Klonoa Empire of Dreams). My theory is that GBA emu does not check for any save types automatically, however. This got me when I tried to load a savegame in Castlevania Harmony of Dissonance but then it got corrupted and rests the game from beginning.

**Comment by Rakashazi** [comment]
Can you post some of the saves in question so I can test them out?

**Comment by AbandonedWitchStarlight** [comment]
[Savegame Test.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7775289/Savegame.Test.zip)

Also note that Castlevania HOD's save file is bigger on GBA.emu (64kb) as opposed to the other emus (32kb).

**Comment by Rakashazi** [comment]
Thanks, there was an issue recognizing 32k SRAM files, and games using that size were writing out 64k saves instead. It's now fixed so 32k saves load correctly, and any existing games with the incorrect 64k saves will switch to 32k next time they write their saves to disk.
