### ISSUE TITLE
Add updated NDK

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#243]
Hi @Rakashazi I've updated the NDK in the attached diff: 
[update_ndk.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7761786/update_ndk.zip)

**Comment by Rakashazi** [comment]
Thanks and happy holidays, just added it now.

**Comment by bladeoner** [comment]
You also enjoy the holidays!
