### ISSUE TITLE
Game file extension shouldn't be case sensitive!

### ISSUE THREAD

**Issue by RebelliousX** [Rakashazi/emu-ex-plus-alpha#244]
I am pretty sure this apply to all emus here, but I am using MSX.emu as a test.

MSX.emu doesn't see game files if the file extension is not "lower" case.
So it won't recognize ".ROM" or ".DSK" as a valid files when scanning a directory.

Unrelated to this (I can't tell if this is an issue really), but sometimes loading rom files
fail for the first time until I do a hard reset (MSX goes to BASIC instead). But maybe because
I am loading the games from a NAS drive using CIFS Document Provider app mounting
a shared folder as a local one. Not a big deal. But I first noticed this in latest release.
Opening rom files from recent games works without issues.

Edit: I confirmed that I have to do hard reset for a game to load correctly on another device (ShieldTV) also Sony Xperia. 

Thanks for the amazing work :)

**Comment by Rakashazi** [comment]
Thanks for the feedback. I've fixed the uppercase extension detection for the upcoming 1.5.56 release.

About the 2nd issue, is there a series of steps that will reproduce the boot failure or is it random? Which BIOS does it happen with?

**Comment by Rakashazi** [comment]
Actually, think I found the issue. The was an bug where media got ejected when attempting to load a save state even when it didn't exist, like an auto-state the first time running a game. Let me know if it still happens in 1.5.56 but that sounds like the bug you were running into.

**Comment by RebelliousX** [comment]
Thanks for the quick response. Both issues are fixed in v1.5.56 :)

Thank you again.
