### ISSUE TITLE
[GBA.emu] Kill.switch rendering error

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#246]
The GBA version of kill.switch has problems in GBA.emu, but not present in other emus. 
Here is a screenshot of this error:
![ksgbarenderror](https://user-images.githubusercontent.com/53141496/147449164-85ce9235-76df-492c-b51d-a41d47f43bfb.png)
It shows green and washed out colors instead of the in-game graphics (since it's a 3D game).
Here is the correct one for comparison:
![ksgbarend](https://user-images.githubusercontent.com/53141496/147477857-dcb7f46b-753b-428c-9cd5-26052d28f9f0.png)
This also happens with the GBA Corvette game as well as Tony Hawk's Downhill Jam, which were also made by Visual Impact.

**Comment by Rakashazi** [comment]
Thanks for the report, these should be fixed in the last commit but let me know in case any other issues with these games appear.
