### ISSUE TITLE
Google play version Discount?

### ISSUE THREAD

**Issue by skelletR** [Rakashazi/emu-ex-plus-alpha#247]
Great apps, now i have Gba.emu 1.5.55, keep this version download from here or buy Google play version? (I don't like very much the bundle apps)  I think buy it if have a little discount for Christmas or New Year

**Comment by Rakashazi** [comment]
Thanks, it's up to you but if you like the apps then buying them on Google Play supports future development. For fairness I don't run sales or discounts.
