### ISSUE TITLE
[GBA.emu] Several game problems

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#249]
In GBA.emu there are some games that have problems and it needed fixing to make these games work.
Here are some of them: 

Smuggler's Run - doesn't boot after selection (in Smuggler's Mission)
Tony Hawk Downhill Jam - does not boot after selecting mode
Smashing Drive - crashes on the first race

**Comment by Rakashazi** [comment]
Thanks for the report, please test these out in the newest nightly and let me know if the issues are resolved.

**Comment by AbandonedWitchStarlight** [comment]
Well they are fixed but Blades of Thunder however does not boot after the mission entry screen

**Comment by Rakashazi** [comment]
Looks like the 2.1.4 release of VBA-M had an issue with the memory handlers that broke Blades of Thunder. I added in the fixes from the GIT version so it should be working now.
