### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#251]
@Rakashazi best wishes for the new year, it seems that the workflow didn't build after the last commit.

**Comment by Rakashazi** [comment]
Thanks and happy new year. It looks like only 2600.emu was updated to use NDK 24 while the others are still building on 23, and some recent changes I made require the newer version of clang in 24. I went ahead and updated them all to use NDK 24 so they should finish building this time.
