### ISSUE TITLE
Added updated and optimized Github Workflow

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#252]
@Rakashazi thank you for fixing the Github Workflow, I saw that I forget to update the NDK version.

To prevent this I've optimized the Github Workflow.

I've implemented a Matrix Strategy which looks for a specific tag which need to match the name of the docker instance and then it will perform those steps. Besides that it will perform the global steps which every docker instance need to perform, like setting up the build environment and download and extract the NDK.

[update_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/7823579/update_workflow.zip)

**Comment by bladeoner** [comment]
A test run just finished without any issues.

**Comment by bladeoner** [comment]
A test build is running:
https://github.com/bladeoner/emu-ex-plus-alpha/actions/runs/1664001684

**Comment by bladeoner** [comment]
Build completed succesfully

**Comment by Rakashazi** [comment]
Thanks, this will be a lot easier to update when a new NDK comes out. I just added it in the last commit.
