### ISSUE TITLE
Gamepad Issue

### ISSUE THREAD

**Issue by emyaqin** [Rakashazi/emu-ex-plus-alpha#254]
From version 1.5.55, there has been some issue with gamepad controller in all of the emulator. I use a gamepad that has some additional button like volume, play/pause, and skip. I use the skip and play button as a menu and save state button, but keep the volume button as volume trigger. Version 1.5.54 just doing fine with this setup, but after updating to 1.5.55 and 1.5.56, I no longer can use the volume button. And also sometimes when I choose custom colour palette in NES.emu, the app crashes, but only sometimes.

**Comment by Rakashazi** [comment]
Thanks for the report, the palette crash is already fixed in the nightly builds and I just added a fix for volume/media buttons on gamepads. Both these fixes will be in the upcoming 1.5.57 update but let me know in case the volume issue happens again in a future update.
