### ISSUE TITLE
any way to support CPS1?

### ISSUE THREAD

**Issue by Visntse** [Rakashazi/emu-ex-plus-alpha#257]
i think world no.1 simple and easy emulator is this x.emu series.
but only missing cps1 or cps2 game support.
so, any ider to make that support?

by the way, i can help translate emu ui to chinese, did you need?

**Comment by Rakashazi** [comment]
I can't give any ETA but CPS support may come to NEO.emu in a future update. Thanks for the translation offer, I'm not ready to accept app translations currently but will let you know if I'm looking for a Chinese translation.

**Comment by Visntse** [comment]
okay～ i hope will be fast to play cps1 game in neo.emu～
and in the future if need s-chi or t-chi translate, can be contact me with my nike name to GMAIL.
last year i try to transalte some text, uh... it’s display well～

if you see this report, close this issues done.
