### ISSUE TITLE
Snes9x core update

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#258]
@Rakashazi I hope you are doing well.

When you find some time is it possible that you update the Snes9x core to the latest commit?

I'm really interested in the commit below:
https://github.com/snes9xgit/snes9x/commit/2bc5302478bb930387dd2ec45e6928916449fe9d

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks and hope you're doing well too. I'm planning to update it soon so I'll also include the commit you mentioned.

**Comment by bladeoner** [comment]
I am doing fine thank you, thanks for your quick response.

**Comment by bladeoner** [comment]
@Rakashazi thanks for updating Snes9x I will close this issue.
