### ISSUE TITLE
Updated BTstack license-incompatible with GNU GPL?

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#26]
This is about the recent commit 4dcf671a20e8aa384be6a7cf29c66ab456d3aa91, "Update bundled BTstack"

The updated BTstack source files have a new/additional clause in the copyright/licensing info:
* 4. Any redistribution, use, or modification is done solely for
*    personal benefit and not for any commercial purpose or for
*    monetary gain.

I think that is not compatible with the GNU GPL v3, which does allow commercial use and redistribution for monetary gain.

**Comment by Rakashazi** [comment]
According to the author, he states "I've changed the license of the public BTstack version by adding a 4th clause that only allows personal and/or non-commercial use. This mostly targets the use of BTstack on embedded systems. BTstack on iOS can still be used without restrictions. "

Referenced from the following post: https://groups.google.com/forum/#!topic/btstack-dev/nLZzs7tPUhI

**Comment by M-a-r-k** [comment]
I don't think the BTstack developer allowing commerical distribution for iOS affects whether or not the BTstack license is GPL-compatible. I think the two are fundamentally incompatible, similarly to how code from MAME (which only allows non-commerical use) cannot be combined with GPL code. Or indeed to the Snes9x-EX situation. While you as author of the Imagine framework can distribute binaries under any license you like, no-one else can, because to do so they would have to comply with both GPLv3 for Imagine, but also require non-commercial use for Snes9x. But they can't have both simultaneously, because GPL forbids a non-commercial restriction.

Anyone distributing an iOS binary with Imagine and BTstack code has to comply with GPLv3. But GPLv3 does not permit adding a "only non-commercial use if you build it for another platform" restriction.
