### ISSUE TITLE
Workflow build didn't run

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#269]
Hi @Rakashazi I'm not sure why but with the latest commit the workflow build was not triggered.

**Comment by Rakashazi** [comment]
That's strange since I didn't modify anything related to the workflow. The next commit is almost ready so let's see if the builds get triggered after that.

**Comment by bladeoner** [comment]
Yesterday I triggered a build by forking the code and it started to run. I think the next build will be triggered but as you said, let's see what will happen.

**Comment by Rakashazi** [comment]
Good to know, looks like the build ran correctly from the last commit.
