### ISSUE TITLE
[PCE.emu] Request: Add Support For Sharp X1, PC-88, Sharp X68000 Games.

### ISSUE THREAD

**Issue by DVDVIDE** [Rakashazi/emu-ex-plus-alpha#270]
On PCE.emu 1.5.58: Can You Please Add Support For Sharp X1, PC-88, Sharp X68000. Add 2 Aspect Ratio In Video: Aspect Ratio (PCE), Aspect Ratio (PC-88, Sharp X1, Sharp X68000)

Aspect Ratio (PCE): 4:3, 8:7, Full Screen

Aspect Ratio (PC-88, Sharp X1, Sharp X68000): 3:2, Full Screen

**Comment by Rakashazi** [comment]
These systems are not related hardware-wise to the PC-Engine and require a completely different emulator so I won't be adding them to PCE.emu.

**Comment by DVDVIDE** [comment]
It Means That There Is No PC-88, Sharp X1, Sharp X68000 On Android.
