### ISSUE TITLE
GBC.emu 1.5.59 Update Core:

### ISSUE THREAD

**Issue by DVDVIDE** [Rakashazi/emu-ex-plus-alpha#274]
Update To VGBA.
Add Support For SGB Enchanted, Add Emulated Hardware In Console Options, Add Super Game Boy Palettes In Video, Add Turbo Buttons.

**Comment by Yave-Yu** [comment]
No, current mGBA's GB/GBC emulation is not better than Gambatte and BGB.

**Comment by DVDVIDE** [comment]
VGBA ALSO SUPPORTS FOR GAME BOY, SUPER GAME BOY, GAME BOY COLOR. I SEE ON MATSU EMULATOR, RETROARCH.

**Comment by DVDVIDE** [comment]
Or SameBoy Is High Accurate

**Comment by DVDVIDE** [comment]
Is SameBoy Emulation Available On Android. Available: RetroArch, Some GBC Emulators Compatible With Chromebook Devices

**Comment by DVDVIDE** [comment]
F**k
