### ISSUE TITLE
Added a bug, a feature request and question report

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#280]
Hi @Rakashazi I just finished creating a bug report, feature request and question report which can be added:
[add_bug_and_feature_reports.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8091679/add_bug_and_feature_reports.zip)

This makes it easier for someone to create an issue, feature request or question and it makes it also easier for you to distinguish.

I created a test repository where you can see how it works, if you go to the following and click on 'New issue' you will see how it will look: https://github.com/bladeoner/repository-to-test/issues

You have three options: Bug Report, Feature request, or Question click on Get Started
Bug report: 
You need to fill in a title behind [Issue]:
The following are mandatory: Describe the bug, Steps to reproduce, Expected behavior (you see a red star behind the names).
The other two Relevant log output and Add screenshots are optional.

Feature request:
You need to fill in a title behind [Feature request]: 
Describe the feature is mandatory, Add screenshots is optional

Question:
You need to fill in a title behind [Question]:
Describe the question is mandatory, Add screenshots is optional

**Comment by Rakashazi** [comment]
Thanks @bladeoner, I'll add this into the next commit.
