### ISSUE TITLE
[Android] [GBA.emu / Snes9x EX] Adding Memory Viewer function?

### ISSUE THREAD

**Issue by QuotunicGit** [Rakashazi/emu-ex-plus-alpha#281]
Hello @Rakashazi! I've been using your apps for a while, especially the snes and gba. And I am surprised by how smooth and easy they are to use. If possible, can you add a memory viewer like in some emulator debuggers (or if it's already possible, may I ask how?), much appreciated.

**Comment by Rakashazi** [comment]
Hi @QuotunicGit and thanks for the feedback. I don't have a memory viewer implemented atm but it would be nice especially for things like cheat creation so I'll add it to my to-do list.
