### ISSUE TITLE
Launchbox and .emu emulators issue

### ISSUE THREAD

**Issue by Demnklnr** [Rakashazi/emu-ex-plus-alpha#282]
I'm recently having an issue where roms launch correctly from .emu emulators but when I try to launch them through launchbox I get a permission denied red flag.  I posted the issue on launchbox form and they said it would have to be fixed by the emulator dev due to some new Google permission requirements or something.   This was working flawlessly up until recently. I really like these. Emu emulators over retroarch personally.  Is this something you can fix

**Comment by IdiotBlueMage** [comment]
IIRC launchbox android isn't tended to anymore.  This is important to the issue.  The scoped storage implimitation has broken most older frontends that haven't updated to accept the same.  Dig is a big example here; the latest stable update won't launch games from the emus, but the latest beta with scoped storage will.

**Comment by Demnklnr** [comment]
OK. Thank you for the info. Still gonna use your .emus over retroarch.  I
just like them better. I own all of them

**Comment by Rakashazi** [comment]
Yes, this sounds like a scoped storage issue with the frontend. Starting with Android 11 it needs to provide a file URI that the emulator has also been granted access to, and not a direct file path. While I can't help directly troubleshoot frontend issues here feel free to let the developer know they can email me and we can try to work out a fix.
