### ISSUE TITLE
[Feature request]: NES.emu 1.5.59 Update:

### ISSUE THREAD

**Issue by SopTheSop2022** [Rakashazi/emu-ex-plus-alpha#286]
### Describe the feature

Add Generator Audio Channel: Square 1 On/Off, Square 2 On/Off, Triangle On/Off, Noise On/Off, DPCM On/Off, FDS On/Off, MMC5 On/Off, VRC6 On/Off, VRC7 On/Off, N163 On/Off, SUNSOFT 5B On/Off In Audio.

### Add screenshots

![Screenshot_20220218-194237](https://user-images.githubusercontent.com/99989661/154744753-ae50e8ca-21b9-4014-966d-112042e2a7b2.jpg)

**Comment by SopTheSop2022** [comment]
@Rakashazi

**Comment by Rakashazi** [comment]
Added in last commit.
