### ISSUE TITLE
[Feature request]: Combined Scanline/CRT Mask overlay effect

### ISSUE THREAD

**Issue by IdiotBlueMage** [Rakashazi/emu-ex-plus-alpha#287]
### Describe the feature

In recent years I've been seeing a lot of CRT filters/shaders that don't just do scanlines, but also the shadow mask along with it.  I believe that a way to replicate this would be combining the overlay effects of Scanlines and CRT Mask, with some minor modifications.  I would imagine that this would look pretty great with Linear+Prescale.

**Comment by Rakashazi** [comment]
Sounds interesting, I'm planning to add multi-texture support to the effects code in the future so a combined effect like this will eventually be possible.
