### ISSUE TITLE
[Feature request]: MD.emu 1.5.59 Update: Update Core To Genesis Plus GX 1.7.4

### ISSUE THREAD

**Issue by SopTheSop2022** [Rakashazi/emu-ex-plus-alpha#290]
### Describe the feature

@Rakashazi Update Core To Genesis Plus GX 1.7.4, Add Support For SG-1000 (.sg), Game Gear (.gg), Add System Hardware In Console Options.

### Add screenshots

![Screenshot_20220220-090635~2](https://user-images.githubusercontent.com/99989661/154834328-51b59551-801d-4c0b-8f17-6ad0b62d8f96.jpg)
![Screenshot_20220220-090725~2](https://user-images.githubusercontent.com/99989661/154834330-abed9638-5e65-4412-8ff4-74cdb2a13fa9.jpg)

**Comment by SopTheSop25** [comment]
SG-1000 On Gearsystem 3.4.1 Core

**Comment by SopTheSop25** [comment]
Stop Spamming. 1.5.59 Is 1.5.58
