### ISSUE TITLE
[Question]: Can you add this github workflow and gradle update?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#293]
### Describe your question

Hi @Rakashazi I've included an update for the github workflow and a gradle update, can you add them in the next commit?
[update_gradle.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8142809/update_gradle.zip)
[update_github_workflow_and_readme.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8148331/update_github_workflow_and_readme.zip)

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks, included them in the last commit.
