### ISSUE TITLE
[Feature request]: GBC.emu 1.5.59 Update: Update Core To Gambatte 0.5.0

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#298]
### Describe the feature

Update Core To Gambatte 0.5.0
Add Emulated Hardware: Auto, GB (Game Boy), SGB (Super Game Boy), GBC (Game Boy Color), GBA (Game Boy Advance)
Add GB Colorization: Auto, GBC, SGB, Internal, Custom
Add GB Colors: GB DMG, GB Light, GB Pocket, SGB 1-A, SGB 1-B, SGB 1-C, SGB 1-D, SGB 1-E, SGB 1-F, SGB 1-G, SGB 1-H, SGB 2-A, SGB 2-B, SGB 2-C, SGB 2-D, SGB 2-E, SGB 2-F, SGB 2-G, SGB 2-H, SGB 3-A, SGB 3-B, SGB 3-C, SGB 3-D, SGB 3-E, SGB 3-F, SGB 3-G, SGB 3-H, SGB 4-A, SGB 4-B, SGB 4-C, SGB 4-D, SGB 4-E, SGB 4-F, SGB 4-G, SGB 4-H, Other.

### Add screenshots

![Screenshot_20220305-100934](https://user-images.githubusercontent.com/99989661/156877664-d4b8822d-29f0-47ac-9ff0-91e728cb7cfd.jpg)
![Screenshot_20220305-100938](https://user-images.githubusercontent.com/99989661/156877673-e10e70b2-2a00-4d2f-ba1f-02feb728c679.jpg)
![Screenshot_20220305-100941](https://user-images.githubusercontent.com/99989661/156877675-e4671d4e-0e31-43bd-a5d2-6a1342ca259c.jpg)
![Screenshot_20220224-220103](https://user-images.githubusercontent.com/99989661/156877683-0ee73874-10d3-43c2-9a40-8391def056b9.jpg)
![Screenshot_20220224-220113](https://user-images.githubusercontent.com/99989661/156877686-d12e048a-0fa3-4b9c-acd8-27b76f38c1ce.jpg)
![Screenshot_20220224-220118](https://user-images.githubusercontent.com/99989661/156877691-1b56621b-1410-4d60-957e-7f60bdc3d0b2.jpg)
![Screenshot_20220224-220123](https://user-images.githubusercontent.com/99989661/156877697-8886aab4-9f25-4432-9087-bdfdbd87a95b.jpg)
![Screenshot_20220224-220328](https://user-images.githubusercontent.com/99989661/156877699-f3938e52-97fd-41d8-b740-0d267c774e11.jpg)
![Screenshot_20220224-214642~2](https://user-images.githubusercontent.com/99989661/156877732-82ba7315-6a4d-445b-b1ff-77e3bc3ae6bc.jpg)
![Screenshot_20220224-214649~2](https://user-images.githubusercontent.com/99989661/156877736-46b66708-934f-4531-98ce-edd59df88a1c.jpg)
![Screenshot_20220224-214656~2](https://user-images.githubusercontent.com/99989661/156877744-a512b04f-ce71-4a53-a935-45303a16fab9.jpg)
![Screenshot_20220224-214702~2](https://user-images.githubusercontent.com/99989661/156877747-c034a7b9-5f6e-4644-aa51-4b8e34955f0f.jpg)
![Screenshot_20220224-215533~2](https://user-images.githubusercontent.com/99989661/156877748-caefd716-fa05-487b-a81a-dc1b611d5c03.jpg)
![Screenshot_20220224-215541~2](https://user-images.githubusercontent.com/99989661/156877751-bb881ebe-bb59-4b29-90f2-e7affeb13c84.jpg)
![Screenshot_20220224-215625~2](https://user-images.githubusercontent.com/99989661/156877754-cdd43da9-3bb4-4834-85fb-ee2121340780.jpg)
![Screenshot_20220224-215638~2](https://user-images.githubusercontent.com/99989661/156877756-3d31a78d-847a-4a27-9863-f7e72f9f5961.jpg)

https://user-images.githubusercontent.com/99989661/156877768-b012cc3e-d54f-476a-bd34-efce757357d8.mp4

**Comment by SopTheSop27** [comment]
I Said To mGBA 0.9.3
mGBA 0.9.3 Is High Accurate.

**Comment by CraftFan22** [comment]
Those Spams About. It Will Not Be On 1.5.59!

**Comment by Yave-Yu** [comment]
On GB/C side, mGBA is not accuracy than Gambatte and BGB, such as that terrible PSG audio emulation.

**Comment by HaroldCraft** [comment]
mGBA is accuracy. It Supports MBC6, MBC7, Pocket Camera & More Mappers, Game Boy Printer. I Tested mGBA On RetroArch. I Tried Sonic 3D Blast 5 (Unl) On Gambatte, but it's Unsupported MBC. On mGBA Works. It Also Has Super Game Boy Enhanced Mode. Game Boy Model:

> Auto
> Game Boy
> Super Game Boy
> Game Boy Color
> Game Boy Advance
