### ISSUE TITLE
[C64.emu] Media Options in media control does not save disk type settings

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#299]
### Describe the bug

Apparently C64.emu does not save the disk types on Media Options in Media Control after setting drives and defaults to 1541-II with no other drives enabled. This makes Disk-based games run with problems. This isn't a problem with the real VICE emulator.
I tried this with Accolade's Comics: Steve Keene, Private Spy and a warning comes up about compatible drives. 

### Steps to reproduce

When the game loads, I selected Media Control, and scrolled to Media Options, then chose drive format on all 4 drives (8-11), and save settings, but when I load a new disk, the problem still comes up. 

### Expected behavior

The drives should be working correctly.

**Comment by Rakashazi** [comment]
Thanks for the report, the drive types are now saved on a per-content basis so they shouldn't reset to default each time you load a disk. This will be included in version 1.5.59 but feel free to test the nightly and let me know if there's still issues.
