### ISSUE TITLE
[Feature request]: Add Turbo Button

### ISSUE THREAD

**Issue by SopTheSop25** [Rakashazi/emu-ex-plus-alpha#301]
### Describe the feature

@Rakashazi Add Turbo Button For NES.emu, GBC.emu, GBA.emu.

Y = Turbo B
X = Turbo A

Add Turbo Pulse Speed.

**Comment by master1274** [comment]
I support the proposal. In these emulators, turbo buttons are very useful!

**Comment by SopTheSop25** [comment]
It May Will Be On 1.5.60 Release. 1.5.59 Is 1.5.58 Release
