### ISSUE TITLE
240 lines

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#303]
Yeah, hope NES.emu & Snes9x could add 240 lines display... I saw update log says "239 lines", but it's 240 lines actually, 0-239 contains 0, so totally 240.

**Comment by Rakashazi** [comment]
I'm not sure about other emulators, but Snes9x at least only outputs 239 visible lines total. Can you provide a source of the full 240 line output you're referring to?

**Comment by Yave-Yu** [comment]
I'm sorry... just NES has full 240 lines.

**Comment by Rakashazi** [comment]
Thanks for clarifying, this new line modes will be included in version 1.5.59.
