### ISSUE TITLE
[Feature request]: GBC.emu & GBA.emu: Update Core To mGBA 0.9.3

### ISSUE THREAD

**Issue by SopTheSop27** [Rakashazi/emu-ex-plus-alpha#304]
### Describe the feature

@Rakashazi GBC.emu & GBA.emu: Update Core To mGBA 0.9.3
GBC.emu: Add More GB Palette: DMG, GB Light, GB Pocket, SGB 1-A, SGB 1-B, SGB 1-C, SGB 1-D, SGB 1-E, SGB 1-F, SGB 1-G, SGB 1-H, SGB 2-A, SGB 2-B, SGB 2-C, SGB 2-D, SGB 2-E, SGB 2-F, SGB 2-G, SGB 2-H, SGB 3-A, SGB 3-B, SGB 3-C, SGB 3-D, SGB 3-E, SGB 3-F, SGB 3-G, SGB 3-H, SGB 4-A, SGB 4-B, SGB 4-C, SGB 4-D, SGB 4-E, SGB 4-F, SGB 4-G, SGB 4-H
GBC.emu: Add Hardware Preset Game Boy Palettes In Video Options
GBC.emu: Add Select Game Boy Model In Console Options: Auto, Game Boy, Super Game Boy, Game Boy Color, Game Boy Advance
GBC.emu: Add SGB Borders On / Off In Video Options

### Add screenshots

![156877683-0ee73874-10d3-43c2-9a40-8391def056b9~2](https://user-images.githubusercontent.com/101358042/158015880-b67dddc3-c692-4f8f-8c6a-fd3b19b9bdef.jpg)
![156877686-d12e048a-0fa3-4b9c-acd8-27b76f38c1ce~2](https://user-images.githubusercontent.com/101358042/158015886-e05bb127-e5c7-4663-afda-7b4e0213fe20.jpg)
![156877691-1b56621b-1410-4d60-957e-7f60bdc3d0b2~2](https://user-images.githubusercontent.com/101358042/158015890-a7f2c596-8010-46b1-9801-7b47dae10b6e.jpg)
![156877697-8886aab4-9f25-4432-9087-bdfdbd87a95b~2](https://user-images.githubusercontent.com/101358042/158015894-793eea7d-9ced-4707-af4b-51ce5e055ceb.jpg)
![Screenshot_20220312-115146~2](https://user-images.githubusercontent.com/101358042/158015897-b349939f-30ef-496b-b6d7-7ad96f7a9bea.jpg)
![156877699-f3938e52-97fd-41d8-b740-0d267c774e11~2](https://user-images.githubusercontent.com/101358042/158015922-bb58fcdd-036f-48ab-a4eb-ccf9424bd302.jpg)
![Screenshot_20220312-115050~2](https://user-images.githubusercontent.com/101358042/158015940-bd99501a-0ca1-48da-aad3-a22f4e798c12.jpg)
![156877732-82ba7315-6a4d-445b-b1ff-77e3bc3ae6bc](https://user-images.githubusercontent.com/101358042/158015949-01732787-a66f-4757-aadc-12dd919653a4.jpg)
![156877736-46b66708-934f-4531-98ce-edd59df88a1c](https://user-images.githubusercontent.com/101358042/158015952-ea17315f-ea01-4f58-bce0-42dfdddc2dc5.jpg)
![156877744-a512b04f-ce71-4a53-a935-45303a16fab9](https://user-images.githubusercontent.com/101358042/158015955-43255ec3-9de8-4bdc-ae43-f35559a24c80.jpg)
![156877747-c034a7b9-5f6e-4644-aa51-4b8e34955f0f](https://user-images.githubusercontent.com/101358042/158015956-3ce4d7cd-a1bc-45f3-8f1b-dac72646122d.jpg)
![156877748-caefd716-fa05-487b-a81a-dc1b611d5c03](https://user-images.githubusercontent.com/101358042/158015966-27293b0d-0e9d-4c48-bace-ddb1623be51a.jpg)
![156877751-bb881ebe-bb59-4b29-90f2-e7affeb13c84](https://user-images.githubusercontent.com/101358042/158015971-77f7c82d-ce81-4ca3-98a6-b4f923003824.jpg)
![156879100-cce9d9ec-1670-48ef-bc1d-556453523724](https://user-images.githubusercontent.com/101358042/158015974-ee6e7f46-7f79-4da2-a061-bd125c91d37d.jpg)
![156877754-cdd43da9-3bb4-4834-85fb-ee2121340780](https://user-images.githubusercontent.com/101358042/158015997-e395d2a3-1108-457a-97e0-93d2e4e6b0c3.jpg)
![156877756-3d31a78d-847a-4a27-9863-f7e72f9f5961](https://user-images.githubusercontent.com/101358042/158016001-9ef8658f-2209-479f-96b1-fb70925660b7.jpg)

https://user-images.githubusercontent.com/101358042/158033652-1162e5de-4ef8-47d3-ad0d-f865e5fb824e.mp4

**Comment by SopTheSop25** [comment]
Yes

**Comment by master1274** [comment]
Emulators GBA.emu and GBC.emu built around other core. GBA.emu - VBA-M. GBC.emu - Gambatte. How can I update for them mGBA?

**Comment by SopTheSop25** [comment]
It's Better To Update To mGBA On GBC.emu, NOT On GBA.emu
mGBA Has SGB Enhanced Support, Emulated Hardware: Auto, GB, SGB, GBC, GBA. Also Has DMG, GB Light, GB Pocket, Super Game Boy Colors. Emulator Core Is libmain.so (.so). Got It!

**Comment by master1274** [comment]
emulator core GBC.emu is an Gambatte. Nothing to do with mGBA does not have. libmain.co it's just the name of the library in the emulator.
![Screenshot_20220313-153822](https://user-images.githubusercontent.com/20639709/158059710-c29d756c-3bcd-43ad-9e7f-c42dfe0ee781.png)

**Comment by SopTheSop27** [comment]
https://github.com/bardeci/gambatte-dms/issues/28#issue-1160308319

**Comment by SopTheSop27** [comment]
See SGB Enhanced Games:
![Screenshot_20220313-151924~2](https://user-images.githubusercontent.com/101358042/158065278-e50344a7-cfe9-4547-84af-fb4d96c4c5a7.jpg)
![Screenshot_20220313-151915~2](https://user-images.githubusercontent.com/101358042/158065280-6df53432-5581-42e4-a6a5-d07806ab2736.jpg)
![Screenshot_20220313-151903~2](https://user-images.githubusercontent.com/101358042/158065283-2a3ebea0-f43c-49db-9da5-a71a96b378c2.jpg)
![Screenshot_20220313-151838~2](https://user-images.githubusercontent.com/101358042/158065284-53cd4bf9-995b-4b34-93b2-94eac84d3822.jpg)
![Screenshot_20220313-151832~2](https://user-images.githubusercontent.com/101358042/158065288-c004185a-4ea5-4e8b-a7f6-1bbceb623f5a.jpg)
![Screenshot_20220313-151750~2](https://user-images.githubusercontent.com/101358042/158065289-55a5cefd-9d4e-4fdc-bee2-64409ba04386.jpg)
![Screenshot_20220313-151719~2](https://user-images.githubusercontent.com/101358042/158065292-2de3db96-cc6c-4386-953a-161ffb1d0b15.jpg)
![Screenshot_20220313-151659~2](https://user-images.githubusercontent.com/101358042/158065295-63c365ac-8ca9-4dd0-b076-5fbb953e81f1.jpg)
![Screenshot_20220313-151646~2](https://user-images.githubusercontent.com/101358042/158065298-228d9cfd-cb6e-486e-8d97-81138e33e182.jpg)
![Screenshot_20220313-151619~2](https://user-images.githubusercontent.com/101358042/158065302-b4427151-0f30-4001-8fc9-584c5d04a801.jpg)
![Screenshot_20220313-151611~2](https://user-images.githubusercontent.com/101358042/158065334-e8650d35-48dd-4881-b1c4-bc47c9ef40dd.jpg)
![Screenshot_20220313-151602~2](https://user-images.githubusercontent.com/101358042/158065346-c4a930f0-0e71-4d9e-b74c-93a55fda4ac1.jpg)
![Screenshot_20220313-151558~2](https://user-images.githubusercontent.com/101358042/158065352-caefff11-c10f-4185-9a34-f05bbf5421c2.jpg)
![Screenshot_20220313-151527~2](https://user-images.githubusercontent.com/101358042/158065363-f7e63ded-6a3e-4dca-bde5-c1b845841e51.jpg)
![Screenshot_20220313-151510~2](https://user-images.githubusercontent.com/101358042/158065367-cc4ac5b5-f1c3-4c1c-b404-7625bfe63bd6.jpg)
![Screenshot_20220313-151502~2](https://user-images.githubusercontent.com/101358042/158065372-b259e4db-d272-43b2-9e21-c89c3c37172c.jpg)
![Screenshot_20220313-151447~2](https://user-images.githubusercontent.com/101358042/158065375-56482d69-27a2-4321-aef2-4c6725fa0036.jpg)
![Screenshot_20220313-151434~2](https://user-images.githubusercontent.com/101358042/158065378-849e99fa-c21b-45d0-9829-4f58b9c3ee55.jpg)
![Screenshot_20220313-151426~2](https://user-images.githubusercontent.com/101358042/158065385-6ed9a4f6-632b-4122-88f0-ef7206336757.jpg)
![Screenshot_20220313-151412~2](https://user-images.githubusercontent.com/101358042/158065390-76fc68b0-c225-405e-b206-a0ee50d2f312.jpg)
![Screenshot_20220313-151400~2](https://user-images.githubusercontent.com/101358042/158065396-1bd34ee4-8dba-4fa4-bd12-080aacc73d1d.jpg)
![Screenshot_20220313-151332~2](https://user-images.githubusercontent.com/101358042/158065400-8910057d-a9ed-4e28-ac1f-337e0c0641a4.jpg)
![Screenshot_20220313-151313~2](https://user-images.githubusercontent.com/101358042/158065402-b277524b-c91c-470f-ac3d-a94c2d98741e.jpg)
![Screenshot_20220313-151247~2](https://user-images.githubusercontent.com/101358042/158065406-cf72bbf7-2876-4f2e-a30f-9348b86b2a52.jpg)
![Screenshot_20220313-151233~2](https://user-images.githubusercontent.com/101358042/158065430-d090579a-9285-437b-9b2d-ff97e8c9508e.jpg)
![Screenshot_20220313-151218~2](https://user-images.githubusercontent.com/101358042/158065436-ed913980-eb10-461e-9b00-8d80eb122845.jpg)
![Screenshot_20220313-151200~2](https://user-images.githubusercontent.com/101358042/158065442-cfcd4831-07ac-447d-b0f5-c1bd9762fe9d.jpg)
![Screenshot_20220313-151152~2](https://user-images.githubusercontent.com/101358042/158065445-ae7c6735-538e-4e97-a8e6-8fe8d784ae76.jpg)
![Screenshot_20220313-151147~2](https://user-images.githubusercontent.com/101358042/158065453-4f8c6dc4-94c0-418b-bb45-e4a29b397b69.jpg)
![Screenshot_20220313-151142~2](https://user-images.githubusercontent.com/101358042/158065457-22d547a3-0a37-4028-bb6a-77274f244d4f.jpg)
![Screenshot_20220313-151122~2](https://user-images.githubusercontent.com/101358042/158065468-7b2a3cc9-3c55-4156-a175-19d546048022.jpg)
![Screenshot_20220313-151037~2](https://user-images.githubusercontent.com/101358042/158065474-596e3e9d-e7a7-4936-b2bb-6755abe4e5be.jpg)
![Screenshot_20220313-151030~2](https://user-images.githubusercontent.com/101358042/158065477-4aa0ee27-06c3-4d80-94e0-c450d47155b2.jpg)
![Screenshot_20220313-151014~2](https://user-images.githubusercontent.com/101358042/158065483-9edcfc66-9984-41c7-b2ea-86b9e358f6f3.jpg)
![Screenshot_20220313-150957~2](https://user-images.githubusercontent.com/101358042/158065489-b7d585ff-eb6d-481b-91d9-9d2c0c870000.jpg)
![Screenshot_20220313-150952~2](https://user-images.githubusercontent.com/101358042/158065496-f620d307-c0c2-4630-8d62-3f80e13940ff.jpg)
![Screenshot_20220313-150916~2](https://user-images.githubusercontent.com/101358042/158065503-ceffb1c1-2ad9-49d2-9d17-bee96a875e71.jpg)
![Screenshot_20220313-150900~2](https://user-images.githubusercontent.com/101358042/158065509-3855d1eb-ddb3-43de-a648-a5931d80da7b.jpg)
![Screenshot_20220313-152325~2](https://user-images.githubusercontent.com/101358042/158065516-1de7410c-89bc-4dc7-8b16-9bffaebb1311.jpg)
![Screenshot_20220313-152319~2](https://user-images.githubusercontent.com/101358042/158065518-26325b5d-cec2-455c-90a7-d25af5b518c9.jpg)
![Screenshot_20220313-152256~2](https://user-images.githubusercontent.com/101358042/158065522-20937195-1d86-4ddd-8876-97bf238c2d6e.jpg)

**Comment by SopTheSop27** [comment]
mGBA & VBA-M Also Has Game Boy, Super Game Boy, Game Boy Color Support. mGBA Is High Accurate Game Boy / Super GB / Game Boy Color Emulator. SGB Enhanced Color Games Isn't Available On Gambatte. It Will Be SGB Enhanced Support On Gambatte 0.5.1 Update.

**Comment by SopTheSop27** [comment]
Coming

**Comment by SopTheSop25** [comment]
Stop Spamming The Same Request! 1.5.59 Is 1.5.58

**Comment by SteveCraft29** [comment]
My OldBoy! Is Based On TGB Dual. TGB Dual Isn't Highly Accurate. Wario Land: Super Mario Land 3 DX Is New ROM Hack But It Doesn't Work On My OldBoy!, John GBC, John GBAC, VGBANext (TGB Dual). https://www.romhacking.net/hacks/6683/ Is Wario Land: Super Mario Land 3 DX.
