### ISSUE TITLE
[Feature request]: NES.emu Famicom Controller II Microphone

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#307]
### Describe the feature

Family Computer Disk System (FDS) had a microphone never found anywhere else.

Microphone 	
A Japan-exclusive built-in feature in the original Player 2 Famicom controller that allows players to use external sound source (e.g. player's voice) as input. 	

Which games make use of Controller II's microphone?

Atlantis no Nazo (NES = Super Pitfall II) - get the microphone power-up and then yell into the microphone to freeze and kill most enemies.

Hikari Shinwa: Palutena no Kagami (NES = Kid Icarus) - talk into the microphone to bargain for lower shop prices.

Raid on Bungeling Bay (NES = Raid on Bungeling Bay) - ?

SD Kamen Rider -- in one of the mini games, blow air into the microphone to get a windmill to spin.

Takeshi no Chousenjou - featuring Takeshi Kitano who starred in Zatoichi, Battle Royale, Violent Cop, etc.) Kitano hates videogames and wanted this game to show its players how futile and pointless their hobby was. Amongst the challenges included in the game were a section where the player must hold a single button for up to an hour, a boss that takes over 1,000 punches to kill and of course the microphone section, where players are required to sing a verse of karaoke or talk whilst playing a pachislo minigame. The microphone section was replaced in later versions of the game once the microphone was dropped from the Famicom.

Zelda no Densetsu: The Hyrule Fantasy (cart/disk) (NES = The Legend of Zelda) - yell into the microphone to kill Pols Voice enemies. 

Legend of Zelda: The Hyrule Fantasy
Light Mythology: Palutena's Mirror
Kaiketsu Yanchamaru 

Support emulators
Mesen
VirtuaNES
Virtual Console

**Comment by AngelofMe** [comment]
More Famicom Microphone Games
https://www.famicomworld.com/forum/index.php?topic=2355.0

**Comment by SteveCraft27** [comment]
NES.emu Is Based On FCEUX. There Is No Famicom Controller II Microphone On FCEUX. It Requires To Request Famicom Controller II Microphone On FCEUX GitHub. FCEUX Uses Different FDS Sound Than Real FDS Sound From Nestopia, Real Famicom Disk System Hardware. This Can Be Heard On Link No Bouken - The Legend Of Zelda 2 (Japan) Death Sound.

**Comment by SteveCraft27** [comment]
NES.emu Based On FCEUX
![Screenshot_20220402-230206](https://user-images.githubusercontent.com/102736511/161401536-cd78d41e-5a0a-4f74-a525-2d2570ba09de.jpg)

**Comment by SteveCraft27** [comment]
And FDS Sound Difference (FCEUX Vs Real FDS)

FCEUX FDS Sound:

https://user-images.githubusercontent.com/102736511/161401554-3f67e272-f6b3-4c38-88ac-179258b2147d.mp4

Real FDS Sound (Tested On Nestopia UE)

https://user-images.githubusercontent.com/102736511/161401573-32a9189f-9744-47d9-9fce-b3a1ea33e5c9.mp4
