### ISSUE TITLE
[Question]: Can you add the updated Github Workflow?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#308]
### Describe your question

@Rakashazi I've updated the Github Workflow file, can you please add it in the next commit?

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks, will add it soon in the next commit.

**Comment by bladeoner** [comment]
@Rakashazi I don't know if you already downloaded the diff file, please use the following:
[update_workflow_v2.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8364596/update_workflow_v2.zip)

I've updated the NDK tools to the stable version of 24, updated some build tools including the Bundletool.
Besides the diff file you will also need the new jar file version 1.9.0 and remove version 1.8.2:
https://github.com/google/bundletool/releases

I did a succesful build run.

**Comment by Rakashazi** [comment]
Thanks, I added your initial workflow changes and will add the NDK & bundletool updates next commit.
