### ISSUE TITLE
[Feature request]: GBC.emu: Super Game Boy Colors For Game Boy Games

### ISSUE THREAD

**Issue by PatrickStar2007** [Rakashazi/emu-ex-plus-alpha#309]
### Describe the feature

Is It Possible To Update Core To Gambatte 0.5.0, Add GB Colorization: Auto, GBC, SGB, Internal, Custom, Add GB Colors: GB DMG, GB Light, GB Pocket, SGB 1-A, SGB 1-B, SGB 1-C, SGB 1-D, SGB 1-E, SGB 1-F, SGB 1-G, SGB 1-H, SGB 2-A, SGB 2-B, SGB 2-C, SGB 2-D, SGB 2-E, SGB 2-F, SGB 2-G, SGB 2-H, SGB 3-A, SGB 3-B, SGB 3-C, SGB 3-D, SGB 3-E, SGB 3-F, SGB 3-G, SGB 3-H, SGB 4-A, SGB 4-B, SGB 4-C, SGB 4-D, SGB 4-E, SGB 4-F, SGB 4-G, SGB 4-H, Add Emulated Hardware: (Auto, GB, SGB, GBC, GBA)

![156877673-e10e70b2-2a00-4d2f-ba1f-02feb728c679](https://user-images.githubusercontent.com/101215826/160292136-6f9d4d92-e5e2-4a56-8611-bbe2b1821dc9.jpg)
![156877675-e4671d4e-0e31-43bd-a5d2-6a1342ca259c](https://user-images.githubusercontent.com/101215826/160292147-7e06e0f6-9214-486b-97ce-628941667c4f.jpg)

GB Colorization:

OFF
![Screenshot_20220327-185133~2](https://user-images.githubusercontent.com/101215826/160292167-7cee54c5-0412-4532-b098-d7f46dad00ef.jpg)
GBC
![Screenshot_20220327-185210~2](https://user-images.githubusercontent.com/101215826/160292175-1d1b7fb1-25d6-4a9d-b45a-c9b620f9f84d.jpg)
SGB
![Screenshot_20220327-185215~2](https://user-images.githubusercontent.com/101215826/160292182-b29e6244-28d8-4012-9c84-80242972ef32.jpg)

**Comment by SopTheSop25** [comment]
Stop Spamming The Same Request. 1.5.59 Will NOT Be Released. 1.5.59 Is 1.5.58!
