### ISSUE TITLE
Commit b757c88 (VICE 2.4.20) broke C64.emu system definition (on Android, perhaps others)

### ISSUE THREAD

**Issue by rhester72** [Rakashazi/emu-ex-plus-alpha#31]
Steps to reproduce:

- Install C64.emu from commit b757c88 or later
- Clear data
- Start C64.emu, go to Options, note the system type is "C64 NTSC" by default
- Load any game/app/disk, allow it to start autobooting
- Return to Options, note the system type has changed to "C64 PAL"

(For what it's worth, I saw the same behavior when I ported my local C64.emu repo to 2.4.19 some time ago, but never figured out what's causing it.  The VICE system order list and enumeration hasn't changed.)

**Comment by Rakashazi** [comment]
This option is getting re-worked for 1.5.30. Previously it displayed the current C64 model in use and loading a save state could indirectly change it. It will now set the default model to use when no save state is loaded, and the C64 model can be changed at runtime from a new option via the main menu.
