### ISSUE TITLE
[Issue]: [MD.emu] Space Harrier 3-D (SMS), Out Run 3D (SMS), Maze Hunter 3D (SMS), Missile Defense 3D (SMS) Are Crashing / Not Responding MD.emu

### ISSUE THREAD

**Issue by SopTheSop29** [Rakashazi/emu-ex-plus-alpha#311]
### Describe the bug

Space Harrier 3-D (SMS)

https://user-images.githubusercontent.com/102625749/160856722-19c5607b-2509-44e5-9645-b8a4dbaf2774.mp4

Out Run 3D (SMS)

https://user-images.githubusercontent.com/102625749/160856896-3cb3a8a2-0b5b-4ecd-861a-a1b8399bc65c.mp4

Maze Hunter 3D (SMS)

https://user-images.githubusercontent.com/102625749/160857013-5000158c-5f63-40cd-8ff0-80586d29b336.mp4

Missile Defense 3D (SMS)

https://user-images.githubusercontent.com/102625749/160857273-02bceffd-367a-4d8a-ab6b-870f12b7efdb.mp4

### Steps to reproduce

Space Harrier 3-D (SMS), Out Run 3D (SMS), Maze Hunter 3D (SMS), Missile Defense 3D (SMS) Doesn't Work On MD.emu And Not Responding Since 1.5.57

### Expected behavior

It's May Be With PicoDrive Or Mednafen Core. MD.emu Need To Use With Genesis Plus GX Core. libmain.so Is A Emulator Core.

### Relevant log output

```shell
?
```

### Add screenshots

?

**Comment by SopTheSop29** [comment]
On 1.5.58 Build 4

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in last commit.
