### ISSUE TITLE
[Issue]: [MD.emu] Black Screen Display With Audio On Super Boy I. (Korea) (SMS), Super Boy II. (Korea) (SMS), Super Boy 3 (Korea) (SMS) Problem

### ISSUE THREAD

**Issue by SteveCraft27** [Rakashazi/emu-ex-plus-alpha#317]
### Describe the bug

Super Boy I. (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768205-32193ace-5afa-489f-ad8c-0f668a6d8d9b.mp4

Super Boy II. (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768348-2fe6191e-feb0-4c13-a3cf-4ab29d8ef363.mp4

Super Boy 3 (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768539-b6ef7618-23b9-470d-94db-c06e1ac92e9b.mp4

With Display (Tested On Genesis Plus GX 1.7.4)

Super Boy I. (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768735-897b82fa-13d8-45b0-9c89-23aeb8b10f12.mp4

Super Boy II. (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768868-35c687ee-8acf-461c-9997-afef02fa725f.mp4

Super Boy 3 (Korea) (SMS)

https://user-images.githubusercontent.com/102736511/161768942-aae204f3-229c-4ed0-9bb0-4b5e160ea5f9.mp4

### Steps to reproduce

I Found Super Boy I., Super Boy II., Super Boy 3 (Korean Master System) Game But It's Black Screen/Display With Audio On MD.emu.

### Expected behavior

It's Used With PicoDrive Core (MD/CD/32X/SMS). Super Boy I., Super Boy II., Super Boy 3 (Korean Master System) With Display Works On Genesis Plus GX 1.7.4. Genesis Plus GX Also Has SG-1000, Game Gear Support.

### Relevant log output

```shell
Super Boy I (Korea).sms
Super Boy II (Korea).sms
Super Boy 3 (Korea).sms
```

### Add screenshots

?

**Comment by SopTheSop29** [comment]
Those Are SG-1000 Games And It's Black Screen Display With Audio On Sega Genesis/MegaDrive Hardware. Sega Genesis/MegaDrive Uses Black Screen Display With Audio On SG-1000 Games. Master System / Game Gear Uses Dark Colors On SG-1000 Games. Master System Emulation On MD.emu Is Based On SMS Plus. It's Supposed That MD.emu Will Use With Genesis Plus GX (Update). .so Is A Emulator Core. libmain.so
SG-1000 Uses TMS VDP Color

**Comment by CraftFan22** [comment]
Those Are SG-1000 Games. It's Black Display Screen With Audio On Genesis / Mega Drive Hardware. SG-1000 Hardware Originaly Uses TMS9918. Master System / Game Gear Hardware Uses Dark Colors On SG-1000 Games (Backward Compatible, TMS9918-Compatible. Genesis / Mega Drive, 32X Hardware Has No TMS9918-Compatible And Will Not Display SG-1000, SC-3000, SF-7000 Games. Master System Emulation On MD.emu Is Based On SMS Plus. It's Supposed MD.emu Updated To Genesis Plus GX

**Comment by SteveCraft27** [comment]
It's Supposed On MD.emu NEW Update Based:

Genesis / Mega Drive **(Genesis Plus)** (arealdy)
Sega CD **(PicoDrive)** (arealdy)
Master System **(SMS Plus GX)** (Need To Update)
Game Gear **(Gearsystem)** (Need To Add Support)
SG-1000 **(Gearsystem)** (Need To Add Support)

**Comment by SteveCraft27** [comment]
https://github.com/drhelius/Gearsystem/releases/tag/gearsystem-3.4.1 Find Source code

**Comment by CraftFan22** [comment]
#160
