### ISSUE TITLE
Add Support for MiFi Controllers on iOS.

### ISSUE THREAD

**Issue by ReddestDream** [Rakashazi/emu-ex-plus-alpha#32]
Is it possible to add support for MiFi controllers to these emulators on iOS?

I'm aware that there aren't that many decent MiFi controllers out there, but it would would still be a nice addition. Thanks! ^_^

**Comment by thededman** [comment]
is there's by default. 
I have two mIf I controller and both work fine. 
In the emulator, select Key/Gamepad Input Setup.
Make sure your Bluetooth is on and the controller is on.
You will see ExtendedGamepad there see screenshot.
Here you can setup the controls. 
Enjoy. 
![image](https://cloud.githubusercontent.com/assets/5215424/8508623/90583214-2245-11e5-8c35-8b35ea1914d8.jpg)

**Comment by ReddestDream** [comment]
Oh, okay! Thank you! What a very pleasant surprise! ^_^

I was planning on buying one (a SteelSeries Stratus like the one you have), and I didn't see anywhere that these emulators had MiFi support! Thank you so much!
