### ISSUE TITLE
[NES.emu] Update Core To FCEUX 2.6.4 Version

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#321]
### Describe the feature

@Rakashazi FCEUX 2.6.4 Version Is Released. Is It Possible To Update Core To FCEUX 2.6.4 Version On NES.emu

**Comment by SteveCraft27** [comment]
https://sourceforge.net/projects/fceultra/files/latest/download

**Comment by Rakashazi** [comment]
Updated in last commit
