### ISSUE TITLE
[Issue]: [MD.emu] Garbled Graphics In California Games II (SMS)

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#322]
### Describe the bug

Garbled Graphics In California Games II (SMS)
![Screenshot_20220415-100253~2](https://user-images.githubusercontent.com/103258834/163544174-5f79d104-ba87-450b-af19-630a504d40c7.jpg)
![Screenshot_20220415-100301~2](https://user-images.githubusercontent.com/103258834/163544197-c88ede79-98bc-4ade-8d29-ae92f8a4b487.jpg)
Fixed (Tested On Genesis Plus GX 1.7.4)
![Screenshot_20220415-100409~2](https://user-images.githubusercontent.com/103258834/163544243-bbd13ba0-76ea-471a-9a93-ba008167060e.jpg)
![Screenshot_20220415-100413~2](https://user-images.githubusercontent.com/103258834/163544251-2772cadc-487c-40ec-84ed-0269793af8db.jpg)

### Steps to reproduce

Need To Fix That. I Found Garbled Graphics In California Games II (SMS) On MD.emu

### Expected behavior

?

### Relevant log output

```shell
?
```

### Add screenshots

?

**Comment by Rakashazi** [comment]
I tested this on my copy of the game but am not getting garbled graphics in the events. The MD5 hash of the rom is 5ac58b3a7fda23161ab1185b3ee797ac, does that match yours?

**Comment by HaroldCraft** [comment]
Sometimes Gets Garbled If I Change To NTSC Mode
