### ISSUE TITLE
[Feature request]: [MSX.emu] Add Crop Overscan In Video Options

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#323]
### Describe the feature

Add Crop Overscan In Video Options: Left & Right Lines, 256x224 to 256x192 (For MSX, MSX2, Colecovision)

### Add screenshots

256x224 to 256x192 (For MSX, MSX2, Colecovision)

256x224 (4:3)
![External (2)](https://user-images.githubusercontent.com/103258834/163633877-47ae8b9d-ab5d-4014-93f6-a1577a37e61b.png)

256x192 (4:3)
![External](https://user-images.githubusercontent.com/103258834/163633972-5b8f75ff-2682-483a-9821-4bbcb61553b4.png)

**Comment by Rakashazi** [comment]
This will be possible in a future update but due to the MSX having multiple video modes, the cropping will need to be percent-based or limited to specific modes.
