### ISSUE TITLE
[Question]: Would you like to add this stale job?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#324]
### Describe your question

Hi @Rakashazi I've added a new Github Workflow job which will tag PRs and Issues which haven't been updated in the last 60 days and leave a comment in those PRs and Issues.
After that it will check if the PR or Issue has not been updated in the last 5 days after tagging it and it will automatically close the Pr or the Issue. The job will run every sunday at 1:00 AM.
[mark-stale-pr-and-issue.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8499669/mark-stale-pr-and-issue.zip)

**Comment by Rakashazi** [comment]
Thanks, added it in last commit.
