### ISSUE TITLE
[Feature request]: MD.emu Sonic 3 & Knuckles?

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#327]
### Describe the feature

The Sonic 3 cartridge can be attached to an adapter on the Sonic & Knuckles cartridge, creating a combined game, Sonic 3 & Knuckles.Sonic the Hedgehog 2 can also be attached, allowing players to control Knuckles in Sonic 2 stages.

MD.emu how to get these games?

### Add screenshots

![Title_Screen_Sonic_3_and_Knuckles](https://user-images.githubusercontent.com/26894447/164614094-10d1e2ac-b432-426e-89c9-6a0555b28ee0.png)
![882-8821446_sonic-3-knuckles-sonic-the-hedgehog-3-cartridge](https://user-images.githubusercontent.com/26894447/164614400-70fb2a4c-b0ca-40db-8475-37360c17898e.png)
![Title_Screen_Knuckles_in_Sonic_2](https://user-images.githubusercontent.com/26894447/164615909-df6128f6-e50a-41f7-b288-182796d39a33.png)

**Comment by Rakashazi** [comment]
This [lock-on creator tool](http://info.sonicretro.org/Sonic_HackingWiz_Pro) can combine existing ROMs, or to combine manually use the copy command on Windows or cat command on Linux/MacOS from a terminal.
