### ISSUE TITLE
[Feature request]: Future Emulator Features

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#329]
### Describe the feature

I would like to request some features for some emulators. They were requested before but here they are

*Rewind Function (It is common now on some emus.)
*MD.emu Game Gear and SG-1000 support as well as updating the emu itself.
*MD.emu master system separate control mapping
*GB.emu update to Gambatte r571
*Netplay support

**Comment by Rakashazi** [comment]
Thanks for the requests. I've compiled a list of these and also previous requests in #330 to better organize everything.

**Comment by LeopoldCraft06** [comment]
> MD.emu Game Gear and SG-1000 support as well as updating the emu itself. 

.gg (Game Gear File Extension Format), .sg (SG-1000 File Extension Format)

> MD.emu master system separate control mapping

Master System Separate Control Mapping Is Button B, C (For SG-1000, SG-1000 II, Mark III, Master System, Master System II, Game Gear Emulation)

> GB.emu update to Gambatte r571 *Netplay support

GBC.emu update to **mGBA** Current Version
