### ISSUE TITLE
Using "Exit" Crashes splashboardd on iOS 8.4.

### ISSUE THREAD

**Issue by ReddestDream** [Rakashazi/emu-ex-plus-alpha#33]
Using the "Exit" option in any of the .emu emulators on jailbroken iOS 8.4 causes splashboardd to crash.

In the syslog, the reason is stated, "There doesn't appear to be a valid compiled storyboard."

This is a very minor crash (many AppStore Apps also cause splashboardd to crash), but I just though you should be aware.

I can send crashlogs and syslog if you would like. Thanks! ^_^

**Comment by Rakashazi** [comment]
The exit function on iOS is only for testing/debugging purposes because no iOS apps should ever exit by themselves according to the Apple developer documentation in the link below, so it's recommended to use the home button instead.

https://developer.apple.com/library/ios/qa/qa1561/_index.html
