### ISSUE TITLE
[Feature request]: MSX.emu C-BIOS 0.29

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#331]
### Describe the feature

Current version C-BIOS 0.23 (2009-01-04)
Latest version C-BIOS 0.29/0.29a (2018-09-23)
[C-BIOS Files](https://sourceforge.net/projects/cbios/files/cbios/)

**Comment by Rakashazi** [comment]
The newer C-BIOS versions have some boot issues with the version of BlueMSX used in MSX.emu, so they cannot be added until those are resolved. If you want to try them anyway then create entries for them in your Machines folder and select them in the system options.
