### ISSUE TITLE
[Issue]: emulator speed error

### ISSUE THREAD

**Issue by Guillermo4060** [Rakashazi/emu-ex-plus-alpha#341]
### Describe the bug

The emulators have jerks, especially the snes9x ex+ if they play games with more advanced graphics, for example, the kirby super star has speed errors and jerks if I would like it to be fixed because the emulators are good and are paid except for one but they have that error nothing more

### Steps to reproduce

To reproduce the error, load the kirby super star rom and you will see how it jerks

### Expected behavior

I would like the emulator not to present these errors since I have seen that others are better

**Comment by Yave-Yu** [comment]
This might be Snes9x itself's issue? Any SuperFX games are faster than it should too... If Snes9x core doesn't fix these issues, the Snes9x EX+ will remain too.
