### ISSUE TITLE
[Feature request]: MSX.emu ColecoVision Compatibility List

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#348]
### Describe the feature

ColecoVision Compatibility List

 Name Compatibility (98%) Notes

 Destructor (1984) (Coleco) 50% (2.8.1) Controls: Driving Controller emulation required

 Size: 32768, MD5: ec72a0e3bebe07ba631a8dcb750c1591,
 SH1: 35283c51f448d877625049266c0c4687bf57ab42

 Donkey Kong Arcade (Oct 25) (2005) (Eduardo Mello) 50% (2.8.1) Other: Requires Opcode Memory Extension emulation

 Size: 32768, MD5: e602e72072766ec2159cf13469e7ef15,
 SH1: 6a754455ec9f6f9811f2fb947c5ac750474dc8e8

 Dukes of Hazzard, The (1984) (Warner Bros) [!] 50% (2.8.1) Controls: Steering wheel emulation required

 Size: 32768, MD5: dbd4f21702be17775e84b2fb6c534c94,
 SH1: 162c7ad3266e02aa88983fa4ece7a77bc1cb9c7a

 Pac-Man Collection Demo by Opcode (2006) (PD) 10% (2.8.1) Stuck: Stuck on home screen

 Size: 32768, MD5: 0021c6f3f52cc6a55a3c14bab8a6339e,
 SH1: d6b67e8f43afe666cdd79a718ddf808e27d6512d

 Slither (1983) (Century II) 50% (2.8.1) Controls: Requires Roller Controller emulation

 Size: 16384, MD5: 7cdc148dff40389fa1ad012d4734ceed,
 SH1: b11de2476f867c7c4efb2977777e12fcb454f10b

 Super Action Controller Test Cartridge (1983) (Nuvatec) 50% (2.8.1) Controls: Requires Super Action Controller emulation

 Size: 16384, MD5: 1210396cb9af270285d25c66fa9c6f6a,
 SH1: 0c6840b7bc24a36529f0a80ccef85ee9f409a972

 Turbo (1982) (Sega) 50% (2.8.1) Controls: Steering wheel emulation required

 Size: 16384, MD5: f042ba432716b58d2f5858abcce81b9f,
 SH1: 732d1f3b2f24895a1f79d15d830aa989ea12fe5e

 Yolk's on You, The (1983) (20th Century Fox) (Prototype) 50% (2.8.1) Controls: Steering wheel emulation required

 Size: 16384, MD5: c10aaca46d063771339d3e5a0582baad,
 SH1: 9b5bfb69d37042d131a5c9576f927e09f44f9666

**Comment by AngelofMe** [comment]
ColecoVision Compatibility List
https://www-arts--union-ru.translate.goog/node/64?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp&_x_tr_sch=http
Список совместимости ColecoVision
http://www.arts-union.ru/node/64

**Comment by AngelofMe** [comment]
ColecoVision Compatibility List
https://www-arts--union-ru.translate.goog/node/64?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp&_x_tr_sch=http
Список совместимости ColecoVision
http://www.arts-union.ru/node/64

**Comment by soundsnow** [comment]
Controls: Driving Controller emulation required
Destructor (1984) (Coleco)  
Size: 32768, MD5: ec72a0e3bebe07ba631a8dcb750c1591,
SH1: 35283c51f448d877625049266c0c4687bf57ab42

Other: Requires Opcode Memory Extension emulation
Donkey Kong Arcade (Oct 25) (2005) (Eduardo Mello)  
Size: 32768, MD5: e602e72072766ec2159cf13469e7ef15,
SH1: 6a754455ec9f6f9811f2fb947c5ac750474dc8e8

Controls: Steering wheel emulation required
Dukes of Hazzard, The (1984) (Warner Bros) [!]  
Size: 32768, MD5: dbd4f21702be17775e84b2fb6c534c94,
SH1: 162c7ad3266e02aa88983fa4ece7a77bc1cb9c7a
Turbo (1982) (Sega)  
Size: 16384, MD5: f042ba432716b58d2f5858abcce81b9f,
SH1: 732d1f3b2f24895a1f79d15d830aa989ea12fe5e
Yolk's on You, The (1983) (20th Century Fox) (Prototype) 
Size: 16384, MD5: c10aaca46d063771339d3e5a0582baad,
SH1: 9b5bfb69d37042d131a5c9576f927e09f44f9666

Stuck: Stuck on home screen
Pac-Man Collection Demo by Opcode (2006) (PD)  
Size: 32768, MD5: 0021c6f3f52cc6a55a3c14bab8a6339e,
SH1: d6b67e8f43afe666cdd79a718ddf808e27d6512d

Controls: Requires Roller Controller emulation
Slither (1983) (Century II)  
Size: 16384, MD5: 7cdc148dff40389fa1ad012d4734ceed,
SH1: b11de2476f867c7c4efb2977777e12fcb454f10b

Controls: Requires Super Action Controller emulation
Super Action Controller Test Cartridge (1983) (Nuvatec)  
Size: 16384, MD5: 1210396cb9af270285d25c66fa9c6f6a,
SH1: 0c6840b7bc24a36529f0a80ccef85ee9f409a972
