### ISSUE TITLE
[NES.emu] Visible Lines & Crop 8 Pixels On Sides In Video Options

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#351]
### Describe the feature

Add in Options < Video < System-specific:

> Visible Lines

> Crop 8 Pixels On Sides

**Comment by Yave-Yu** [comment]
Agree, make it global, I'd like to show 240 lines on all games not just one game.

**Comment by Rakashazi** [comment]
I added a default visible lines option in the last commit.
