### ISSUE TITLE
[Feature request]: NES.emu title screen white index finger graphics postion error

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#353]
### Describe the feature

Hyper Olympic (Japan) (Genteiban!)
Hyper Olympic (Japan)
I tried select, same! 
We or I stay at START location
please run! why you don't move?
look timer
It cost much time 

### Add screenshots

![Hyper Olympic (Japan) (Genteiban!) 000](https://user-images.githubusercontent.com/26894447/166266060-f12c0673-0171-44b9-9e53-bf44f2d18192.png)
![Hyper Olympic (Japan) 000](https://user-images.githubusercontent.com/26894447/166266078-fe7639ef-d615-44b0-a9f2-adff6bd7fe0a.png)
![Hyper Olympic (Japan) (Genteiban!) 000](https://user-images.githubusercontent.com/26894447/166267310-26e7ac0a-e8e3-4304-b533-57b7919f7926.png)
![Hyper Olympic (Japan) 000](https://user-images.githubusercontent.com/26894447/166267315-96218ee3-7540-43a9-aa9c-15f9cb62e422.png)

**Comment by Rakashazi** [comment]
The Hyper Shot controller needed by this game is now automatically connected when loading it.
