### ISSUE TITLE
[Question]: which Linux distribution is needed to compile for android?

### ISSUE THREAD

**Issue by anjilite7** [Rakashazi/emu-ex-plus-alpha#354]
@Rakashazi Hi. Tell please which version of Android Studio, Linux etc do you use. I have tried different Linux distributions but every time different errors. Also, In 2022, is [this ](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/135#issuecomment-566444207)an up-to-date instruction?

/home/user/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace; did you mean '__signbit'?
Package emuframework was not found in the pkg-config search path.
Package imagine was not found in the pkg-config search path.
./src/genplus-gx/m68k/musashi/m68k.h:33:10: fatal error: 'imagine/logger/logger.h' file not found

**Comment by Rakashazi** [comment]
Hi @anjilite7, I'm using Gentoo Linux and the latest stable Android Studio. Those instructions should still be accurate but now it's also possible to build under Ubuntu Linux if you set up your system like the CI workflow in the .github directory.

**Comment by anjilite7** [comment]
> also possible to build under Ubuntu Linux if you set up your system like the CI workflow in the .github directory.

I suppose i builded. But only got MdEmu-release.aab. Where is apk? I tried to find in whole project folder but not found.
