### ISSUE TITLE
[Feature request]: Is it possible to do this on video ratio?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#357]
Make it automaticly, for example:
If video resolution is 256x224, ratio use 8:7; if 256x240, ratio use 16:15.
This option may call somehow “native”.

**Comment by Yave-Yu** [comment]
1.5.59 come out, but I'd like that visible lines option on globle video setting, rather than just control one game.

**Comment by Rakashazi** [comment]
Sure, I can add a global version of the 240 lines option in the next update.

About the aspect ratio, I think I'll keep the aspect ratio settings as they are but add another option to apply correction when not using 224 lines, so 8:7 will map to 16:15 like in your example.

**Comment by Rakashazi** [comment]
Ok, I added a default visible lines option so you can use 240 lines globally. There's also a correct line aspect ratio option that will scale the aspect ratio based on the visible lines like this: (video aspect ratio) * (224 / visible lines). So from the previous example: (8 / 7) * (224 / 240) = 16 / 15.
