### ISSUE TITLE
[Feature request]: NES.emu SPACE SHADOW with HYPER SHOT - best famicom lightgun controller & game

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#361]
### Describe the feature

There are a total of five stages in this game. You have access to a machine-gun weapon, as well as grenades. However, ammunition for both weapons is limited. If you run out of ammo at any point in the game, you will lose. Therefore, it is important to conserve your ammunition throughout the game.

Space Shadow was the pack-in game for the Bandai Hyper Shot, a sub-machine gun shaped Light Gun for the Famicom. It was essentially a modified Zapper with rapid fire capability. It also had a direction pad built into it, allowing you to both shoot and move. Despite the fact that Light Gun games tended to do far better in the US, neither the Hyper Shot nor this game were ever released outside of Japan. 

### Add screenshots

![s-l400](https://user-images.githubusercontent.com/26894447/167290834-b190eaed-b376-4b7d-9d40-5222d6ba7a2a.jpg)
![s-l400(2)](https://user-images.githubusercontent.com/26894447/167290836-6e7bbe83-7156-47d6-9143-da1b9be5990e.jpg)
![s-l400(1)](https://user-images.githubusercontent.com/26894447/167290840-1ce66e85-259a-46ee-9af4-507f63261bc5.jpg)
![space-shadow 0](https://user-images.githubusercontent.com/26894447/167290939-3df7979a-db90-4149-b8a5-29a285a95c3f.png)
![images](https://user-images.githubusercontent.com/26894447/167290940-08b30be5-c0af-4a26-88cb-5cba064c7d53.png)

**Comment by Rakashazi** [comment]
The Hyper Shot light gun is now automatically connected to the system when loading Space Shadow.
