### ISSUE TITLE
[Question]: Can you add this updated Github Workflow?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#365]
### Describe your question

@Rakashazi I saw your comment in https://github.com/Rakashazi/emu-ex-plus-alpha/issues/354 how to compile the APK files.

In the Github Workflow I patched a file to do this, so I've updated the Github Workflow and removed the patch:
[update_github_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/8646820/update_github_workflow.zip)

Can you add the updated Github workflow?

Thanks in advance.

**Comment by Rakashazi** [comment]
@bladeoner Thanks, added it in the last commit
