### ISSUE TITLE
[Question]: Is it possible to add Debug to the Android build?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#366]
### Describe your question

@Rakashazi I want to ask if it is possible to add a Debug build so we can remove the other patch that is used in the Github Workflow?

I did some attempts myself to get it working but I didn't succeed.

The patch is applied to the following file at this moment: imagine/make/gradle/app/build.gradle

It removes:
    // set code signing variables in ~/.gradle/gradle.properties
    signingConfigs {
        release {
            storeFile file(ANDROID_KEY_STORE)
            storePassword ANDROID_KEY_STORE_PASSWORD
            keyAlias ANDROID_KEY_ALIAS
            keyPassword ANDROID_KEY_PASSWORD
        }
    }

And then it changes:
Old value: signingConfig signingConfigs.**release**
New value: signingConfig signingConfigs.**debug**

Thanks in advance.

**Comment by Rakashazi** [comment]
Sure, I'll look into it adding flag or parameter to the build system to sign with a debug key in a future commit.

**Comment by Rakashazi** [comment]
@bladeoner No problem, I was able to fit this into the last commit and looks like the builds finished successfully.

**Comment by bladeoner** [comment]
@Rakashazi thank you!
