### ISSUE TITLE
[Feature request]: MSX.emu MD.emu I can't play almost all ColecoVision games

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#373]
### Describe the feature

ColecoVision controller pleeease
MSX keyboard isn't compatible with CopecoVision games
ColecoVision controller buttons
123456789*0#LR
a few of them can be played directly
but others not good
they told me select skill level
i tried every MSX keyboard keys, it's useless
if you play Facemaker (USA), you'll need a ColecoVision controller
not AB and keyboard
portrait
1|2|3
4|5|6
7|8|9
star|0|#
D-Pad|L|R
landscape
1|2|3|4|5|6|7|8|9
D-Pad|star|0|#|L|R
sorry that symbol can't be visible so i use"star"

standard Sega Control Pad
SG-1000 II, Mark III, Master System, Game Gear
D-Pad|START|1|2

### Add screenshots

![Screenshot_20220510-175237_Trebuchet](https://user-images.githubusercontent.com/26894447/167611151-3c29fdde-773a-433f-8924-0befa8ffa30f.png)
![Screenshot_20220510-184059_NumPadPlayer](https://user-images.githubusercontent.com/26894447/167611170-6f208c2e-d672-4446-accc-29e2451110bf.png)
![Screenshot_20220510-183423_Trebuchet](https://user-images.githubusercontent.com/26894447/167611181-36db2cf7-c3af-4de2-9f84-e73622259492.png)
![Screenshot_20220510-183509_Trebuchet](https://user-images.githubusercontent.com/26894447/167611190-87da67da-5a13-49cb-954b-4e82773b2c19.png)
![Screenshot_20220510-183734_Trebuchet](https://user-images.githubusercontent.com/26894447/167611197-c6004f02-cb9b-4409-985d-1657f866c402.png)
![Screenshot_20220510-175414_Trebuchet](https://user-images.githubusercontent.com/26894447/167611218-5163a315-f6f6-434d-ab72-ea762c9009de.png)

**Comment by AngelofMe** [comment]
sega 8 bit console controllers no mode button

**Comment by AngelofMe** [comment]
sega 8 bit console controllers no mode button

**Comment by Rakashazi** [comment]
I fixed the Coleco number key mapping on the keyboard in the last commit. A dedicated ColecoVision controller will come in a later update.

**Comment by AngelofMe** [comment]
that's not good, no *
you need numpad, left and right buttons at the same time to play some games
so I upload screenshots let you know what's right
and HB button is unnecessary for ColecoVision games
many games need * to play

**Comment by AngelofMe** [comment]
that's not good, no *
you need numpad, left and right buttons at the same time to play some games
so I upload screenshots let you know what's right
and HB button is unnecessary for ColecoVision games
many games need * to play
