### ISSUE TITLE
[Issue]: 2600.emu isn't responding BUG

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#375]
### Describe the bug

game: 
Karate (USA)
Air Raiders (USA)
three times

### Steps to reproduce

*

### Expected behavior

*

### Add screenshots

![Screenshot_20220510-204108_Trebuchet](https://user-images.githubusercontent.com/26894447/167630958-96e4d620-08da-42b7-adf0-958fb947006b.png)
![Screenshot_20220510-205041_Trebuchet](https://user-images.githubusercontent.com/26894447/167632541-d028b286-6acf-450d-9357-6638b150fae6.png)

**Comment by Rakashazi** [comment]
Thanks for the report, this should be fixed in the last commit.
