### ISSUE TITLE
Add hard reset option to NES.emu

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#39]
The Reset menu item in NES.emu seems to be for a soft reset, equivalent to pressing the Reset button on a real console. It would be helpful to have a hard reset option too, equivalent to powering a real console off then on again.

Certain multi-game cartridges need a hard reset to return to the game selection screen. Currently (on Android NES.emu) to get the game selection screen to appear you have to choose the ROM again from Load Game or Recent Games, and choose not to use the auto-saved state.

Various Codemasters/Camerica games are like that, e.g. 
Quattro Adventure (USA) (Unl).zip
Quattro Arcade (USA) (Unl).zip
Quattro Sports (USA) (Unl).zip
Super Sports Challenge (Europe) (Unl) (Plug-Thru Cart).zip

**Comment by Rakashazi** [comment]
Support for soft & hard resets was added and will be included in the 1.5.30 release.
