### ISSUE TITLE
[Feature request]: MD.emu Remove 3 button gamepad "mode button" 

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#399]
### Describe the feature

mode - It's a 6 button controller button
you made a big mistake
i use 3 button gamepad, why i need a useless mode button
display an unnecessary "mode" picture
3 button gamepad to 3 button gamepad?

**Comment by Rakashazi** [comment]
The mode button is now hidden when not needed in the last commit.
