### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by Blad3forc3** [Rakashazi/emu-ex-plus-alpha#402]
### Describe the bug

APKs wont install on nvidia shield

### Steps to reproduce

Try to sideload any app

### Expected behavior

Install app

**Comment by guilhermeoc97** [comment]
Does this only happen with the emulators' APKs? What version of Android you're running (and its' API level)?

**Comment by Blad3forc3** [comment]
Yes just with the emulators apks. It's the latest version for the shield pro Android 11
