### ISSUE TITLE
[GBA.emu request] Add a save type option?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#403]
Saving in official game is no problem, but in bootleg like Pocket Monster - Emerald (known as Chinese Emerald) will fail. I remember VBA-M standalone could set save type manually, so it's nice to have in GBA.emu ֍
![Pocket Monster - Pokemon Emerald 000](https://user-images.githubusercontent.com/54294476/168743232-8f52c397-c6fd-4465-b275-729eb4276536.png)

**Comment by Rakashazi** [comment]
I added the ability to set the save type under console options in the last commit.
