### ISSUE TITLE
[Issue]: Black bar appears in place of status bar in horizontal orientation (Pixel 4a, Android 12)

### ISSUE THREAD

**Issue by Bruxism** [Rakashazi/emu-ex-plus-alpha#406]
### Describe the bug

A black bar has appeared in the SNES app in horizontal orientation in place of where the status bar is in vertical orientation after transitioning from Android 11 to Android 12 on the Google Pixel 4a.

### Steps to reproduce

Use Pixel 4a with Android 12 while set to horizontal orientation.

### Expected behavior

The expected behavior is that the app takes up the full screen.

### Add screenshots

![SNES Ex+ Black Bar](https://user-images.githubusercontent.com/38876789/169591104-662a59d6-665f-4cd9-99da-2fc61a47e07f.png)

**Comment by Rakashazi** [comment]
In Options -> GUI, what's set for "Dim OS UI", "Hide OS Navigation", and "Hide Status Bar" ?

**Comment by Bruxism** [comment]
Dim OS UI: In Emu
Hide OS Navigation: In Emu
Hide Status Bar: In Emu

**Comment by Rakashazi** [comment]
Thanks for the info, after doing some research it looks like the phone's camera cutout is the reason for the black bar since that region isn't used to layout the app. I'll need to add support for some new APIs to use it and will try to fit it in 1.5.60 depending on how complex the implementation is.

**Comment by Bruxism** [comment]
> Thanks for the info, after doing some research it looks like the phone's camera cutout is the reason for the black bar since that region isn't used to layout the app. I'll need to add support for some new APIs to use it and will try to fit it in 1.5.60 depending on how complex the implementation is.

I'm excited to learn how to fix this. I've done some bash scripting and have followed a Python book before. This particular problem feels to be something meaningful to work towards contributing towards fixing because I feel like I was the first to fall upon it and report it, and it really affected how the app felt after the bar appeared after updating Android.

Plus, I have a friend that works on and loves C, and I think that we could learn a lot from this together. They seemed really impressed with your work.

Pardon me for this newbie question, but could you point me in the direction of related learning materials for this problem so that I may come to comprehend how to contribute to fixing this problem, please?

**Comment by Rakashazi** [comment]
Sure, the main documentation for handling display cutouts is here:

https://developer.android.com/guide/topics/display-cutout

However, some work is needed to get the app displaying edge-to-edge first as shown here:

https://developer.android.com/training/gestures/edge-to-edge

These are for Android's Java/Kotlin API so everything needs to be passed up to native code and implemented with the app's custom gui system. I've been looking into getting edge-to-edge working for a little while now and may have an implementation ready soon so stay tuned.
