### ISSUE TITLE
[MD.emu] [SMS]: TMS9918 Video Mode

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#416]
### Describe the feature

Master System is backward compatible with SG-1000 / SC-3000

Is it possible to add TMS9918 Video Mode support.

I renamed .sg to .sms file and I tried to play TMS9918 Master System games on MD.emu but it's black screen display.

TMS9918 Master System games:

- Congo Bongo (SG-1000)
- Wonder Boy (SG-1000)
- Back Panic (SG-1000)
- Bomb Jack (SG-1000)
- Bomberman Special (Taiwan) (SG-1000)
- Castle, The (Japan) (SG-1000)
- Lode Runner (SG-1000)
- Championship Lode Runner (SG-1000)
- Dr. Hello (Korea) (SG-1000)
- Super Bio Man I (Korea) (SG-1000)
- Super Boy I. (Korea) (SG-1000)
- Super Boy II. (Korea) (SG-1000)
- Super Boy 3 (Korea) (SG-1000)
- Super Bubble Bobble (Korea) (SG-1000)
- Loretta no Shouzou (SG-1000)

[SG-1000 Games (.sms) Download](https://drive.google.com/file/d/12wc_FpV2iAgMygu3c5oP9KA_H8dz-45J/view?usp=drivesdk)

**Comment by Squidward22** [comment]
#160

**Comment by SopTheSop27** [comment]
with specific Master System VDP for Master System / Mark III / Master System II emulation.

It requires update MD.emu to Genesis Plus GX 1.7.4 (current GIT version)
