### ISSUE TITLE
[Feature request]: MD.emu all Korea games black screen

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#426]
### Describe the feature

![Screenshot_20220605-120800_ZArchiver](https://user-images.githubusercontent.com/26894447/172034699-f4a3d6be-844f-448e-8f16-74b17afeb90a.png)
![Screenshot_20220605-121004_ZArchiver](https://user-images.githubusercontent.com/26894447/172034703-4ab8b8d3-9f8e-4a7b-acd1-1a303ef93ac5.png)

**Comment by AngelofMe** [comment]
they all can be played, but i can't see everything

**Comment by Squidward22** [comment]
No. All TMS9918 Games are black screen. Mark III / Master System is backward compatibility with TMS9918, SG-1000. Genesis / Mega Drive doesn't support TMS9918 mode.

**Comment by Squidward22** [comment]
No. All TMS9918 Games are black screen. Mark III / Master System is backward compatibility with TMS9918, SG-1000. Genesis / Mega Drive doesn't support TMS9918 mode

TMS9918 Original:
![Super Boy I (1989)(Zemina)001](https://user-images.githubusercontent.com/105673473/172063619-b4ae8d03-cb55-4b91-a6ef-03559742f81e.png)
Master System VDP:
![Super Boy I (1989)(Zemina)000](https://user-images.githubusercontent.com/105673473/172063637-4729bfe4-2b9e-4e0f-823c-46dc6dc57516.png)
