### ISSUE TITLE
[Issue]: NES.emu Adventures of Panzer, The (World) (Aftermarket) (Unl)

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#427]
### Describe the bug

![Adventures of Panzer, The (World) (Aftermarket) (Unl) 000](https://user-images.githubusercontent.com/26894447/172054044-b1feb56e-eb02-4aa9-a3c7-6784b2000096.png)
![Adventures of Panzer, The (World) (Aftermarket) (Unl) 001](https://user-images.githubusercontent.com/26894447/172054048-b06903c2-34a0-4128-9262-0435acb2e998.png)

### Steps to reproduce

*

### Expected behavior

*

**Comment by AngelofMe** [comment]
a similar bug
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/353

**Comment by AngelofMe** [comment]
a similar bug
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/353

**Comment by Rakashazi** [comment]
This looks like a problem with the ROM. I tested the demo version 1.2 of this game with no issues: https://9panzer.itch.io/the-adventures-of-panzer
