### ISSUE TITLE
Show numeric key codes when mapping unknown keys

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#43]
If the emulator doesn't have a string for a key name, it shows that key as Unknown when mapping it. Having possibly several Unknown entries in the list could be confusing. So it would be helpful to also show the numeric key code, e.g. "Unknown (0x55)"

The ipega PG-9025 Bluetooth controller has media keys which are currently shown as Unknown:
  KEYCODE_MEDIA_PLAY_PAUSE (0x55)
  KEYCODE_MEDIA_PREVIOUS (0x58)
  KEYCODE_MEDIA_NEXT (0x57)

**Comment by Rakashazi** [comment]
Names for the media keys, as well as displaying key codes for unknown keys has been committed and will be included in the 1.5.30 release.
