### ISSUE TITLE
[NES.emu] add .unif FILE EXTENSION FORMAT

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#430]
### Describe the feature

@Rakashazi is it possible to add .unif FILE EXTENSION FORMAT on NES.emu

I found .unif NES games but it's not visible. **FCEUX supports .nes, .fds, .unf, .unif FILE EXTENSION FORMAT**

[Download .unif NES Games (.unif file)](https://drive.google.com/file/d/11Ldb33OnSFnRuIrbtN0ZKHVtvO9lsuuD/view?usp=drivesdk)

**Comment by Rakashazi** [comment]
.unif files are now detected in the last commit.
