### ISSUE TITLE
For a curious on GBA.emu's core

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#432]
The VBA-M core is always have low volume on channel 4 (Noise channel), that cause some music's drum (such as Pokémon FireRed and Emerald's song) couldn't be heard clearly, so is it possible to make channel 4's volume louder?

**Comment by Rakashazi** [comment]
Since increasing the noise volume can introduce clipping or audio distortion with the current implementation, I instead added separate volumes for the GBA and GB sound hardware in the last commit. By slightly lowering the GBA's PCM volume it will emphasize the GB sounds including the noise channel.

**Comment by Yave-Yu** [comment]
I see.
I've seen a foobar2000 GSF Plugin that uses VBA-M as audio core before, it boosts channel 4 so drums could hear clearly. https://foobar2000.xrea.jp/up/files/up1284.7z Because this, I came here and sent this issue ֍
