### ISSUE TITLE
[MD.emu] display aspect ratio on Genesis / Mega Drive Emulation should not be 4:3

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#446]
### Describe the feature

Genesis/Mega Drive 320x224 uses 10:7 Aspect Ratio, 256x224 uses 8:7 Aspect Ratio

320x224 (10:7)
![Sonic the Hedgehog (USA, Europe) 000](https://user-images.githubusercontent.com/105673473/173841962-66cd26b7-6978-4c13-8325-ec91921cf2ce.png)
256x224 (8:7)
![Mega Man - The Wily Wars (Europe) 000](https://user-images.githubusercontent.com/105673473/173842226-1ec9c7ae-85aa-4e85-b062-d14f38189d31.png)

Need to add **"Native"** Aspect Ratio in Video Options

320x224 uses 10:7 (Genesis / Mega Drive)
256x224 uses 8:7 (Genesis / Mega Drive, Master System, SG-1000 / SC-3000)
256x192 uses 4:3 (Master System, SG-1000 / SC-3000)
160x144 uses 10:9 (Game Gear)

**Comment by Rakashazi** [comment]
The current behavior is correct because the system doesn't use square pixels on its output signal and the aspect ratio doesn't change when games switch from 320 to 256 horizontal pixels. What you're looking for is Options -> Video -> Content Zoom -> Integer-only.

**Comment by Squidward22** [comment]
I looking for 1:1 PAR (Pixel aspect ratio) / Pixel Perfect aspect ratio from RetroArch. Options -> Video -> Aspect Ratio -> Pixel Perfect

1:1 PAR (Pixel aspect ratio) for example: if it's 320x240, then uses 4:3 display aspect ratio, if it's 256x240, then uses 16:15 display aspect ratio, if it's 256x192, then uses 4:3 display aspect ratio, if it's 256x224, then uses 8:7 display apsect ratio, If it's 320x224, then uses 10:7 display apsect ratio. It's called "Pixel Perfect" Aspect Ratio.
[MSX.emu] MSX, MSX2, MSX2+, Colecovision emulation Resolution are 256x224 (8:7 display aspect ratio).
