### ISSUE TITLE
MSX.emu machine name path too short

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#45]
If the name of a MSX.emu machine folder is too long, it gets truncated and isn't saved or accessed correctly. For example, I put "MSX2 - Daewoo Zemmix CPG-120 Normal/" in /storage/sdcard0/MSX.emu/Machines/ and it gets truncated to "MSX2 - Daewoo Zemmix CP". I've tried increasing optionMachineNameStr's size and forcing optionMachineName's size with no luck. Renaming the folder and editing config.ini appropriately works, but is kind of annoying.

**Comment by xperia64** [comment]
I found that sizeof(optionMachineName) in EmuMenuViews.hh's SystemOptionView's select() function always returns 24, so that looks to be the issue. I'm not sure how to fix besides using an arbitrarily large buffer size.

**Comment by Rakashazi** [comment]
Thanks for spotting that. I fixed the destination parameter for that call and updated various instances of string_copy to use the newer version for fixed size arrays so the size parameter can be omitted.
