### ISSUE TITLE
[Issue]: NES.emu Zhan Guo Si Chuan Sheng (Asia) (Idea-Tek) (Unl)

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#457]
### Describe the bug

NES.emu
![Zhan Guo Si Chuan Sheng (Asia) (Idea-Tek) (Unl) 000](https://user-images.githubusercontent.com/26894447/174207290-39b54f76-ebd2-4cfd-926a-a7dcb5f51877.png)

### Steps to reproduce

You know how to fix

### Expected behavior

FCEUmm, Mesen
![Zhan Guo Si Chuan Sheng (Asia) (Idea-Tek) (Unl)-220617-095202](https://user-images.githubusercontent.com/26894447/174207159-bfd0298d-d660-4439-ae4a-456d50aa660c.png)

**Comment by Rakashazi** [comment]
I updated a few mappers in the last commit including a fix for this game.
