### ISSUE TITLE
[MD.emu] 32x, Game Gear, Master System II, SG-1000, SC-3000, SF-7000, ColecoVision, Pico support?

### ISSUE THREAD

**Issue by CraftFan23** [Rakashazi/emu-ex-plus-alpha#464]
### Describe the feature

@Rakashazi Is it possible to add 32x, Game Gear, Master System II, SG-1000, SC-3000, SF-7000, ColecoVision, Pico support on MD.emu next update?

Emulator core base:

32x **PicoDrive (1.99)**
Game Gear **Genesis Plus GX (1.7.4)**
Master System II **Genesis Plus GX (1.7.4)**
SG-1000 **Genesis Plus GX (1.7.4)**
SC-3000 **blueMSX**
SF-7000 **blueMSX**
ColecoVision **blueMSX**
Pico **Genesis Plus GX (1.7.4)**

**Comment by Squidward22** [comment]
ColecoVision is already on MSX.emu

Genesis Plus GX has no 32X, SC-3000, SF-7000.
