### ISSUE TITLE
[Question]: Is there anything we can do about the stale job to improve it?

### ISSUE THREAD

**Issue by IdiotBlueMage** [Rakashazi/emu-ex-plus-alpha#465]
### Describe your question

This idea was on the right track as far as removing the unclosed items from Issues, but after a while it now results in what is apparently a resident sockpuppet brigade abusing it by referencing their own stale issues that reference the same subject.  By now it looks like almost the entirety of the issues tab is taken up by one user, and the others are mostly another one of the same person's accounts.  It results in bug reports drowning in a sea of request spam that I can barely read through.

**Comment by guilhermeoc97** [comment]
I'd usually tell you to report them to GitHub, I know I did...
Sucks that apparently they're not interested in following up with their users' requests.
Maybe lock the issues to contributors and only accept new issues from them?
Of course that kinda neglects people that don't code and people that never contributed here, but there must be a way for these people to contribute without direct access to issues.

**Comment by Rakashazi** [comment]
I'll start to clean up the spam/repeated issues today and look into what can be done if it continues to be a problem. Hopefully we can continue to keep the issues tab open to everyone.
