### ISSUE TITLE
[Feature request]: [PCE.emu]: add Show Horizontal Overscan, Initial Scanline, Last Scanline in Console Options, Default Video Options

### ISSUE THREAD

**Issue by ghost** [Rakashazi/emu-ex-plus-alpha#470]
### Describe the feature

![Screenshot_20220702-155807](https://user-images.githubusercontent.com/107685666/177004033-ca78ba12-8a11-4566-b704-2e9bd06941ea.jpg)

**Comment by Rakashazi** [comment]
Scanline video options were added in the last commit.
