### ISSUE TITLE
[Question]: Can you add the updated stale job?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#471]
### Describe your question

Hi @Rakashazi I hope you are doing fine, I've updated the stale job to close stale issues and PR's after 3 days instead of 5 which makes more sense to the days the job runs.

Can you add the updated stale job?
[update_stale_job.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9038621/update_stale_job.zip)

Thanks in advance

**Comment by Rakashazi** [comment]
Thanks @bladeoner, hope you're also doing well. I've added this in the last commit.

**Comment by bladeoner** [comment]
@Rakashazi I'm fine thank you and thanks for adding the commit.
