### ISSUE TITLE
When scrolling through menus, stop or pause at top and bottom

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#48]
When using a gamepad to scroll through emulator menus (on Android), pressing and holding up or down causes the highlighted item to move up or down quickly. On reaching the bottom the highlight quickly loops around to the top if you didn't release the button at exactly the right time. And vice versa on reaching the top.

Some suggestions which could make that a bit more user-friendly:
- Slow down the repeat rate or make it user-configurable.
- When the highlight reaches the top or bottom, require the user to release and press the button again before looping around to the other end.
- When the highlight reaches the top/bottom, only loop around after a small delay (half a second say) to give the user enough time to release the button.

**Comment by Rakashazi** [comment]
Closing out some old issues, suggestion #2 was implemented.
