### ISSUE TITLE
NEO.emu (android-15) will not install

### ISSUE THREAD

**Issue by rhester72** [Rakashazi/emu-ex-plus-alpha#49]
Not sure which change caused it, but the trunk pull compiles fine as android-15 but refuses to install (no error given from Android).

**Comment by Rakashazi** [comment]
android-15 only includes X86 and ARM64 binaries by default while the ARMv7 binary is in android-9. Were you trying to install android-15 on an ARMv7 device?

**Comment by rhester72** [comment]
No, installation was on the Shield Android TV with 64-bit X1 processor running Lollipop.  All other emulators compiled with android-15 install and work fine.  I will try to track down which specific change broke this.

By the way, conversely, installing android-9 compiled binaries on the same device results in a lot of breakage - menus don't paint and other oddities, even though the underlying emulation code is clearly running.  Is this expected behavior?

**Comment by rhester72** [comment]
*LOL*  That was easy.

As of commit 188e2ef283571ed3c3dc121b382def759cc8f524 (and beyond),
NEO.emu/android-15.mk and NEO.emu/android-release-15.mk need this line:

android_arch := x86

altered to this:

android_arch := arm64 x86

for presumably obvious reasons <G>

**Comment by Rakashazi** [comment]
Currently the android-15 APK only includes X86 binaries because it's still more efficient to use the assembly code in the ARMv7 build even on ARM64 devices. There shouldn't be any compatibility issues installing the android-9 APK on such devices.
