### ISSUE TITLE
[Feature request]: GBC.emu Pocket Family GB 2 (Japan) & Pocket Family GB (Japan) (SGB Enhanced)

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#498]
### Describe the feature

You deleted that test results issue, so i don't remember which games working for gambatte but GBC.emu not.
it is/they are gambatte supported game(s)
i don't know what game(s) i should submit
i'm sorry, that's your fault
did you remember? 
I uninstalled GBC.emu, so i won't test gb/gbc files again

**Comment by Rakashazi** [comment]
I appreciate the test reports and have made note of the non-working games but please don't spam issues with little or no relevant information, as these are not helpful and make browsing the issues tab more difficult.

**Comment by SteveCraft28** [comment]
Gambatte emulation isn't accuracy. I test MBC6, MBC7, Pocket Camera ROMs, Sonic 3D Blast 5 (Unl) Error loading
