### ISSUE TITLE
C64.emu will not allow soft/hard reset selection

### ISSUE THREAD

**Issue by rhester72** [Rakashazi/emu-ex-plus-alpha#50]
After the soft/hard reset change, other emulators (i.e. 2600.emu) supports selection of soft or hard reset, but C64.emu (despite having support for it) does not - the dialog simply says "Really Reset?".

**Comment by Rakashazi** [comment]
C64.emu didn't define EmuSystem::hasResetModes = true, fixed in latest commit.
