### ISSUE TITLE
[Issue]: [NES.emu] Some Famicom Disk System games do not load when prompted to switch disk sides

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [Rakashazi/emu-ex-plus-alpha#504]
### Describe the bug

Another problem that I encountered, is that NES.emu when loading Famicom Disk System games, apperently when the game asks to switch disk sides to Disk 1 Side A or B, going to the menu and switching disk sides, the game won't load after switching. This is a problem in NES.emu when playing with a Bluetooth controller like the SN30 Pro+.

Games that have this problem:
*Neunzehn - 19
*Aspic - Majaou no Noroi
*Idol Hotline - Nakayama Miho no Tokimeki High School
*Fairytale
*Pulsar no Hikari

### Steps to reproduce

1. Loaded a Famicom Disk System game
2. Waiting for the game to load
3. When the prompts for inserting side B appears, I go to the menu and choose Disk 1 Side B
4. After switch disk sides, the game still stuck to the set side b screen. 

This should be fixed since I think the Bluetooth controller is a problem, so I turned off the Bluetooth and did the same process but now it loads, although I have to reconnect my controller again. 

### Expected behavior

It is fixed with several disk system games since the others work.

**Comment by Rakashazi** [comment]
Thanks for the report. I don't think the Bluetooth controller is the direct cause, but it's the game itself not checking for a new disk when they're swapped quickly. When you change disk sides from the menu it first ejects the current disk, runs the emulation for 1 second so the game can detect there's no disk present, and then the new disk side is actually inserted.

I've increased time in between ejecting and inserting the disk now to 2 seconds which seems to fix all the games you listed. If any more pop up let me know, but a workaround in case it does happen is to manually eject the disk, go back to the emulation for a few seconds, then go back to the menu and set the disk side.
