### ISSUE TITLE
[GBA.emu] ADD .gb, .gbc, .sgb, .cgb, .dmg FILE EXTENSION

### ISSUE THREAD

**Issue by Squidward22** [Rakashazi/emu-ex-plus-alpha#506]
### Describe the feature

@Rakashazi is it possible to add .gb, .gbc, .sgb, .cgb, .dmg file extension [GBA.emu]. .gb, .gbc, .sgb, .cgb, .dmg file extension are available on VBA-M

**Comment by Rakashazi** [comment]
GB and GBC isn't supported on GBA.emu, it only uses the GBA core from VBA-M.
