### ISSUE TITLE
C64.emu PAL/NTSC selection still broken under System & IO Control

### ISSUE THREAD

**Issue by rhester72** [Rakashazi/emu-ex-plus-alpha#51]
The default setting works properly and as expected, but System & IO Control/C64 Model still reflects the wrong model (speaking of, how is that intended to be used - i.e. how does it differ from setting the default model...is it possible this is now a redundant/unused option?).

**Comment by Rakashazi** [comment]
Closing out some old issues, should be addressed from updates made in newer versions.
