### ISSUE TITLE
[Feature Request] Support for retroachievements.org Snes9x EX+

### ISSUE THREAD

**Issue by dochankpin** [Rakashazi/emu-ex-plus-alpha#510]
### Describe the feature

Hello guys, greetings!
I'm sending this message to the emulator developers: Snes9x EX+ .
Is it possible for you to add support for game achievements?

Through website Support:
retroachievements.org

It would be nice, because the emulator is already very good.
And with retroachievements support the emulator would be PERFECT!
Thank you very much in advance for everyone's attention and understanding.
Thanks again and CONGRATULATIONS to the developers!
You are very good!
See you later, bye.
😃👍

**Comment by Rakashazi** [comment]
Thanks for the feedback, this is on my list of requested enhancements #330 and I'll look into it for a future update.

**Comment by dochankpin** [comment]
Thank you very very much friend 👍
