### ISSUE TITLE
[Issue]: Space Gun Unplayable

### ISSUE THREAD

**Issue by section-leader** [Rakashazi/emu-ex-plus-alpha#513]
### Describe the bug

While Space Gun loads and generally works, the controls are broken. Pressing the fire button works as well as selecting which special to use. But there's no cursor for aiming so I assume the directional buttons don't work. The firing is broken as there's no cusror. Using the special attacks also cause the game to crash and freeze. 

### Steps to reproduce

Simply playing the game, it's clear what issues are present. There are no special circumstances to reproduce. Trying to use the special attacks seem to cause the game to freeze.

### Expected behavior

Cursor, firing and so on. Regular game play. 

### Add screenshots

Uploading Screen_Recording_20220719-220348_MDemu.mp4…

**Comment by section-leader** [comment]
https://user-images.githubusercontent.com/40920316/179848626-4c41a5fb-947e-4adb-9e58-656b95a1be88.mp4

**Comment by soundsnow** [comment]
@section-leader 
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/347#issue-1220836007

**Comment by Rakashazi** [comment]
Thanks for the report. There were some issues with the Light Phaser code but they're fixed in last commit so this game should work properly now.
