### ISSUE TITLE
[Question]: Is MD.emu based on / forked from PicoDrive

### ISSUE THREAD

**Issue by SteveCraft28** [Rakashazi/emu-ex-plus-alpha#515]
### Describe your question

Is MD.emu may use PicoDrive emulation?
I test Super Boy I. (SMS), Super Boy II. (SMS), Super Boy 3 (SMS) on MD.emu and PicoDrive, It's black screen with audio.

**Comment by Rakashazi** [comment]
PicoDrive is only used as a basis for the SegaCD emulation and isn't used at all for SMS.
