### ISSUE TITLE
[Issue]: Space Gun Unplayable

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#516]
### Describe the bug

![Space Gun (Europe) 000](https://user-images.githubusercontent.com/109885044/180782224-96ffa898-bf2f-41a3-9f74-a370a37cda6e.png)

https://github.com/Rakashazi/emu-ex-plus-alpha/issues/513

### Steps to reproduce

.

### Expected behavior

SMS 1, 2 Button

**Comment by Rakashazi** [comment]
Ok, looks like I have to show the virtual gamepad but have it map to port 2 when the light gun is in port 1.

**Comment by Rakashazi** [comment]
Should be working properly in last commit.
