### ISSUE TITLE
[Issue]: vba-m solar sensor brightness bar or buttons

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#518]
### Describe the bug

https://github.com/libretro/vbam-libretro/blob/master/src/libretro/libretro.cpp
line 411 and 412
RETRO_DEVICE_ID_JOYPAD_L2
RETRO_DEVICE_ID_JOYPAD_R2

### Steps to reproduce

two options or buttons

### Expected behavior

Solar Sensor (Darker)
Solar Sensor (Lighter)
Boktai (ボクらの太陽) GBA trilogy
2003	Boktai: The Sun Is in Your Hand
2004	Boktai 2: Solar Boy Django
2005	Boktai 3: Sabata's Counterattack
[Boktai Wikipedia](https://en.m.wikipedia.org/wiki/Boktai)
[Boktai: The Sun Is in Your Hand Wikipedia](https://en.m.wikipedia.org/wiki/Boktai:_The_Sun_Is_in_Your_Hand)
[Boktai 2: Solar Boy Django Wikipedia](https://en.m.wikipedia.org/wiki/Boktai_2:_Solar_Boy_Django)

**Comment by soundsnow** [comment]
gba brightness bar
@Rakashazi 
![image20](https://user-images.githubusercontent.com/109885044/181665042-3d4d1625-aca6-4e55-95e8-8d03a57d3472.png)

**Comment by Rakashazi** [comment]
Added to the requested enhancements list #330
