### ISSUE TITLE
[Issue]: improve/add mice support for 16-bit consoles

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#519]
### Describe the bug

Emulator | Mouse Supported
Mednafen | Yes
Genesis Plus GX | Yes
Snes9x | Yes 

### Steps to reproduce

PC Engine/TurboGrafx-16
Super Family Computer/Super Nintendo Entertainment System
Mega Drive/Genesis

### Expected behavior

PCE Mouse
[NEC Retro](https://necretro.org/PC_Engine_Mouse)
Compatible games
PC Engine
CD-ROM²
Super CD-ROM²

    1552 Tenka Tairan
    A.III.
    The Atlas: Renaissance Voyager
    Brandish
    Dennou Tenshi: Digital Ange
    Eikan ha Kimi ni: Koukou Yakyuu Zenkoku Taikai
    Lemmings
    Nemurenu Yoru no Chiisana Ohanashi
    Power Golf 2: Golfer
    Princess Maker 2
    Tokimeki Memorial
[Kaka](http://www.slowdays.org/kaka/List_of_Mouse-Supporting_PC_Engine_Games)
List of Mouse-Supporting PC Engine Games

    1552: Tenka Dairan
    A-Ressha de Ikkō 3
    Brandish
    Dennō Tenshi
    Dōkyūsei
    Eikan wa Kimi ni
    Hatsukoi Monogatari
    Jamanoid
    Jantei Monogatari 3: Saver Angels
    Lemmings
    Metal Angel *
    Metal Angel 2 *
    Nemurenu Yoru no Chiisana Ohanashi
    Power Golf 2: Golfer
    Princess Maker 2
    The Atlas: Renaissance Voyager
    Tokimeki Memorial
    Vasteel 2 *

(* to be confirmed)

MD Mouse
[Sega Retro](https://segaretro.org/Sega_Mouse)
Compatible Games
Mega Drive

    Body Count
    Cannon Fodder
    Fun 'n' Games
    Janou Touryuumon
    Jimmy White's Whirlwind Snooker
    Lemmings 2: The Tribes
    Lord Monarch: Tokoton Sentou Densetsu
    Marble Madness
    Nobunaga no Yabou: Haouden
    Nobunaga's Ambition
    Richard Scarry's Busytown
    Shanghai II: Dragon's Eye
    Wacky Worlds

Mega CD

    Crime Patrol
    Dungeon Master II: Skullkeep
    Eye of the Beholder
    Links: The Challenge of Golf
    Mad Dog II: The Lost Gold
    Mad Dog McCree
    Might and Magic III: Isles of Terra
    My Paint: The Animated Paint Program
    Nobunaga no Yabou: Haouden
    Panic!
    Shin Megami Tensei
    StarBlade
    The Secret of Monkey Island
    Urusei Yatsura: Dear My Friends
    Warau Salesman
    Who Shot Johnny Rock?
    Yumemi Mystery Mansion

SNES Mouse
[Wikipedia](https://en.m.wikipedia.org/wiki/Super_NES_Mouse)
List of compatible gamesEdit

The Super NES Mouse was supported by many games during its lifetime, and even by the Super Game Boy accessory.[2] Certain games released after the Mouse—such as Super Mario All-Stars, Tetris & Dr. Mario, Yoshi's Island, and Kirby Super Star—display a warning message indicating that the mouse is incompatible with that game.

This is an incomplete list of games that support the accessory:

    Acme Animation Factory[2]
    Advanced Dungeons & Dragons: Eye of the Beholder[3]
    Alice no Paint Adventure (Japan only)
    Arkanoid: Doh It Again[4]
    Asameshimae Nyanko (Japan only)
    Bishoujo Senshi Sailor Moon S: Kondo wa Puzzle de Oshiokiyo! (Japan only)
    Brandish 2: Expert (Japan only)
    BreakThru!
    Cameltry (called On the Ball in North America and the UK)
    Cannon Fodder (PAL only)
    Dai-3-ji Super Robot Taisen (Japan only)
    Dai-4-ji Super Robot Taisen (Japan only)
    Dōkyūsei 2 (Japan only)
    Doom
    Dragon Knight 4 (Japan only)
    Dynamaite: The Las Vegas (Japan only)
    Farland Story 2 (Japan only)
    Fun 'n Games
    Galaxy Robo (Japan only)
    Hiōden: Mamono-tachi tono Chikai (Japan only)
    J.R.R. Tolkien's The Lord of the Rings: Volume 1
    Jurassic Park
    King Arthur's World
    Koutetsu no Kishi (Japan only)
    Koutetsu no Kishi 2: Sabaku no Rommel Shougun (Japan only)
    Koutetsu no Kishi 3: Gekitotsu Europe Sensen (Japan only)
    Kid Kirby (unreleased)
    Lamborghini American Challenge
    Lemmings 2: The Tribes
    Lord Monarch (Japan only)
    Mario no Super Picross (Japan only)
    Mario Paint[2]
    Mario & Wario (Japan only)[5]
    Mario's Early Years: Fun with Letters
    Mario's Early Years: Fun with Numbers
    Mario's Early Years: Preschool Fun
    Mega lo Mania (PAL only)
    Might and Magic III
    Motoko-chan no Wonder Kitchen (Japan only)
    Nobunaga's Ambition
    Operation Thunderbolt[2]
    Pieces[6]
    Populous II: Trials of the Olympian Gods (PAL only)
    PowerMonger (PAL/Japan)
    Revolution X
    Sangokushi Seishi: Tenbu Spirits (Japan only)
    Sgt. Saunders' Combat! (Japan only)
    Shanghai - Banri no Choujou (Japan only)
    Shanghai III (Japan only)
    Shien's Revenge
    Sid Meier's Civilization
    SimAnt: The Electronic Ant Colony
    Snoopy Concert (Japan only)
    Sound Fantasy (unreleased)
    SpellCraft: Aspects of Valor (unreleased)
    Super Caesars Palace
    Super Castles (Japan only)
    Super Game Boy
    Super Pachi-Slot Mahjong (Japan only)
    Super Solitaire
    T2: The Arcade Game[7]
    Tin Star[2]
    Tokimeki Memorial: Densetsu no Ni no Shita de (Japan only)
    Troddlers
    Utopia: The Creation of a Nation
    Vegas Stakes[2]
    Warrior of Rome III (unreleased)
    Wolfenstein 3D
    Wonder Project J: Kikai no Shounen Pino (Japan only)
    Zan II Spirits (Japan only)
    Zan III Spirits (Japan only)
    Zico Soccer (Japan only)

**Comment by Rakashazi** [comment]
Added to the requested enhancements list #330
