### ISSUE TITLE
Audio sample rate setting not saved/remembered

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#52]
On Android, if the user changes the Options->Audio->Sound Rate setting, the new setting doesn't seem to be saved. Or, it's not loaded. Either way, the rate reverts to the default every time you launch the emulator.

[I noticed this testing on a Huawei G620S phone, where audio crackles at the default 48kHz but seems fine at 44kHz.]

**Comment by Rakashazi** [comment]
There were incorrectly initialized variables in the sound rate code. Fix committed for the 1.5.30 release.
