### ISSUE TITLE
[Feature request]: MSX and ColecoVision Improved Virtual Gamepad w/ Pause Buttons

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#521]
### Describe the feature

angelofme's idea is good
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/472
why did he disappear?
i don't think he's a particularly rude person, and he'll apologize too. 
i'm not very good at English either
https://github.com/drhelius/Gearcoleco/issues/19
some ColecoVision games |#| is pause key
https://github.com/libretro/FBNeo/issues/997
since then, I've learned that the original MSX has two pause keys
STOP almost all namco and other developer games
F1 konami and few other developer games
MSX
|F1|STOP|
Screenshot 1
ColecoVision
|*|0|#|
Screenshot 2

'Add support for translated strings in different languages'
If you need someone who can translate a foreign language, maybe he can help
Virtual Virtual Boy (Virtual Boy emulator) Traditional Chinese, Simplified Chinese, Japanese and Russian by AngelofMe
https://github.com/SupernaviX/vvb#credits
https://github.com/SupernaviX/vvb/pull/29
https://github.com/SupernaviX/vvb/pull/30

### Add screenshots

![image15](https://user-images.githubusercontent.com/109885044/181029993-3770b505-f9e9-4bcb-98aa-d1c18f393351.png)
![image16](https://user-images.githubusercontent.com/109885044/181035973-3ddd732a-9c3b-4e95-8630-d6eed699fd5b.png)

**Comment by soundsnow** [comment]
If you've played Java mobile aka J2ME games, @Rakashazi  don't need him (AngelofMe) to explain what each key does
ColecoVision games require a keypad to play instead of a keyboard
|*|0|#|
these three keys are generally used for pause or other options
like Nintendo Select/Start
I recommend you a game

after you test it, you'll know why no one needs a keyboard to play ColecoVision games

Aquattack
|#| Pause
|*| Continue (Died)
|1|2|3|4|5|6|7|8|9|0|*| Play (|#| Paused)
Left Trigger Up Shoot
Right Trigger Down Shoot
|4|5|0| Left Shoot
|1| Left + Up 45 Shoot
|2| Up Shoot
|3| Right + Up 45 Shoot
|6| Right Shoot
|7| Left + Down 45 Shoot
|8| Down Shoot
|9| Right + Down 45 Shoot

**Comment by soundsnow** [comment]
![image17-01](https://user-images.githubusercontent.com/109885044/181214356-ecfc8dc7-c0f7-47eb-936f-43bd771370a1.jpeg)

**Comment by soundsnow** [comment]
J2ME Symbian N-Gage Emulator
![J2ME Symbian N-Gage](https://user-images.githubusercontent.com/109885044/181242524-1bded8d8-6e15-44ee-9031-f42d2d8eecc9.png)
ColecoVision Emulator
![ColecoVision](https://user-images.githubusercontent.com/109885044/181242541-fad946e3-4d2d-47ce-b160-c94afcb03fd8.png)

**Comment by Rakashazi** [comment]
I've added this to requested enhancements list #330. About AngelofMe, they were posting many incomprehensible and irrelevant issues. I understand AngelofMe isn't good with english and have just unblocked them, but please tell them to only post clear and concise issues from now on.
