### ISSUE TITLE
[Issue]: GBA.EMU's sound filter doesn't work properly 

### ISSUE THREAD

**Issue by juamnitruh** [Rakashazi/emu-ex-plus-alpha#523]
### Describe the bug

Even when i set the interpolation amount to 100, there's still not a noticiable difference. In VBA 2.1.4 for pc, the sound filter actually works fine. 

### Steps to reproduce

Go to options, audio, turn on sound filter.

### Expected behavior

It should actually filter the audio.

**Comment by Rakashazi** [comment]
Thanks for the report. I accidentally excluded some functions needed for sound filtering to work from the build but it should be fixed in last commit.
