### ISSUE TITLE
[Feature request]: Add more granular fast forward options

### ISSUE THREAD

**Issue by hilltop804** [Rakashazi/emu-ex-plus-alpha#525]
### Add 1.25x and 1.5x fast forward speeds to emulators

Hi, I created a pull request #524 to add additional fast forward options to the emulator framework. I'm pretty new to coding, so I hope all this code is correct. I've never contributed on GitHub, so I apologize if any of this is not appropriate.

Please let me know if there's anything else needed to support this request.

**Comment by Rakashazi** [comment]
Thanks for the request and always feel free to contribute. I've been meaning to update the fast forward code to support fractional values too and integrated the necessary changes in the last commit. Here are the issues with the pull request for reference:

* Speed multipliers stored in EmuAudio and EmuTiming are still stored as ints
* Menu item IDs as well as the fast forward option value are currently stored as ints so they require scaling when setting (ex. 1.25 -> 125)
