### ISSUE TITLE
Pressing two turbo buttons at the same time doesn't work correctly

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#54]
I noticed a strange problem with turbo buttons. I tested with two Bluetooth controllers, an OnLive one and a Saitake STK-7003, and on two Android phones running Android 4.1.1 and 4.4.4. Same issue on both. The problem might not be Bluetooth-specific, but NES.emu doesn't seem to have a way to configure on-screen turbo buttons so I couldn't try that.

To easily show the problem I used programs that show the console controller button state:
- "Super Famicom Controller Test Program" for Snes9x EX
- "Controller Test (USA)" for NES.emu.

Here are (hopefully) steps to demonstrate the problem:

- Map two buttons on your controller to turbo functions, i.e. Turbo A and Turbo B. Load the controller test ROM and start emulation.

- Hold down Turbo A. The A button symbol flashes on screen as it should. Keeping that button held down, hold down Turbo B as well. The B button symbol does not flash. The console thinks you're keeping B pressed rather than repeatedly tapping it.

- Keeping Turbo B pressed, release Turbo A then press it again. The A symbol flashes so Turbo A seems to work correctly.

- Release both buttons. Now press and hold Turbo B. This time the B symbol flashes correctly. Keeping Turbo B pressed, hold Turbo A too. The A symbol is constantly on.

- Release both buttons again. Now press both Turbo A and Turbo B at exactly the same time. That seems to fix things and the two turbo buttons now work correctly (independently) as they should. But if you open the emulator menu then press back to return to emulation, the problem is present again.

**Comment by Rakashazi** [comment]
This is related to key repeat events in Android causing a key press to use up all the turbo slots in the emulator. Fix committed for the 1.5.30 release.
