### ISSUE TITLE
[Feature request]: all emulators Screen Rotation (Mesen NES emulator)

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#548]
### Describe the feature

https://github.com/SourMesen/Mesen/blob/86326e832974d984846ae078e568c023a5f76f1f/Docs/content/configuration/Video.md
90/180/270 degrees
Rotates the display by the specified angle. This is useful to play games (generally homebrew games) designed for a vertical display.

**Comment by Rakashazi** [comment]
Rotation supported was just added in the last commit, do you have a list of homebrew that displays vertically?

**Comment by soundsnow** [comment]
i don't know, mesen and its libretro core support

**Comment by soundsnow** [comment]
> Rotation supported was just added in the last commit, do you have a list of homebrew that displays vertically?

i don't know, mesen and its libretro core support
I only know one SNES homebrew game
Sure Instinct
It supports mouse and joystick

**Comment by soundsnow** [comment]
> Rotation supported was just added in the last commit, do you have a list of homebrew that displays vertically?

I think it should be flying shooters
Such as Space Invaders

**Comment by soundsnow** [comment]
[Vertically scrolling shooters](https://en.m.wikipedia.org/wiki/Vertically_scrolling_video_game#Vertically_scrolling_shooters) or vertical scrolling shooters present the action from [above](https://en.m.wikipedia.org/wiki/Video_game_graphics#Top-down_perspective) and scroll up (or occasionally down) the screen.

[Side-scrolling shooters](https://en.m.wikipedia.org/wiki/Side-scrolling_video_game) or horizontal scrolling shooters present a side-on view and scroll horizontally.

I think this option should be added to all emulators, not only shooters, some game developers will deliberately rotate the screen
@Rakashazi
