### ISSUE TITLE
[Feature request]: Additions to the gba solar sensor

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#550]
### Describe the feature

I'm so stupid, adding Brightness Bar on the screen will only increase the power consumption, it's better to change it to a percentage option

https://github.com/libretro/vbam-libretro/blob/master/src/libretro/libretro_core_options.h

>         "Solar Sensor Level",
>         "Adjusts simulated solar level in Boktai games. L2/R2 buttons can also be used to quickly change levels.",
>         {
>             { "0",  NULL },
>             { "1",  NULL },
>             { "2",  NULL },
>             { "3",  NULL },
>             { "4",  NULL },
>             { "5",  NULL },
>             { "6",  NULL },
>             { "7",  NULL },
>             { "8",  NULL },
>             { "9",  NULL },
>             { "10", NULL },
>             { NULL, NULL },
>         },

@Rakashazi sorry

**Comment by Rakashazi** [comment]
Solar sensor support was added in the last commit.
