### ISSUE TITLE
[Question]: Is pce emulator based on Mednafen (PCE-Accurate)?

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#552]
### Describe your question

there are two mednafen pce emulators
Mednafen (PCE-Accurate) and Mednafen (PCE-Fast)
I recommend Mednafen (PCE-Accurate)

emu-ex-plus-alpha/PCE.emu/src/main/PCEFast.cc

add a button
mode switch
[beetle-pce-libretro](https://github.com/libretro/beetle-pce-libretro/blob/master/libretro.cpp)
>      { INDEX, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_L2,    "Mode Switch" },\

[Avenue Pad 6](https://necretro.org/Avenue_Pad_6)
SLOW/OFF
[Arcade Pad 6](https://necretro.org/Arcade_Pad_6)
6 - 2
and turbo switches
some games require turbo
>       "pce_show_advanced_input_settings",
>       "Show Advanced Input/Turbo Settings",
>       NULL,
>       "Show Multitap, Mouse, Turbo Buttons and advanced parameters. NOTE: You need to go back in game and re-enter the menu to refresh the list.",
>       NULL,
>       NULL,
>       {
>          { "enabled",  NULL },
>          { "disabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_Turbo_Toggling",
>       "Turbo Hotkey Mode",
>       NULL,
>       "Enable turbo buttons. Hotkeys (buttons III and IV) can behave as either toggle switches or dedicated (hold to use) turbo buttons.",
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "toggle", "Toggle" },
>          { "always", "Dedicated" },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_turbo_toggle_hotkey",
>       "Alternate Turbo Hotkey",
>       NULL,
>       "Assign RetroPad's L3/R3 buttons as turbo hotkeys instead of buttons III and IV. Works only in 'Toggle' mode and only as long as nothing is assigned to the L3/R3 buttons. You can avoid remapping buttons III and IV when switching to 6-button controller mode with this.",
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_Turbo_Delay",
>       "Turbo Speed",
>       NULL,
>       "Choose how fast button presses are repeated.",
>       NULL,
>       "input",
>       {
>          { "Fast", NULL },
>          { "Medium", NULL },
>          { "Slow", NULL },
>          { NULL, NULL},
>       },
>       "Fast"
>    },
>    {
>       "pce_p0_turbo_I_enable",
>       "P1 Turbo I",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p0_turbo_II_enable",
>       "P1 Turbo II",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p1_turbo_I_enable",
>       "P2 Turbo I",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p1_turbo_II_enable",
>       "P2 Turbo II",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p2_turbo_I_enable",
>       "P3 Turbo I",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p2_turbo_II_enable",
>       "P3 Turbo II",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p3_turbo_I_enable",
>       "P4 Turbo I",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p3_turbo_II_enable",
>       "P4 Turbo II",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p4_turbo_I_enable",
>       "P5 Turbo I",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },
>    {
>       "pce_p4_turbo_II_enable",
>       "P5 Turbo II",
>       NULL,
>       NULL,
>       NULL,
>       "input",
>       {
>          { "disabled", NULL },
>          { "enabled", NULL },
>          { NULL, NULL},
>       },
>       "disabled"
>    },

**Comment by Rakashazi** [comment]
It's currently based on Mednafen's pce_fast module but an option to use the more accurate pce module will be added in a future update.

**Comment by Rakashazi** [comment]
The more accurate pce emulation core was added in the last commit.
