### ISSUE TITLE
[Issue]: nes/2600 BUG and IMPROVEMENT Track & Field/Hyper Sports/Hyper Olympic

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#554]
### Describe the bug

unplayable bug
Hyper Sports (Japan) (Rev 1).nes
playable
Hyper Sports (Japan).nes
![image25](https://user-images.githubusercontent.com/109885044/182288008-289b980a-46b2-40e9-8968-a28d1352a351.png)

### Steps to reproduce

2600: Track & Field
Konami and Atari 
swap button positions
![image23](https://user-images.githubusercontent.com/109885044/182288140-94c70bac-ae73-4e0f-bc1e-14ac8f373041.png)
![8595153560_076c6436de_b](https://user-images.githubusercontent.com/109885044/182288305-5fd218a9-b97c-40e4-9c0d-7e104f174058.jpg)

Track and Field (USA).a26
Size: 16.00KB (16384B)
MD5: 6ae4dc6d7351dacd1012749ca82f9a56

### Expected behavior

famicom: Hyper Shot
Konami
reverse 180 degrees
![image24](https://user-images.githubusercontent.com/109885044/182288802-f6cb5f72-5cf4-4f4d-a526-9daad14e4c6e.png)
![Konami_Hyper_Shot-01](https://user-images.githubusercontent.com/109885044/182288422-371ff9bf-33eb-4164-af7c-bd84a241e99e.jpeg)
![Konami_Hyper_Shot](https://user-images.githubusercontent.com/109885044/182288425-773e639a-b750-4250-b340-8ab76a4343b8.jpg)

Hyper Sports (Japan).nes
Size: 24.01KB (24592B)
MD5: b98f22d8d34a92aa9dbeef2cc2f57d5f

Hyper Sports (Japan) (Rev 1).nes
Size: 24.01KB (24592B)
MD5: 6dbe2629c90911d5ea3423d807dc4352

Hyper Olympic (Japan).nes
Size: 24.01KB (24592B)
MD5: 10f0220a5c12e8c01ada54d618732e5c

Hyper Olympic (Japan) (Genteiban!).nes
Size: 48.01KB (49168B)
MD5: 428195a37efb210bf6268c209113dc2f

**Comment by soundsnow** [comment]
these Konami sports games are suitable for left-handed, right-handed or double-handed people to play
but the layout of @Rakashazi 's emulator buttons is too anti-human
I was forced to adjust the weight of my hands all the way to the right side
![image26](https://user-images.githubusercontent.com/109885044/182295340-59e1c7a4-bb30-43af-94da-7bb55f217ed7.png)

**Comment by Rakashazi** [comment]
Hyper Sports (Japan) (Rev 1) is now recognized and will enable the hyper shot controller, a dedicated virtual gamepad for it will come in a future update.
