### ISSUE TITLE
[Issue]: Loading a .a26 file for a long time

### ISSUE THREAD

**Issue by AngelofMe** [Rakashazi/emu-ex-plus-alpha#558]
### Describe the bug

bug？

### Steps to reproduce

I just want to know if 3-D Ghost Attack is not [playable](https://github.com/Rakashazi/emu-ex-plus-alpha/issues/473)
RetroArch Libretro Stella looks all right and can select and enter the game normally
when I try to open the a26 file with 2600.emu, it shows that Loading is too long
finally I changed two Pac-Man games, the same•••
Open Content -> Browse For File -> ***.a26
my mobile system is based on AOSP and it is very stable
I think it's because you didn't optimize the emulator

### Expected behavior

now I don't even know if that 3D game can be played, because I waited too long without entering the game
a26 file is not big ah, why consume so much time

### Relevant log output

```shell
3-D Genesis (USA) (Proto).a26
Size: 8.00KB (8192B)
MD5: cac9928a84e1001817b223f0cecaa3f2

3-D Ghost Attack (USA) (Proto).a26
Size: 16.00KB (16384B)
MD5: fcbdf405f0fc2027b0ea45bb5af94c1a

3-D Havoc (USA) (Proto).a26
Size: 8.00KB (8192B)
MD5: 60cd61a2dfccb0e2736434f9792c1672

3-D Tic-Tac-Toe (Europe).a26
Size: 2.00KB (2048B)
MD5: e3600be9eb98146adafdc12d91323d0f

3-D Tic-Tac-Toe (USA).a26
Size: 2.00KB (2048B)
MD5: 0db4f4150fecf77e4ce72ca4d04c052f

3-D Zapper (USA) (Proto) (1982-12-15).a26
Size: 4.00KB (4096B)
MD5: 4f32b24869d8c1310fecf039c6424db6

3-D Zapper (USA) (Proto) (Earlier).a26
Size: 4.00KB (4096B)
MD5: 50c7edc9f9dc0369abcdab3b4efeb5e9

Ms. Pac-Man (USA).a26
Size: 8.00KB (8192B)
MD5: 87e79cd41ce136fd4f72cc6e2c161bee

Pac-Man (USA).a26
Size: 4.00KB (4096B)
MD5: 6e372f076fb9586aff416144f5cfe1cb

Rubik's Cube 3-D (USA) (Proto).a26
Size: 4.00KB (4096B)
MD5: 40b1832177c63ebf81e6c5b61aaffd3a
```

### Add screenshots
![Screenshot_20220803-171351_Trebuchet](https://user-images.githubusercontent.com/26894447/182578296-2daab58e-884b-46b6-ad3a-c031942293e3.png)

_No response_

**Comment by AngelofMe** [comment]
sorry, because I've seen people mention mgba all the time before, so I'll start posting related content too
But I don't mean any harm.
Actually I don't want to hurt you
Just because you ignored me for more than half a month, I thought you didn't care about its updates
That's why I started posting duplicate issues to get your attention afterwards
And I recently re-asked someone to teach me English

**Comment by AngelofMe** [comment]
I noticed early on that GBA.emu was taking up a lot size, and I mentioned it in passing in the issue where I removed the GBA.emu Bundled Content
But you didn't notice the storage space at the time
At that time you just deleted my issue
It was only after someone re-mentioned this that you fixed it

**Comment by AngelofMe** [comment]
It's not that I want to use your simulator, but recently someone asked me to translate your simulator
He introduced me to a foreign language teacher, so that's why I was able to localize Virtual Virtual Boy
github com SupernaviX vvb pull 31
Why is that PR still OPEN?
"Sorry I'm so slow to respond during the week, lately I've only had energy to work on this on weekends. ------SupernaviX"
But before that I have to get 3-D Ghost Attack running, otherwise I'm not willing to translate for it
One more thing, I don't know how to translate your emulator at all
There is no single strings.xml file that contains all the text
I can't even find a Readme or a tutorial

**Comment by soundsnow** [comment]
you can try to open the same game again 
when I opened it also kept loading, then I turned it off and reopened the game
maybe it's because you just installed this emulator, I've opened quite a few games already
I don't know what caused this
3-D Ghost Attack is now playable
Stella Core has been updated once recently
