### ISSUE TITLE
[Feature request]: Reduce the number and size of c64 bios files

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#567]
### Describe the feature

C64.emu.zip
Size: 1.00MB (1051466B)
MD5: d78bf89c81d1bd1f15593058f5910dfe
Type: zip / Deflate
File count: 329
Content size: 3.78MB (3969614B)
Compression ratio: 26%

Commodore - 8-bit (VICE).zip
Size: 981.20KB (1004752B)
MD5: 646c1f677b25ad081aefa4e7e3a76638
Type: zip / Deflate:Maximum
File count: 258
Content size: 3.66MB (3844781B)
Compression ratio: 26%

Commodore - 8-bit (VICE).zip available for libretro vice cores
[C64.emu.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9264485/C64.emu.zip)
[Commodore - 8-bit (VICE).zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9264486/Commodore.-.8-bit.VICE.zip)

**Comment by Rakashazi** [comment]
I've updated C64.emu.zip on Google Drive to use LZMA for a better compression ratio.

**Comment by soundsnow** [comment]
It seems @Rakashazi  misunderstood me.
Never mind, it doesn't matter
It's my fault for not checking
It seems that the files I found in the data folder are not complete, you don't have to compress the same files again for that
The file you uploaded is complete, mine is not
Sorry to have wasted your time
The files in the vice folder are used in the libretro cores
Can you add support for these files as well?

Commodore - 8-bit (VICE).zip/vice/

JiffyDOS_1541-II.bin
JiffyDOS_1571_repl310654.bin
JiffyDOS_1581.bin
JiffyDOS_C64.bin
JiffyDOS_C128.bin
scpu-dos-1.4.bin
scpu-dos-2.04.bin

Also can you update the MSX BIOS file? I have created separate folders for 200 machines
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/571

**Comment by soundsnow** [comment]
> It seems @Rakashazi misunderstood me. Never mind, it doesn't matter It's my fault for not checking It seems that the files I found in the data folder are not complete, you don't have to compress the same files again for that The file you uploaded is complete, mine is not Sorry to have wasted your time The files in the vice folder are used in the libretro cores Can you add support for these files as well?
> 
> Commodore - 8-bit (VICE).zip/vice/
> 
> JiffyDOS_1541-II.bin JiffyDOS_1571_repl310654.bin JiffyDOS_1581.bin JiffyDOS_C64.bin JiffyDOS_C128.bin scpu-dos-1.4.bin scpu-dos-2.04.bin
> 
> Also can you update the MSX BIOS file? I have created separate folders for 200 machines #571

These are all systems supported by blueMSX

COL
Forte II Games
MSX
MSX2
MSX2+
MSXturboR
SEGA
SVI

The file contains three C-BIOS folders, I'm not sure if it's the same version as the one that comes with @Rakashazi  emulator

I don't recommend using blueMSX as an SG-1000 emulator
It lacks many SG-1000 Mappers
Genesis Plus GX supports more SG-1000 games than it does
So use it only as a SC-3000 and SF-7000 emulator
I checked its libretro source code and it only contains .sc file extension, but the SF-7000 has .sf file extension
