### ISSUE TITLE
Various Emulators and Save States????

### ISSUE THREAD

**Issue by CanadianJeff** [Rakashazi/emu-ex-plus-alpha#57]
so I know that for example save games are done with extensions

SNES = .srm
GBA/GBC/GB = .sav

there are not really any problems here but when it comes to save states lets say I play on my PC and create a save state and copy it over to my android it may use an odd naming scheme an option to load a save state from a file would be nice

PC [romname]-01.sgm
DROID [romname]1.sgm

**Comment by CanadianJeff** [comment]
actually this may cause some unknown side effects playing on a save state from my android back on to my pc it started to have audio hiccups and other issues I checked a sha256 hash of my game on both my android and pc and they match

**Comment by M-a-r-k** [comment]
I think save state file format is specific to each emulator, and can differ between different versions of the same emulator, and between different architectures (x86 vs ARM). So unless there is some portable standard for save states, interchanging them is probably unlikely to work very well.

Having said that, are you using the same emulator on your PC as on the Android device?

**Comment by CanadianJeff** [comment]
I have solved this problem by deleting all your emulators and switching to retroarch and using the same cores on both PC and DROID so for example mGBA on PC and mGBA on DROID the states work on both platforms I just sync my save folder
