### ISSUE TITLE
HOW TO BUILD!!!!

### ISSUE THREAD

**Issue by xuwakao** [Rakashazi/emu-ex-plus-alpha#58]
How to build this project?
I want to build an android release version,but when i try to build the Image module like the follow, but always failed,my platform is unbuntu.
1.Change to "bundle/all" directroy.
2.bash makeAll-android-armv7.sh TAR=gnutar

Then failed,

running make on src/libogg/android-armv7.mk
android-armv7.mk:1: **\* missing separator.  Stop.

How to solve this problem?Or can u provide wikis to tell how to build this project,plz?

**Comment by Rakashazi** [comment]
Are you using at least GNU Make 3.82? Type make -v to check.
