### ISSUE TITLE
[Feature request]: GBA Motion Controls 

### ISSUE THREAD

**Issue by jiujitiancai** [Rakashazi/emu-ex-plus-alpha#595]
### Describe the feature

Use sensor as d-pad
because Warioware: Twisted requires me to activate it
if no Motion Controls, This game will not be playable

### Add screenshots

![f131ee73a84651511b66b7b0b1f085a](https://user-images.githubusercontent.com/4254752/183462117-ea37fa3a-cb52-488a-9759-011c90eede46.jpg)

**Comment by Rakashazi** [comment]
I added hardware tilt/gyro support in the last commit so games that use those are controllable on phones now. I'm planning to add simulating the sensors with gamepad keys in a future update.
