### ISSUE TITLE
[Feature request]: separate screenshot folder

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#597]
### Describe the feature

screenshot and save are not the same kind of file, no one likes to find a picture in a large amount of data

Also, @Rakashazi  please solve all my issues as soon as possible, I've paid too much for it!
I have stayed up so many days, I don't want a github bot to close all my unresolved issues after two months.
not that I like to find you trouble, but your emulator is really not good enough
I don't have time to play games at all, I'm thinking of your user base

**Comment by soundsnow** [comment]
you only know something is wrong when someone tells you
If no one gives you feedback, you can pretend nothing happened

**Comment by Rakashazi** [comment]
A screenshot path option was added in the last commit.
