### ISSUE TITLE
Add image orbiting option to reduce chance of screen burn-in

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#60]
AMOLED, CRT and plasma screens can be susceptible to burn-in. Regions corresponding to the brightest parts of the image age faster than the rest. Parts of the screen which are constantly bright, such as game score line or TV station logo are problematic. Over time a "ghost" image becomes visible when a different image is shown, where the parts which have been burnt/worn most are dimmer than the rest.

Some CRT projectors (e.g. Barco, Sony) and plasma screens have a picture orbiting function which varies the position of the image gradually to spread wear over a larger area. A similar option could be useful for the various .emu programs, particularly when the user is using 100% scanlines overlay. With that, alternate lines are always black, so there will be no wear on screen pixels corresponding to the black lines, but normal wear on the rest. Over (a long) time that could cause burn-in.

A simple approach to handle the scanlines overlay case would be to have the overlay affect even or odd lines on alternate game launches. On the first run lines 2, 4, 6, ..., 480 would be black with the image on lines 1, 3, 5, ..., 479. And vice versa on the next run.

What about other burn-in, from e.g. static score displays? On each run you could vary the image position slightly, horizontally as well as vertically. E.g. instead of centering the image horizontally, position it within (say) 6 pixels of center, the offset being random each time emulation is started/continued. And similarly for vertical.

With integer vertical scaling where the image doesn't fill the whole screen (e.g. phone screen 800x480, output image height 448) orbiting the image by several pixels horizontally and vertically wouldn't cause any picture detail to be lost.

**Comment by rhester72** [comment]
You're trying to solve a hardware problem in software, which is not advisable.  The thing you're asking for would apply equally to Android itself, would it not?  Individual applications have no business doing things like this, IMHO.

**Comment by M-a-r-k** [comment]
I take your point, but for using the scanlines overlay (alternating which are the on and off lines) at least, that issue doesn't apply to Android itself. So an option to do that only would be helpful IMO.

**Comment by Rakashazi** [comment]
Closing out some old issues, out of the scope of the project.
