### ISSUE TITLE
[Feature request]: Dark Filter

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#601]
### Describe the feature

RACE (NGP)

      "Dark Filter Level (percent)",
      "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds.",
      {
         { "0",  NULL },
         { "5",  NULL },
         { "10", NULL },
         { "15", NULL },
         { "20", NULL },
         { "25", NULL },
         { "30", NULL },
         { "35", NULL },
         { "40", NULL },
         { "45", NULL },
         { "50", NULL },

### Add screenshots

![King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja)-220809-155323](https://user-images.githubusercontent.com/109885044/183595732-21c70672-b3c5-4e13-95b1-e50e085c3f38.png)
![King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja)-220809-155336](https://user-images.githubusercontent.com/109885044/183595750-bc7caeef-342d-43bf-a2c5-6b25453aba62.png)

**Comment by soundsnow** [comment]
for handheld games, this option must not be missing
especially ngp games, those games can not use the palette

**Comment by soundsnow** [comment]
https://github.com/libretro/RACE/blob/master/libretro/libretro_core_options.h

**Comment by soundsnow** [comment]
Gambatte (GB)

      "Dark Filter Level (%)",
      "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds, which are intended for display on a non-backlit Game Boy Color and can therefore appear uncomfortably bright when viewed on a modern backlit screen.",
      {
         { "0",  NULL },
         { "5",  NULL },
         { "10", NULL },
         { "15", NULL },
         { "20", NULL },
         { "25", NULL },
         { "30", NULL },
         { "35", NULL },
         { "40", NULL },
         { "45", NULL },
         { "50", NULL },

https://github.com/libretro/gambatte-libretro/blob/master/libgambatte/libretro/libretro_core_options.h

**Comment by Rakashazi** [comment]
RGB level controls were added in the last commit, which allows reducing brightness as a percentage.
