### ISSUE TITLE
Issues making on Kanotix Linux (Debian Jessie)

### ISSUE THREAD

**Issue by gannon345** [Rakashazi/emu-ex-plus-alpha#61]
I've followed all the instructions in the Install and Install-android docs, have all paths properly set but I can't build the SDK. When I run make, I get the error:

make: *** No rule to make target '/make/config.mk'

I'm running 

make -f /$HOME_PATH/explusalpha/explusalpha-master/imagine/android.mk install V=1 -j4 as per the instructions. The config.mk file is in the /make folder, but it seems like the script is looking for /make on the root path?

I'm running GNU MAKE 4.0, automake 1.14.1. Linux kernel is 4.2.0-25-generic, x86_64.

Any ideas?

**Comment by Rakashazi** [comment]
Sounds like make isn't seeing your IMAGINE_PATH variable, try to echo it and make sure it isn't empty.
