### ISSUE TITLE
Option to skip frames regularly

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#62]
I'm not sure how useful this would be but thought I'd mention it anyway.

Some (Android) devices have a non-60Hz display refresh rate. For example a phone I bought recently reports a rate of 56.67Hz.

Would there be any benefit to allowing the user to specify a "skip one in N frames" setting? In that specific case, skipping 1 in every 18 output frames would match the display's refresh rate.

**Comment by Rakashazi** [comment]
Closing out some old issues, manual frame rate setting was added.
