### ISSUE TITLE
[GBA.emu] How to Add/put or use Cheats Easily?

### ISSUE THREAD

**Issue by dochankpin** [Rakashazi/emu-ex-plus-alpha#623]
### Describe your question

Hi guys!
Sorry in advance if I'm already asking a question that has already been answered, ok?
I recently bought the GBA.emu version from Google Play,
and I'm having a bit of trouble finding a Cheats menu in the main tweaks.
Also, I'm not finding any GBA.emu emulator "folder" on my android device's system,
so I can put the Cheats manually, you know?
If anyone knows how to resolve this.
Or how to use Cheats more easily,
and can help with this topic, I would be very grateful.
In advance, thank you all for your attention.
See ya, bye.

**Comment by Rakashazi** [comment]
Hi, GBA.emu uses the VisualBoyAdvance .clt format for cheats. By default they are loaded from wherever your save files (.sav & .sgm) are stored. To add/edit cheats use System Actions -> Cheats.
