### ISSUE TITLE
[NES.emu] update core to FCEUX GIT c37f86d (2022.08.19)

### ISSUE THREAD

**Issue by MineSteve22** [Rakashazi/emu-ex-plus-alpha#624]
### Describe the feature

@Rakashazi is it possible to update core to FCEUX GIT [c37f86d](https://github.com/TASEmulators/fceux/commit/c37f86dbd16d64339f857a8389d4041c004d8f31) (2022.08.19)

**Comment by Rakashazi** [comment]
NES.emu was updated to the latest FCEUX GIT in the last commit.
