### ISSUE TITLE
[Feature request]: gba mobile devices REAL built-in illuminance/solar sensor

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#626]
### Describe the feature

If you prefer real sunlight, this should be a good idea
emulate
tablet, phone, and something you can lift
An illuminance light sensor senses the presence of light. Photodiodes and photoresistors are two types of devices used to sense light. They are responsible for the ambient screen brightness in your smartphone. When the photosensor in your phone detects high intensity it increases your phone’s brightness automatically. This is one of the many applications of the illuminance sensor. They are used in the shipping industry for security, and in agriculture and setting up solar panels.

If you live in a place where the clouds are always thick, manually adjusting the brightness is a good option
simulate
heavy electronic devices without illuminance sensor
      "Solar Sensor Level",
      "Sets ambient sunlight intensity. Can be used by games that included a solar sensor in their cartridges, e.g: the Boktai series.",
      "input",
      {
         { "sensor", "Use device sensor if available" },
         { "0",      NULL },
         { "1",      NULL },
         { "2",      NULL },
         { "3",      NULL },
         { "4",      NULL },
         { "5",      NULL },
         { "6",      NULL },
         { "7",      NULL },
         { "8",      NULL },
         { "9",      NULL },
         { "10",     NULL },
      },
      "0"

**Comment by soundsnow** [comment]
and RTC

**Comment by soundsnow** [comment]
Settings - Display - Adaptive Brightness
operating systems that support this feature should have this option
an "A" next to the brightness bar

**Comment by Rakashazi** [comment]
Real light sensor support was added in the last commit.
