### ISSUE TITLE
[Question]: is MD.emu based on / forked from Genesis Plus GX for Master System / Mark III (SMS) emulator

### ISSUE THREAD

**Issue by MineSteve22** [Rakashazi/emu-ex-plus-alpha#632]
### Describe your question

Genesis Plus GX - Sega MD/CD/MS/GG/SG-1000

Genesis Plus GX would allow for Game Gear and SG-1000 support

**Comment by Rakashazi** [comment]
Yes, it's forked from an older version of Genesis Plus GX. Game Gear & SG-1000 isn't currently supported but may be added in a future update.

**Comment by CraftCraft55** [comment]
New build of Genesis Plus GX already supports Game Gear and SG-1000. Already available as Libretto core.

![Screenshot_20220827-191012](https://user-images.githubusercontent.com/112271983/187041660-1d7bb509-4c94-4973-bf7d-05e3f67ee917.jpg)
![Screenshot_20220827-190956](https://user-images.githubusercontent.com/112271983/187041656-331cab2a-2748-4e3d-ac81-8d47c8e45cf8.jpg)

What about **MEKA** emulator - SG-1000, SC-3000, SF-7000, Master System, Game Gear, ColecoVision, Othello Multivision

**Comment by CraftCraft55** [comment]
New build of Genesis Plus GX already supports Game Gear and SG-1000. Already available as Libretto core.

![Screenshot_20220827-191012](https://user-images.githubusercontent.com/112271983/187041660-1d7bb509-4c94-4973-bf7d-05e3f67ee917.jpg)
![Screenshot_20220827-190956](https://user-images.githubusercontent.com/112271983/187041656-331cab2a-2748-4e3d-ac81-8d47c8e45cf8.jpg)

What about **MEKA** emulator - SG-1000, SC-3000, SF-7000, Master System, Game Gear, ColecoVision, Othello Multivision. MEKA is an open-source

https://www.smspower.org/meka/
