### ISSUE TITLE
[Feature request]:mappers nes.emu 1.5.62

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#635]
### Describe the feature

hello Mr. Robert, can he add new mappers as a developer?
INES Mapper 134
INES Mapper 342
INES Mapper 176
INES Mapper 413
in version 1.5.62 please because I would like to see these mappers

### Add screenshots

![Screenshot_2022-08-23-14-06-20-754_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186155684-0ccec034-f4e3-45dd-ad24-4076257e8d48.jpg)
![Screenshot_2022-08-23-14-07-00-734_com explusalpha NesEmu](https://user-images.githubusercontent.com/109180532/186155692-9004e72a-48fc-4f8e-9a4a-fc6510f8db26.jpg)

**Comment by TheBoxGame** [comment]
![186195249-f81ea5e4-fef1-4533-86c6-312111918af0](https://user-images.githubusercontent.com/109180532/186415530-5e659d35-48ff-4e15-be08-68a57fe002d1.png)
![186195245-f0f94494-f515-43a6-ae42-8cd7c2f3f0ca](https://user-images.githubusercontent.com/109180532/186415533-183db103-15ce-41ee-9698-52437585e937.png)
![186195235-5cdd251c-22f8-4a7d-8f1a-ab48c127031d](https://user-images.githubusercontent.com/109180532/186415536-9fdc2c35-8155-4e2b-9f68-9e2a17ced623.png)

**Comment by Rakashazi** [comment]
All but mapper 413 were added in the last commit. That one will take more research so I don't have an ETA for now.

**Comment by TheBoxGame** [comment]
well this mapper 413 doesn't have to be important that those are
