### ISSUE TITLE
Will the Google Play Store versions of these emulators be updated in the future?

### ISSUE THREAD

**Issue by gannon345** [Rakashazi/emu-ex-plus-alpha#64]
I noticed there was a long period with updates, but seems you've been making commits again recently. Does that mean updates are coming? (Because that would be awesome).

Thanks for your work, btw, I've really enjoyed your emulators.

**Comment by Rakashazi** [comment]
Yes, sorry about the long delay, more regular releases are coming and I'm currently looking into setting up open beta testing via the Play Store for additional builds.
