### ISSUE TITLE
[PCE.emu] add 3+243 in Visible Lines

### ISSUE THREAD

**Issue by MineSteve22** [Rakashazi/emu-ex-plus-alpha#642]
### Describe the feature

@Rakashazi 

3+243 visible lines is 240 lines

![PCE 240p](https://user-images.githubusercontent.com/111375765/187027200-c48fec8f-5a17-4c35-82b8-c020bbf51ac8.png)

**Comment by Rakashazi** [comment]
For reference, the lines that can show graphics are 0 to 241 (242 lines total). The top 3 lines are blank in this game so use 3+239 which shows 3 to 241 (239 lines total).
