### ISSUE TITLE
[Feature request]: snes sufami turbo games

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#648]
### Describe the feature

SuFami Turbo, is an accessory released by Bandai for Nintendo Super Famicom system

**Comment by Rakashazi** [comment]
Sufami Turbo games should now load correctly in the last commit provided you have the BIOS set in the options. Note you'll need to hard reset the console if you load an old auto save state that was saved without the BIOS.
