### ISSUE TITLE
Shaders broken on Master w/Adreno 330

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#65]
The latest master has broken shaders on an Adreno 330 with the following lines in the Logcat:
E/Adreno-SC( 5706): <CPPErrorToInfoLog:847>: GLSL line 6: Error: new macro body must match the old macro body 
E/Adreno-SC( 5706): <CPPErrorToInfoLog:847>: GLSL line 6: Error: new macro body must match the old macro body 

The current Google Play versions function properly, and the latest master works fine on other devices like the Nvidia Shield Tablet.

**Comment by Rakashazi** [comment]
Thanks for the report, fixed in Jun 14, 2016 commit
