### ISSUE TITLE
MSX.emu Machine Type Missing

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#66]
It appears that the code to add the "msxMachine" MultiChoiceMenuItem around https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/MSX.emu/src/main/EmuMenuViews.cc#L216 is missing.

I added
```
item.emplace_back(&msxMachine);
```
and it appears to work fine now.

**Comment by Rakashazi** [comment]
Sorry about that, thought I added it back in earlier, fixed now :)
