### ISSUE TITLE
MSX.emu and Snes9x use LTO regardless of O_LTO

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#68]
Both MSX.emu and Snes9x enable -flto if RELEASE is defined, rather than O_LTO, which causes linking problems at the end of compilation if O_LTO isn't defined. In addition, MSX.emu cannot find references to some internal lto-related functions when linking if LTO is correctly enabled globally. (undefined reference to 'write.lto_priv.877').

**Comment by Rakashazi** [comment]
Closing out some old issues, should be addressed in updates made since the last post.
