### ISSUE TITLE
[Feature request]: mappers 1.5.64

### ISSUE THREAD

**Issue by TheBoxGame** [Rakashazi/emu-ex-plus-alpha#687]
### Describe the feature

9999999 in 1.nes Mapper 59
(JY-201) 1997 Super 7-in-1.nes Mapper 411
76-in-1 (Y2K) (Unl).nes Mapper 237
67-in-1 (Mario) (Unl).nes Mapper 370

**Comment by Rakashazi** [comment]
These mappers were added in the last commit.

**Comment by TheBoxGame** [comment]
that is, what will be added in version 1.5.63 because these roms do not work, there is only a gray screen

**Comment by TheBoxGame** [comment]
![collage95compil](https://user-images.githubusercontent.com/109180532/189482310-f436db3e-ff2b-417b-97e4-e7afe508cc05.png)
