### ISSUE TITLE
libpng16 pnglibconf.h

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#69]
The bundled libpng includes macro definitions of png_error and png_warning, which conflict with imagine's LibPNG.cc's definitions as the included pnglibconf.h ensures that PNG_ERROR_TEXT_SUPPORTED and PNG_WARNINGS_SUPPORTED are not defined.
Commenting out the macro definitions in png.h OR defining the above macros in LibPNG.cc allow the project to compile.

**Comment by Rakashazi** [comment]
Closing out some old issues, should already be addressed.
