### ISSUE TITLE
[Issue]: swan show/hide buttons bug

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#694]
### Describe the bug

Makaimura for WonderSwan
Show Y buttons - On
A - Jump, B - Shot

Show Y buttons - Off
A - Shot, B - Jump

I think vertical games may also have this bug
@Rakashazi  have to fix it

screenshots

### Steps to reproduce

![Makaimura for WonderSwan (Japan) 000](https://user-images.githubusercontent.com/109885044/189395666-35587763-a046-47e3-8d36-5a2672356159.png)
![Makaimura for WonderSwan (Japan) 001](https://user-images.githubusercontent.com/109885044/189395678-e20d8726-650f-44ae-addc-b6e2f5afaafa.png)
![Makaimura for WonderSwan (Japan) 002](https://user-images.githubusercontent.com/109885044/189395680-1327403d-b7cb-4db0-8583-81eb941363d2.png)

### Expected behavior

Add a D-Pad, and the Y buttons will also move the character

**Comment by soundsnow** [comment]
when will you reply to all my issues?
it's almost two months
they will be closed by the github bot if not fixed
they wasted a lot of my time and I don't want to post again

**Comment by Rakashazi** [comment]
Thanks for the report, I fixed it in the last commit. About your other issues, I don't have time to reply to every one individually but I have added them to my notes so don't worry about them getting auto-closed.
