### ISSUE TITLE
[Feature request]: swan show Y/X as button(s)/D-Pad(s)

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#695]
### Describe the feature

wonderswan
show Y as buttons
show Y as D-Pad
show X as buttons
show X as D-Pad

pocket challenge v2
show three/four buttons as D-Pad
show three/four buttons

**Comment by Rakashazi** [comment]
Support for mapping functions to dpad directions was added in a recent commit
