### ISSUE TITLE
Always force gcc-ar?

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#70]
Would there be any downside to changing AR ?= gcc-ar to AR := gcc-ar in https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/imagine/make/gcc.mk or at least forcing it in linux-gcc.mk ?
I haven't found a build environment where gnu make doesn't predefine AR as 'ar'.

**Comment by Rakashazi** [comment]
I'm now using the origin function and check if AR is defined as a default variable and if so, set it to gcc-ar. Should fix it defaulting to ar on the linux build.
