### ISSUE TITLE
[Issue]: swan birthday february 31?

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#707]
### Describe the bug

birth month
input 1 to 12
2

birth day
input 1 to 31
31

### Steps to reproduce

birthday 1999.2.31?
who was born on february 31?

### Expected behavior

January 31
February 28 or 29
March 31
April 30
May 31
June 30
July 31
August 31
September 30
October 31
November 30
December 31

**Comment by Rakashazi** [comment]
Even though not all possible dates exist, they're still valid values in the WonderSwan's memory. It's possible to implement a real calendar picker in the future but is probably overkill for such a small hardware feature.
