### ISSUE TITLE
[Question]: openMSX

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#719]
### Describe your question

I think [openMSX](https://github.com/openMSX/openMSX) is better than blueMSX
they have been released for almost twenty years
openMSX was released earlier than blueMSX
It supports more games

another thing I found inconvenient was that I had to create a single folder and a config.ini file for each file

It's so anti-human

It is no longer maintained

openMSX is the only MSX emulator that supports Palcom LaserDisc games

openMSX is more user-friendly and easier to use for dummies

the developers of blueMSX had planned to release 2.9.1 or 3.0, but for some reason it is no longer being updated

> Next release
> ============
> Z80 IRQ timing (not yet)
> Fix DER files in panasonic FDC
> Add search for numbers (byte, word, dword) in degugger
> Wildcard search (part of numbers or strings)
> Support for new EEPROM in Activision PCB

for those who are keen on MSX games, openMSX is currently the only choice

I have used blueMSX to play a ColecoVision game, but the game characters (rooster and hen) are all stuck in place
only with the SVI-603 BIOS can you play properly, the other three ColecoVision BIOS are completely ineffective
even GearColeco, a niche ColecoVision emulator, can play this game properly with the same BIOS file
Yolk's on you, The (Europe) (Proto)

No one likes to create almost 200 folders for all the files, it's a waste of time
To be honest, blueMSX may have been great in the past, but now its disadvantages are coming to light

C-BIOS machine configurations for openMSX
=========================================

Note: these configurations will only work in openMSX 0.9.2 or later.

Installation instructions:
1. Copy "C-BIOS_*" files to "share/machines" in the openMSX
   installation directory or the openMSX user directory.
2. Copy "cbios_*.rom" to the openMSX ROM pool ("share/systemroms").

C-BIOS machine configurations for blueMSX
=========================================

Installation instructions:
1. Copy "MSX - C-BIOS", "MSX2 - C-BIOS", "MSX2+ - C-BIOS",
   "MSX - C-BIOS - JP", "MSX2 - C-BIOS - JP" and "MSX2+ - C-BIOS - JP",
   "MSX - C-BIOS - BR", "MSX2 - C-BIOS - BR" and "MSX2+ - C-BIOS - BR"
   "MSX - C-BIOS - EU", "MSX2 - C-BIOS - EU" and "MSX2+ - C-BIOS - EU",
   subdirectories to "Machines" in the blueMSX installation directory.
2. Copy "cbios_main_msx1.rom" and "cbios_logo_msx1.rom" into the
   "MSX - C-BIOS" directory.
3. Copy "cbios_main_msx1_jp.rom" and "cbios_logo_msx1.rom" into the
   "MSX - C-BIOS - JP" directory.
4. Copy "cbios_main_msx1_br.rom" and "cbios_logo_msx1.rom" into the
   "MSX - C-BIOS - BR" directory.
5. Copy "cbios_main_msx1_eu.rom" and "cbios_logo_msx1.rom" into the
   "MSX - C-BIOS - EU" directory.
6. Copy "cbios_main_msx2.rom", "cbios_logo_msx2.rom" and "cbios_sub.rom" into
   the "MSX2 - C-BIOS" directory.
7. Copy "cbios_main_msx2_jp.rom", "cbios_logo_msx2.rom" and "cbios_sub.rom" into
   the "MSX2 - C-BIOS - JP" directory.
8. Copy "cbios_main_msx2_br.rom", "cbios_logo_msx2.rom" and "cbios_sub.rom" into
   the "MSX2 - C-BIOS - BR" directory.
9. Copy "cbios_main_msx2_eu.rom", "cbios_logo_msx2.rom" and "cbios_sub.rom" into
   the "MSX2 - C-BIOS - EU" directory.
10. Copy "cbios_main_msx2+.rom", "cbios_logo_msx2+.rom", "cbios_sub.rom" and
   "cbios_music.rom" into the "MSX2+ - C-BIOS" directory.
11. Copy "cbios_main_msx2+_jp.rom", "cbios_logo_msx2+.rom", "cbios_sub.rom" and
    "cbios_music.rom" into the "MSX2+ - C-BIOS - JP" directory.
12. Copy "cbios_main_msx2+_br.rom", "cbios_logo_msx2+.rom", "cbios_sub.rom" and
    "cbios_music.rom" into the "MSX2+ - C-BIOS - BR" directory.
13. Copy "cbios_main_msx2+_eu.rom", "cbios_logo_msx2+.rom", "cbios_sub.rom" and
    "cbios_music.rom" into the "MSX2+ - C-BIOS - EU" directory.

If you have time, can you port openMSX?

**Comment by LeopoldCraft0055** [comment]
ColecoVision GearColeco

SG-1000 PicoDrive

**Comment by soundsnow** [comment]
> ColecoVision GearColeco
> 
> SG-1000 PicoDrive

I don't recommend Gearcoleco because its libretro buttons can go wrong
and it does not support Super Action Controller and Steering Wheel
Genesis Plus GX is compatible with the largest number of official and unofficial SG-1000 games
