### ISSUE TITLE
[Question]: Possible to update Snes9x EX?

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#752]
### Describe your question

Hi @Rakashazi I hope you are doing fine.

I wanted to ask if it is possible to update Snes9x EX to the latest Snes9x commit?

There are two commits I'm interested in:
A fix for the oops state: https://github.com/snes9xgit/snes9x/commit/8685db48a7a758425674c3804b259ea06ff046f8
Cleanup of the logger files, which reduces the footprint slightly: https://github.com/snes9xgit/snes9x/commit/f3fafab8b327df5012cb048f567f1679033c9d6f

Thanks in advance.

**Comment by Rakashazi** [comment]
Thanks @bladeoner, I'm doing fine and hope you are as well. I'll take a look at the new Snes9x GIT commits soon, but note that I already don't use the logger system so that commit won't have any effect on my build.

**Comment by bladeoner** [comment]
@Rakashazi I am also fine, thank you.

Thank you for letting me know that the logger system is not in use, then the commit will only cleanup the files.

**Comment by bladeoner** [comment]
@Rakashazi thanks for updating Snes9x!!! I will close this
