### ISSUE TITLE
libarchive.a Build error (IMAGINE ENGINE) Mac OS X 10.11.15

### ISSUE THREAD

**Issue by thededman** [Rakashazi/emu-ex-plus-alpha#76]
I have had the Xcode and update MacPorts as of last night. Built the bash **makeAll-ios.sh TAR=GNUTAR**
Goes for a spell then ends at libarchive.a.

Applications/Xcode.app/Contents/Developer/usr/bin/make -C /tmp/imagine-bundle/libarchive/build/ios-arm64 DEV_CFLAGS=
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       libarchive/archive_read_support_filter_xz.lo
  CC       libarchive/archive_read_support_format_7zip.lo
  CC       libarchive/archive_read_support_format_xar.lo
  CC       libarchive/archive_util.lo
  CC       libarchive/archive_write_disk_posix.lo
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3490:2: error: 
      use of undeclared identifier 'acl_t'
        acl_t acl, dfacl = NULL;
        ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3493:2: error: 
      use of undeclared identifier 'acl'
        acl = acl_get_fd(tmpfd);
        ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3493:8: error: 
      implicit declaration of function 'acl_get_fd' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        acl = acl_get_fd(tmpfd);
              ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3494:6: error: 
      use of undeclared identifier 'acl'
        if (acl == NULL) {
            ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3503:2: error: 
      use of undeclared identifier 'dfacl'
        dfacl = acl_dup(acl);
        ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3503:10: error: 
      implicit declaration of function 'acl_dup' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        dfacl = acl_dup(acl);
                ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3503:18: error: 
      use of undeclared identifier 'acl'
        dfacl = acl_dup(acl);
                        ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3504:10: error: 
      implicit declaration of function 'acl_set_fd' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        acl_r = acl_set_fd(dffd, dfacl);
                ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3504:10: note: 
      did you mean 'acl_get_fd'?
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3493:8: note: 
      'acl_get_fd' declared here
        acl = acl_get_fd(tmpfd);
              ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3504:27: error: 
      use of undeclared identifier 'dfacl'
        acl_r = acl_set_fd(dffd, dfacl);
                                 ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3512:6: error: 
      use of undeclared identifier 'acl'
        if (acl)
            ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3513:3: error: 
      implicit declaration of function 'acl_free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                acl_free(acl);
                ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3513:12: error: 
      use of undeclared identifier 'acl'
                acl_free(acl);
                         ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3514:6: error: 
      use of undeclared identifier 'dfacl'
        if (dfacl)
            ^
/tmp/imagine-bundle/libarchive/libarchive-3.2.1/libarchive/archive_write_disk_posix.c:3515:12: error: 
      use of undeclared identifier 'dfacl'
                acl_free(dfacl);
                         ^
14 errors generated.
make[2]: *** [libarchive/archive_write_disk_posix.lo] Error 1
make[1]: *** [all] Error 2
make: *** [/tmp/imagine-bundle/libarchive/build/ios-arm64/.li

**Comment by Rakashazi** [comment]
This will be fixed in the next release of libarchive but I've added a patch to the bundled 3.2.1 version as a workaround.
