### ISSUE TITLE
[GBA.emu] Why L key triggers light sensor?

### ISSUE THREAD

**Issue by Yave-Yu** [Rakashazi/emu-ex-plus-alpha#762]
### Describe the bug

In 1.5.64, why L key always trigger light sensor? That causes original L key doesn't work.

### Steps to reproduce

Just touch L key.

### Expected behavior

L key should do L key job, not trigger light sensor.

### Add screenshots

![Screenshot_2022-09-25-09-35-06-035_com explusalpha GbaEmu](https://user-images.githubusercontent.com/54294476/192124617-006d1e09-76dd-402d-81ed-9b8d8d9e9c7c.jpg)

**Comment by Rakashazi** [comment]
It was a due to typo in the code, but I already fixed it in 1.5.65 so please update to that version.
