### ISSUE TITLE
[Issue]: gba Metroid: Zero Mission unplayable original game

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#779]
### Describe the bug

[metroid save and state.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9717236/metroid.save.and.state.zip)
![Miteluode - Lingdian Renwu (China) 000](https://user-images.githubusercontent.com/109885044/194107457-0b79e675-f1fc-41e8-9f4b-66f8cc6fef07.png)
![Miteluode - Lingdian Renwu (China) 001](https://user-images.githubusercontent.com/109885044/194107474-f8d5fe98-578e-4833-b4ca-cb1077874e01.png)
![Miteluode - Lingdian Renwu (China) 002](https://user-images.githubusercontent.com/109885044/194107491-c8d0730f-7d86-4f88-8123-ce0cb6a020e9.png)
![Miteluode - Lingdian Renwu (China) 003](https://user-images.githubusercontent.com/109885044/194107504-857d01c7-e02c-4326-adf9-47705e644cca.png)

### Steps to reproduce

I spent more than 5 hours testing this game, but the original version doesn't work

download my save and state file
open this game
Miteluode - Lingdian Renwu (China)
密特罗德-零点任务
start
options（选项）
原始密特罗德

### Expected behavior

Completion of the game unlocks an [emulated](https://en.m.wikipedia.org/wiki/Emulated) version of the original Metroid game. Zero Mission also allows players to unlock the [Metroid Fusion](https://en.m.wikipedia.org/wiki/Metroid_Fusion) picture gallery by linking between Zero Mission and Fusion cartridges via the [Game Boy Advance Game Link Cable](https://en.m.wikipedia.org/wiki/Game_Boy_Advance_Game_Link_Cable).

**Comment by soundsnow** [comment]
where's samus
move!
no, nothing happened

**Comment by Rakashazi** [comment]
Can you test if this works on [VBA-M 2.1.4](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4) on PC? The .sav file will work between both emulators.

**Comment by soundsnow** [comment]
> Can you test if this works on [VBA-M 2.1.4](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4) on PC? The .sav file will work between both emulators.

sorry, i can't
