### ISSUE TITLE
Add ability to reduce sound volume

### ISSUE THREAD

**Issue by M-a-r-k** [Rakashazi/emu-ex-plus-alpha#78]
I noticed this issue testing Snes9x EX on an Alcatel Pixi 3 4.5 (4G version) Android phone.

On some devices, even when the system volume control is at the lowest possible, emulator sound can be too loud for some situations. E.g. at night the user may want the sound to be very quiet. [That actually applies to all apps, not just emulation.]

A volume control in the emulator would allow the user to reduce the emulator sound volume. The in-emulator volume control would be set to maximum by default. A full volume control wouldn't be necessary; options to just e.g. halve or quarter the output sound volume would probably be sufficient.

**Comment by Rakashazi** [comment]
Closing out some old issues, volume option was added.
