### ISSUE TITLE
[Feature request]: Better pixel filters

### ISSUE THREAD

**Issue by juamnitruh** [Rakashazi/emu-ex-plus-alpha#781]
### Describe the feature

Prescale 2x is fine, but it is a little too blurry.
I think filters like Sharp Bilinear or Pixelate would be nice. 
Yeah, i could just use internal scale, but then i would be forced to use the pixel perfect aspect ratio. I'll rather play them with 4:3, as intended.

**Comment by Rakashazi** [comment]
Sure, I should be able to add some additional prescale filters so you can dial in a sharper image in the next update.

**Comment by Rakashazi** [comment]
Ok, prescale 3x and 4x were added in the last commit.
