### ISSUE TITLE
[Feature request]: use 24-hour format

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#782]
### Describe the feature

Really Load State From: 10/06/22 03:08:34 PM
What's PM?
12+3?
Obviously 24-hour format is more intuitive
I had to calculate the corresponding time myself
15:08:34

**Comment by guilhermeoc97** [comment]
I think it would be more effective to follow the OS' current locale instead of hardcoding the format. That way people can read the date on whatever format they're accustomed with.

Or maybe have a "12/24 hour format" switch as an option.

**Comment by Rakashazi** [comment]
Thanks for the report, looks like Android doesn't support locales from C/C++ code calling strftime() which I'm using to handle time to string conversions on plain file paths. When accessing files via the Storage Access Framework, I'm using the Java DateFormat class which does respect the system's set 12/24 hour time so you should get proper formatting on Android 11+ devices already.

For older devices, I need to refactor the time conversion code out of the file system layer and move it to the application layer so all file paths can use the DateFormat class. This shouldn't be too difficult so I think it'll be ready in the next update.

**Comment by Rakashazi** [comment]
This should be fixed in the last commit, including on screenshot filenames which now are based on the time they're taken.
