### ISSUE TITLE
[Issue]: swan Overclocking bug

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#800]
### Describe the bug

Fire Lancer (USA) (Demo) (2018-12-25) (Aftermarket) (Unl).wsc
Fire Lancer (USA) (Demo) (2019-01-03) (Aftermarket) (Unl).wsc

### Steps to reproduce

The speed of movement and music playback is too fast

### Expected behavior

Is Mednafen the latest version? I don't think this bug should appear

**Comment by Rakashazi** [comment]
It looks like this game uses different display timings than retail games. I'll look into it for a future update.

**Comment by Rakashazi** [comment]
Timing is now fixed in last commit.
