### ISSUE TITLE
Android M/N Forbidden Folders

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#81]
I noticed some reviews of Snes9x EX+ mentioning permission being denied on certain folders.

Just as a heads up, Android M/N deny access to certain folders which were accessible before so certain assumptions must be made:
Android M:
/storage/emulated

this folder should be redirected to /storage/emulated/0 or /storage/emulated/legacy if it can't be read (at least these are the assumptions I use)

Android N:
/storage/emulated
/

for root, I make /storage the top level directory if it can't be read as all relevant storage devices should be accessible through there.

**Comment by Rakashazi** [comment]
Closing out some old issues, addressed in storage updates since last post.
