### ISSUE TITLE
[Feature request]: time format

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#814]
### Describe the feature

Are there any differences between them?
they are completely different
0 (10/13/22 19:12)
1 (10/13/22 19:12)

20221013-191203
20221013-191256

### Add screenshots

![Screenshot_20221013-191254_Trebuchet](https://user-images.githubusercontent.com/109885044/195582955-917d901b-2bbc-4fb2-b8d5-4c9bc9674a74.png)

**Comment by soundsnow** [comment]
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/813

**Comment by soundsnow** [comment]
my suggestion
![Screenshot_20221013-192634_Trebuchet](https://user-images.githubusercontent.com/109885044/195584482-16505fb1-8ac2-4cfd-b471-a3c0ff8b0255.png)

**Comment by soundsnow** [comment]
2022-10-13 19:24:38

**Comment by Rakashazi** [comment]
Ok, I've added the seconds display to the save state menus. On another note, to stop with the issue spam I've added some new rules for the kind of requests I'm accepting and may delete those issues that don't follow what I've listed. Please read them here #330
