### ISSUE TITLE
[Question]: better choice mGBA and SameBoy!!!

### ISSUE THREAD

**Issue by soundsnow** [Rakashazi/emu-ex-plus-alpha#818]
### Describe your question

FCEUX 2.6.4 Mar 24, 2022
FCEUX interim-build 2022-10-13T00:51:11

Snes9x 1.61 Mar 05, 2022

Gambatte r571 2014-09-28
SameBoy 0.15.6 26 days ago

Visual Boy Advance - M 2.1.4 Oct 02, 2019
mGBA 0.10.0 2 days ago

VBA-M has not released a stable version for many years, which means it has not improved significantly over the years.
Many games are actually supported, but can only open game files in certain situations.

Mythri (USA) (Proto).gba
I first opened the black screen
After that, I tried several times in different situations to finally get it to display the screen

Miteluode - Lingdian Renwu (China).gba
Metroid - Zero Mission
Original Metroid freezing
After that, I tried several times in different situations to finally get it to be played

However for some of its games that don't require sensors, if it's a black screen 100 times, then don't waste your time

The stable version of VBA-M has not been updated for more than 3 years, and Gambatte has stopped updating for more than 8 years.

Many of VBA-M's recent updates are translations.
There are 96 Multiboot games that cannot be opened by it, they are all .gba files.
mGBA is fully capable of opening these game files.

Gambatte does not support games that require sensors and other unlicensed/special games.

VBA-M's random black screens, white screens and freezes make it not as stable an emulator. If you do not retry at different times you simply do not know that it is its own problem.
For licensed games that do not require sensors, Gambatte's inability to run is very unsatisfactory.

mGBA and SameBoy are both emulators that are being actively updated with partial support for Game Boy Camera, Kirby - Tilt 'n' Tumble acceleration sensor and many more games

I know an emulator developer, the emulator has been updated for about five years, and he spent four months replacing the backend with another emulator that was active for compatibility

I wonder if @ consider SameBoy and mGBA, I don't want to judge again if it's a problem in itself because of VBA-M and the Gambatte that can enter the game but can only press start

**Comment by Rakashazi** [comment]
Changing emulation back-ends is a major engineering decision and will be done at my discretion, I won't accept further requests like this and they'll be deleted.
