### ISSUE TITLE
Recent Android Compilation Issues

### ISSUE THREAD

**Issue by xperia64** [Rakashazi/emu-ex-plus-alpha#84]
Couple of android compilation errors I've encountered with the most recent commit:

This could be my system, but evalPkgConfigCFlags.mk is incorrectly adding "-I/usr/include" when compiling "PThread.cc" and only for that file. I've worked around this by removing "PKG_CONFIG_SYSTEM_INCLUDE_PATH=$(PKG_CONFIG_SYSTEM_INCLUDE_PATH)" from evalPkgConfigCFlags.mk

The other error is that CONFIG_RESOURCE_FACE is not actually defined anywhere, meaning that the actual contents of GfxText.hh won't be included, leading to compilation errors.

**Comment by Rakashazi** [comment]
Closing out some old issues, should already be addressed.
