### ISSUE TITLE
Is it possible to have a command by command guide to compile under iOS?

### ISSUE THREAD

**Issue by ecstaticax** [Rakashazi/emu-ex-plus-alpha#85]
Thanks

**Comment by thededman** [comment]
@ecstaticax I have working on new instructions for myself under https://github.com/thededman/emu-ex-plus-alpha the notes i have are in OneNote, just to find time to update the screenshots and macport instructions. 
This weekend I have compiled the latest code successfully but having trouble with keeping the emulator to stay in Docuemnts folder. Hopeful to be fixed in upcoming releases.

**Comment by ecstaticax** [comment]
Thanks a lot for the reply. I will try to compile it again.

**Comment by thededman** [comment]
dang! I was pretty detailed from my notes from last year! Total forgot. I will update this fork with more as time permits.
FYI - the latest version will build, but will not be able to see DOCUMENTS folder within the emulator. I have rolled back to an older version 1.5.29. This works fine. Is somethinkg with newer Xcode and Sandbox directory (NSDocumentDirectory )
I'm not a coder, but have been try to resolved on my own. 

https://github.com/Rakashazi/emu-ex-plus-alpha/commit/53862f1ba566e7963a3c8f49b9378551bf9b923f

**Comment by ecstaticax** [comment]
So what can I do to compile it using your instructions and an older version? More easily, sorry if I ask, could you send me the ipa (that I can sign by self) of the emulators already compiled?

**Comment by NE1WeKnow** [comment]
ecstaticax - I've seen your comments on a few c64 projects now. Had any luck with tracking down a suitable emulator to push to your device? I've used sideloading for other emulators and even compiled some but no luck so far with a c64 emu (except through idos but performance was poor)

**Comment by ecstaticax** [comment]
NE1WeKnow - I found an ipa of C64.EMU but I wasn't able to compile it. It works perfectly. There is also C64 Scene emulator, but it does not support MFI controllers. Apart  from them, the C64 scene on iOS is quite dead.

**Comment by NE1WeKnow** [comment]
ecstaticax - yes it's most disappointing that the c64 emu scene is not as vibrant as it is for other platforms. I see VICE 64 is still receiving updates and there's an android version but no ios :-(

I've reached out to the dev for C64.emu to contribute to the project but in the meantime can you point me in the right direction for the ipa?

**Comment by ecstaticax** [comment]
Write to me at my address: ecstaticax (at) gmail (dot) com.
