### ISSUE TITLE
One global palette for all ROMs (NES.emu)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#86]
Current NES.emu version allow to set individual palette for each ROM:
```
Super_Mario_Bros_(U).nes ------> Super_Mario_Bros_(U).pal
Castlevania_(U).nes ------> Castlevania_(U).pal
```
Very need for ability to set one global *.pal-file for all ROMs,
as did in every recent NES emulators.

**Comment by Rakashazi** [comment]
Closing out some old issues, a global palette option was added.
