### ISSUE TITLE
Swap Duty Cycles option (NES.Emu)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [Rakashazi/emu-ex-plus-alpha#96]
Can you add please "Swap Duty Cycles" checkbox to NES.Emu audio options?
You're updated FCEUX core to svn3200,
All the code logic for "Swap Duty Cycles" already implemented in svn3200, so you're need only make checkbox for it.

**Comment by Rakashazi** [comment]
A Swap Duty Cycles option was recently added and will be included in version 1.5.58.
