### ISSUE TITLE
[GBA.emu] Lufia Ruins of Lore text corruption

### ISSUE THREAD

**Issue by SirPrimalform** [Rakashazi/emu-ex-plus-alpha#98]
I'm experiencing this bug in GBA.emu:
http://vba-m.com/forum/thread-301-post-6006.html#pid6006

It's long since been fixed in VBA-M, I was wondering if the fix could be carried over into GBA.emu? The thread contains a post with some details on the fix, but I don't pretend to understand them.

**Comment by Rakashazi** [comment]
Apologies for the late reply, the GBA.emu core was updated to VBA-M 2.1.4 in the last commit including this fix.
