### ISSUE TITLE
[Question]: Can you update the Github Workflow

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#989]
### Describe your question

Hi @Rakashazi there are some warnings appearing under the Github Actions with the advice to move from Node.js 12 to Node.js 16: https://github.com/Rakashazi/emu-ex-plus-alpha/actions/runs/3296738077

I have just updated the Github Workflow, can you please update the Github Workflow with the attached file?
[update_github_workflow.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9838468/update_github_workflow.zip)

Thanks in advance.

Have a nice weekend!

**Comment by Rakashazi** [comment]
Thanks @bladeoner, I'll add it into the next commit. Have a good weekend too :)
