### ISSUE TITLE
[Feature request] SD card write permission for Android Nougat

### ISSUE THREAD

**Issue by molul** [Rakashazi/emu-ex-plus-alpha#99]
I can't save games on Nougat on any .emu (Mega drive, NES, SNES, NeoGeo...). It would be cool to be able to do it like in previous Android versions.

**Comment by Silver-Void** [comment]
+1 on that. Gba.emu is the only Android emulator that supports changing the save file folder that I've found so far. I can load save files from my EZFlashIV's SD card and play just fine but I can't save. If you add this, I could play the same games with the same save file from the same SD card on my computer, phone and GBA.

**Comment by Silver-Void** [comment]
I think it should be as easy as adding `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` to the `imagine/src/base/android/imagine-v9/src/main/AndroidManifest.xml` file. I'm not good at android programming so I don't know if it's that simple but when I was trying it out, I couldn't build the thing even without that change. I have no idea how to... I tried for hours.

**Comment by Rakashazi** [comment]
Closing out some old issues, should be addressed in storage updates since last post.
