### ISSUE TITLE
[Issue]: snes9x - View's height for cheats is too small

### ISSUE THREAD

**Issue by SedapnyaTidur** [Rakashazi/emu-ex-plus-alpha#991]
### Describe the bug

Well, as the title says, I can hardly see the cheat code. If you're curious, the code is `7effff`.

### Steps to reproduce

1) Add a new cheat code (`7effff00`).
2) Try to modify it.

### Expected behavior

A bigger view.

### Add screenshots

![Screenshot_20221022_230856](https://user-images.githubusercontent.com/76834441/197346903-b09b8881-450e-4126-ad7d-6154205cc179.png)

**Comment by Rakashazi** [comment]
Can you test on the current nightly and let me know if it's fixed? There was an issue where not enough vertical padding size was added depending on the font/theme.

**Comment by SedapnyaTidur** [comment]
@Rakashazi Do I need to compile the source code myself? That isn't gonna happen then. I am just a regular user, no more no less. I've no idea about github nor android. If you're unable to compile and provide a temporary link, I will assume this issue as done and you can safely close it. Thanks.

**Comment by bladeoner** [comment]
@SedapnyaTidur you can download Nightly Builds here, while being logged in and clicking on the build you want:https://github.com/Rakashazi/emu-ex-plus-alpha/actions

Direct link to the latest Nightly Build: https://github.com/Rakashazi/emu-ex-plus-alpha/actions/runs/3296738077

Under Artifacts you can download Snes9x EX.

**Comment by SedapnyaTidur** [comment]
@bladeoner Thanks. Almost be missed them if I hadn't scrolled far enough. The direct link is really helpful for someone me. Yes, it fixed the issue.
