### ISSUE TITLE
[Feature request]: snes9x - More UI quick shortcuts.

### ISSUE THREAD

**Issue by SedapnyaTidur** [Rakashazi/emu-ex-plus-alpha#992]
### Describe the feature

I would like to have other UI shortcuts to make the gameplays more convenient and fun to play such a "quick save" and "quick load" the default save state and "access cheats" buttons. Also a button to enable/disable one selected cheat would be great - similar to the fast forward button.

Another thing is colored and combo buttons. Not long ago, there's a game that uses these combinations (both letters and colors) as a hint of a puzzle. Worst, there were parts that makes you smashing the A button.

### Add screenshots

My current shortcuts (cropped).
![Screenshot_20221023_053423](https://user-images.githubusercontent.com/76834441/197364510-0dce7e29-6f12-41e3-a689-1a5fa6b31494.png)

Shortcuts I would like to have (cropped):
![Screenshot_20221023_053209](https://user-images.githubusercontent.com/76834441/197364517-b107da18-b7c6-4879-b2a1-b5ed62aed1a6.png)

Or this one (cropped):
![Screenshot_20221023_053301](https://user-images.githubusercontent.com/76834441/197364523-35c671c3-57ce-471a-93cd-fe20bc4fa875.png)

**Comment by Rakashazi** [comment]
Thanks for the suggestions, I'm planning to re-do the on-screen controls code soon to support adding/removing an arbitrary amount of buttons. I'll look into colorizing the buttons too.

**Comment by Rakashazi** [comment]
This feature was added in beta version 1.5.68 and is now in stable version 1.5.69
