### ISSUE TITLE
[Issue]: can't save state: Error writing file 

### ISSUE THREAD

**Issue by DarthSchwab** [Rakashazi/emu-ex-plus-alpha#999]
### Describe the bug

I've just installed your snes simulator on android, and I wanted to try super mario world, I can play the game fine, butI tried 2 different roms with the same result : Each time I try saving, it says "can't save state: Error writing file"

### Steps to reproduce

Menu -> save autosave state
Or
Menu -> Manual save state -> save state 

### Expected behavior

Save?
I have the megadrive genesis paid version, and it works like a charm, so I don't know what's going on here. 

### Add screenshots

![Screenshot_20221026-212636_Snes9x EX+](https://user-images.githubusercontent.com/116758609/198118595-0dd17e7a-17b2-4218-aa0c-412190dcdb9a.jpg)

**Comment by Rakashazi** [comment]
Try opening the game by first selecting File Locations -> Browse For Folder since that will give the app access to whole folder for saving games. Alternatively, set a save path with Options -> File Paths -> Saves -> Select Folder and see if that fixes it.

**Comment by DarthSchwab** [comment]
Thanks! It worked!

**Comment by Rakashazi** [comment]
No problem, good to hear you got it working :)
